### ISSUE TITLE
VESA driver: detect preferred resolution

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1001]
Unless explicitly configured otherwise, the VESA driver sets up a resolution of 1024x768 by default.

The VESA BIOS extensions 2.0 allow for the detection of the preferred resolution via EDID information. It would be useful to evaluate this information at the startup of the driver and use the preferred resolution as default.

**Comment by chelmuth** [comment]
In my experiments years back I discovered that the *preferred resolution* approach is not robust as monitors tend to report over-optimistic mode tables. As we also do not use the VESA driver for product-level applications, I vote for closing this issue.

**Comment by nfeske** [comment]
I agree.
