### ISSUE TITLE
fb_sdl: warn on missing libsdl-dev

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1004]
Without libsdl-dev installed on host system, at least compiling fb_sdl fails with compile errors like:

```
/home/lypo/genodelabs/genode/mstein/libports/include/SDL/SDL_events.h:113:2: error: ‘Uint8’ does not name a type
...
```

and

```
  Program drivers/framebuffer/sdl/fb_sdl
Package sdl was not found in the pkg-config search path.
Perhaps you should add the directory containing `sdl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sdl' found
    LINK     fb_sdl
/home/lypo/genodelabs/genode/mstein/os/src/drivers/framebuffer/sdl/fb_sdl.cc:92: undefined reference to `SDL_UpdateRect'
...
```

I was not able to find a hint to the real problem - the missing libsdl-dev.

**Comment by chelmuth** [comment]
Since this issue was created many aspects changed (e.g., libsdl is now a real port in world an the compilation of fb_sdl would fail instantly) I close it as obsolete.
