### ISSUE TITLE
noux: handle missing shared object gracefully

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1040]
Executing a binary in noux w/o having all shared objects already in place
results in abort():

```
[init -> noux] replay: missing ds_info for dataspace at addr 0x11000
unmapping of managed dataspaces not yet supported
unmapping of managed dataspaces not yet supported
[init -> noux] Could not open file "pcre.lib.so"
[init -> noux] C++ runtime: Genode::Rom_connection::Rom_connection_failed
[init -> noux] void* abort(): abort called
```

It would be better to notify the user instead, imho.

**Comment by alex-ab** [comment]
@chelmuth: may you please add 1fcf45c25d62a851e41738f399e1bfdf9325ff2f to staging, the other part of the issue commit "add missing .so files to noux_tool_chain.inc" is already on master

**Comment by chelmuth** [comment]
Sorry, the commit just slipped through :-|
