### ISSUE TITLE
usb uhci driver works only occasinal on 64bit host

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1045]
If the physical memory of the allocated dataspace for DMA is above 4G the usb uhci driver dies. Currently we have on Genode no support to specify some kind of range restrictions to the ram_session interface to express that we need memory below 4G physical.

**Comment by alex-ab** [comment]
@nfeske: commits of #696 and #1045 are fixups to make our test machine happy on 32bit host and fixes this issue

**Comment by nfeske** [comment]
@alex-ab Looks very good. Merged into staging.
