### ISSUE TITLE
Encrypting/authenticating block server

### ISSUE THREAD

**Issue by m-hansp** [genodelabs/genode#1086]
Baseline:
Encryption without authentication can be implemented easily. Encryption with authentication is more complex.

Idea:
The idea is to equally target confidentiality, integrity and authentication within a separate component. This would not only provide security against evil maid attacks (e.g. reading out/writing the hard drive with physical access to the computer), but it would also protect against colluding components (e.g. a malicious hard drive could deliver blocks from a TOP SECRET application to a SECRET application in an MLS scenario).

Authenticated vs. transparent encryption:
While authenticated encryption (e.g. GCM mode of operation) might be useful, it uses additional headers for authentication. This counters the goal of transparent block encryption. 

Still, authentication headers have to be placed at some part of the storage device: either in conjunction with each block or in a separate storage device partition.

Proposal for authentication:
Authentication data (i.e. a set of message authentication codes) is stored on a separate storage device partition at the beginning of the storage device. Therefore,  blocks of data partitions can be transparently encrypted.
The operating system is supposed to boot from a different device (e.g. a USB stick).
The authentication data would be placed within a tree structure (similar to a hash tree). This way, replay attacks (i.e. a malicious hard drive or driver tries to reinsert a previously authenticated block) would be prevented. The root of the mac tree has to be protected from tampering.

Suggested use of the crypto storage service: 

[FS and applications] <-> crypto_blk <-> blk_cache <-> part_blk <-> [atapi_drv and other drivers]

If necessary, the block server could be implemented in two separate steps.
1. Only transparent block encryption (e.g. XTS-AES mode of operation) without any authentication or integrity protection.
2. Solving the authentication problem separately (i.e. without authenticated encryption).

It might be interesting to also mitigate covert channels over the shared storage hardware and the resource multiplexing components.

As nfeske previously pointed out, the encryption key has to be delivered to the block service in a secure manner.

Any comments or further requirements?

**Comment by ehmry** [comment]
If someone wants to try and do this natively I have a libsodium port, which is much cleaner and simplier than using openssl for crypto.
https://github.com/ehmry/genode-cjdns
http://doc.libsodium.org/

**Comment by nfeske** [comment]
This issue is superseded by the CBE project. See the recent article series by Martin Stein at https://genodians.org
