### ISSUE TITLE
hw & demo: double-nitpicker crash

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1087]
I ran demo with hw_arndale and then first started an instance of liquid_fb. After that, I started an instance of nitpicker, which is fine and results in a head-bar popping up inside liquid_fb. Then I try to start another instance of nitpicker which ends in console output:

```
Assertion failed: _state == INACTIVE
  File: /home/lypo/genodelabs/genode/mstein/base-hw/src/core/kernel/ipc_node.h:275
  Function: void Kernel::Ipc_node::await_request(void*, Kernel::size_t)
```

Consequently the whole system gets stuck at this point due to the assertion.

**Comment by nfeske** [comment]
What is the status of this issue?
