### ISSUE TITLE
libports: libuv

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1098]
> libuv is a multi-platform support library with a focus on asynchronous I/O. It was primarily developed for use by Node.js, but it's also used by Mozilla's Rust language, Luvit, Julia, pyuv, and others.

https://github.com/joyent/libuv

I am attempting to port Libuv to Genode for the sake of [cjdns](https://github.com/cjdelisle/cjdns), but if it works we get the afformentioned stuff for cheap.

I can build it because I started by stubbing everything out, but need a decent way of using the libuv tests within the build system before moving on.

[my branch](https://github.com/3M3RY/genode/tree/libuv)

**Comment by bjoernd** [comment]
Is this issue still active?

**Comment by ehmry** [comment]
@bjoernd I would say no, I haven't been working on it for some time.

**Comment by ehmry** [comment]
If you are interest I can tidy up and hand off what I have.

**Comment by bjoernd** [comment]
That was more curiosity than a concrete interest. I'll get back to you if I need it. Thanks!

**Comment by ehmry** [comment]
I'm closing this for now, if I get back to work on it I will do it in my personal repo.
