### ISSUE TITLE
linux: "getting started" tutorial needs host toolchain

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1099]
The tutorial is a step by step guide to run _demo_ on _base-linux_. Therefore the _framebuffer/sdl_ driver is needed, which is a hybrid program based on _libsdl_. Hybrid programs are built with the genode toolchain is this scenario but _linked_ with the host c++ tool. The tutorial should be reviewed for viability on a plain Linux desktop installation.

This issue was discovered by Wolfgang Schmidt and posted to the Sourceforge [forum](https://sourceforge.net/p/genode/discussion/825067/thread/0fd66a80/).

**Comment by nfeske** [comment]
g++ is mentioned in the getting-started documentation.
