### ISSUE TITLE
launchpad fails

### ISSUE THREAD

**Issue by abique** [genodelabs/genode#111]
After starting 29 testinit, I got this logs :

[init -> nitpicker] create session with args: fb_width=256, fb_height=256, fb_format=1, label="launchpad -> testnit.29", ram_quota=139264
[init -> launchpad -> testnit.29] screen is 256x256
[init -> launchpad] starting testnit with quota 524288
[init -> launchpad] using unique child name "testnit.30"
thread alloc failed
thread -1 is not bound to a PD

Then the launcher does not response, but colored frames (with gradients) can be moved.

I am using okl4.

**Comment by chelmuth** [comment]
I'd like to defer merging patches in this issue until we revised the Cpu_session interface. Methods that may fail should throw not return `!= 0`.

**Comment by alex-ab** [comment]
As you mean, but I don't see the benefits. It is already inconsistent between the base platforms, so base-foc, base-nova check for it and behave correctly - generic base, okl4, pistachio, hw does not and this can be practically exercised by using the demo run script.

**Comment by chelmuth** [comment]
Hm, maybe you're right to go with your fix as a stop-gap solution.
