### ISSUE TITLE
rtc: revise and document service interface

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1148]
The real-time clock driver provides time elapsed since the epoch 1.1.1970 as is defined for *time_t* or UNIX time. The current implementation has an undocumented granularity of microseconds* while the original *time_t* provides seconds. So, are there any opinions about where to go?

**Comment by alex-ab** [comment]
Can this be closed, to me it looks like it got resolved in #1381 ?

**Comment by nfeske** [comment]
Thanks for the hint!
