### ISSUE TITLE
lwip.lib.so exports rather generic symbols

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1175]
While working on th rdesktop port, I discovered a strange and *silent* name clash between *rdesktop/tcp.c:tcp_connect()* and *lwip.lib.so:tcp_connect()*. The symbol name sounds rather generic to me to be exported by a shared library. Therefore, it may be a good idea to limit the exported symbols with a version script. A starting point may be
```
{
	global: lwip_*;
	local: *;
};
```
If this issue applies also to other libraries a mechanism for providing an optional version script when building shared libraries may be a good idea.

**Comment by nfeske** [comment]
I wonder, wasn't this issue addressed by 901b39259c6c056efad2a0bc78038cfd2779b2d5? May we close it?

**Comment by chelmuth** [comment]
Indeed.
