### ISSUE TITLE
gdb_monitor run test fails continuously

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1192]
On  nova_x86_32 and foc_pbxa9 (both using qemu) the gdb_monitor run test fails every night. @cproc do you've an idea what's going wrong?

**Comment by alex-ab** [comment]
With the changes of the commit the gdb_monitor*.run scripts work in general again, so foc does, nova sometimes. (This is the same state as before the run tool adaptation and shared library new implementation). @nfeske: please add the one commit to staging if @skalk aggrees.

**Comment by skalk** [comment]
@alex-ab : I'm a bit alienated why you ask for my permission, but certainly you have it. I'm glad to see gdb_monitor run script to succeed again!

**Comment by alex-ab** [comment]
@skalk: because the commit does not fix entirely your reported problem, only partially - thatswhy ;-)

**Comment by nfeske** [comment]
May we close this issue since @cproc's GDB work entered master with version 16.05?
