### ISSUE TITLE
x86: support message signaled interrupts (MSI) in Genode

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1216]

**Comment by alex-ab** [comment]
MSIs are now in general working on current staging, please review. Will test some other machines these days.

**Comment by alex-ab** [comment]
Working for Fiasco.OC as Nova.

**Comment by chelmuth** [comment]
Besides my few comments I'm fine with the commits (and eager to merge them to staging).

**Comment by alex-ab** [comment]
I incorporated all your comments and updated the branch accordingly.

**Comment by chelmuth** [comment]
Did you already finish your testing odyssey through the lab?

**Comment by alex-ab** [comment]
Not done, but our x86 test machine is no fine with MSIs for xhci. Please add to staging

**Comment by chelmuth** [comment]
It seems wifi_drv chokes on the current commits. @alex-ab and @cnuke could you please have a look?

**Comment by alex-ab** [comment]
Yep.

**Comment by cnuke** [comment]
@chelmuth  or @nfeske please merge 92df5e9 to staging. (The audio_out_drv _needs_ write access to this registers.)
