### ISSUE TITLE
hw: unlock kernel earlier

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1223]
There is C++ code at the end of a kernel pass that doesn't depend on processor-global kernel data. Thus the in-sync window might get shortened.

**Comment by nfeske** [comment]
Is there a tangible plan to work on this issue, or shall we close it?

**Comment by m-stein** [comment]
@nfeske Fixed the issue. However, while thinking about this issue, I found that there are several Kernel calls that can break the kernel with SMP. A good example is Kernel::delete_thread. It might get called while the targeted thread gets loaded (Kernel exit code after data_lock().unlock()) or while the it is running (user mode). But this can't be solved through the Kernel lock and should thus be fixed in another issue.

**Comment by nfeske** [comment]
@m-stein Thanks for revisiting it. I just marked the issue as fixed so that we pick up the commit for staging.

**Comment by m-stein** [comment]
Sure, thanks :)

**Comment by chelmuth** [comment]
Merged into staging - hope @skalk confirms.
