### ISSUE TITLE
hw: re-design cpu model

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1252]
I strongly vote for a re-design of the current CPU model in base-hw. Currently, there are cpu base classes from generic to more specific hardware, that don't include object-local data, e.g.: Cortex_a9::Cpu inheriting from Arm_v7::Cpu inheriting from Arm::Cpu. They only implement static class functions.

From these classes inherits the kernel-specific Processor class, which has contains necessary cpu-local data. If somethings has to be done on the local CPU you've to decide, whether some cpu-local data is used. In that case the actual cpu object is identified via reading the cpu's id via one of the class functions of the hardware-specific cpu interface, and a lookup in another class Processor_pool, which is essentially an array of Kernel::Processor objects.
This procedure is quite cumbersome (you've to distinguish between object-specific methods, and class methods). The naming scheme is still a bit confusing (Cpu vs. Processor). The widespread usage of class functions prevents the usage of common C++ design patterns, e.g.: defining virtual hook functions. Last but not least, the inheritance pattern is a bit contradictory (first from the generic to the specific hardware, and the last leaf defines the generic kernel interface). 

Moreover the current lookup for the actual cpu object is a bit expensive, which prevented us from getting rid of the class functions in the past.

Therefore, I propose the following design for cpu objects in base-hw:
- The inheritance tree goes strongly from the generic to the specific implementation. Given the previous example it would be: Kernel::Cpu (! not Processor! ) inherits from Arm::Cpu inherits from Arm_v7::Cpu inherits from Cortex_a9::Cpu.
- All current methods are getting "normal C++" methods, not class functions
- There is one new class function in Kernel::Cpu, that is called myself(), which returns the actual Cpu object, analoque to the one in Genode::Thread_base
- Analoque to the Genode::Thread_base class, the retrival of the current CPU object is done via the stack pointer, as they are disjunct between different core's anyway.

The CPU area containing all CPU objects is similar to the thread context area in Genode. The layout will be similar to this one:

```
lower address
...
============================ <- aligned at the virtual context size

            empty    

----------------------------

            stack
             (top)              <- initial stack pointer
----------------------------
   pointer to user context
----------------------------
     kernel context
----------------------------
               ID
============================ <- aligned at the virtual context size
  ...
higher address
```

The lookup of the current CPU object is simply aligning the stackpointer, which also can be used in the assembler path of the exception vectors to save execution time.

**Comment by nfeske** [comment]
This issue dried up since 6 years. @skalk and @m-stein what should we do about it?

**Comment by m-stein** [comment]
I'm fine with it, but anyway I'm not that deep into base-hw anymore. That said, I think that it's up to @skalk.

**Comment by skalk** [comment]
@nfeske: to me it is still needed. But there was not enough pressure to prioritize it against new features etc.. As I saved it in the back of my head anyway, we can also close the issue as long as nobody is actively working at it.
