### ISSUE TITLE
hw: sync thread delete and TLB flush

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1253]
By now, if a thread gets destructed while waiting for the completion of a TLB shoot-down in an SMP system, the unfinished TLB operations on remote CPUs might get lost. The destruction syscall should block until TLB shoot-down is done.

**Comment by skalk** [comment]
@m-stein: I wonder if there is such a use case at all. Actually, TLB flushes are done when altering the page tables only. But this always done by core-threads, which do not get destroyed at all. So I do not see the case that a thread currently doing a TLB flush will get destroyed. Maybe I oversee something?

**Comment by m-stein** [comment]
I agree that we do bot do it although it is theoretically possible to do it. So, how about at least giving the user a hint when he's doing it? This way, we couldn't silently fall into this hardly debuggable trap when doing future modifications.

**Comment by skalk** [comment]
@m-stein I do not see how to do this easily. But again, I do not see the issue. Actually, it is the core entrypoint only (doing unmap) that is using the corresponding kernel syscall and non-core threads are not allowed to use that call. So why should I implement some hand-stands for the case that the core entrypoint might get destructed in the future. I would say, this will be serious than anyway. I would like to close this issue.

**Comment by m-stein** [comment]
I've added it to the documentation of the syscall:
b8cd65d232 hw: fix documentation of Kernel::update_pd

**Comment by skalk** [comment]
Ok, thank you.
