### ISSUE TITLE
noux_tool_chain_auto.run enhancement proposal

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1277]
The Noux tool-chain test has a rather complex configuration that tries to adhere to several platform specifics, which are build target, boot time, worst-case build duration, and required tool chain. The current implementation aligns the build target with the tested platform, e.g., build hw_arndale on arndale (both hw and foc). IMO this makes the whole script much too complex and magic.

Therefore, I propose to change noux_tool_chain_auto to fix the configuration of the build target (preferably base-hw) and provide a working cross-compilation tool chain. The worst-case build duration and the assumed boot time may then be defined for each supported test platform plus test abort on missing configuration of `tool_chain_timeout` resp. `noux_boot_timeout`.

**Comment by chelmuth** [comment]
We discussed the current state of this issue briefly today and came up with the idea to replace the build of *core* for base-hw by a build target that does not change frequently like *app/scout* from the demo repo.

**Comment by alex-ab** [comment]
Addressed by #2601 now. May we close this issue ?

**Comment by chelmuth** [comment]
You're right, thanks.
