### ISSUE TITLE
base & arm: simplify and optimize cmpxchg

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1292]

**Comment by skalk** [comment]
@m-stein do you think we can close this?

**Comment by m-stein** [comment]
Hm, unfortunately I still don't see the point in not merging it. Although it might not be that much of an optimization it is definitely less redundancy and, as I think, better understandable.

**Comment by m-stein** [comment]
Btw. this is the result of some reading I had to do anyway in the context of another issue, so it would be a benificial side effect.

**Comment by skalk** [comment]
Ok, I did not want to devalue your work. Surely, it is better documented and maybe also a performance optimization. In that case, do you like to re-master the commit to staging and mark it as fixed?

**Comment by m-stein** [comment]
I didn't receive it as devalueing ;)
I see your points that there are more effectful optimizations but this is already done and I can't see why to waste the effort.

Here's a rebased version:
a8ab343331 base & arm: simplify and optimize cmpxchg
