### ISSUE TITLE
hw: provide readable identification of scheduling contexts

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1300]
This enables us to set scheduling subjects into the global context of threads, VMs and idle contexts when it comes to debugging. Although this isn't necessary for the working system, it should be added permanently as it is a pretty basic and often useful debugging feature which has no effect on the binaries when not used.

**Comment by skalk** [comment]
@m-stein as this is pretty outdated, I would like to close it. If there is pressure for more debug options we might re-open it. Do you agree?

**Comment by m-stein** [comment]
Sounds sensible.
