### ISSUE TITLE
Runtime dependency metadata

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1322]
How about documenting runtime dependencies for components?

Something like:
```abnf
componentGroup  = *component
component       = requiresService providesService libraries
libraries       = *library
library         = requiresService providesService libraries
requiresService = *service
providesService = *sevice
service         = *ALPHA
```

I'm missing things like libc and networking plugins but I'm not familiar with those yet.

I don't know much about XML but I know that with XSLT there are tools that could generate init configs if enough dependency info was present in XML (though possibly converted to XML from another format).

**Comment by nfeske** [comment]
How should we go about this issue?

**Comment by ehmry** [comment]
I think this is best approached as dynamic composition issue, and a solution will come when the problem is more pressing. I'm closing this issue because I think it would be a mistake to try and document this without real use for the information.
