### ISSUE TITLE
nic: report link state to enable network-stack reconfiguration

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1327]
Nic-service providers enabled to report if their link goes down or up, connected Nic clients can reconfigure their network settings via DHCP. This is esp. useful with the wifi_drv but also makes sense for LAN drivers.

**Comment by cnuke** [comment]
All components that provide a Nic session were adapted. For now, only lwIP will make use of the notification interface.

**Comment by cnuke** [comment]
@chelmuth or @nfeske please merge d8e74b5 to staging.

**Comment by chelmuth** [comment]
Done.

**Comment by cnuke** [comment]
@chelmuth or @nfeske please merge f6beb83 and 65b8550 to staging. These changes should calm the buildbot.

**Comment by cnuke** [comment]
@chelmuth please merge 0e8cae3 to staging.

**Comment by cnuke** [comment]
@chelmuth or @nfeske please merge 554be4d and 69a7d50 to staging.

**Comment by cnuke** [comment]
@chelmuth please also merge 0ecb0ad to staging.
