### ISSUE TITLE
Disable certificate checking when downloading ports

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1334]
Currently, we have an issue with red.libssh.org and wget/curl that can't validate the certificate information of the site. Firefox has no such problem. After some more investigations I discovered the problem from an _intermediate certificate_ from StartCom used to sign the server/node certificate for red.libssh.org (also discussed [here](http://security.stackexchange.com/questions/57535/why-do-i-need-to-install-the-startcom-intermediate-certificate)).

The issue could be fixed on server and client side by installing the intermediate certificate. But, I'd rather like to question if we should use certificate checking (or even HTTPS) when downloading third-party code as we check the archive integrity with our checksums anyway. Opinions?

**Comment by cnuke** [comment]
:+1: for using HTTP only for now.

In the long term, more server will probably switch to using HTTPS only (hence for obvious but arguably good reasons) I guess — so the issue with certificate checking will not go away.

**Comment by nfeske** [comment]
For protecting the integrity of the downloaded data, HTTPS does not add much value. The checksums are sufficient for that. The only advantage that HTTPS has over HTTP is that the mere information about which files are downloaded from the server is protected. I don't think that we should jump through hoops to hide this bit of information.

I agree to stay with HTTP for downloading libssh.

**Comment by chelmuth** [comment]
Unfortunately, the case of libssh is just like @cnuke apprehended: The download is available via HTTPS only. Even after the server admin fixed the certificate issue after I approached him, we still miss the SNI support in wget < 3.14 and, therefore, need to add `--no-check-certificate` for a successful download on Ubuntu 12.04 LTS :cry:
