### ISSUE TITLE
ldso: split main.cc into multiple headers

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1349]
Right now, the code of the dynamic linker looks very clean and well structured but it is still hard to comprehend as most of the code is contained in a single file: https://github.com/genodelabs/genode/blob/master/repos/base/src/lib/ldso/main.cc

To ease the review of the code by third parties, it would be beneficial to split the file into multiple headers - ideally one header per class. The header of each file should contain a brief description of the purpose of the class, maybe referencing certain sections of the ELF specification.

@ssumpf What do you think?

**Comment by ssumpf** [comment]
Sure, we could, for example, separate the dynamic section code, the shared-object interface, the exception handling support,  and the ELF objects (libs, binary, linker).

**Comment by nfeske** [comment]
Sounds good. I would like to leave the granularity up to you.

**Comment by ssumpf** [comment]
@nfeske: First version, please review.

**Comment by nfeske** [comment]
This looks superb! Thank you for reworking it. :-)

**Comment by chelmuth** [comment]
Merged to master.
