### ISSUE TITLE
ldso: ctors in shared libraries loaded for the 'Shared_object' API

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1350]
When loading a shared library via the ```Shared_object``` interface, I expect that global constructors contained in the library are executed. However, in the current version of the dynamic linker, this does not seem to happen.

**Comment by nfeske** [comment]
The commit https://github.com/nfeske/genode/commit/d62c2e3e9aef9b9435ce7bd4ab962fa642f03004 adds a corresponding test to ldso.run.

When executed (i.e., on base-linux), the test gets stuck at the construction of the ```Shared_object```.

**Comment by ssumpf** [comment]
@nfeske: Ok, I will look into that.

**Comment by ssumpf** [comment]
@nfeske, @chelmuth: Please cherry pick both commits.

**Comment by nfeske** [comment]
Why does the change of the run script appears in the first commit? Shouldn't this be part of the second one (the test)?

**Comment by chelmuth** [comment]
I merged both commits. Is that okay with you (both)?

**Comment by ssumpf** [comment]
@nfeske: That is because the run script changes where missing in your commit. As @chelmuth suggested, I would just squash the two of them.
