### ISSUE TITLE
hw vea9x4: remove trustzone support

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1351]

**Comment by m-stein** [comment]
Fixed by https://github.com/m-stein/genode/commit/9a4a0448bed1d71f7cf153632bc0b450c1214e14 that is based on staging.

Should fix recent builtbot problems with ``hw_vea9x4_tz`` ;)

**Comment by chelmuth** [comment]
That's unexpected (at least)...

**Comment by nfeske** [comment]
@skalk and @m-stein spoke with me about it earlier today. Right now, the vea9x4 TrustZone support is not in a state where we can run a large number of tests. To fix that, we'd require to invest a significant amount of time. But nobody is actually using TrustZone on this platform. So the work would not benefit anyone really. So we have two options:

* Keeping the TrustZone support for vea9x4, but untested (and thereby possibly broken)
* Removing it, keeping only things in base-hw that are thoroughly tested

I support the second option. Whenever someone needs to have TrustZone on the vea9x4 platform re-enabled, we still can revive the old code from our Git history.
