### ISSUE TITLE
AHCI driver lacks support for shared IRQs

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1352]
The current version of the AHCI driver opens an IRQ session at the startup but only occasional calls ```wait_for_irq``` - when it actually expects an interrupt. This approach has the problem that core / the kernel unmasks the interrupt of the IRQ session at the interrupt controller only during the call of ```wait_for_irq```. At all other times, the IRQ stays masked. This becomes a problem when the IRQ is shared by multiple drivers. In the presence of the AHCI driver, the IRQ stays masked all the time, except when the AHCI expects an interrupt. Other drivers suffer.

There are several possible solutions:

* Improve the AHCI driver to always call ```wait_for_irq``` and thereby unmask the IRQ for all drivers that may be interested in it. To do that, a dedicated thread is needed.
* Change the IRQ session interface to work asynchronously: IRQs could be delivered as signals and the drivers could acknowledge each IRQ via an RPC call. Core could initially unmask the IRQ (when the IRQ session is created), mask the IRQ when the signals are delivered to the clients, and unmask the IRQ again once all acknowledgements came in. Hence, this design change would implicitly fix the shared-IRQ issue for AHCI.
* Avoid the use of shared IRQs by using message-signalled interrupts (MSI)

I think we need a combination of all three solutions.

I propose to go for the second option first because the rework of the IRQ session interface has a number of additional benefits: It simplifies core (by avoiding IRQ proxy mechanism) and the drivers (by alleviating the need for IRQ threads). On the other hand, this is a quite far-reaching change. All base platforms and drivers must be touched.

The first line of work is necessary, too. Right now, the AHCI driver is in a pretty dire state. Ideally, it should be changed to use the server API, which change the entire structure of the driver.

The third point is of course the right way to go. But for the AHCI issue at hand, it is rather a work around than a fix. The shared-IRQ issue must still be addressed if we want to maintain the support for platforms with no MSI support.

**Comment by alex-ab** [comment]
Fixed with new ahci driver.
