### ISSUE TITLE
imx31: remove platform

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1360]
As already discussed on the mailing list, I'd like to remove this outdated and not used platform from Genode to reduce maintainance overhead.

**Comment by m-stein** [comment]
:+1:

**Comment by nfeske** [comment]
I agree.

**Comment by chelmuth** [comment]
I'll instantly merge your commit to staging!

**Comment by skalk** [comment]
@chelmuth : feel free to do so ;-)
