### ISSUE TITLE
AHCI doesn't work on (some) real hardware

### ISSUE THREAD

**Issue by NobodyIII** [genodelabs/genode#1362]
This is the problem I've talked about on the mailing list. Basically, AHCI doesn't work with my SSD. In my latest Genode scenario I've tested, I used a read-only version of test-blk-cli. The test gave no output. Here is the serial output from Genode:

Hello World.
Need 015d8000 bytes to relocate modules.
Relocating to bcb39000: 
Copying 260616 bytes...
Copying 10485760 bytes...
Copying 296724 bytes...
Copying 900576 bytes...
Copying 351204 bytes...
Copying 325488 bytes...
Copying 266228 bytes...
Copying 434196 bytes...
Copying 320292 bytes...
Copying 3514682 bytes...
Copying 463984 bytes...
Copying 136304 bytes...
Copying 1668924 bytes...
Copying 1079180 bytes...
Copying 296448 bytes...
Copying 297784 bytes...
Copying 263552 bytes...
Copying 313332 bytes...
Copying 1618 bytes...
Copying 483180 bytes...
Copying 242500 bytes...
Copying 392848 bytes...
Copying 56226 bytes...

Welcome to Fiasco(ia32)!
DD-L4(v2)/ia32 microkernel (C) 1998-2009 TU Dresden
Rev: rUNKNOWN compiled with gcc 4.7.2 for Intel Pentium    [] 
Performance-critical config option(s) detected:
  CONFIG_ASSEMBLER_IPC_SHORTCUT is off
  CONFIG_NDEBUG is off
  CONFIG_NO_FRAME_PTR is off
  CONFIG_FINE_GRAINED_CPUTIME is on

Enabling special fully nested mode for PIC
Using the PIT (i8254) on IRQ 0 for scheduling
SERIAL ESC: Using serial hack in slow timer handler.
SERIAL ESC: No IRQ for specified uart port.
Using serial hack in slow timer handler.
Absolute KIP Syscalls using: Sysenter
CPU: AuthenticAMD (15:2:0:0) Model: Unknown CPU at 3492 MHz

  48/512 Entry I TLB (4K pages)     24/512 Entry I TLB (4M pages)
  64/1024 Entry D TLB (4K pages)     64/1024 Entry D TLB (4M pages)
  64 KB L1 I Cache (2-way associative, 64 bytes per line)
  16 KB L1 D Cache (4-way associative, 64 bytes per line)
2048 KB L2 U Cache (8-way associative, 64 bytes per line)

Freeing init code/data: 20480 bytes (5 pages)

Calibrating timer loop... done.
SIGMA0: Hello!
  KIP @ 1000
  Found Fiasco: KIP syscalls: yes
  allocated 4KB for maintenance structures

KIP @ 1000
    magic: 4be6344c
  version: 87004444
         sigma0  esp: 002da72c  eip: 00104558
         sigma1  esp: 00000000  eip: 00000000
           root  esp: 00000000  eip: 010536ec
MBI @ 68000
 mod[3] [1212000,1212652) config
 mod[4] [1213000,125f7f4) init
 mod[5] [1260000,12a0580) timer
 mod[6] [12a1000,12e9b38) rom_blk
 mod[7] [12ea000,1332600) part_blk
 mod[8] [1333000,143a78c) rump.lib.so
 mod[9] [143b000,15d273c) rump_fs.lib.so
 mod[10] [15d3000,15f4470) rump_fs
 mod[11] [15f5000,1666470) ld.lib.so
 mod[12] [1667000,19c113a) fs_rom
 mod[13] [19c2000,1a10324) pci_drv
 mod[14] [1a11000,1a7b014) fb_drv
 mod[15] [1a7c000,1abcff4) ps2_drv
 mod[16] [1abe000,1b0d770) acpi_drv
 mod[17] [1b0e000,1b63be4) atapi_drv
 mod[18] [1b64000,1c3fde0) usb_drv
 mod[19] [1c40000,1c88714) ahci
 mod[20] [1c89000,2689000) ata.raw
 mod[21] [268a000,26c9a08) test-blk-cli-nowrite
:ram_alloc: Allocator 10760b8 dump:
 Block: [00063000,0006301c) size=0000001c avail=00000000 max_avail=00000000
 Block: [0006301c,00063038) size=0000001c avail=00000000 max_avail=00000000
 Block: [00063038,00063054) size=0000001c avail=00000000 max_avail=00000000
 Block: [00063054,00063070) size=0000001c avail=00000000 max_avail=00000000
 Block: [00063070,0006308c) size=0000001c avail=00000000 max_avail=00000000
 Block: [0006308c,000630a8) size=0000001c avail=00000000 max_avail=00000000
 Block: [000630a8,000630c4) size=0000001c avail=00000000 max_avail=00000000
 Block: [000630c4,000630e0) size=0000001c avail=00000000 max_avail=00000000
 Block: [000630e0,000630fc) size=0000001c avail=00000000 max_avail=69400000
 Block: [000630fc,00063118) size=0000001c avail=00000000 max_avail=00000000
 Block: [00063118,00063134) size=0000001c avail=00000000 max_avail=00000000
 Block: [00063134,00063150) size=0000001c avail=00000000 max_avail=00000000
 Block: [00063150,0006316c) size=0000001c avail=00000000 max_avail=00000000
 Block: [0006316c,0006356c) size=00000400 avail=00000000 max_avail=00000000
 Block: [0006356c,00063588) size=0000001c avail=00000000 max_avail=00035fe4
 Block: [00063588,000635a4) size=0000001c avail=00000000 max_avail=00000000
 Block: [000635a4,00068000) size=00004a5c avail=00004a5c max_avail=00004a5c
 Block: [00069000,0006901c) size=0000001c avail=00000000 max_avail=00035fe4
 Block: [0006901c,0009f000) size=00035fe4 avail=00035fe4 max_avail=00035fe4
 Block: [0010a000,0010a01c) size=0000001c avail=00000000 max_avail=69400000
 Block: [0010a01c,0010a038) size=0000001c avail=00000000 max_avail=00000000
 Block: [0010a038,01000000) size=00ef5fc8 avail=00ef5fc8 max_avail=00ef5fc8
 Block: [01087000,0108701c) size=0000001c avail=00000000 max_avail=69400000
 Block: [0108701c,01212000) size=0018afe4 avail=0018afe4 max_avail=0018afe4
 Block: [026ca000,40000000) size=3d936000 avail=3d936000 max_avail=69400000
 Block: [50000000,b9400000) size=69400000 avail=69400000 max_avail=69400000
 => mem_size=2816417792 (2685 MB) / mem_avail=2816416236 (2685 MB)
:region_alloc: Allocator 10771e8 dump:
 Block: [00002000,00063000) size=00061000 avail=00061000 max_avail=00061000
 Block: [0009f000,0010a000) size=0006b000 avail=0006b000 max_avail=06c00000
 Block: [01abd000,01abe000) size=00001000 avail=00001000 max_avail=00001000
 Block: [02689000,0268a000) size=00001000 avail=00001000 max_avail=06c00000
 Block: [b9400000,c0000000) size=06c00000 avail=06c00000 max_avail=06c00000
 => mem_size=114089984 (108 MB) / mem_avail=114089984 (108 MB)
:io_mem: Allocator 1076504 dump:
 Block: [00000000,00001000) size=00001000 avail=00001000 max_avail=00001000
 Block: [00002000,00063000) size=00061000 avail=00061000 max_avail=00061000
 Block: [0009f000,0010a000) size=0006b000 avail=0006b000 max_avail=46bfffff
 Block: [01abd000,01abe000) size=00001000 avail=00001000 max_avail=00001000
 Block: [02689000,0268a000) size=00001000 avail=00001000 max_avail=46bfffff
 Block: [b9400000,ffffffff) size=46bfffff avail=46bfffff max_avail=46bfffff
 => mem_size=1187835903 (1132 MB) / mem_avail=1187835903 (1132 MB)
:io_port: Allocator 1076950 dump:
 Block: [00000000,00010000) size=00010000 avail=00010000 max_avail=00010000
 => mem_size=65536 (0 MB) / mem_avail=65536 (0 MB)
:irq: Allocator 1076d9c dump:
 Block: [00000000,00000010) size=00000010 avail=00000010 max_avail=00000010
 => mem_size=16 (0 MB) / mem_avail=16 (0 MB)
:rom_fs: Rom_fs 107762c dump:
 Rom: [012ea000,01332600) part_blk
 Rom: [01667000,019c113a) fs_rom
 Rom: [01b0e000,01b63be4) atapi_drv
 Rom: [01c40000,01c88714) ahci
 Rom: [01abe000,01b0d770) acpi_drv
 Rom: [01c89000,02689000) ata.raw
 Rom: [01212000,01212652) config
 Rom: [01a11000,01a7b014) fb_drv
 Rom: [00001000,00002000) l4v2_kip
 Rom: [01213000,0125f7f4) init
 Rom: [015f5000,01666470) ld.lib.so
 Rom: [01333000,0143a78c) rump.lib.so
 Rom: [01a7c000,01abcff4) ps2_drv
 Rom: [019c2000,01a10324) pci_drv
 Rom: [012a1000,012e9b38) rom_blk
 Rom: [0143b000,015d273c) rump_fs.lib.so
 Rom: [015d3000,015f4470) rump_fs
 Rom: [01260000,012a0580) timer
 Rom: [0268a000,026c9a08) test-blk-cli-nowrite
 Rom: [01b64000,01c3fde0) usb_drv
:core ranges: Allocator 10797ac dump:
 Block: [00063000,00068000) size=00005000 avail=00005000 max_avail=00005000
 Block: [00069000,0009f000) size=00036000 avail=00036000 max_avail=00036000
 Block: [0010a000,01abd000) size=019b3000 avail=019b3000 max_avail=69400000
 Block: [01abe000,02689000) size=00bcb000 avail=00bcb000 max_avail=00bcb000
 Block: [0268a000,40000000) size=3d976000 avail=3d976000 max_avail=69400000
 Block: [50000000,b9400000) size=69400000 avail=69400000 max_avail=69400000
 => mem_size=2838687744 (2707 MB) / mem_avail=2838687744 (2707 MB)
Genode 14.11-9-g36ca049 <local changes>
int main(): --- create local services ---
int main(): --- start init ---
int main(): transferred 2685 MB to init
int main(): --- init created, waiting for exit condition ---
[init] parent provides
[init]   service "ROM"
[init]   service "LOG"
[init]   service "CAP"
[init]   service "RAM"
[init]   service "RM"
[init]   service "CPU"
[init]   service "PD"
[init]   service "IRQ"
[init]   service "IO_PORT"
[init]   service "IO_MEM"
[init]   service "SIGNAL"
[init] child "acpi"
[init]   RAM quota:  134053888
[init]   ELF binary: acpi_drv
[init]   priority:   0
[init]   provides service PCI
[init]   provides service IRQ
[init] child "timer"
[init]   RAM quota:  134053888
[init]   ELF binary: timer
[init]   priority:   0
[init]   provides service Timer
[init] child "rom_blk"
[init]   RAM quota:  33390592
[init]   ELF binary: rom_blk
[init]   priority:   0
[init]   provides service Block
[init] child "ahci"
[init]   RAM quota:  134053888
[init]   ELF binary: ahci
[init]   priority:   0
[init]   provides service Block
[init] child "test-blk-cli-nowrite"
[init]   RAM quota:  134053888
[init]   ELF binary: test-blk-cli-nowrite
[init]   priority:   0
[init -> acpi] available memory for ACPI 2048 kiB, for PCI_DRV 128572 kiB
[init] child "timer" announces service "Timer"
[init] child "rom_blk" announces service "Block"
[init -> ahci] --- AHCI driver started ---
[init] child "ahci" announces service "Block"
[init -> acpi] void Acpi_table::_parse_tables(T*, Genode::uint32_t) [with T = uT
[init -> acpi] MADT IRQ 0 -> GSI 2 flags: 0
[init -> acpi] MADT IRQ 9 -> GSI 9 flags: f
[init -> acpi] void Acpi_table::_parse_tables(T*, Genode::uint32_t) [with T = uG
[init -> acpi] MCFG BASE 0xe0000000 seg 00 bus 00-ff
[init -> acpi -> pci_drv] PCI driver started
[init -> acpi -> pci_drv] Could not open file "pci_device_pd"
[init -> acpi -> pci_drv] PCI device protection domain for IOMMU support is note
[init -> acpi -> pci_drv] 00 BDF start 0, functions: 0x10000, physical base 0xe0
[init -> acpi] ACPI table format is supported - rewrite GSIs
[init -> acpi] Rewriting 01:00.0 IRQ: 10 -> GSI: 24
[init -> acpi] Rewriting 01:00.1 IRQ: 11 -> GSI: 25
[init -> acpi] Rewriting 02:00.0 IRQ: 10 -> GSI: 48
[init -> acpi] Rewriting 03:05.0 IRQ: 10 -> GSI: 20
[init -> acpi] Rewriting 05:00.0 IRQ: 11 -> GSI: 19
[init] child "acpi" announces service "PCI"
[init] child "acpi" announces service "IRQ"
[init -> ahci] Found AHCI HBA (Vendor ID: 1002 Device ID: 4391 Class: 00010601)
[init -> ahci] Port 0: ATAPI no
[init -> ahci] Port 0: Detected interface is active
[init -> ahci] AHCI Version: 1.0200
[init -> ahci] CAPs:
[init -> ahci]  Port count: 4
[init -> ahci]  Command slots: 32
[init -> ahci]  AHCI only: yes
[init -> ahci]  Native command queuing: yes
[init -> ahci]  64 Bit: yes

Note that the scenario works perfectly with rom_blk, so configuration isn't the issue.

**Comment by skalk** [comment]
When looking at your log output, I can see that you start rom_blk as well as ahci. Both components announces a block service. Would you please provide your run script too?

**Comment by NobodyIII** [comment]
I can't right now, but ROM_blk is there so I can easily switch between it
and AHCI. My configuration should not be the issue.

**Comment by skalk** [comment]
It would be nice anyway to take exactly your configuration to reproduce your results. Please post it as soon as you have access to it again. Thanks in advance.

**Comment by NobodyIII** [comment]
Here it is.

On Wed, Jan 14, 2015 at 11:09 AM, Stefan Kalkowski <notifications@github.com

**Comment by chelmuth** [comment]
@NobodyIII the files did not make it to Github. I suggest you open a https://gist.github.com/ and post the link in this thread.

**Comment by NobodyIII** [comment]
Here is a Google Drive link.
   config
<https://docs.google.com/file/d/0Byr3WX_C3550WGlXZ2doUDNVWGtZQnFwWFVUTHBQaDVZZS00/edit?usp=drivesdk>
On Jan 15, 2015 2:20 AM, "Christian Helmuth" <notifications@github.com>
wrote:

@NobodyIII <https://github.com/NobodyIII> the files did not make it to
Github. I suggest you open a https://gist.github.com/ and post the link in
this thread.

—
Reply to this email directly or view it on GitHub
<https://github.com/genodelabs/genode/issues/1362#issuecomment-70059020>.

**Comment by chelmuth** [comment]
This issue applies to the old AHCI driver. Reopen for the new driver if the issue persists.
