### ISSUE TITLE
lxip: fix udp poll

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1371]
The sock_op poll operation expects as first argument a pointer to a `struct file` object. The poll implementation of the TCP protocol ignores this argument whereas the UDP protocol checks the f_flags field. Up to now our port always used `0` as argument which ends in a NULL-pointer dereference in the
UDP implementation if a UDP socket is polled.

**Comment by nfeske** [comment]
It would be nice to have a short description of the symptom that is solved by the fix in the description of the issue.

**Comment by chelmuth** [comment]
From the commit message, I would expect a NULL-pointer dereference, right?
