### ISSUE TITLE
hw: print useful information if an unresolvable page fault occurs

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1382]
Right now, core on base-hw merely prints a brief message when a thread dies because of an unresolvable page fault

```
void Genode::Pager_object::unresolved_page_fault_occurred(): not implemented
unknown signal context
```

On NOVA, the response of core is far more useful:

```
virtual void Genode::Signal_session_component::submit(Genode::Signal_context_capability, unsigned int): invalid signal-context capability
static void Genode::Pager_object::_page_fault_handler(): unhandled page fault, 'pager:Command Terminal' address=0xa03fd8c0 ip=0x10a4327
```

It would be nice to have such diagnostic information available on base-hw, too.

**Comment by chelmuth** [comment]
Hm, did you settle on 102b9bf? Still missing the *confirmed* flag here and in #1406.
