### ISSUE TITLE
hw: support for large physical address extension

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1387]
ARM's large physical address extension (LPAE) is a prerequisite to support ARM's virtualization extensions.

**Comment by skalk** [comment]
@m-stein I've updated and rebased the commits according to your suggestions, would you please check it once more resp. confirm it?

**Comment by m-stein** [comment]
@skalk: Thank you for your modifications :)

**Comment by skalk** [comment]
@nfeske : I've rebased it to staging again, please apply above commits first before applying additional base-hw changes.

**Comment by nfeske** [comment]
Merged to staging.
