### ISSUE TITLE
File system node locking

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1388]
Ported programs will inevitably need to lock files to prevent race conditions between processes.

A simple way to do it would be lock files (the file x is locked when the file x.lock is present), but without access to global process information I think would be difficult to identify stale locks.

A server that stores lock information and proxies File_system service to another File_system server seems reasonable to me. It would add some overhead but I would think it could be applied conservatively through a VFS policy.

**Comment by nfeske** [comment]
I like your proxy idea. This way, the file-system session interface could probably stay clean of the locking feature.

**Comment by ehmry** [comment]
If I need it, I'll implement it.
