### ISSUE TITLE
foc: l4android doesn't compile nor run

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1390]
Currently, the compiler argues about the Genode ballooning driver, which was developed using l4linux and a more recent version of Linux. Moreover, it bleats about a cxx library related issue that was already fixed for L4Linux with commit eab8217bdb9f186d94840d038d915f2dd7d473ca

**Comment by li94575** [comment]
I have replaced the funtion "l4re_ma_alloc" with previous version, namely, all memory is allocated once. and that error has gone, I don't know if it will affect other parts.

**Comment by skalk** [comment]
@li94575 would you try out above commit 2858242 ? You will need to prepare l4android once more, I've moved our patches to a git clone of l4android.org.

**Comment by li94575** [comment]
OK, I'll try out above commit, and prepare l4android again.

**Comment by czzcz** [comment]
When prepared L4android ,  I got a fatal error: reference is not a tree...
I guess there is something wrong with your git url.

**Comment by skalk** [comment]
sorry, I've missed one update of the tree, now it's commit 60e5ec532d0094fc8e9906b5ddbd5e066a8143e9

**Comment by li94575** [comment]
@skalk I have tested the new l4android with your patches, that error did not appear. Thank you!  Can you tell me which files have been changed in l4android?
