### ISSUE TITLE
rump: Fix startup latency

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#1393]
On some kernels rump requires up to 10 seconds to bootstrap.

**Comment by m-stein** [comment]
@nfeske: I've added a [fixup](https://github.com/m-stein/genode/commit/df429f501bb5641f97cd52696b81aaeffc450c0d) that should fix problems with hw.rump_ext2.

**Comment by nfeske** [comment]
@m-stein this should not be a fixup for the rump-fs commit but rather than an individual commit, don't you think so? If you agree, I would change the commit message accordingly.

**Comment by m-stein** [comment]
:+1:
