### ISSUE TITLE
hw: platform ODROID XU kernel does not come up

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1396]
Due to needless redundancy between the boards Arndale and ODROID XU, several changes made and tested via Arndale did not reached the code base of ODROID although both are quite similar, as they ground on Exynos5 SoC.

To prohibit such regression, I vote for eliminating all code duplication of both platforms.

**Comment by m-stein** [comment]
:+1:

**Comment by skalk** [comment]
was confirmed by m-stein
