### ISSUE TITLE
pistachio: Does not boot on platforms with +4GB of RAM

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#1402]
Bender relocates boot modules at to the highest possible free physical memory region. Since core identity maps the modules, it might end up accessing kernel reserved memroy (>=0xc0000000).

**Comment by nfeske** [comment]
@ssumpf Could you please add a link to the modified bender source code here?

**Comment by alex-ab** [comment]
@nfeske: please replace the original commit by the new one.

**Comment by nfeske** [comment]
@alex-ab I actually had to cherry-pick your patch atop of the original commit. I have squashed both into one commit and pushed the result to staging.

**Comment by alex-ab** [comment]
@nfeske: please add also to staging - humanreadable message if this overlap of regions happens next time

**Comment by alex-ab** [comment]
@nfeske: please add the fixup commit to staging "fixup nova: detect overlapping module regions"

**Comment by chelmuth** [comment]
@alex-ab I double-checked that the sha1sum of _tool/boot/bender_ is as in _origin/staging_ this morning after the adventurous binary merge conflict. For the log it was 8dc9c194036f8040b52318c2cb9267b9e05cc41d.

**Comment by alex-ab** [comment]
Confirmed.
