### ISSUE TITLE
Noux: exit with init child

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1408]
Noux currently does not exit when its first child exits.

I fixed that but I get an error thrown after Noux main returns:
C++ runtime: Genode::Signal_receiver::Context_not_associated

Needed for https://github.com/genodelabs/genode/issues/1399

**Comment by ehmry** [comment]
I didn't actually fix it, it seems the standard io channels need to be taken care of before the init child gets destroyed.

**Comment by ehmry** [comment]
Fixed at https://github.com/ehmry/genode/commit/f2257bc566d348b78642dc56aab0bf1435815487

**Comment by chelmuth** [comment]
Merged it to staging.

**Comment by chelmuth** [comment]
46858cf made it into master. Can we close the issue?

**Comment by ehmry** [comment]
Yes
