### ISSUE TITLE
hw & odroid_xu: network tests fail

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1410]

**Comment by m-stein** [comment]
I've fixed all compile and config problems but the network tests (*lwip*/*lxip*) get stuck after
```
[init -> usb_drv] Services::Services(): No <hid> config node found - not starting the USB HID (Input) service
[init -> usb_drv] Services::Services(): No <storage> config node found - not starting the USB Storage (Block) service
[init -> usb_drv] Services::Services(): No <raw> config node found - not starting external USB service
[init -> usb_drv] Enabled EHCI (USB 2.0) support
[init -> usb_drv] Using configured mac: 02:00:00:00:01:01
```
I assume the platform driver or USB driver implementation to differ between Arndale and Odroid-XU and my simple approach to merge both into Exynos5 is bad.

**Comment by m-stein** [comment]
@ssumpf: My [branch](https://github.com/m-stein/genode/tree/1410_hw_odroid_xu_network_tests_fail).

**Comment by skalk** [comment]
I do not think we concentrate on this anymore, and therefore will close it.
