### ISSUE TITLE
sanitize affinity location information in core and init

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1412]
Currrently it is possible to set via the cpu_session()->affinity(...) almost arbitary coordinates which will be out of range of available physical cpus. Question: should this sanitization be done in the affinity() method or should each platfrom take care (hw, foc, nova, etc) ?

**Comment by alex-ab** [comment]
@nfeske: may you please review dd7daf3ad5be5911a299abcbb4aa93ee964540b0 and 2e08ebab8d6d848b31ab6701cdd9c30150291c0f

**Comment by alex-ab** [comment]
I updated the commits according to @nfeske comments: dd7daf3ad5be5911a299abcbb4aa93ee964540b0, 89f2665b9e281afd131dd7c42f81358f52a4beba and 3b593c1d81be3d31bad0ff104f58880388ff6b41

**Comment by alex-ab** [comment]
Sorry, had to clean up left over in the commits, just see issue_1412 branch.

**Comment by nfeske** [comment]
Super! Thanks for extending the test program also. I merged your commits to staging now.

**Comment by alex-ab** [comment]
commits entered master

**Comment by alex-ab** [comment]
@chelmuth: dea09d4cc685591d86b0215354802d32f6826984 contains the discussed fix
