### ISSUE TITLE
fb_sdl: improve configuration

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1414]

**Comment by chelmuth** [comment]
Looks good for me, so i labeled it _fixed_. I'll merge it to our staging branch soon. BTW if your commit message contained `Fixes #1414`, the issue would be closed automatically when the commit enters the master branch. Our common workflow uses this feature regularly.

**Comment by ehmry** [comment]
Good to know. With this I thought there might be other issues with sdl that could be addressed so I left it open.

**Comment by chelmuth** [comment]
The identified issue was fixed and is in master and, therefore, I close the issue. Please feel free to re-open if other configuration option come up.
