### ISSUE TITLE
jitterentropy port update

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1416]
The jitterentropy collection allocator was hanging for me under certain conditions on NOVA, and updating the library fixed it for me.

Upstream changelog shows that improvments have been made: http://chronox.de/jent.html

**Comment by chelmuth** [comment]
According to the chronox site [version 1.2.0](http://chronox.de/jent/jitterentropy-1.2.0.tar.xz) of the library is out. Retrospective, I wonder what made us hesitate to merge the update to 1.1.0, @cnuke?

**Comment by cnuke** [comment]
There is no particular reason IIRC, it probably just slipped our mind because it is not marked as fixed.

**Comment by ehmry** [comment]
I can bump this to 1.2.0 when I get a chance.

**Comment by ehmry** [comment]
That should do it.

**Comment by chelmuth** [comment]
Merged into staging.

**Comment by chelmuth** [comment]
Made it into 15.05
