### ISSUE TITLE
foc: thread test succeeds although not all threads got constructed correctly

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1418]
```
[2015-02-23 23:59:24] thread alloc failed
```

**Comment by chelmuth** [comment]
Which phase of the thread test triggers the failed allocation? `test_context_alloc` creates many threads just to stress the context allocator and does not represent a real use case. IMO 64 threads is already a rather big number for one component.

**Comment by alex-ab** [comment]
So, you mean we should just limit the test case up to 64 parallel starting threads ? Currently it could be 90.

**Comment by chelmuth** [comment]
No objections from my side but I'm curious what @nfeske thinks about it.

**Comment by nfeske** [comment]
I am fine with reducing the maximum number of threads in the test,

But I have another thought: If the test is indeed meant to stress the context allocator, wouldn't it be a good idea to test the corner case where no additional context can be allocated? This corner case could be provoked without the need to create too many physical threads. Instead, we can trigger it via the ```alloc_secondary_stack``` function. That said, I do not propose to extend the test right away. I just wanted to record the idea somewhere.
