### ISSUE TITLE
init: invalid route to non-existing server

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1423]
Just now I had a typo in the routing declaration of a child in a very restrictive run script: no default routes, no wildcards. Therefore, I was surprised that everything worked as intended before and after I fixed `time` to `timer`. The only hint was
```
[init] launcher: invalid route to non-existing server "time"
```
in the log. The reason is that _init.h:672_ only prints the warning but continues to lookup the service in the registry with `Genode::Server *server == 0`. `Service_registry::find()` then acts like documented and returns any matching server per default.

I doubt this is intended behavior as I explicitly stated to route the service request into Nirwana and had no wildcards/defaults. IMO we should print the warning and fail like in the other cases. What's your opinion?

**Comment by nfeske** [comment]
It looks like a bug, indeed.
