### ISSUE TITLE
vbox: replace too strict assertion with debug message 

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#1426]
The 'continue_hw_accelerated' assertion at the end of the recall handler can fail if the 'Timer' thread has set a 'forced action pending' flag in the meantime, which is not an error.

**Comment by chelmuth** [comment]
I experienced this assertion too. Shouldn't we adapt the `Assert` condition according to your findings, i.e., assert that no flag beside _forced timer action pending_ is set?

**Comment by cproc** [comment]
I'm not sure if it is really an error if any of the flags is set.

**Comment by chelmuth** [comment]
So, we should find out ;-)

**Comment by cproc** [comment]
Commit 5e43f80d073b1fa4e4c4b4cc581fc246ece0902a replaces the assertion with a debug message, which gets printed if any of the 'not yet verified as safe' flags is set.
