### ISSUE TITLE
libssh: git repo for source retrieval

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1428]
http://red.libssh.org is extremely shaky these days. On the other hand, the Git repository at http://git.libssh.org/projects/libssh.git is a different server and has GPG-signed release tags. Therefore, I propose to switch from tarball download to a Git clone.

**Comment by skalk** [comment]
@chelmuth: how about cherry-picking this fixup so that the buildbot does not complain about "port_check" anymore?
