### ISSUE TITLE
Tool to check all port's remote sources availability

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1430]
Such a tool would allow to regularily check for all remote 3rd party sources, independend of the 'prepare_port' tool. The tool should not download everthing, but just look whether the remote resources are available.

**Comment by chelmuth** [comment]
With the two commits above all ports except the broken libssh are checked successfully.

**Comment by skalk** [comment]
@chelmuth: thanks for the fixups!

**Comment by chelmuth** [comment]
You're welcome ;-)
