### ISSUE TITLE
Unify indentation of the Genode API headers

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1432]
For the semi-automatic generation of the functional specification for the forthcoming Genode documentation, I desire a uniform way of how namespaces and classes are indented. In many old places, we still use the old-fashioned way:

```
namespace Genode {
  class Foo
  {
    ...
  };
}
```

Newer code follows a different pattern:

```
namespace Genode { class Foo; }

class Genode::Foo
{
  ...
};
```

We should keep only the latter style in our code.

**Comment by m-stein** [comment]
:+1:
