### ISSUE TITLE
gdb: port preparation generates files into Genode source repository

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1435]
In general, generated files should not end up in Genode's source repository. In this specific case it is especially not wanted, if you share a contrib directory between several Genode source repositories. In case of our nightly buildbot: it re-uses the same contrib directory every night without the need to prepare again and again. The current state prevents several platforms from compiling `repos/ports/src/lib/gdbserver_platform`.

**Comment by nfeske** [comment]
Wouldn't it be possible to perform the generating step at the build time? In my opinion, it would be preferable to avoid custom make rules in the port files.

**Comment by cproc** [comment]
With commit 6fd56966f626063bcc820669269385fc419d4587, the files get generated at build time.

**Comment by nfeske** [comment]
Thanks! I merged your new commit to staging.

**Comment by skalk** [comment]
Using the new solution after preparing GDB I get the following error when compiling `run/gdb_monitor`:

```
  Library gdbserver_platform
    COMPILE  gdbserver_platform_helper.o
    COMPILE  linux-x86-low.o
    COMPILE  okl4_x86_low.o
    MERGE    libc_lock_pipe.lib.so
    MERGE    gdbserver_platform.lib.a
/usr/local/genode-gcc/bin/genode-x86-ar: i386-avx.o: No such file or directory
make[2]: *** [gdbserver_platform.lib.a] Error 1
make[1]: *** [gdbserver_platform.lib] Error 2
make[1]: *** Waiting for unfinished jobs....
    MERGE    libc_terminal.lib.so
```

**Comment by cproc** [comment]
Commit beb001433df6d6f8eb85b65159a97f32a2763400 should fix the problem.

@nfeske, @chelmuth: please rename the commit message of the merged commit to 'gdb: save generated files in the build directory'
