### ISSUE TITLE
vbox: wait longer for stable timer state

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#1437]
Some functions in the time manager, for example 'TMTimerSet()' and 'TMTimerStop()' let VirtualBox abort with a failed assertion if the timer does not change to a 'stable' state after 1000 calls of a mixture of 'yield' and 'nanosleep'. On Genode, this happens sometimes when the 'EMT' thread is executing 'TMTimerSet()' and gets interrupted by the 'TAP' thread, which calls 'TMTimerStop()' and waits for the 'EMT' thread to finish setting the timer. Since the 'EMT' thread has the lowest priority, 1000 retries can be too few. Without the assertion, these functions would return an error code, which is often ignored by the caller, so it seems safer to keep retrying until the function can return successfully.

**Comment by nfeske** [comment]
Wouldn't the excellent commit message a candidate for an in-source comment?

On another note, could you please rebase the patch on the current staging branch? Unfortunately, it conflicts with alex` recent patch.

**Comment by cproc** [comment]
@nfeske: I've rebased the commit and added the comment to the patch file
