### ISSUE TITLE
hw: init_main_thread functions missing in core

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1440]
As @reet- pointed out in the current implmentation of base-hw/core the exception handling is not initialized, which is no problem on ARM platforms, but on x86. Moreover, initial calls done on all other platforms like env_context_area_rm_session() to reserve core's context area are lost in base-hw's core.

**Comment by m-stein** [comment]
Except the two suggestions in the commit I'm fine with it.

**Comment by skalk** [comment]
@m-stein : reworked it

**Comment by m-stein** [comment]
Thank you :)
