### ISSUE TITLE
vbox: support multi touch input events

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1444]
Enable support in virtualbox and our usb driver to process multi touch input events. That would enable us to use gestures in (Windows) guests.

**Comment by alex-ab** [comment]
This version based on staging works now reliable. Please review the input interface changes. Especially the signalling of the end of a touch event I don't like until now. Better suggestions are welcome.

**Comment by alex-ab** [comment]
@nfeske, @chelmuth : changed the commits according to your comments

**Comment by nfeske** [comment]
This looks very good. Unfortunately, commit c10a0df25f0ee1da9069aa1f875f27e2e110da86 does not apply on the current staging branch. Could you please rebase this commit?

**Comment by alex-ab** [comment]
@nfeske: use f4a2bfaa722c2d6a982fb5837f796bc8f59e29f4

**Comment by nfeske** [comment]
Thanks, merged to staging.

**Comment by nfeske** [comment]
I get the following warning when compiling the window manager now:

```
In file included from repos/gems/src/server/wm/main.cc:32:0:
/repos/gems/src/server/wm/nitpicker.h: In member function ‘Input::Event Wm::Nitpicker::Session_component::_translate_event(Input::Event, Wm::Nitpicker::Point)’:
repos/gems/src/server/wm/nitpicker.h:471:11: warning: enumeration value ‘TOUCH’ not handled in switch [-Wswitch]
```

**Comment by alex-ab** [comment]
@nfeske: use the fixup

**Comment by alex-ab** [comment]
@nfeske: actually 7487c745ea7b823526fcd21c5007dedb4dcea060 is the better one
