### ISSUE TITLE
Cpu_state inconsistency

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1452]
The `Cpu_state` class in cpu/cpu_state.h is defined slightly inconsistent across CPU architectures. In base/include/arm/cpu/cpu_state.h, all member variables are uninitialized whereby in base/include/x86_32/cpu/cpu_state.h and base/include/x86_64/cpu/cpu_state.h, all member variables are initialized with 0. Which approach is correct?

**Comment by skalk** [comment]
The initialization is surely the favored approach. I've changed and tested the ARM cpu_state accordingly in above commit.

**Comment by skalk** [comment]
@chelmuth I've updated the commit according to your comment.
