### ISSUE TITLE
linux: log diagnostic message on exceptions (e.g. segmentation fault)

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1457]
Debugging segmentation faults and friends under base-linux usually surprises new developers as Genode's log does not contain any hints about the occurred exception. The attached patch offers a base line solution that logs the fact an exception will terminate the process and hints to have a look into the Linux kernel log for more information.

The signal-handling mechanism in Linux is able to provide more information about the exception but this requires to use the more complex `sigaction` variant and more invasive changes in `linux_syscalls.h` resp. source code using `lx_sigaction`.

**Comment by nfeske** [comment]
Cool!
