### ISSUE TITLE
i.MX53: SD-card driver

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1458]

**Comment by m-stein** [comment]
The driver for the Freescale eSDHCv2 doesn't support the highest available bus frequency by now and also the bus width may be set to a higher value but that needs further checks on the capabilities of the inserted card.

The commits provide a benchmark as it exists for the OMAP4 SDHC driver.

**Comment by m-stein** [comment]
Modified last commit according to comment by @chelmuth.

**Comment by chelmuth** [comment]
Merged to staging.

**Comment by chelmuth** [comment]
Sorry for noise last night - I missed to cherry-pick cba831d4 yesterday.
