### ISSUE TITLE
Consider exposing the retry template of platform_env_common.h to the public API

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1461]
The retry template function is handy in situations when we need to upgrade session quota on demand: https://github.com/genodelabs/genode/blob/master/repos/base/src/base/env/platform_env_common.h#L35

For example, the fix of issue #1247 would benefit from it.

**Comment by m-stein** [comment]
:+1:Had this problem too recently.

**Comment by nfeske** [comment]
Fixed by https://github.com/genodelabs/genode/commit/217f62b89d3baa17a8bcdb527ba780f5a4af553c in master
