### ISSUE TITLE
hw: i.MX6 support

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1467]

**Comment by m-stein** [comment]
Updated the port according to the suggestions and added a clean-up commit not directly related to the port.

**Comment by m-stein** [comment]
@skalk: What do you think.

**Comment by skalk** [comment]
I'm fine with it

**Comment by m-stein** [comment]
@skalk

I've added a fix-up that should fix build-bot problems with ``imx53_qsb_tz``. Thanks for the hint.

**Comment by m-stein** [comment]
@nfeske 

Can we merge the fix-up?
