### ISSUE TITLE
docs: Broken link in coding style

### ISSUE THREAD

**Issue by wolfgang42** [genodelabs/genode#1468]
Kensan in #genode reported that the following link in `doc/coding_style.txt` is broken:
http://web.archive.org/web/20050311153439/http://electroly.com/mt/archives/000002.html

Unfortunately, a lack of archive.org makes it difficult to find out what this was supposed to be pointing to.

**Comment by nfeske** [comment]
Thanks for the report. In the commit above, replaced the link with a brief example.
