### ISSUE TITLE
base-host does not even compile

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1476]
Do we still need base-host? Currently it does not compile, is never tested, and AFAIK not used at all.

**Comment by nfeske** [comment]
I think we can remove it. The intention behind base-host was to document the interface between the generic and platform-specific part of the base framework. But in hindsight, this role was never really important - and neither was it accomplished by base-host (as evidenced by your issue).

**Comment by chelmuth** [comment]
:+1: for the removal

**Comment by m-stein** [comment]
:+1:
