### ISSUE TITLE
pci: provide all resources via the platform driver

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1487]
Beside irq, all resources like io_port and io_mem should be provided via the pci driver

**Comment by nfeske** [comment]
Hats off! This is shaping up very nicely. :-)

**Comment by alex-ab** [comment]
@nfeske, @chelmuth : all changes are rebased to staging - this 1487 branch contains the all changes regarding pci (#1471, #1486, #755, #1487)

**Comment by alex-ab** [comment]
@nfeske, @chelmuth : please add commits from issue_1487_staging to staging, I adjusted all the autopilot run scripts accordingly
