### ISSUE TITLE
hw: separate declaration from implementation in kernel

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1492]
A lot of kernel related headers contain most of the function's implmentation. Thereby a lot of object member functions are implicitely inlined and increase the kernel/core's text segment. Moreover, every change of a function implies a lot of compilation units have to be recompiled. Last but not least it is often impossible to use certain functionality because of circular dependencies.

**Comment by m-stein** [comment]
Good direction. I did some minor changes. Do you agree?

**Comment by m-stein** [comment]
@skalk 
Good direction. I did some minor changes. Do you agree?

**Comment by skalk** [comment]
@m-stein sure

**Comment by chelmuth** [comment]
Merged to staging.

**Comment by m-stein** [comment]
@skalk, @chelmuth 
I've added two fixes for the recent HW compile errors on build-bot.

**Comment by m-stein** [comment]
@chelmuth 
Another fixup https://github.com/m-stein/genode/commit/845bc536945e872d692a5e4ab674c32273b5a31a. Thank you for the hint.
