### ISSUE TITLE
hw: acknowledge IRQs via Kernel::ack_irq

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1493]

**Comment by chelmuth** [comment]
Fixed without commit?

**Comment by m-stein** [comment]
I don't wanted to encourage others to fix it but also don't want the commit to go to staging because someone else who doesn't like re-basing would have to re-base.

**Comment by m-stein** [comment]
@skalk 
Do you agree with the commit?

**Comment by skalk** [comment]
@m-stein yes I'm fine with it.
