### ISSUE TITLE
thread self-destruction causes core crash on Fiasco.OC

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#1495]
Related to issue #633, but not only a pthread problem: when a thread calls 'Cpu_session::kill_thread()' on its own thread capability, core crashes on Fiasco.OC and HW.

**Comment by cproc** [comment]
Test case added.

**Comment by skalk** [comment]
Should be fixed by the fix for issue #1537 regarding HW.

**Comment by nfeske** [comment]
We won't fix this issue for Fiasco.OC.
