### ISSUE TITLE
hw: timer test sometimes hangs on panda

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1496]
Seen last night by our buildbot, the timer test hangs in very rare cases on hw_panda. I had to loop the test and experienced the issue on the 13th retry with the following script
```bash
for i in $(seq -w 1 30); do
	echo
	echo "TEST: $i"
	echo
	make -C build/hw_panda run/timer || exit 1;
done
```

**Comment by m-stein** [comment]
There are several sporadic issues with hw_panda currently (#1147, #982, noux) that might come from a problem with caches / branch prediction we investigated some time on last year but haven't found yet.

**Comment by chelmuth** [comment]
My intention was to just record this rather sporadic issue. Thanks for cross linking to the other issues.

**Comment by skalk** [comment]
I have tried the same loop that chelmuth proposed and cannot reproduce the problem with current staging anymore.

**Comment by chelmuth** [comment]
We did not change cache/branch predictor related code in the meantime and @m-stein's assumption did not apply, right?

**Comment by skalk** [comment]
We did not change such code that is right, but honestly I do not know which changes affected this issue.
