### ISSUE TITLE
dde_bsd: audio drivers from OpenBSD

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1498]
The new `audio_out_drv` supports Intel HDA and ES1370 (mainly for use with Qemu) soundcards. It replaces the aging OSSv4 based dde_oss.

**Comment by ssumpf** [comment]
:+1:

**Comment by chelmuth** [comment]
:+1: does this issue deserve a `fixed`?

**Comment by cnuke** [comment]
Not yet. There are some options (e.g. using the mmap interface instead of read/write) I want to  checkout first.

**Comment by cnuke** [comment]
@chelmuth or @nfeske please merge 9dc39fc to staging.

**Comment by cnuke** [comment]
@chelmuth or @nfeske please merge 5b587e7 and 5785c1b to staging.
