### ISSUE TITLE
foc: timer test sometimes hangs on imx53

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1500]
As in issue #1496, I ran

``` bash
for i in $(seq -w 1 100); do
    echo
    echo "TEST: $i"
    echo
    (make -C build/foc_imx53 run/timer | ts "[%F %H:%M:%S]") || exit 1;
done
```

and experienced an `Error: Test execution timed out` on the 12th iteration.

**Comment by skalk** [comment]
Fiasco.OC i.MX53 support was maintained by Genode patches only and gets removed, see issue #2405.
