### ISSUE TITLE
usb_drv: generate a device list report

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#1506]
The report lists all connected devices and gets updated when devices are added or removed.

Example report:

```
<devices>
    <device vendor_id="0x17ef" product_id="0x4816"/>
    <device vendor_id="0x0a5c" product_id="0x217f"/>
    <device vendor_id="0x8087" product_id="0x0020"/>
    <device vendor_id="0x8087" product_id="0x0020"/>
    <device vendor_id="0x1d6b" product_id="0x0002"/>
    <device vendor_id="0x1d6b" product_id="0x0002"/>
</devices>
```

There is no distinction yet for multiple devices of the same type.

The report is named "devices" and an example policy for 'report_rom' would look like:

```
<policy label="vbox -> usb_devices" report="usb_drv -> devices"/>
```

The report only gets generated if enabled in the 'usb_drv' configuration:

```
<config>
    <raw>
        <report devices="yes"/>
    </raw>
</config>
```

**Comment by nfeske** [comment]
Very good. Thanks for giving the README some attention, too. :-)
