### ISSUE TITLE
seoul: create the Halifax object with the required alignment

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#1526]
@alex-ab: please add commit https://github.com/cproc/seoul/commit/cccc83db0f0e1452a777d8d769a5c77df4cdcfb0 to your seoul repository. Then we need to adapt the port file to the new commit hash.

**Comment by alex-ab** [comment]
@cproc: done. (4c82009d2da7b771c6402d7cdaf3f65cdc6fde62) Do you add a genode update commit ?

**Comment by cproc** [comment]
@alex-ab: done
