### ISSUE TITLE
hw_x86_64: Support for dynamic IRQ mode setting

### ISSUE THREAD

**Issue by Kensan** [genodelabs/genode#1528]
Currently the IRQ trigger mode and polarity on hw_x86_64 is hardcoded. Remove this limitation by adding support for dynamic IRQ mode handling similar to how this is treated on base-foc.

**Comment by Kensan** [comment]
I rebased the change on the latest staging branch (394e8f8...) and verified that the **run/libc_ffat** script works on real hardware.

**Comment by chelmuth** [comment]
@m-stein do you confirm the patch?

**Comment by m-stein** [comment]
@Kensan, @chelmuth 
I enjoyed reading this new and essential feature.
I've added a fix-up with some minor modifications.
Do you agree?

**Comment by Kensan** [comment]
@m-stein
I am fine with the changes but would like to point out that I followed the function naming of the base-foc implementation, see https://github.com/genodelabs/genode/blob/master/repos/base-foc/src/core/include/platform.h#L134. Maybe that implementation could be renamed accordingly for consistency's sake?

**Comment by chelmuth** [comment]
@m-stein I agree with most of the fixup changes beside renaming `setup_irq_mode` as the function is more than just a plain _setter_.

**Comment by m-stein** [comment]
@Kensan @chelmuth 
I removed the renaming from the fix-up.
