### ISSUE TITLE
l4linux: run scripts use incompatible initrds but download only if file does not exist

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1529]
Seen several times during the last weeks on nightly tests foc_arndale run scripts for l4linux stopped with error 'initrd.gz: FAILED'. This is due to conflicting initrd images for distinct test cases. The initrds are downloaded only if the file does not exist yet, which ends up in failing md5sum check in l4linux.run. A possible fix would be to download the md5sum file first and also download the actual script if the first check fails.

**Comment by nfeske** [comment]
We removed L4Linux in Genode 17.02
