### ISSUE TITLE
remove cap_integrity test from base

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1536]
I'd like to remove test/cap_integrity from the base repository. This test makes no sense under NOVA, base-hw, and seL4. Moreover, it just tests what is known to be a vulnerability under OKL4, Pistachio, Fiasco, Codezero and Linux. There will be no fix for these platforms, as they do not support kernel-backed capabilities. The only platform, which support kernel-backed capabilities and still needs some kind of global names for object retrieval in Genode is Fiasco.OC. This is the only platform where this test makes sense to detect some kind of regression. Nevertheless, there is already a clone for this test in the base-foc repository, because it did not match the platform-specific API appropriately.
To sum up I'd like to remove the test from 'base/src/test' and move the run-script to the base-foc repository. Opinions?

**Comment by alex-ab** [comment]
:+1: Added a fixup to remove also the base-nova version of the test.
