### ISSUE TITLE
hw: destroy active scheduling context

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1537]
Because of helping, it is possible that a core thread that wants to destroy another thread at the kernel is using the scheduling context of the thread that shall be destroyed at this point in time. When building without `GENODE_RELEASE` defined, this always triggers an assertion in the kernel. When building with `GENODE_RELEASE` defined, this might silently lead to kernel-memory corruption.

**Comment by m-stein** [comment]
I started to enhance the scheduler so that it is aware of destroying the active context but the solution tends to become more complex than I thought. Thus, I've created a simple patch that, at least, prevents silent memory corruption due to this bug for now.

**Comment by skalk** [comment]
Already brought up by cproc in issue #1495.

**Comment by m-stein** [comment]
Thanks for the hint to the test case.

**Comment by skalk** [comment]
@chelmuth @nfeske: please consider commit c8634e1 for staging
@m-stein: I've also tested the cpu_scheduler.run, it still worked
