### ISSUE TITLE
VirtualBox: dynamic adaptation to screen-size changes

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1554]
Thanks to the VirtualBox guest additions, VirtualBox is principally able to dynamically respond to screen-size changes. E.g., when changing the size of the window that contains the guest OS, the guest OS adapts its desktop environment to the new window size. This feature is desired in scenarios like issue #1552. However, our version of VirtualBox does not support it yet.

**Comment by nfeske** [comment]
Fantastic! It works perfectly. Thanks @cproc :-)

**Comment by chelmuth** [comment]
Most interestingly the fix does not change anything when running Windows 8.1. Don't ask me why...

**Comment by chelmuth** [comment]
Please ignore my last comment as it applies to #1589 - I apologize for any confusion caused.
