### ISSUE TITLE
VBox pointer: policy selection via nitpicker session labels

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1557]
The current version of the vbox_pointer assumes that VirtualBox has a dedicated nitpicker domain "vbox". The code has an annotation (XXX) that it should read this policy from the configuration. Moreover, it would be nice to have a way to express a policy do a specific nitpicker session label (alternatively to a nitpicker domain). For example, in the Turmvilla scenario of issue #1552, VirtualBox runs in the same domain as all regular GUI clients and has the label "wm -> cli_monitor -> linux -> nit_fb". It would be ideal to be able to define a policy that matches all views that belong to "wm -> cli_monitor -> linux".

**Comment by chelmuth** [comment]
Exactly what I stumbled over today: I have more than one instance of VirtualBox running, each of them providing a shape report. In this scenario vbox_pointer has to display the shape associated to the currently hovered session. One special domain seems to be just a stop gap solution I have to generalize now.

**Comment by chelmuth** [comment]
@nfeske please have a close look at cbef9d2b9da87b5210f9733711e9aef95d67254f and 120cfb66fc8616c0f37667a161f2097ea43088c3.

**Comment by nfeske** [comment]
Delicious! :-)

Just a small question crossed my mind: Why are you naming the children and labels all uppercase? This is quite a derivation from from our usual practice.

**Comment by chelmuth** [comment]
You're right, this looks confusing and is just a remnant from my early testing phase. I will polish tomorrow ;-)
