### ISSUE TITLE
dde_linux: remove dde_kit (usb_drv, wifi_drv, lxip)

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1565]

**Comment by alex-ab** [comment]
@ssumpf: starting with commit 199a2a8a02144589c5836dba60e4399d379dd716 the usb driver does not work anymore - it causes some un-handled page faults on native hardware (qemu does not trigger the issue). The commits before are working fine and are sufficient to get the usb driver running on the touchy test machine.

**Comment by ssumpf** [comment]
@alex-ab: Please try https://github.com/ssumpf/genode/tree/issue_1565

**Comment by alex-ab** [comment]
@ssumpf: works like a charm - so I tag this as fixed
