### ISSUE TITLE
x86: add more I/O resources to platform driver 

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1578]
Following the lines of the discussion in #1359 we should complete the I/O resource management in the x86 platform driver until no common driver needs a direct route to core for IO_PORT, IO_MEM, or IRQ. The list of candidates to adapt is as follows

* [ ] rtc_drv
* [ ] VESA fb_drv
* [X] PIT timer
* [ ] uart_drv

The adaption also includes to provides proper `<device name="TYPE">` types.

**Comment by nfeske** [comment]
This issue remained unattended for 5 years. Let us pick up the topic when a concrete use case arises.
