### ISSUE TITLE
vbox: time passes too slow in linux guest

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1583]
When running a linux guest (see  #1552) in virtualbox on Genode, the time passes slower than it does in reality.  When stopping time after 10 minutes, about 3 minutes elapsed in the VM.

**Comment by cproc** [comment]
Just to be sure: is this with the commit from issue #1548 applied?

**Comment by cnuke** [comment]
Yes.

**Comment by nfeske** [comment]
In VirtualBox5, this issue does not seem to occur anymore. As I doubt that we will ever fix it for VirtualBox4, I am closing it.
