### ISSUE TITLE
hw: deadlock in core-paging

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1588]
Currently, a deadlock occurs when core's heap substitue, namely Core_mem_allocator, tries to establish a new mapping and thereby triggers that core's page allocator targets the Core_mem_allocator to gain more backing store.

**Comment by m-stein** [comment]
Its cool to see the reduction in code complexity that this modification causes. I especially like that the early translations table stuff isn't anymore. Besides some minor comments I've added to the commit, I have no objections.

**Comment by skalk** [comment]
@m-stein I've re-written the commit including using more consistent names instead of Page_allocator.

**Comment by m-stein** [comment]
Besides the one comment I totally like the new version, especially of the allocator header. Much clearer. Thanks for taking the time to re-write it!

**Comment by skalk** [comment]
The solution provided in commit cc58b11 leads to a very large .bss segment for core, because the maximum page-table set for core is held within it. This leads to an unnecessary large binary size, which is unwanted on especially tiny embedded platforms. Therefore, a follow-up work is wanted that takes the memory for the page-tables of core from anonymous memory instead of the .bss segment.

**Comment by skalk** [comment]
@nfeske, @chelmuth please have a look at the upper 4 commits, they solve the memory problems you have criticed and also solves current issues with Rasperry Pi detected by the nightly buildbot tests.

**Comment by m-stein** [comment]
Despite the minor issues I've commented in the commits, this looks cool to me.

**Comment by skalk** [comment]
@nfeske, @chelmuth: commits 86843c3df9fbd334386a63d6b541cc460c141bc5 cb7e5e007a7680241173975403eabc0261735dd7 f0d095c2a01596a6e7170dc5a0c94952149c9eb7 and 5a26ac16c4f7044a6377922f5c385c1d3582adf9 are the overworked variants to solve the binary bloat and current issues with Raspberry Pi after review by m-stein

**Comment by m-stein** [comment]
@skalk Thanks for taking the time to apply my suggestions :)
