### ISSUE TITLE
vbox: too many device models cause an unspecific abort of vbox

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1591]

**Comment by chelmuth** [comment]
As the issue is not marked `fixed` yet, I assume your open for discussion. What do you think about applying the _retry_ pattern in case `create_thread` throws an exception due to exceeded quota? In this case you could still log the fact that the quota did not suffice.

**Comment by alex-ab** [comment]
Ok, reworked the patches. I would not mind to have the cxx patch not included, if this causes headaches.

**Comment by chelmuth** [comment]
@nfeske do you think f805720 could cause to much hassle in corner cases?

**Comment by nfeske** [comment]
The patch looks good.

**Comment by chelmuth** [comment]
Both commits on staging now.
