### ISSUE TITLE
base: Locked_ptr to weak pointer object hangs infinitely

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1607]
When a Locked_ptr is taken to a weak object that is currently within destruction, the thread that tries to obtain the locked object hangs infinitely.

**Comment by skalk** [comment]
Above test routine can be used to reproduce the problem.

**Comment by skalk** [comment]
@nfeske: I've re-worked the test routine f2e42f6, and provided a fix 5a27b3a

**Comment by nfeske** [comment]
Very good! Thanks for discovering, investigating and solving this tricky issue.

**Comment by skalk** [comment]
As it turned out, my proposed solution solves the deadlock problem, but introduces a new race condition. Therefore, I've remove the fixed label. Please remove the current half-solution from staging again.

**Comment by chelmuth** [comment]
For the record, I removed the proposed fix just now, but kept the extended test.

**Comment by skalk** [comment]
@nfeske @chelmuth : I have tried to implement the solution we discussed intensively. Please review commit 3549613 attentively again. Thank you in advance.

**Comment by alex-ab** [comment]
Please don't forget to adjust the current user on master, e.g.  repos/base/src/core/include/address_space.h and  repos/base/src/core/include/trace/source_registry.h.

**Comment by chelmuth** [comment]
I have no objections to merge this patch. @nfeske, what do you think?

**Comment by skalk** [comment]
@alex-ab I did not forget it, I'm currently working on a separate solution where Weak_object<T> should already do that job for you

**Comment by alex-ab** [comment]
@skalk: all right ;-)

**Comment by nfeske** [comment]
I like the patch a lot. Thanks @skalk for the careful implementation of the idea.

**Comment by skalk** [comment]
@chelmuth @nfeske : I've add a fixup 564b30d150187f5943b33d8f8a0af1c379bb9024 that detects missing "lock_for_destruction" calls in the weak object base class, and adds all such calls in the most specific classes that inherit from weak object.

**Comment by alex-ab** [comment]
@skalk: for hw we get warnings in the bomb case like:

```
[init -> bomb-master] [2] It's time to kill all my children...
[init -> bomb-master] virtual Bomb_child::~Bomb_child()
Weak object 177e090 not destructed properly there are still dangling pointers to it
cxa pure virtual function called, return addr is 70044314
```

It seems that lock_for_destruction is not issued in platform_pd for base-hw. (all other base-* platform have the call). So fixes b799075b328f42aa0c0f573ff9f033fefa68fabc the issue or do I oversee something ?

**Comment by skalk** [comment]
@alex-ab thanks for noticing, nfeske also observed this before. I fear I've overlooked HW when adapting core for the new weak pointer usage.

**Comment by alex-ab** [comment]
@nfeske, @chelmuth : please addb799075b328f42aa0c0f573ff9f033fefa68fabc  to staging

**Comment by nfeske** [comment]
@alex-ab thanks for the fix. Added to staging.

**Comment by skalk** [comment]
@alex-ab : so you're faster, my fixup commit 6b8be6e1a2e7a5a392045462bfadb635ab150b0b came right now

**Comment by nfeske** [comment]
@skalk I just added your fixup as well. ;-)

**Comment by alex-ab** [comment]
@nfeske  :-D - now we have the some content two times in platform_pd.[h|cc] - just take one

**Comment by nfeske** [comment]
@alex-ab thanks for the notice. I wonder how cherry picking the second commit even succeeded. Anyway, I removed the second one. The fixup wouldn't have worked anyway because the original commit is on master already.
