### ISSUE TITLE
dde_ipxe: Enable Broadcom BCM57xx cards

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#1609]

**Comment by alex-ab** [comment]
Added the test card to our test machine and tested with nova, works fine. However the card does not like msi - so is the same for foc as nova.

**Comment by alex-ab** [comment]
Just for the archive, msi can be disabled explicitly in the platform driver configuration, e.g.:
```
<policy label="nic_drv" irq_mode="nomsi">  ... </policy>
```

**Comment by chelmuth** [comment]
Some reading in the Linux tg3.c commit log reveals that several BCM cards are shaky with MSI...

**Comment by chelmuth** [comment]
Merged into master.
