### ISSUE TITLE
remove VEA9x4 from supported platforms

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1611]
As already discussed one year ago on the mailing-list (http://comments.gmane.org/gmane.os.genode.devel/2371), I would like to remove the ARM Versatile Express board from our supported platforms, it is very slow (therefore misses several timeouts in our run-scripts), very expensive (so nobody owns it), but causes additional maintainance work. Nobody cried against it, so I'll remove the platform.

**Comment by m-stein** [comment]
:+1:
