### ISSUE TITLE
nova: update of r9 branch

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1615]
The updated branch contains fixed regarding freeing up kernel memory.

**Comment by alex-ab** [comment]
@chelmuth: sorry, already squashed the README to the bomb commit

**Comment by alex-ab** [comment]
@chelmuth: please add to staging. You may, if so, also squash it (and put the commit message to the squashed one), as you want to.

**Comment by chelmuth** [comment]
Merged and squashed - thanks.
