### ISSUE TITLE
cpu_quota.run: some issues

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1616]

**Comment by m-stein** [comment]
Branch https://github.com/m-stein/genode/tree/1616_cpu_quota_run_some_issues.

**Comment by chelmuth** [comment]
@m-stein please double-check if I collected all relevant commits (in the most up-to-date version) for #1616, #1620, and #1621 from your branches.

**Comment by m-stein** [comment]
@chelmuth As far as I can see, all commits of the these issues made it to staging.
