### ISSUE TITLE
base: more appropriate allocator for IRQs

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1622]

**Comment by nfeske** [comment]
Could you please be a bit more elaborate about your motivation behind the issue? How is the current allocator inappropriate? ;-)

**Comment by m-stein** [comment]
Both https://github.com/m-stein/genode/commit/5f3df51056884e9f7d8fc84cf49ffa28b1480c27 and https://github.com/m-stein/genode/commit/68bd600b0f6460fad15a2c91ecb0ac474391938a try to fit the IRQ type into the interface of the used ``Range_allocator``. In related discussions, we came to the conclusion that it would be cleaner to switch to another allocator instead. The Range_allocator implementation and interface are more generic then necessary for IRQ allocation. Thus, I now try to introduce an Irq_allocator that uses the Bit_allocator template as back end.

**Comment by nfeske** [comment]
Thanks for the explanation!

**Comment by nfeske** [comment]
This issue is stale for two years. @m-stein, do you still consider it as relevant, or may we close it?

**Comment by m-stein** [comment]
It's still the same. But I've no problems with closing the issue.
