### ISSUE TITLE
Thread test fails on hw_arndale

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1623]
With the current staging branch (4b7b440a5ec969881715e1e3d20b225c36d0353b) `make run/thread` on hw_arndale fails like follows.
```
[init -> test-thread] Uncaught exception of type 'N6Genode10Rm_session17Invalid_dataspaceE' (use 'c++filt -t' to demangle)
[init -> test-thread] abort called - thread: 'helper'
```
The test works flawlessly on master (af5c03edaf3db9e8444cad9c7ede1dbb70cc1d1b). My bisect identified commit 0d6b26713696b1d375b2314a9a7fd4991b8ec64d "base: use proper Cpu_session when tracing threads" as the first one failing.

**Comment by chelmuth** [comment]
@cnuke Are there hidden/not accounted allocations in the tracing framework?

**Comment by cnuke** [comment]
Not that I know of. One issue with commit is https://github.com/genodelabs/genode/commit/0d6b26713696b1d375b2314a9a7fd4991b8ec64d#diff-575e5cd61108cfd019f67c1a91bfe7d9L193 though. We have to detach it after the platform thread has been destructed because will get a page fault on next RPC call otherwise.

**Comment by chelmuth** [comment]
It seems the exception is thrown by Thread_base::Thread_base() very early in the log. How could that be?

**Comment by chelmuth** [comment]
The issue still triggers each night. Any ideas?

**Comment by chelmuth** [comment]
With current staging the issue is till there...

**Comment by skalk** [comment]
maybe I'm blind, but both last nights it was working on current staging, wasn't it?

**Comment by chelmuth** [comment]
I ran it manually yesterday and it got stuck...

**Comment by skalk** [comment]
I see :(

**Comment by chelmuth** [comment]
A glimpse into last nights buildbot results reveals that foc_x86_64 and hw_panda may suffer from a similar issue. The former also fails with `Uncaught exception of type 'N6Genode10Rm_session17Invalid_dataspaceE' (use 'c++filt -t' to demangle)`, while the latter just gets stuck.

**Comment by chelmuth** [comment]
With help from @m-stein and @skalk I could hunt down the problem with 03b9075. The thread test triggers an issue in the base-hw kernel interface particularly in IPC with capability arguments: The helper threads created in the context-allocator stress test create many threads (that never start btw) concurrently. During the thread creation the `Thread_base` constructor requests the trace-control dataspace for the components CPU session, which is one and the same dataspace (i.e., dataspace capability) for all threads. With the high concurrency of the scenario, we end up with multiple copies of the dataspace capability ID in the UTCBs of the helper threads. At this stage, the `Native_capability` reference counting is not effective as the capability was not yet demarshalled. The cause of issue #1623 is now that one helper demarshals the trace-control dataspace capability but also proceeds further until it destructs the last `Native_capability` instance for the capability, the reference counter drops to 0, and `Kernel::delete_cap()` for this capability is called. In response. the kernel frees the object-ID reference, i.e., capability slot. The UTCB of a second helper still contains the capability ID replied to its request to get the trace-control dataspace, which is now stale and the disaster begins as the `Native_capability` reference counting becomes corrupted by demarshalling a stale capability ID and later deleting a still needed RAM dataspace capability. In the end, the RM session complains an attempt to attach an invalid RAM dataspace (see above).

What we need now is a robust handling of those *in-flight* capability IDs, which where copied into the UTCB of thread performing an IPC call but were not yet demarshalled (and therefore ref-counted by ?`Native_capability`).

My commit contains some instrumentation for debugging and also a log in log.txt.

**Comment by chelmuth** [comment]
I merged f83dffb7397eab92a0c94bdaaa7b9883c05f1814 but insist on you to open the "optimization" issue for the evaluation of the UTCB-chain solution.

**Comment by m-stein** [comment]
@skalk The solution looks pretty cool to me :)

**Comment by skalk** [comment]
@chelmuth I would love to do that, but an "optimization" label is missing unfortunately ;-)

**Comment by chelmuth** [comment]
@skalk I'm confident this will not keep you off from opening the issue anyway ;-)
