### ISSUE TITLE
hw_x86_64: read serial I/O port from BDA

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1625]
On NOVA, the I/O port of the UART is retrieved from the BIOS data area, which is very handy when debugging several systems with standard ports, AMT SOL, or plugin PCI I/O cards. The port is written to the BDA by bender, which scans the PCI bus for an appropriate device. (discovered during debug of #1624)

**Comment by alex-ab** [comment]
Please check if this is ok, it is based on #1403. @Kensan, @reet- please have also a look, whether this is ok.

**Comment by reet-** [comment]
The code in `serial.h` looks fine to me.

Since we do not provide a BDA to subjects on Muen, we would just continue to use the previous `serial.h` with static port value.

The fixup commit code on the other hand looks a bit special, but it is marked as *fixme* so I assume it is only a temporary solution.

**Comment by m-stein** [comment]
Added some commits via my https://github.com/m-stein/genode/tree/1625_hw_x86_64_read_serial_IO_port_from_BDA branch.

**Comment by chelmuth** [comment]
Merged 39ce878 and 0e41b61.

**Comment by m-stein** [comment]
7077b93e81702ffb423da412eb6ae6e6a69df28f?

**Comment by chelmuth** [comment]
Please update staging, it was replaced by 7cff97e80e86d92487e6d7a507b26c4b9305ad6b.

**Comment by m-stein** [comment]
Thank you for the hint :)

**Comment by alex-ab** [comment]
Could we factor out the Bda class to some place, so that base-nova also can use it ? (Currently on staging there is the old do it by hand version: f7ea7b1506cf2da428fc17362cd3a2110e503347)

**Comment by m-stein** [comment]
I think thats a good idea! Shall I fix it?

**Comment by alex-ab** [comment]
That would be great.

**Comment by m-stein** [comment]
There it is: e78dc3383f6a2adf0e0a9a2451b0d60e031ee75f.

**Comment by alex-ab** [comment]
Looks good, thanks.
