### ISSUE TITLE
foc_odroid_x2: USB device driver support

### ISSUE THREAD

**Issue by rmillo** [genodelabs/genode#1627]
USB device driver support for Odroid-X2, based on the issue #1597 and #1603.

**Comment by alexygallar2** [comment]
We have tested succesfully some basic GenodeOS examples:

* usb_hid
* usb_storage
* lwip
* netperf_lwip 

We have achieved a throughput of 91% with netperf.

**Comment by alexygallar2** [comment]
@chelmuth   reimplementation of  USB driver based on the framework MMIO device is ready. Please review and if you have any suggestions.

**Comment by chelmuth** [comment]
I merged your contribution to staging but skipped 84a3957 as it changes generic parts of the network test I'd like not to change just before the release.

**Comment by alexygallar2** [comment]
It's okay.

**Comment by chelmuth** [comment]
Great and also great work :-D
