### ISSUE TITLE
NOVA: let the VMM update the PDPTE registers if needed

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#1637]
When running a Windows 8 VM in VirtualBox with two virtual CPUs, a triple fault occurs in the VM after the second vCPU gets switched to protected mode with paging and PAE enabled. It turned out that the PDPTE registers of the second vCPU had not been initialized.

According to the Intel manual section 4.4.1 of Vol. 3A, the PDPTE registers in the CPU get updated as part of certain 'MOV to CR' operations. It seems that the registers need to get updated manually
if the operation caused a VM exit and nested paging is enabled, because according to the Intel manual section 26.3.2.4 of Vol. 3C, on the following VM entry the values of the registers are loaded
from the VMCS structure.

The commit

https://github.com/alex-ab/NOVA/commit/902ccd998fddbf140bb6f87b75d7c9df97e6380f

lets the NOVA kernel call the 'control register access' VM exit handler of the VMM, if necessary, to let it update the PDPTE registers with the values stored in guest-physical memory.

The next commit will update the port hash and the NOVA syscall bindings.

**Comment by alex-ab** [comment]
Nice !
