### ISSUE TITLE
os: add Audio_in session for recording audio samples

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1644]

**Comment by chelmuth** [comment]
@cnuke Does the issue deserve a _fixed_ yet?

**Comment by cnuke** [comment]
@chelmuth not yet but soon™.

**Comment by cnuke** [comment]
As in now :-)

**Comment by cnuke** [comment]
The white space errors was fixed as well as the driver renamed.

**Comment by chelmuth** [comment]
Merged into staging.
