### ISSUE TITLE
timer: reprogramming timeouts masks longer timeouts

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1646]
The timer driver apparently misses the delivery of timeouts in the presence of a client that continuously schedules timeouts before they fire. E.g., the USB HID driver registers a timeout of 250 milliseconds on each key press. When pressing keys at a rate faster than 250 ms, all other timeouts of more than 250 ms won't be delivered anymore. E.g., a concurrently running CPU load display that is normally updated every second freezes.

**Comment by chelmuth** [comment]
Grats for this big catch :+1:
