### ISSUE TITLE
vbox: enable (preliminary) Audio support

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1647]

**Comment by cnuke** [comment]
@chelmuth please merge b5b5e89 to staging.

**Comment by chelmuth** [comment]
done

**Comment by chelmuth** [comment]
@cnuke please always check `./tool/ports/update_hash <port>` when preparing a commit series. Fixed it just now.

**Comment by cnuke** [comment]
ACK.

@chelmuth please also merge 7ed828d to staging.
