### ISSUE TITLE
base: redesign object pool

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1658]
The current object pool implementation hands out pointers to objects, which are can be locked, but do not necessarily need to be locked (e.g. first() accessor). This opens up potential for bugs:

* we might get dangling object pointers when using them without holding the lock
* forgetting the unlock leads to deadlock situations

To eliminate such bugs by design, it would be nice to access objects within the pool with functors/lambdas only. Thereby the pool implementation can take care of the synchronized access, and there is no need to export object pointers at all.

**Comment by skalk** [comment]
@nfeske @chelmuth : I've rebased the new object pool to current staging.

**Comment by chelmuth** [comment]
Added the commit to staging to give it a spin this night...

**Comment by nfeske** [comment]
I just browsed the commit and like it a lot! @skalk Thank you very much for the long-overdue renovation! :-)
