### ISSUE TITLE
vbox: sporadically vanishing 'interrupt pending' flag

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#1660]
By default, the EMT thread of the last vCPU handles expired timers. When running VirtualBox with 2 vCPUs, it sporadically happens that the EMT thread of the second CPU clears an 'interrupt pending' flag for the first vCPU after changing the state of a timer device model, which is not expected by our Genode-specific code (failed assertion '!_irq_win' in the recall handler).

The problem did not occur yet when letting the EMT thread of the first vCPU handle the expired timers, so we could do that as an interim fix until the problem has been further investigated.

**Comment by cproc** [comment]
@nfeske, @chelmuth: please add the workaround commit to staging

**Comment by nfeske** [comment]
This issue is outdated.
