### ISSUE TITLE
usb: kingston sticks on usb2.0 ports not working

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1664]
For setting up a VM completely running from a USB stick, so Genode/Nova and the actual VM vdi image, i tried several 16 GB Kingston USB (USB3.0) sticks:

Datatraveler G4 16GB:

```
Bus 001 Device 011: ID 0951:1666 Kingston Technology
```

They work perfectly fine on a USB3.0 port, but doesn't work on a USB2.0 port. In contrast, I found and used a Intenso 16 GB stick (USB3.0), which works on USB2.0 as USB3.0 ports without any issue.

Intenso 16GB:

```
Bus 001 Device 012: ID 090c:1000 Silicon Motion, Inc. - Taiwan (formerly Feiya Technology Corp.) Flash Drive
```

**Comment by alex-ab** [comment]
d73c15275033e3248a4043a23a622f7222c9f43d contains the relevant output of the dde_linux debug messages from the kingston as the intenso on a  usb2.0 controller

**Comment by chelmuth** [comment]
Does 16.05 still suffer from this issue?

**Comment by alex-ab** [comment]
Unfortunately, yes.

**Comment by nfeske** [comment]
I guess this issue is obsolete now, @alex-ab? *crossing-fingers*

**Comment by alex-ab** [comment]
Yes.
