### ISSUE TITLE
Apply SPEC approach consequently to all repositories

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1673]
Within the 'repos/base-hw' directory structure, we've test-wise applied the SPEC-approach to all aspects of the kernel/core. With SPEC-apporach I mean that the build system is totally controlled by SPEC variables. Moreover, we always distinguish at the various directory levels between generic and SPEC-related code, by having explicit 'spec' subdirectories containing the diverse SPEC-subdirectories. We should apply this approach to all Genode repositories, and thereby get rid of the quite overloaded 'platform' term. As 'platform_*' is just a specific form of aSPECt.

**Comment by chelmuth** [comment]
Merged your work into staging and did some first fixups from `make drivers` on several platforms. Currently, I discovered only one open issue with *drivers/usb_net_stat* on several platforms.

**Comment by skalk** [comment]
@chelmuth thanks for the first fixups, I've added another one to my staging branch, it should fix current build failures, and fix the run tests for Fiasco.OC

**Comment by chelmuth** [comment]
Merged it just now \*cross fingers*

**Comment by skalk** [comment]
I'm afraid we've to cross fingers again. @chelmuth commit ab33d282467c744f366a5da1dee43097f976179c is ready for staging.

**Comment by chelmuth** [comment]
Okay 6c6d3db4c45519544c24b03d31222e98dac9dda2 and yours (0f08cd0f7c885757918d26dd6d630c9ed235b8e7) are now on staging \*cross fingers and thumbs*
