### ISSUE TITLE
hw: pager entrypoint violates address space weak pointer

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1674]
Currently, HW's pager entrypoint implmentation does not hold a locked pointer of the corresponding address space when resolving a pager object's fault. Thereby, it happens (e.g.: when running the bomb test) that the address space gets destroyed during a page-fault resolution.

**Comment by m-stein** [comment]
@skalk Cool commit. Again, I'd would vote for copying the core of the issue description to the commit message.
