### ISSUE TITLE
foc_odroid_x2: HDMI Support.

### ISSUE THREAD

**Issue by alexygallar2** [genodelabs/genode#1678]
Support for  HDMI on Odroid-x2 (Framebuffer)

**Comment by alexygallar2** [comment]
Exynos5 framebuffer driver was adapted for it to be used also by the ODROID-x2, basically the changes are for the base addresses are taken from board_base.h and make it more generic. I tested with the scripts  framebuffer.run and demo.run using native resolution of 1920x1080 and worked fine on odroid-x2 .

**Comment by chelmuth** [comment]
@skalk could you have a look at this contribution regarding the specs integration?

**Comment by skalk** [comment]
@chelmuth: ok I've rebased the commit and produced a fixup commit regarding the specs integration, as well as some coding style fixes.

**Comment by skalk** [comment]
the fixup commit is 19ff6bef01e7c53e0bfcba4f2b0f4e0869188a3a

**Comment by chelmuth** [comment]
@alexygallar2 I merged 1027b8a, 50024cf, and 45d4106 into staging. Please review for rebasing issues.

**Comment by alexygallar2** [comment]
@chelmuth Review the changes and I look very good. The tested changes in ODROID-x2 and everything works fine.

**Comment by chelmuth** [comment]
@alexygallar2 Great, thanks for the test on real hardware.
