### ISSUE TITLE
hw: kernel object destruction does not invalidate all capabilities

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1682]
There is a critical bug in the newly introduced kernel capabilities of the HW kernel. When a kernel object gets destroyed the initially assigned so called "object identity" (analogon to Nova's portals or Fiasco.OC's IPC gates) gets invalidated too, but every "object identity" that was constructed at a later point (via a new capability when using the CAP session) is not implicitly invalidated. So if a kernel thread object gets destroyed before its corresponding CAP session there might exist capabilities that refer to already freed kernel objects, leading to kernel memory corruption.

**Comment by m-stein** [comment]
@skalk I'd love to see the essentials of the issue description in the commit message.
