### ISSUE TITLE
VirtualBox: exit after shutdown

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1687]
Currently, VirtualBox does never call ```Genode::env()->parent()->exit()```. For the Turmvilla scenario (#1552), I wish to automatically remove the rich OS subsystem once the VM is shut down. The issue is related to #1686 and #1685.

There is a function ```Shutdown()``` in the front end but - according to the log produced when triggering the shutdown - it is never called. How should I go to identify a suitable hook function inside VirtualBox to place the call to ```parent()->exit()```? @alex-ab Do you have a good idea?

**Comment by alex-ab** [comment]
I presume that 'fireStateChangedEvent()' in  'repos/ports/src/virtualbox/frontend/console.cc' is called and the the state of 'MachineState_T a_state' turns to 'MachineState_PoweredOff'. That is probably the right trigger. To verify that just set the debug variable in console.cc and see whether it is actually called and what aState is telling us.

**Comment by alex-ab** [comment]
```com::Shutdown()```  looks rather something related to the (X)COM protocol which we - for our port 	"short-circuited" - so maybe it is never called or is only called for fatal errors. Up to now it was never called because it is tagged as DUMMY.

**Comment by alex-ab** [comment]
My guess was actually right. However there are some other issues letting the exit code not be called everytime E.g. one reason is that the pthreads of virtualbox destruct themselves which leads to some deadlocking issues ...

**Comment by alex-ab** [comment]
Deadlocking within the virtualbox VMM process - i have to say.

**Comment by chelmuth** [comment]
I thought this was fixed with #1505 ?

**Comment by alex-ab** [comment]
I mean the threads which does the self-destruction succeed - however other alive threads become stuck - sometimes - especially the thread which does the VM shutdown ... Maybe some locks are still hold by the dying threads - don't know yet.

**Comment by chelmuth** [comment]
@alex-ab could you please extract the issue-relevant commits in a issue branch?

**Comment by alex-ab** [comment]
branch [issue_1687](https://github.com/alex-ab/genode/commits/issue_1687)
