### ISSUE TITLE
Building base-common breaks for linux_x86

### ISSUE THREAD

**Issue by senier** [genodelabs/genode#1694]
A Genode build (master) bails out for linux_86 (Debian/Stretch, x86_64):

`/usr/include/linux/types.h:4:23: fatal error: asm/types.h: No such file or directory`

Adding the respective include directory to etc/tools.conf fixes the issue:

`HOST_INC_DIR += /usr/include/x86_64-linux-gnu/`

However, this should work out of the box. The HOST_INC_DIR set in import-syscall.mk does not sufice, as `gcc -dumpmachine` yields `x86_64-pc-linux-gnu` on my system.

**Comment by chelmuth** [comment]
@senier I added 2bce247 to staging. It just adds */usr/include/x86_64-linux-gnu* to `HOST_INC_DIR` as we already did for *i386-linux-gnu*. Thanks for making us aware of this issue.
