### ISSUE TITLE
Virtualbox: support clipboard guest addition feature

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1696]

**Comment by alex-ab** [comment]
The current version works for a Linux Guest using text as transfer type (the other would be bitmap). One has to replace the mode attribute of ```<Clipboard mode="Disabled"/>``` in the respective VM configuration file *.vbox file to either ```Bidirectional```, ```HostToGuest``` or ```GuestToHost```.

For ```GuestToHost``` a Genode report will be generated whenever new data arrives from the Guest VM called "clipboard". For ```HostToGuest``` virtualbox will ask for a ROM called 'clipboard' and will respond to changes of the ROM. ```Bidirectional``` are both modes together enabled.

Will test with Windows guest the next days.

**Comment by chelmuth** [comment]
Nice. I talked with @nfeske today and we agreed that UTF-8 would be the best text encoding. Is this also possible with available VirtualBox functions?

**Comment by alex-ab** [comment]
In the commit I convert it from UTF16 (Guest) to iso-8859-1 (Genode) and the way back. I already use the VBox built-in convertation functions - there should be also one for UTF16toUTF8 - if we want to.

**Comment by nfeske** [comment]
@chelmuth brought up UTF8 because it is more future-proof than latin-1. E.g., when a Chinese user wants to use the copy-paste mechanism between VMs, iso-8859-1 would not cut it but UTF8 would work well. Right now, the only component that somehow relies on iso-8859-1 is the terminal. But this, we could change quite easily.

**Comment by alex-ab** [comment]
Clipboard in Windows 7 guest is now also functional.

**Comment by nfeske** [comment]
Cool! :+1:

**Comment by alex-ab** [comment]
The utf8 change is pending, but one can try the commit already.

**Comment by alex-ab** [comment]
I removed the latin1 changes and now use the vbox utf8 functions. Also use the append function of the xml generator as implemented by @nfeske and reverted my change.

**Comment by cproc** [comment]
Added a second fixup commit with more error checks and fixed string length calculation.

**Comment by chelmuth** [comment]
Are there still open issues with this feature or may we generate a summarized feature commit?

**Comment by alex-ab** [comment]
No - for me at least. @cproc ?

**Comment by cproc** [comment]
I added a third fixup commit which uses 'append_sanitized()' instead of 'append()' and adds one more error check.
