### ISSUE TITLE
Qt5 demo breaks with missing 'drivers/pci'

### ISSUE THREAD

**Issue by senier** [genodelabs/genode#1700]
I'm trying to build a Qt5 program (namely Arora). Target is Nova/x86_32, Host is Debian/Stretch x86_64. I'm using 5cf8c49cb80abd7ee0a11349a81bed0f2248304d.

A `make run/arora` breaks with `Error: target 'drivers/pci' does not exist`.

**Comment by chelmuth** [comment]
This issue is part of #1695. Closing it as duplicate.
