### ISSUE TITLE
Libc: implement access

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1703]
Our libc dummy for access always returns -1, but should instead check for the existence of a file.

Failure-by-default is causing issues with dosbox.
http://sourceforge.net/p/dosbox/code-0/HEAD/tree/dosbox/trunk/src/dos/drive_local.cpp#l360

**Comment by ehmry** [comment]
@chelmuth added ENOENT and cleaned up catch.

**Comment by chelmuth** [comment]
Thanks, merged into staging.
