### ISSUE TITLE
override libc access in Noux

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1706]
My libc plugin access function is overriding the Noux implementation, the most obvious symptom of this is Vim complaining that all files are read-only because the ``access(..., W_OK)`` call is going thru the libc VFS rather than Noux syscalls.
https://github.com/genodelabs/genode/issues/1703

**Comment by nfeske** [comment]
That makes sense. When looking at the code, I think that we (in the future) should consider moving most of the libc_noux code into a ```Vfs::Noux_file_system``` plugin and let the ```Libc::vfs_config``` function return something like ```<vfs><noux/></vfs>```. This way, we can eventually get rid of the original libc plugin mechanism and retain the VFS as the only plugin mechanism, saving one indirection.

**Comment by ehmry** [comment]
Yea, this problem caught me off guard because at first I forget Noux had its own libc plugin.
