### ISSUE TITLE
nova: PIC compatible syscall_5

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1721]
The addressing must be PC-relative, so adapt the approach from the other nova_x86_32 syscall bindings. The bug only showed up with "-O0" in libc.lib.so in form of a unwanted text relocation.

**Comment by chelmuth** [comment]
@alex-ab do you confirm? It solves the issue for me...

**Comment by alex-ab** [comment]
Agree. Thanks @ssumpf for the explanation.
