### ISSUE TITLE
vbox: make I/O port access less noisy

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1726]
Whitelist a few more ports because Linux probes quite a few I/O ports at boot. Though it stands to reason if we need the PWRN message at all. Other OSes like OpenBSD probes all I/O ports in the ISA PnP range (0x0203 - 0x03ef) which slows down booting a lot.

**Comment by chelmuth** [comment]
You may be right that we reached a state of development in which these diagnostic messages are not important anymore. What do you think about just adding a `verbose` flag which is set by default and white-lists all ports?

**Comment by cnuke** [comment]
I would rather remove the code all together since it is merely a diagnostic feature that can be add easily again for debugging purposes. Than again there is no harm in having `if (verbose) PWRN(…);` and removing the white-listing.

**Comment by chelmuth** [comment]
Yes, that sounds reasonable. Thanks for the adaption.
