### ISSUE TITLE
vbox: replace usage of alarm_timer for periodic gip update

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1727]
At the moment updating the time information depends on the alarm_timer thread that in return only ticks with 10 ms granularity. Using a timer connection or kernel primitive enables us to use a much finer granularity.

**Comment by nfeske** [comment]
Thanks for bringing up this issue! I am all for using one-shot timeouts instead of the periodic timeout processing. I'm curious, do you have something in the works? ;-)
