### ISSUE TITLE
qt5: lupdate/lrelease tools are missing from <build-dir>/tool/qt5

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1736]
For the generation of Qt Linguist source and module files the tools mentioned above are needed. Currently, developers need an installation of the distributions Qt Linguist, which may produce issues due to version conflicts.

**Comment by chelmuth** [comment]
@cproc is this feature provided by qt5-host?

**Comment by cproc** [comment]
@chelmuth: currently not, maybe with the planned Qt5 update?

**Comment by chelmuth** [comment]
Okay, please put it on the TODO list for the update as we'll need it in the Qt SDK anyway.

**Comment by cproc** [comment]
Fixed in ef5aada.
