### ISSUE TITLE
base: Dispatch signals in entry point

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#1738]
Currently, when a signal arrives in the main thread, the signal dispatcher is retrieved  and called from the main thread, the dispatcher uses a proxy object that in turn sends an RPC to the entry point. This becomes a problem when the entry point destroys the dispatcher object, before the  `dispatch` function has been called by the main thread. Therefore, the main thread should simply send an RPC to the entry point upon signal arrival and the dispatching should be handled solely by the entry point.

**Comment by nfeske** [comment]
Apart from the minor cosmetic detail (see my inline comment), the patch looks very good to me. Thanks @ssumpf for the rework!

**Comment by chelmuth** [comment]
I'll add the fix to staging as soon as the mentioned function description is fixed/fixuped.

**Comment by ssumpf** [comment]
@chelmuth: Do 09e48ef and 8e3d992 suffice?

**Comment by chelmuth** [comment]
@ssumpf So shall it be.

**Comment by ssumpf** [comment]
@chelmuth: So let the bot build

**Comment by ssumpf** [comment]
@chelmuth: 04d0994 should implement the correct behaviour for base-hw

**Comment by ssumpf** [comment]
@m-stein: Thanks for clarifying things.

**Comment by m-stein** [comment]
@chelmuth @skalk Fixed.
