### ISSUE TITLE
hw_x86: detect and use all physical available memory

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1741]

**Comment by alex-ab** [comment]
@reet- & @Kensan : with the patches hw_x86_64 is now able to detect and use all available physical memory of a machine by parsing the multiboot info structure provided by the bootloader. We need this to run on various machines and to start using more sophisticated workloads like running the noux tool_chain scenario. Can you please have a look for hw_x86_64_muen? The hw kernel now expects to find a multiboot info structure to scan for the available physical memory ranges. I suspect that they can be setup/provided by some muen subject configuration maybe (as you don't use a bootloader in the hw_muen case, right?) ? Thanks in advance.

**Comment by Kensan** [comment]
Currently for us it would be simplest if the old behavior could be kept for hw_x86_64_muen in the short term. At a later stage a Muen tool could generate the Multiboot information for the Genode/hw_x86_64_muen subject during system integration time.

**Comment by alex-ab** [comment]
Ok, I kept the original static physical ram detection for hw_muen and moved the dynamic physical ram detection to hw_x86_64 only platform_support code.

**Comment by Kensan** [comment]
Thanks for following up on our suggestion. I gave 1d1be2d hw_x86_64_muen a spin on real hardware and everything looks fine from the Muen side of things.
