### ISSUE TITLE
Let Path_base::strip_last_element remove the path delimiter

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1744]
RIght now, the function keeps the trailing ```/```, which must be removed by an subsequent ```remove_trailing("/")``` operation. Since this is the common pattern, we should let the strip_last_element function remove the trailing slash. Note that this requires a slight change of libports/src/lib/libc/file_operations.cc

**Comment by ehmry** [comment]
Fixed at d873752c362adfa306c5916270a8b51b5f55704d.
