### ISSUE TITLE
init: fix uninitialized variables

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#1753]
The 'cpu_quota_pc' and 'constrain_phys' member variables of the 'Init::Child::Resources' structure remain uninitialized if they are not defined in the config file.

**Comment by cproc** [comment]
Commit e800346 initializes 'cpu_quota_pc' with 0, which is the value it had in its uninitialized state most of the time. But I'm not really sure if this is the correct value.

**Comment by chelmuth** [comment]
c9272937e76541a876749aca7350cacef560edee applied the following change in child.h
```patch
 			Read_quota(Genode::Xml_node start_node,
 			           Genode::size_t & ram_quota,
-			           Genode::size_t & cpu_quota,
+			           Genode::size_t & cpu_quota_pc,
 			           bool           & constrain_phys)
 			{
 				Genode::Number_of_bytes ram_bytes = 0;
-				Genode::size_t          cpu_percent = 0;
 
 				try {
```
@m-stein would it still be correct to set `cpu_quota_pc = 0`?

**Comment by chelmuth** [comment]
@m-stein do you have any reservations to apply e8003466622fe0e4a480b0fa15e849c8ecca6114 fro m the background of my comment above?

**Comment by m-stein** [comment]
@chelmuth @cproc Looks fine. Thank you for the fix!
