### ISSUE TITLE
usb host controller does not work on USB armory in Genode

### ISSUE THREAD

**Issue by vladimir-lu** [genodelabs/genode#1755]
As above - the OTG functionality of the controller needs to be enabled for this to work. 

I made some progress earlier in the summer with this - see https://github.com/vladimir-lu/genode/commit/72b30de05ea2b7f4ce19e4d0c6447f5b1d37795d and the whole branch for details, but got stuck on actually getting the port power on (I think).

**Comment by vladimir-lu** [comment]
@ssumpf Did you have any chance to look at this and give a pointer or two for things to further to investigate?

**Comment by nfeske** [comment]
As this topic has become stale, I am closing this issue. It can be re-opened if there is any new interest in it.
