### ISSUE TITLE
Implement sigprocmask

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1756]
Only because the DUMMY macro is trashing my log output.

**Comment by cnuke** [comment]
I would rather implement `sigprocmask` locally then adding it to the libc. In any case the implementation in the libc has to be weak so that other plugins may override the symbol.

**Comment by chelmuth** [comment]
Why should the implementation be weak? I can't image how plugins may effectively implement signals on their own - remember how complex select() grew. We rather have to implement signals in the libc and enable backends, e.g., the VFS plugin, to notify.

**Comment by cnuke** [comment]
I agree that it should be handled by the libc itself eventually but currently there is `libc_noux` that depends on overriding `sigprocmask()`.

**Comment by ehmry** [comment]
I made it weak.

**Comment by chelmuth** [comment]
I noticed and it seems the way to go for now ;-)
