### ISSUE TITLE
vbox: handle potential warping/drifting of the TSC

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1769]
With `rdtsc` trapping disabled (see #1768) VMs or other long running processes that run on the same CPU core can influence each other if the TSC is used for e.g. calibration or as timing source in general. In addition the guest sees the actual host TSC if TSC offsetting is not enabled which might be a problem from a security related point of view.

**Comment by nfeske** [comment]
@cnuke is this issue still relevant today?

**Comment by cnuke** [comment]
@nfeske AFAICS the issue is only relevant for vbox5 and we may therefor close it.
