### ISSUE TITLE
VFS symlink not checking path at readlink

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1790]
Readlink on the symlink builtin is missing a check on the incoming path, so the first symlink found can be read instead of the correct symlink that would be found further in the hierachy.

**Comment by nfeske** [comment]
Merged to staging.

**Comment by nfeske** [comment]
Oh, I just noticed that the issue is actually not marked as fixes. Have I merged it too quickly?

**Comment by ehmry** [comment]
The difference between the first and second commit here is that the first one was not marked as fixed :\
