### ISSUE TITLE
vbox: 64-bit guest support

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#1791]

**Comment by cproc** [comment]
@alex-ab: my updated seoul branch includes the AHCI controller model commit from your genode_15_08 branch, which was not referenced in the seoul.port file. Is this ok?

**Comment by alex-ab** [comment]
@cproc: great work !
I adjusted the links as suggested by @chelmuth.

The vbox_auto_win81_64.run script seems not to succeed for me on the test machine, since in the log the sequence ´´´Guest Additions capability report: seamless: yes, hostWindowMapping: no, graphics: yes``` does not appear. (Still Win81/64bit is up).

@cproc: did it work for you, and if yes, do you have an idea ?

**Comment by cproc** [comment]
@alex-ab: the last time I executed the run script on the x250 yesterday, it succeeded. But I'm not sure if I had the VDI auto-reset feature enabled at the time or not, so there might have been differences with the content of the VDI images (guest additions?).

**Comment by chelmuth** [comment]
I merged commit and fixup to staging but are still wondering why the commit touches seoul. Does there exist any interdependency?

**Comment by cproc** [comment]
Seoul has its own definition of the UTCB structure, which must be kept in sync with the one in NOVA.

**Comment by chelmuth** [comment]
Okay, nevertheless I suggest to split the commit into two: one for the NOVA extension (incl. seoul adoption) and one for the vbox extension tomorrow.

**Comment by cproc** [comment]
@chelmuth: I've split the commit as suggested. The two new commits replace the original one. I also updated the VDI image on the autopilot test machine. The log message which triggers the success of the run script only appeared after user login, so I removed the password of the user and now it logs in automatically.

**Comment by chelmuth** [comment]
@cproc I'll merge the work in a second...
