### ISSUE TITLE
vbox: handle EPT violation during event delivery

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#1798]
If the injection of an event causes an EPT violation, the event must be injected again.

**Comment by cproc** [comment]
@nfeske: please try this commit in your turmvilla setup

**Comment by nfeske** [comment]
I applied the patch to my Turmvilla setup and booted Linux 8 times - no problems occurred.

**Comment by cproc** [comment]
The fixup commit fixes a copy & paste error.

@nfeske, @chelmuth: please add to staging
