### ISSUE TITLE
Packet stream 'peek' function

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#1800]
Implement `peek_packet` function in packet stream, this pre-conditions like packet allocations ca be checked without actually removing a packet. This gives us the possibility to retry the operation at a later point.

**Comment by chelmuth** [comment]
Implemented in 6a186f6ed0045b1ec6a18a2ecec1c441caf26b8a.

**Comment by chelmuth** [comment]
@ssumpf please see my fix above. Ready for staging?
