### ISSUE TITLE
hw: remove main thread's initial UTCB from virtual memory

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1804]
Currently, the main thread's initial UTCB is not cleared from the corresponding RM session not even in core, which leads to "double insertion" exceptions when trying to map something to this area (e.g. pf in core when running bomb test on hw_x86_64). We should simply take out the initial UTCB area from the ranges used by the RM sessions.

**Comment by m-stein** [comment]
I would vote for a short explanation for why we have choosen this address in the commit message as well as in the source code. A hint on why we need to choose the address statically anyway would also be useful, I think (this should have been documented already by me when implementing the function in the first place). Apart from that I'me fine with the commit.

**Comment by skalk** [comment]
@chelmuth I followed m-stein's suggestion, please add the fixup commit 3b12e52a1fef1bdbd901189c189b78a4c2547295 to staging. It includes a commit message addon within its commit message.

**Comment by chelmuth** [comment]
Okay, both commits are now squashed and on top of staging to preserve the commit message update. Please check.

**Comment by skalk** [comment]
@chelmuth fine, thanks!
