### ISSUE TITLE
nova: handle multiboot/hip memory descriptor region of size 0

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1814]
According to

http://sourceforge.net/p/genode/mailman/genode-main/?viewmonth=201511&viewday=27

not all physical memory of a 64bit Genode setup could be utilized because of a memory region of size 0.

**Comment by chelmuth** [comment]
Is this one ready for staging?

**Comment by alex-ab** [comment]
I asked Harm for a re-validation/confirmation of the commit via mailing-list ... beside that it is ready for staging.
