### ISSUE TITLE
noux-pkg: update lynx to 2.8.8rel.2

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1818]

**Comment by chelmuth** [comment]
Your commit removes the noux_net_lynx_interactive run script. Does it no longer work or was it broken before?

**Comment by cnuke** [comment]
The run script itself works fine, although lynx cannot resolve DNS requests (I have not spend time to track down the reason yet). Rather than having a scenario that is used in an interactive way I would prefer to have a run script that we can run automatically like the netcat one. Hence, I decided to remove the run script for now.
