### ISSUE TITLE
Utility string functions to convert values to ASCII (to_ascii)

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1822]
As discovered in #1819, it seems desirable to provide string-utility functions that reverse the ascii_to overloads. The potential users of these utilities are `Xml_generator` and our flavors of `printf` including the `String_console`.

**Comment by nfeske** [comment]
Given our new output facilities, does this issue still apply? Or may we close it?

**Comment by chelmuth** [comment]
You're right, the output approach should suffice for all value-to-string cases,
