### ISSUE TITLE
base-linux: get_pid debug func clashes with usb_drv dummy

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1829]
When building the `usb_drv` on `base-linux` on my system I get this error:

```
/genode/build/linux_x86/var/libcache/usb/usb.lib.a(dummies.o): In function `get_pid':
/genode/repos/dde_linux/src/lib/usb/dummies.c:681: multiple definition of `get_pid'
/genode/build/linux_x86/var/libcache/base-common/base-common.lib.a(debug.o):/genode/repos/base-linux/src/base/env/debug.cc:60: first defined here
collect2: error: ld returned 1 exit status
```

Since there are several static libraries involved hiding certain symbols might not be possible. Should we remove or prefix the symbol in base-linux?

**Comment by chelmuth** [comment]
I removed the function as it seems to be a remnant from the SCM rights development. It was added but not used in f33c7c73bdbf5761fa6b2b6ceb8109300b41bb20.
