### ISSUE TITLE
Correct quota check in Ram_session_component

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1831]
On `alloc()` the current implementation checks if the allocation can be realized in https://github.com/genodelabs/genode/blob/master/repos/base/src/core/ram_session_component.cc#L128 by comparing the available _RAM-session_ quota to the calculated amount, but the slab block for the dataspace will later be allocated from the _meta-data allocator_. The result is that a RAM session can never use its final 4 KiB.

**Comment by nfeske** [comment]
Obsolete since the RAM-session interface has become part of the PD service.
