### ISSUE TITLE
editing config doesn't update anything (e.g <configfile>)

### ISSUE THREAD

**Issue by NobodyIII** [genodelabs/genode#1833]
I built the Turmvilla scenario, and I edited the config files using vim (in noux), but nothing happened. I tried changing the window colors in multiple files, I tried adding the background grid (I disabled it in the default config), and I tried editing the wifi_drv config. In all of these situations, the updated files saved successfully and persisted when I reopened them, but there was no visible effect. I checked the logs as I tried these config changes, but nothing showed up to indicate that the programs received the configuration updates.
In case it helps, I am using the master branch (updated today), with a few cherry-picked commits for the Turmvilla scenario and for VGA console debugging.

**Comment by nfeske** [comment]
Can you please double-check that you have cherry-picked the following commit? https://github.com/nfeske/genode/commit/1e4aacc51a31654438ef0fa9a3fde6e552b87811

**Comment by NobodyIII** [comment]
Thanks! That fixed it.
