### ISSUE TITLE
ahci: use Session_policy and clarify diagnostic message

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1844]
ahci_drv implements the traditional policy-configuration parsing and, therefore, lacks support for exact `label`, `label_prefix`, and `label_suffix` matching. It should be adapted to use Session_policy, which provides all these.

Currently, if the ahci_drv does not find a policy matching the label of the session request it logs
```
No confguration found for client: <label>
```
This is misleading (as it does not hint a policy is missing) and should follow the convention of other components with
```
rejecting session request, no matching policy for '<label>'
```
as in part_blk and the vfs server.

**Comment by ehmry** [comment]
Fixed at 37b3d04b429ed976824e811bce4ecb8172cbcd77
