### ISSUE TITLE
VirtualBox USB2/3 passthrough support

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1863]
The USB2/3 passthrough support consists of a xHCI PCI device model for VirtualBox that uses the xHCI device model from Qemu. The device model is tested with Windows 7, Windows 8.1 and Debian 8 32Bit guests and works fine for a variety of USB devices, especially USB sticks. USB1 low-speed device are currently known not t work properly.

**Comment by nfeske** [comment]
Cool!

**Comment by chelmuth** [comment]
It was a pleasure to review the port. I'm eager to merge it to staging after @nfeske's and my remarks were addressed.

**Comment by cnuke** [comment]
I have addressed your remarks and as icing on the cake by fixing IRQ transfer low-speed input devices now also work.

**Comment by cnuke** [comment]
@chelmuth could you please add 820e7fd to staging.

**Comment by cnuke** [comment]
@chelmuth  could you please add 42a3411 to staging. Without this fix vbox cannot be properly stopped at run-time because an assertion will trigger.
