### ISSUE TITLE
nic_bridge: different threads for RPC and signals leads to race-conditions

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1865]
Although the nic_bridge was one of the first components that worked state-machine like, and did not incorporated lots of threads anymore, it does not use the server framework until now. Therefore, the signal handling and RPC handling are still be done by two different threads. Especially during the startup of the nic_bridge this can lead to race-conditions (e.g.: experienced in noux_net_netcat run script).
To circumvent this kind of problem class, we should use the server framework within the nic_bridge too. Thereby RPC and signal handling are done by one and the same thread: server entrypoint.

**Comment by alex-ab** [comment]
So - I may close #1823  as duplicate, right ?

**Comment by skalk** [comment]
oh sorry, forgot about it, so yes.
