### ISSUE TITLE
port xz-utils

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1867]
@NobodyIII ported xz-utils to noux 13495f0cf0e6e6699ee3bf608d9e7171792623ce, but I'd like to have **liblzma.lib.a** as well as the **xz** utility.

**Comment by nfeske** [comment]
Is this a candidate for genode-world?

**Comment by ehmry** [comment]
Yes, I think so. I intended to do something about this a while ago and never did. I believe there are a few things in Noux/libc that need to be tweaked to get to work attached to a pipe when spawned by tar.
