### ISSUE TITLE
AHCI driver improvement proposal

### ISSUE THREAD

**Issue by publicjoke** [genodelabs/genode#1882]
I have removable SATA HD and I use it on several machines so it is uncomfortable to set the fixed port number for it in the "policy" section of ahci_drv config. In modified driver you can set "model" and "sn" of your HD instead of "device" port number (old method still available too of course). You can obtain those model and serial numbers using hdparm -I your_device.

Appropriate commit: https://github.com/publicjoke/genode/commit/329e38a86a55fe73055c3f8e2e27753b672ed438

Btw, how can I label this issue as "feature"?

**Comment by ssumpf** [comment]
@publicjoke: Sounds reasonable, I will have a look and test your code before we can merge it. Thx.

**Comment by ssumpf** [comment]
@publicjoke: Okay, the code looks very C-isch. I will have to move two or three things around. In the meantime, could you sign the Genode Contributers Agreement (http://genode.org/community/gca.pdf) and send it to us? We have to make sure, that our vision remains and that no claims can be made.

**Comment by publicjoke** [comment]
Ah, sweet burocracy ;) Can I at least omit the phone number?

**Comment by ssumpf** [comment]
@publicjoke: I guess so,  just enter 911 or 110 (german version). It is not required, on the other hand, I will call you up if you do submit it.;)

**Comment by chelmuth** [comment]
@ssumpf bureaucracy is done, but is the patch ready for staging?

**Comment by ssumpf** [comment]
@chelmuth: Please merge 88beec8 and 26abdae into staging.

**Comment by chelmuth** [comment]
I merged the commit to staging just now.

**Comment by publicjoke** [comment]
Confirmed. 07.03.2016, 14:35, "Christian Helmuth" <notifications@github.com>:Closed #1882 via b9263a7.—Reply to this email directly or view it on GitHub.
