### ISSUE TITLE
Issue in ACPI parsing code

### ISSUE THREAD

**Issue by tomga** [genodelabs/genode#1883]
There is a problem in acpi.cc that causes not parsing acpi tables properly on my pc. The problem is that there is an incomplete check for usability of xsdt table. According to some documentation on the net value 0 in revision entry in rsdp means that this is acpi 1.0 and xsdt table is not available but this was not checked.

**Comment by chelmuth** [comment]
@alex-ab I'd like to merge the fix. What do you think?

**Comment by alex-ab** [comment]
I'm fine with it.
