### ISSUE TITLE
graphical file manager

### ISSUE THREAD

**Issue by NobodyIII** [genodelabs/genode#1895]
I have been writing a file manager for Genode, and it's now fairly usable, so I have made a commit in my personal repo for it: ad0c0bf (on branch file_manager).
Notes:
1. The code is dirty and incomplete. Please feel free to improve it.
2. The file manager uses the File_system service directly, rather than using the VFS. When adding support for multiple filesystems, I ran into the issue of paths. I considered using the POSIX tree system with mount points, but it seemed more logical to use the format label:/path/to/dir.
3. The run script is commit eb5a87a.

**Comment by chelmuth** [comment]
Thanks for sharing your work with the community. It's nice to see you staying on the subject. But in my opinion, this work is fairly complementary to the Genode base system. Therefore, I'd suggest to move the development from a Genode branch to a personal repository. This repository could then be integrated into the source directory like we do with the [genode-world repo](https://github.com/genodelabs/genode-world). If you like to make the community aware of your developments, please use the mailing list for update postings.

From this background, I'm going to close this issue.
