### ISSUE TITLE
Remove chroot support from base-linux

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1903]
We originally added chroot support to the Linux version of Genode to accommodate the use of Genode as middleware on Linux. We enabled the configuration of custom UIDs, GIDs, and chroot paths for components started by init. However, apart from a brief period of time where we experimented with the idea, it is no longer pursued. Now, with our aspiration to attain binary compatibility across kernels, the feature stands in the way. Since it is unused, I'd like to remove it.

**Comment by chelmuth** [comment]
:+1: for removal. If somebody would try to enable Genode for the described purpose, modern mechanisms for _containers_ look more attractive than the ancient chroot.
