### ISSUE TITLE
Add Out_of_metadata exception to File_system session

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1909]
For any method of the File_system session interface that allocates a handle the error ``Out_of_node_handles`` can be thrown when the handle registry is full. I suggest that this error be replaced with a more generic ``Out_of_metadata`` exception. This indicates to the client that perhaps the session quota may be upgraded and the operation tried again.

For now an upgrade would not do anything, but I only occasionally see Out_of_node errors with fs_rom. But it would allow the vfs server to request more quota from clients when allocating VFS handles, see #1751. It is also useful where small File_system shim servers must split their client quota with a session that they proxy, and this allows them to inject or forward session upgrade requests.

The client handling of this error can be done transparently, methods which throw Out_of_metadata can trigger an automatic upgrade and retry within the File_system::Connection class.

This would also allow servers to operate without a practical limit on the number of open handles by dynamically allocating additional handle registries.

**Comment by nfeske** [comment]
I like the idea. For the client, the distinction does not offer any advantage anyway. The best it can do is to upgrade the quota donation in both cases.

**Comment by ehmry** [comment]
See #1751

**Comment by chelmuth** [comment]
@ehmry please have a thorough look at 09ab2e2 which fixes a bug with `make run/rump_ext2` due to uncatched exception in the rump_fs server. Do you agree with the fix? Could you please check for similar issues with other file-system RPC functions?

**Comment by ehmry** [comment]
@chelmuth I think in the case of unlink ''Invalid_name'' is redundant with ``Lookup_failed``, but yes, I will look for similar problems.

**Comment by ehmry** [comment]
Er, maybe not, I didn't realize that the name check only checked for slashes.

**Comment by ehmry** [comment]
@chelmuth I believe all the reasonble exceptions should be covered, my only addition is 833fca5fed8aae509168349a2c808cf229c6df30, which tightens the Name argument check in the vfs server.
