### ISSUE TITLE
Serial console output with bender

### ISSUE THREAD

**Issue by dwaddington** [genodelabs/genode#1911]
I've been struggling getting console output (foc_x86_64) on a real machine.  Turns out that removing bender and using pulsar to boot directly into 'bootstrap' solves the problem (at least on foc, but nova also gives good output).

**Comment by cnuke** [comment]
Bender scans the PCI bus and rewires the first BIOS data area entry if it finds a fitting device, e.g. AMT SOL or an PCI(e) serial device like an RS232 expresscard. So if your machine has other serial devices, i.e. in addition to the legacy onboard device, the wrong device might be used when booting with bender.

**Comment by dwaddington** [comment]
Could be. It's just a standard Dell PC (Optiplex 990) with no extra cards in.

**Comment by dwaddington** [comment]
I just checked the BIOS, no other COM ports to be seen.

**Comment by alex-ab** [comment]
If you just start bender (without any kernel), it reports on the screen which PCI device it found and which I/O ports it writes to the BiosDataArea. You may instrument and rebuild your bender tool (use https://github.com/alex-ab/morbo/commits/genode_bender), if you need some more information/debugging.

```
Looking for serial controllers on the PCI bus ...
Promisc is off.
  found at 800b300.
Patching BDA with I/O port 0x1808.
Bender: Hello World.
```
```

**Comment by chelmuth** [comment]
Any news regarding this issue or can we close it?

**Comment by chelmuth** [comment]
No news since two months, so, I close this issue.
