### ISSUE TITLE
Reduce the maximum LOG session string length

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#1919]
When printing a long string with libc 'printf()', which writes to a LOG session via the VFS, an IPC error occurs on 32-bit Fiasco.OC and a warning that the message does not fit into UTCB message registers is printed on OKL4.

Test case in https://github.com/cproc/genode/commit/29616ca6b86db1d8ed45ed7a6c95c0f20df419d3

**Comment by ehmry** [comment]
The public length enum will be nice to have.
