### ISSUE TITLE
Align Rpc_entrypoint destructor in base and base-nova

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1921]
When noux exits I get the following log on NOVA which differs from other platforms.

```
[init -> noux] Object pool not empty in operator()
[init -> noux] Error: tried to remove AVL node that is not in an AVL tree
```

This is caused by a slightly different implementation of `~Rpc_entrypoint` in base-nova. Since 458b4d6f, the base implementation just logs the fact that the object pool is not empty but does not try to cleanup the data structure. base-nova on the other hand calls `Object_pool<>::remove_all()` and, unfortunately, tries to dissolve the objects twice - in `remove_all()` and also in the lambda function.

The last mentioned bug should be fixed to remove the error message, but I'm not certain which way to go: Stay with `remove_all` or just do it like the base implementation?

**Comment by alex-ab** [comment]
The double remove() call is a bug - indeed. 
Beside that - the dissolving is - at least for base-nova - essential to avoid any incoming RPCs via - yet not dissolved - Rpc_objects. On base-nova the destruction of the Genode entrypoint thread does not lead in the kernel to the destruction of the thread, if still portals (Genode capabilities to rpc_objects) exists. That means it could happen that you still receive RPCs in Genode on a already destroyed RPC_entrypoint if we would skip the dissolving.

**Comment by chelmuth** [comment]
Enlightening, how about other platforms like hw and sel4?

**Comment by m-stein** [comment]
On hw, the kernel thread object gets destroyed with the Genode thread object. So a closed entrypoint can't be addressed by IPC anymore. AFAIK the kernel should, in this case, prevent invokation of corresponding capabilities anyway but I'm not sure how this is achieved. Maybe @skalk can give an insight.

**Comment by skalk** [comment]
Sorry, I never recognized above mentioning of me before (just now recognized the "mentions:" search in the issue tracker). Anyway, when a capability target gets destroyed in hw, and somebody invokes the capability it does not get found and the invocation fails, e.g., ipc-call fails.

**Comment by skalk** [comment]
I wonder if this bug is still present and an issue @chelmuth @alex-ab?

**Comment by alex-ab** [comment]
Looked a bit through, my estimation is yes. With commit 458b4d6fc4711f2503618eff5bd4f6558a34a844 a bug is introduced on base-nova as soon as a object gets dissolved and the caller is not the entrypoint. Beforehand this was handled correctly.

**Comment by chelmuth** [comment]
I added the bug label to this issue.

**Comment by alex-ab** [comment]
My analyses was wrong, since I missed that the removed functionality was re-added by eb236a1a10f9ca72df5cf47eb56fc1127acc1a75.
