### ISSUE TITLE
vfs: report zero-length read from server

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1930]
The FS file system in VFS currently tunes reads according to the size reported on stat(), which renders most read operations exactly sized for the remainder of the file. But, if a file-system server cannot determine the real file size upfront and the actual read operation can't return a single byte, this fact must be reported to the client.

@ehmry what do you think about the following patch?
```diff
diff --git a/repos/os/src/server/vfs/main.cc b/repos/os/src/server/vfs/main.cc
index c8d0ae9..858c37c 100644
--- a/repos/os/src/server/vfs/main.cc
+++ b/repos/os/src/server/vfs/main.cc
@@ -97,10 +97,8 @@ class File_system::Session_component : public Session_rpc_object
 			}
 			}
 
-			if (res_length) {
-				packet.length(res_length);
-				packet.succeeded(true);
-			}
+			packet.length(res_length);
+			packet.succeeded(!!res_length);
 		}
 
 		void _process_packet()
```

**Comment by ehmry** [comment]
Looks good to me.

**Comment by ehmry** [comment]
I'm not sure now if a zero read should be an error. What if I seek to the end of the file and I'm polling for new data?

**Comment by chelmuth** [comment]
In retrospect, I'm sure `succeeded()` should be removed entirely. We had the discussion before and the operation-specific semantics can't be reduced to just true or false. Do you agree? Currently, no code uses `succeeded()` anyway.

**Comment by ehmry** [comment]
I would prefer either no ``succeeded()`` or a small error enum with maybe INVALID_NODE, IO_ERR, NO_SPACE, NO_PERM.

**Comment by chelmuth** [comment]
Fixed in master.
