### ISSUE TITLE
Consolidate RM service into PD session

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1938]
Currently, the RM, CPU, and PD services provided by core are pretty much decoupled. This design originated from our initial lack of confidence about how those services would be used in practice. E.g., we considered the need for user-level page-fault handlers, or the potential migration of threads between PDs. However, over the past ten years, we gathered a much more tangible feel for the mechanisms that work well in practice, in contast to those that are interesting from an academic point of view but make the system more complicated to no real benefit. We should change core's services according to these findings:
- Currently, threads are bound to PDs via `Pd_session::bind_thread`. The flexibility of this late binding approach was never used in practice but it raised several problems.
  - Foremost, it introduces the intermediate state where a thread exists but is not bound to a PD yet. In this state, most thread operations (such as start, pause, ...) are undefined.
  - Even worse, on most platforms, physical threads cannot be allocated before knowing the thread's protection domain. Those allocations had to be deferred to the binding of the thread. Hence, allocation errors would occur not at the creation time but on the binding time, which is counterintuitive.
  
  In practice, we relied on a certain sequence of operations when creating threads (create, bind, associate to RM session, start). However, the API principally allows for any other orders of these steps, which eventually remain unstressed. Because of these problems, the late binding of threads to PDs should be abandoned. Instead, each thread should be associated to one PD at its creation time.
- The RM service is fairly freestanding but it is always involved as an ingredient for the creation of components. Specifically, a typical component employs three RM sessions: An address space, a managed dataspace for the stack area, and a managed dataspace for the linker area (where shared libraries are mapped). In the current design, a PD is not directly associated with those RM sessions but each thread living in the PD is individually associated with the PD's address space via `Rm_session::add_client`. The intention behind this design was the consideration of the RM service as a mere utility for managing region maps but to keep if largely agnostic with regard to its use as a PD's address space. In particular, we wanted to retain a certain freedom to implement user-level page-fault handling. In practice, however, we never went this route. E.g., the notion of a "pager" outside of core remained an obscurity. But the representation of each region map as a dedicated session raised a number of problems: For each regular component, we need to issue three session requests to core's RM service in addition to the PD, CPU, and RAM sessions.
  - Each RM session has its independent session quota that is accounted separately to no practical benefit.
  - Second, when used as mechanism to implement managed dataspaces (and the user-level resolution of RM faults), each managed dataspace required a session at core, which is fairly heavy-weight.
  - The merely indirect association of a PD with its address-space layout through the threads bound to the PD complicates the page-fault handling in core, involves an intermediate state where a thread has no address space, and raises uncertain corner cases at API level. For example, two threads of the same PD could be associated with different RM sessions. This has no practical use but raises uncertainties.
  
  Therefore, I'd like to the replace the current notion of an RM session with a new one. The current functionality will be moved to a plainly-called "region map", which is not a session but still an RPC object managed by core. Each PD is equipped with three region maps at its creation time, namely its address space, its stack area, and its linker area. This reduces the number of session requests at the component creation and fixes the problem with associating PDs with their address spaces. The RM service in core will merely be an allocator-like front end to create and destroy region maps. Its sole purpose will be the creation of managed dataspaces. In contrast to today, any number of managed dataspaces can be created out of a single RM session, which makes the use of managed dataspaces more viable in practice.

**Comment by nfeske** [comment]
Related to #1832

**Comment by m-stein** [comment]
:+1:

**Comment by nfeske** [comment]
Fixed in master,
