### ISSUE TITLE
xml reporter: support xml (start) node different from report name

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1940]
Currently the report name is used implicitly as first xml node name for the report. This is inconvenient if one component wants to generate various xml reports under various names (e.g. to steer consumers/clients slightly differently) that have a common/same xml node tree structure.

**Comment by alex-ab** [comment]
Both commits achieve the wanted extension - which one do you prefer ?

**Comment by nfeske** [comment]
Hehe... a menu of commits to pick from! :-)

I prefer c6466ed8f782c2a7d0c19639cd8d5272f6944116 but with the order of the arguments changed as follows

```
Reporter(char const *xml_name, char const *label = 0, size_t buffer_size = 4096)
```

So the report type is the first (aka most significant) argument, and the buffer size comes last because it is very rarely specified at all.

**Comment by alex-ab** [comment]
I see, I will adjust the commit and update all places in the repos which already uses the buffer_size argument as second parameter.
