### ISSUE TITLE
Copy-paste bug in oom handling of NOVA

### ISSUE THREAD

**Issue by Nils-TUD** [genodelabs/genode#1944]
I was just looking through your recent NOVA changes and found by accident, that there seems to be a copy-paste bug in [Ec::oom_call_cpu](https://github.com/alex-ab/NOVA/blob/r9/src/oom.cpp#L186) (at least, I can't imagine that this is intended :)). It should be `sys_pd_ctrl`, not `sys_pt_ctrl`.

**Comment by alex-ab** [comment]
Yes, I'm going to fix it. Thanks!

**Comment by alex-ab** [comment]
@chelmuth: please try again with last commit

**Comment by chelmuth** [comment]
Thanks, merged it just now.
