### ISSUE TITLE
Possible race in Rm_session_component destruction with in-flight page faults

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1946]

**Comment by chelmuth** [comment]
@alex-ab would you agree that this may trigger the issue we discussed offline?

**Comment by chelmuth** [comment]
I forgot to mention that the test branch is based on 16.02 (where the initial issue occurred) and the suspected code is currently under renovation in staging. So, we have to investigate after @nfeske's current developments settled.

**Comment by alex-ab** [comment]
@chelmuth: yes

**Comment by nfeske** [comment]
This issue is outdated.
