### ISSUE TITLE
Remove `Genode::Process` from API

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1949]
The `Genode::Process` class was never used in a stand-alone way. We always use it indirectly via the `Genode::Child` class. Also, since we changed our terminology from speaking of processes to speaking of components, the term "process" became misleading. Therefore, I'd like to make it private to the child class and thereby remove it from the public view.

Furthermore, I'd like to change the constructor arguments to the `Child` (and `Child::Process`) class in order to alleviate the need to perform RPCs during the steps of the component creation. Right now, we pass capabilities to the constructor where we could simply pass references for the corresponding interfaces. This makes it impossible to implement a single-threaded runtime environment that provides customized CPU or PD services.

**Comment by chelmuth** [comment]
:+1:

**Comment by m-stein** [comment]
:+1:
