### ISSUE TITLE
Multi-context signal dispatcher

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1957]
I would like to use something similar to ``Genode::Signal_handler`` but with the Signal context passed as an argument to the handler method. My reason is I want a single thread and object to dispatch many signals, without creating many signal receivers.

**Comment by ehmry** [comment]
Nevermind, it looks like I can use multiple ``Genode::Signal_dispatcher`` with a single receiver.

**Comment by chelmuth** [comment]
Sounds like the multiple-dispatcher method works for you. Can we close the issue?

**Comment by ehmry** [comment]
Yes, works for me
