### ISSUE TITLE
Pass `Env &` as first argument to connection objects

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1960]
The connection objects used to rely on the globally available `Genode::env()` function, which we will eventually remove. Instead of relying on side effects, the new API will make the interaction with the component's resources more explicit. While constructing a connection, the component interacts with its environment in the following ways:

* It issues a session request to its parent (using the parent interface)
* It implicitly decreases its RAM quota by the amount of the session quota provided to the server
* It may set up shared memory between client and server, i.e., all packet-stream-based session interfaces do this. Hence, it interacts with the component's local address space (it's PD session). The attach operation may trigger the dynamic upgrade of the PD session's quota.
* It may set up signal handlers, implicitly consuming PD-session quota due to the allocation of signal contexts.

To sum it up, establishing a connection involves quite intensive (and potentially complex) interactions with  the component's environment. In principle, we could pass solely the session-specific resources to the respective connection constructor. E.g., for a log session, we'd pass just the `Parent &`, whereas we'd pass a tuple of `Parent &, Region_map &` to a connection that also sets up shared memory. However, this approach seems too rigid and cumbersome to use. In the example above, it would prevent us from changing the underlying communication mechanism of the LOG session to shared memory (because the `Log_connection` wouldn't be able to access the local address space) without changing the API. I foresee that we would eventually pass the tuple of arguments to almost each connection constructor because most sessions rely on a combination of shared memory, RPC, and signals. To make our life not too complicated, I propose the convention of passing an `Env &` as the first argument to each connection object.

Does anyone has objections against this convention?

**Comment by alex-ab** [comment]
no
