### ISSUE TITLE
extended ACPI support to read/evaluate system state

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1962]
Modern PCs provide via ACPI an enormous amount of ways to monitor and to configure the system. We have already a basic ACPI driver, which is mainly used to look up low level data that are essential for the platform driver to operate properly. Beyond that it would be nice to have further features enabled/supported like reset and shutdown support, battery status information, lid information and so on. The [ACPICA library](https://www.acpica.org/) is one way to get access to the intended system state information.

**Comment by alex-ab** [comment]
I pushed my current state. Mainly the acpica library is ported and a pure Genode app, also called acpica, utilize the acpica library and generates Genode reports when system state changes, currently lid, embedded controller, ac adapter, battery charging/discharging. The current state is not ready yet, but maybe you can give it a try and or review on your machines. The X201 is known to behave not well yet, but some more modern notebooks seem to report acpi state changes well enough. If you need to get a more verbose acpica app, uncomment in the run script the '<binary name ...' node.

**Comment by alex-ab** [comment]
What i forgot, you also may reset or shutdown the machine, look for ``reset`` and ``poweroff`` in the run script to enable the functionality.

**Comment by alex-ab** [comment]
@chelmuth: from my side the feature is ready for staging, please use issue_1962_staging

**Comment by alex-ab** [comment]
oh, a new staging with nova changes ;-), i will have to rebase

**Comment by alex-ab** [comment]
@chelmuth: update issue_1962_staging to current staging

**Comment by chelmuth** [comment]
I cherry-picked what I thought is relevant for staging - please check.

**Comment by alex-ab** [comment]
Checked - all fine !

**Comment by alex-ab** [comment]
@chelmuth: please have a look - f576b9a6179d2a1add605a6f3eccf803c137ad4f adds a server that takes ACPI events and transform it to Genode input events

**Comment by alex-ab** [comment]
@chelmuth: had to update the commit, is now 8d066b8d1d8ecd9bb90b02a1db8142e21836c544
