### ISSUE TITLE
dde_linux: update drivers to Linux 4.4.3

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1974]

**Comment by chelmuth** [comment]
`- TODO bla bla bla` ?

**Comment by cnuke** [comment]
There will be a proper commit message as fixup commit later on.

**Comment by cnuke** [comment]
@chelmuth please merge 55a5e09 and 510ccf7 to staging.

**Comment by skalk** [comment]
@chelmuth please merge e4f1afe467811f2410d45b96964f274ba2f73101 and ac9e71f4102c1765dbd18d3f99fee1b4afdbe2d3 as well.

**Comment by chelmuth** [comment]
Done.

**Comment by chelmuth** [comment]
The amount of warnings when building lxip is shattering - can we do something about it?

**Comment by cnuke** [comment]
@chelmuth please merge b0a46e6 to staging.

**Comment by ssumpf** [comment]
@chelmuth: Please merge 766f141 into staging.

**Comment by ssumpf** [comment]
@chelmuth: Please merge 18138ec and 4bf85de into staging.

**Comment by cnuke** [comment]
@chelmuth please merge 74735e9 to staging.

**Comment by chelmuth** [comment]
I merged three commits just now.
