### ISSUE TITLE
Noux: same capability multiple times in object pool

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#1978]
The 'Noux::Rom_session_component' creates a 'Rom_dataspace_info' object for its ROM dataspace capability and inserts this object into the Noux-global dataspace registry, which is of type 'Object_pool'. If the same file (for example "config") is requested multiple times (by one or multiple Noux clients), it can happen that multiple 'Rom_dataspace_info' objects with the same capability get inserted into the registry. This can cause problems when looking up the 'Dataspace_info' object for a given capability. For example, the object found by '_ds_registry.apply()' in '~Rom_session_component()' can be a different one than the one belonging to this particular component and this can cause a deadlock later on.

**Comment by nfeske** [comment]
The commit went to master a long time ago. Further improvements of noux in this respect are not planned.
