### ISSUE TITLE
platform_drv: leaks quota when using dma-allocation dynamically

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1980]
When doing dma alloc/free dynamically during the session lifetime, the platform driver unconditionally takes the size to be allocated for its own quota, and transfers it to the session's ram-quota. Unfortunately the transfer never gets reversed before the session gets closed.
This is a problem for scenarios like the intel framebuffer driver, which allocates/frees big framebuffer dma dataspaces when changing resolutions or displays. Then the quota of that client permanently leaks into its platform session.

**Comment by skalk** [comment]
@chelmuth: can you put the interims fix 490702c137c581166f97fbbc28b27c5839b6f0a6 to staging? It is already confirmed by alex-ab.

**Comment by chelmuth** [comment]
In this case... merged just now.

**Comment by alex-ab** [comment]
please review 1719d8101f6c880425410e676d75b3e858170502 to fix this issue
