### ISSUE TITLE
Transition to the new base API

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#1987]
With the release of version 16.05, we refined Genode's API in many ways: http://genode.org/documentation/release-notes/16.05 Now it is time to adapt the existing components to the new API. This is a huge undertaking. According to the number of _target.mk_ files, our source tree hosts nearly 400 components, not counting those hosted in the genode-world repository. My goal is to finish the transition of all components until the release of Genode 16.11.

_Component entry, use of the new environment_

We should start with the easy ones
- Components that use the former `Server` API are quite easy as they are already structured in the new way. The change is almost mechanical, following the "Migration guide" of the release notes 16.05.
- Plain single-threaded non-server components such as many test cases can handled by replacing their `main` functions by corresponding `Component::construct` functions.

The remaining components should be either redesigned or removed. We should use this issue to discuss such decisions. As a guiding principle, I would argue to keep a component only if we have at least one run script that actually uses it. Otherwise, the component is essentially dead anyway. So we will have to make up our minds whether to spend time to update the component including a test case, or to drop it. For example, in my opinion, we could easily drop the iso9660 server, or the xvfb application while keeping in mind that the code is not lost (as it is still present in the source history).

_Removing old printf-style output functions_

We should replace all occurrences of `#include <base/printf.h>`, `PDBG`, `PWRN`, `PERR`, `PINF`, `PLOG`, and `Genode::printf` by the new facilities of _base/log.h_. Note that this is not merely a mechanical activity. We will possibly need to adjust the success-criterions of various run scripts because this adjustment will certainly change the overall output. (e.g., I am thinking of the PDGB messages during the startup of core)

_Eliminating the use of `Genode::env()`_

This step will require us to propagate a `Env &` to all code parts that have to interact with the environment. This is particularly the case for creating connection objects and for code that used to rely on `Genode::env()->heap()`.

**Comment by skalk** [comment]
@chelmuth: can you please cherry-pick commits:  	673c69e 8437f4a 1fb6e1f 0b76891 and  	224da91 to staging?

**Comment by chelmuth** [comment]
Merged the series.

**Comment by cnuke** [comment]
@chelmuth please merge 7f49504, a533da7, 3d816ec and bbb0673 to staging.

**Comment by ehmry** [comment]
Nit_fb updated.

**Comment by ehmry** [comment]
Nic::Root updated at 428cac8bf3550f9643fc49d9e1c4099235c788e3

**Comment by ehmry** [comment]
Actually, ignore the Nic stuff for now, I will try and implement #2034 in two commits, the API transition and then the session changes.

**Comment by ehmry** [comment]
@nfeske I have patches for the vfs server and vfs stress test, 0463fcba472153ec2cbae14a8f549036f7ae6f2c, 0311a4f0d70b183a2fa2f6f4758ae8ffa0089798.

**Comment by nfeske** [comment]
Wow - that was quick. :-) Thanks a lot! I merged both commits to staging.

**Comment by nfeske** [comment]
I merged my big patch "base: avoid use of deprecated base/printf.h" to staging now. The following areas need additional love by the respective authors:

* The implementation of the `Logging` infrastructure of seoul still relies on Genode::printf.
* VirtualBox is not completely adjusted because I could not tell which of the many debug messages are obsolete by now. @alex-ab Could you please take care of the remaining adjustments?
* The Qt5 patches still depend on `base/printf.h`. @cproc Could you please adjust the patches to use the new `base/log.h` mechanism?
* OpenVPN is not updated for the same reason as for VirtualBox. @cnuke Could you please have a look?
* `lx_kit` still depends on `base/printf.h` on very few places. It should not be difficult to fix, but I'd like to leave that to @cnuke

I would like to add those adjustments as fixups to the big commit. If anyone of you is not able to respond quickly, please give me a short note.

**Comment by alex-ab** [comment]
@nfeske: 7c6d1c42e0dbbb9d99403561dc01968c44e9f06f contains the vbox adjustments

**Comment by cproc** [comment]
@nfeske: adjusted Qt5 patches in 3de21d8ef1a74342d0a235e974b68249a9dc712a

**Comment by cnuke** [comment]
@nfeske please merge 1ade4c5 and 637c7d3.

**Comment by nfeske** [comment]
I repeatedly stumbled over the problem that printing `char *` arguments is ambiguous. It is unclear whether to print the argument as pointer or null-terminated string. I am going to introduce a new type `Cstring` that allows the caller to express that the argument should be handled as null-terminated string. As a nice side effect, with this type in place, I am able to remove the optional `len` argument of the `String` class. Instead of supplying a pair of (char const *, size_t), the constructor accepts a `Cstring`. This, in turn, clears the way let the `String` constructor use the new output mechanism to assemble a string from multiple arguments (and thereby getting rid of `snprintf` within Genode).

To enforce the explicit resolution of the `char *` ambiguity, I am going to mark the corresponding overload of `print` as deleted.

**Comment by cnuke** [comment]
@nfeske please merge 86ed56a to staging — it should solve the issues with the `noux_net_netcat` test.

**Comment by cproc** [comment]
@nfeske: please add 91f63c4552e1d67d589e0e20947afa4083ecc460 to staging

**Comment by ehmry** [comment]
I made some updates to input stuff at 136e4193f9b49bc5f141f7791f7ad419d4235f87. The biggest change is attaching the session event buffer in Input::Client, which all clients are handling by themselves right now.

**Comment by nfeske** [comment]
@ehmry Moving the dataspace handling to the `Input::Session_client` is a very sensible idea. You could even further improve it by a minor addition: How about adding a `for_each_event` method that takes a lambda function as argument? The method would call the lambda for each event currently present in the event buffer.  This way, we would eliminate the need to call the `events` accessor in the first place and don't run into potential buffer-overflow issues. In fact, the current client-side implementations do not check the upper bound of the event buffer when iterating over the events. They inherently trust the input server to return a valid number of events that does not exceed the event buffer. With the `for_each_event` approach, we could place the bounds check at a single place and know to be safe everywhere.

...just another welcome opportunity for shunning pointers... ;-)

**Comment by nfeske** [comment]
Maybe we reach the conclusion that we can don't need the `events` method then? This would be the ideal outcome in my opinion.

**Comment by ehmry** [comment]
I like it, i wasn't very comfortable with returning that pointer anyway

**Comment by chelmuth** [comment]
Just another example for the advantage of *taking (at least) one step back* to find the best approach.

**Comment by ehmry** [comment]
I have a new version of the input update at 3429f57dcc43979ca9c4fe8393c7103f8bcca5fc, the commit got much bigger that I planed.

There was a problem with wm and decorator, wm was returning an invalid input sub-session capability to decorator, which was then trying to request a dataspace using that capability from the ``Nitpicker::Connection`` class. I added a dummy input session component to wm as a fix.

**Comment by nfeske** [comment]
@ehmry Your latest commit is wonderful! :-)

**Comment by ehmry** [comment]
I have a fixup for bounds checking.

I think it may be worth considering removing the Framebuffer and Input clients from ``Nitpicker::Connection`` and allowing Nitpicker services to throw an error rather than return a sub-session, because if an invalid session is returned, the client doesn't seem to notice. Not a big deal, but a bit of an edge-case.

**Comment by ehmry** [comment]
Replacement fixup at 4579b23aa14384bfec0815f2bfea2832ac3b2eda

**Comment by chelmuth** [comment]
@ehmry could you please rebase on origin/staging or at least 9d67f74bd2c9e66667e0e0aafa55eb2b99606d43, which also changed the input test?

**Comment by ehmry** [comment]
@chelmuth Yes, I have a new commit faa42e8e6f80f3d35fe682197cc2135ad51dc046 that contains the fixup.

**Comment by chelmuth** [comment]
Merged both commits as 560ad8b08bcce66c9f95d79866bfba44bd38f2e6.

**Comment by ehmry** [comment]
Mixer updated at 3768e56814573ad65572ba0acb9d16874d49a8dd

**Comment by ehmry** [comment]
Please use 88b8d369d5e241225fd6d42183e9cc5e8e60ed2c from my issue1987 branch, the previous commit touches audio_drv when it doesn't have to.

**Comment by nfeske** [comment]
The two commits 729af608b15d07eb0d2f598caa95753b24fc7704 and 37e793f9850a2f1c94bb0e636da891688d17a0cd adapt both window decorators to the new API.

**Comment by ehmry** [comment]
I have an update for **rom_logger** at 3a35f28159f87ea684fb6c26e8cc83f174f3eccd, I also added an option for inspecting binary roms.

**Comment by ehmry** [comment]
@chelmuth I have a small fixup to the rom_logger hexdump, 8cb0cd2e2af72aec8ba6a22b344b27369a6a7036. I trust that if there are dataspaces bigger than the 32 bit address space, no one will want to print them.

**Comment by chelmuth** [comment]
Sounds reasonable but what is the rationale behind replacing `size_t` by `uint32_t`? Many places in the code base use `size_t` for *size* calculation.

**Comment by ehmry** [comment]
Its just to save screen space when printing offsets.

**Comment by chelmuth** [comment]
Oh, I missed that formatting issue ;-)

**Comment by chelmuth** [comment]
@ehmry staging now includes your branch until 7b07afcf7bfd4030f287ca7a35fe477be597590f

**Comment by alex-ab** [comment]
@nfeske: please add all seoul commits from [branch](https://github.com/alex-ab/genode/commits/issue_1987) to staging

**Comment by cnuke** [comment]
@chelmuth @nfeske please merge e7dd8c1, 	1ff0f1f and ead0581 to staging.

**Comment by cnuke** [comment]
@chelmuth please merge 76c4e77, 	1662b79 and 8a7e2f1 to staging.

**Comment by ehmry** [comment]
6f11c5620ac35e5ccef2790ba0975f9bb88b6911 and 8da5bea1b71229772aa9664c80b46ed7a829d47d ready for staging.

**Comment by nfeske** [comment]
As a heads-up warning, I have enabled warnings about the use of the deprecated global `env()` accessor now.

**Comment by ehmry** [comment]
9fb0bbf09418a11895df0b2a6a7b007d80f822fc ready for staging

**Comment by m-stein** [comment]
I'll do the os/src/test components. Anyone else who is currently at this?

**Comment by m-stein** [comment]
@nfeske These commits should do the rest of os/src/test (most recent first):
8dd8356 autopilot.list: add some missing tests of 'os'
2af633e test/reconstructible: move to base
bb2a3c4 test/synced_interface: move to base
c5d52bf os/test: transition to new base API
b0af688 timer_accuracy: generalize, automate, new base API
5687f3c test/nic_raw: remove
a4f0532 test/packet_stream: remove
cf96d1a test/gpio_led: remove
ca35099 test/gpio_signal: remove
3bda105 test/gpio_drv: remove
657c4b3 test/config_args: remove
653eb89 test/fb_block_adapter: remove
42e7a66 input.run: fix and simplify session routing
f82bc44 test/ram_fs_chunk: fix bug in allocation tracking
d659cbc run/boot_dir/foc: avoid error on link creation

**Comment by chelmuth** [comment]
I merged all commits but those commented.

**Comment by m-stein** [comment]
@chelmuth daec810580d46bfdda797a185e1b0ceb62bee3b6 recovers the REQUIRES for the RPC name policy. I forgot that after restructuring the trace test.

**Comment by ehmry** [comment]
@chelmuth If the VFS and Id_space commit makes it to staging, please apply 65ad31e149542a9a144bad9390e421ff92fbc431 for API cleanup at the VFS server.

**Comment by m-stein** [comment]
From my journey with the DB:
5ae09ba os: fix some more deprecated warnings

**Comment by chelmuth** [comment]
With current staging (2a9102f1e02bcd9a7e2382d2b5367aea7c09ed0c) we already reduced the amount of deprecated warnings significantly but we're still not there. If we'd remove all deprecated functions now several components would break. Today I gathered a short, not complete list of candidates if someone's in the mood for cleaning...
- os/src/drivers/framebuffer/spec/exynos/driver.cc
- demo/src/server/liquid_framebuffer/main.cc:203:51: warning: narrowing conversion
- os/src/drivers/ahci/ahci.h (all specs)
- test/framebuffer/intel
- os/src/drivers/framebuffer/spec/omap4/
- os/src/drivers/sd_card (all specs)
- test/sd_card_bench
- os/src/test/gpio_drv/gpio_test.h
- os/src/server/tz_vmm/
- test/lwip/http_clnt
- test/python/
- src/lib/lwip/platform/ ?
- libc/malloc.cc
- libc/socket_fs_plugin.cc
- libc_pipe/plugin.cc
- pthread

**Comment by alex-ab** [comment]
> - os/src/drivers/ahci/ahci.h (all specs)

@chelmuth: please consider  233d65170cad2d4894a14912beb911eabcfcf1b4 for staging

**Comment by chelmuth** [comment]
@alex-ab That's great! Thank you.

**Comment by alex-ab** [comment]
@chelmuth: please have a look for the 4 commits

**Comment by ehmry** [comment]
@chelmuth please add 45fc58724f784139659726ce4a6fa66f4dc88fe3 to staging.

**Comment by ehmry** [comment]
I have a low-priority fix to SDL at 4ad6739d80d6765263c712c333b99dce16b75d41.

**Comment by m-stein** [comment]
I'll have a look at test-xml_node next.

**Comment by ehmry** [comment]
@nfeske fixup for `Reporter` at 07fa74b3fd1bb5a05ab9edec8728c61b7d31a94d.

**Comment by ehmry** [comment]
I have a patch to fix Seoul logging at 87d2594bdd2c6152c8057116ff9515bc50b6f259, this is independent of the Fifo issue and is tested to be UTCB safe.

**Comment by nfeske** [comment]
> I have a patch to fix Seoul logging...

Thanks a lot! I have to admit that I completely overlooked these dusty corners of Seoul. Merged to staging.

**Comment by nfeske** [comment]
Fixed in Genode 19.02.
