### ISSUE TITLE
os: support packets without payload

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#1988]
Under some circumstance (USB control messages), we do not need payload when submitting packets, since all can be achieved through the packet's meta data. Therefore, we decided to not call the allocator for zero sized packets during `alloc_packet` and `release_packet` and perform the `packet_valid` check on the `packet_content` function instead of `get_packet`. We also want to remove the `valid` function for packets, since is does depend on the packet size, which will be zero for these kind of packets. Components that do not support packets without payload should use the `size` function (as `valid` did before) in order to determine invalid packets.

**Comment by cnuke** [comment]
:+1: fixes the USB device removal issue w/o using #1981.

**Comment by chelmuth** [comment]
Merged with 49946163461a0e2b1a15f660f998a9f225e57ce5
