### ISSUE TITLE
usb: Fix mouse and keyboard for RPI

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#1999]
On RPI mouse and keyboard do not work any longer. We found the trouble to be caused by our timer update function, which causes an IPC to the timer server for each IRQ (there are a lot of them). Because of this, we missed some split transaction which are USB 1.x packets. Until some better solution comes around, we will take advantage of a hardware timer on the RPI.

**Comment by chelmuth** [comment]
Thanks for your effort. I'll merge as soon as @cnuke confirms the lx_kit changes.

**Comment by cnuke** [comment]
@chelmuth looks good to me :+1:
