### ISSUE TITLE
linux: Some messages from valgrind during service registration

### ISSUE THREAD

**Issue by myrkr** [genodelabs/genode#200]
When running valgrind on one of our services some issues were
output. valgrind didn't output which part of the msg were not
initialized.

line 56 of lx_syscall.S is marked with "==>" below.

    /*_DOARGS_6(44) end*/
	movl 20(%esp), %eax /* Load syscall number into %eax.  */
	ENTER_KERNEL        /* Do the system call.  */
    /*    POPARGS_6*/       /* Restore register contents.  */
    /*    POPARGS_6 begin */
    ==>    popl %ebx;                                                                                               
	.cfi_adjust_cfa_offset -4;                                                                               
	.cfi_restore %ebx;                                                                                       
    L(POPBX1):
	popl %esi;                                                                                               

Platform of testing was x86_32.

==7237== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
==7237==    at 0x80A97EA: ??? (lx_syscall.S:56)
==7237==    by 0x80A658A: send_to(int, long, char const*, void*, unsigned int) (linux_syscalls.h:86)
==7237==    by 0x80A6782: Genode::Ipc_client::_call() (ipc.cc:274)
==7237==    by 0x809ECE4: void Genode::Capability<Genode::Parent>::_call<Genode::Parent::Rpc_session>(Genode::Parent::Rpc_session::Client_args&, Genode::Parent::Rpc_session::Ret_type&) (ipc_generic.h:440)
==7237==    by 0x80A391A: Genode::Platform_env::Local_parent::session(Genode::Rpc_in_buffer<64u> const&, Genode::Rpc_in_buffer<160u> const&) (capability.h:187)
==7237==    by 0x809D90D: T.317 (platform_env.h:356)
==7237==    by 0x809DDAE: Genode::env() (env.cc:28)
==7237==    by 0x808A240: Genode::Connection<Genode::Cap_session>::session(char const*, ...) (connection.h:93)
==7237==    by 0x808A478: main (connection.h:27)
==7237==  Address 0xbe8c4985 is on thread 1's stack
==7237== 
==7237== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
==7237==    at 0x80A97EA: ??? (lx_syscall.S:56)
==7237==    by 0x809EFD0: void Genode::Capability<Genode::Parent>::_call<Genode::Parent::Rpc_announce>(Genode::Parent::Rpc_announce::Client_args&, Genode::Parent::Rpc_announce::Ret_type&) (ipc_generic.h:440)
==7237==    by 0x809F101: Genode::Parent_client::announce(Genode::Rpc_in_buffer<64u> const&, Genode::Capability<Genode::Root>) (capability.h:187)
==7237==    by 0x808A5EE: main (parent.h:68)
==7237==  Address 0xbe8c4f22 is on thread 1's stack
==7237== 
==7237== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
==7237==    at 0x80A97EA: ??? (lx_syscall.S:56)
==7237==    by 0x809EFD0: void Genode::Capability<Genode::Parent>::_call<Genode::Parent::Rpc_announce>(Genode::Parent::Rpc_announce::Client_args&, Genode::Parent::Rpc_announce::Ret_type&) (ipc_generic.h:440)
==7237==    by 0x809F101: Genode::Parent_client::announce(Genode::Rpc_in_buffer<64u> const&, Genode::Capability<Genode::Root>) (capability.h:187)
==7237==    by 0x808A6CE: main (parent.h:68)
==7237==  Address 0xbe8c4f2a is on thread 1's stack
==7237== 
==7237== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
==7237==    at 0x80A97EA: ??? (lx_syscall.S:56)
==7237==    by 0x80A658A: send_to(int, long, char const*, void*, unsigned int) (linux_syscalls.h:86)
==7237==    by 0x80A6864: Genode::Ipc_server::_reply_wait() (ipc.cc:345)
==7237==    by 0x80A80AA: Genode::Rpc_entrypoint::entry() (ipc_generic.h:592)

The code being tested has some invocations of:

    template <typename T>
    void start_service(Genode::Cap_connection *cap,
	    Genode::Sliced_heap *heap, Genode::Rpc_entrypoint *ep)
    {
	    static T service_root(ep, heap);
	    Genode::env()->parent()->announce(ep->manage(&service_root));
    }
    }

    static Genode::Sliced_heap sliced_heap(Genode::env()->ram_session(),
					   Genode::env()->rm_session());
    start_service<Some::Root_component>(&cap, &sliced_heap, &ep);
    ...

to register its services.

Here is a typical example of such a Root_component:

    namespace Some {
	    struct Session_component : Genode::Rpc_object<Session>
	    {
		    int list();
		    void changed_signal(Genode::Signal_context_capability cap);

		    Genode::Dataspace_capability dataspace()
		    {
			    return buffer.cap();
		    }

		    Session_component()
			    : buffer(Genode::env()->ram_session(), 100 * sizeof(Information))
		    {
		    }
	    private:
		    Genode::Attached_ram_dataspace buffer;
		    Genode::Signal_context_capability changed_signal_cap;

		    void send_signal();
	    };

	    class Root_component : public Genode::Root_component<Session_component>
	    {
	    protected:
		    Session_component *_create_session(const char *args)
		    {
			    return new Session_component();
		    }
	    public:
		    Root_component(Genode::Rpc_entrypoint *ep,
				   Genode::Allocator *allocator)
			    : Genode::Root_component<Session_component>(ep, allocator)
		    {
		    }
	    };
    }

The program is started with a simple wrapper code to perform the
valgrind testing. In this example /genode/bin/original-service is the
program which would normally be started via the /genode/bin/config
file:

    #include <string.h>
    #include <unistd.h>

    int main()
    {
	    execl("/bin/valgrind", "valgrind",
		  "--leak-check=full",
		  "--show-reachable=yes",
		  "--error-limit=no",
		  "--gen-suppressions=all",
		  "--log-file=/tmp/valgrind.log",
		  "/genode/bin/original-service", (char*)0);
	    perror("execl");
    }

Of course, the /genode/bin/config needs to be modified to replace
"original-service" with this program. Our original wrapper is more
complex to allow to select whether to start valgrind on the kernel's
cmdline.

Torsten

**Comment by nfeske** [comment]
I think that this issue is no longer relevant (the discussion came to a halt long ago, anyway). So let's close it.
