### ISSUE TITLE
uniform XML boolean attribute access

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2002]
Since df0bbe0b0eac1b7c1f6fcd3c7b26d44ae9b4176d it is possible to read the boolean attributes from XML without string comparisons, yet there remains a mix of the new ``attribute_value("...", true/false)`` and the old ``attribute("...").has_value("yes")``. Now that the boolean accessor has survived a release cycle without any changes, I say the remaining instances of ``.has_value("yes")`` be replaced.

Somewhat related to #1959

**Comment by ehmry** [comment]
Fixed at 67a931b.

**Comment by cnuke** [comment]
@chelmuth, @nfeske please merge b03513a to staging.

**Comment by nfeske** [comment]
done.

**Comment by cnuke** [comment]
@nfeske please also merge 9d19ab9 to staging.

Thanks @reet- for reporting.
