### ISSUE TITLE
libc: GENODE_OSREV variable setting leads to git error

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#2003]
The GENODE_OSREV variable set within repos/libports/src/lib/libc/version.inc uses a git command without specifying the git repository path. This leads to a wrong variable content, but even more annoying provokes an error message when libraries are checked or the libc is built:
```
fatal: Not a git repository (or any parent up to mount point /XXX)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by ehmry** [comment]
@nfeske and I had talked about moving this information to a ROM at core, but I don't remember anything concrete.

**Comment by nfeske** [comment]
I am actually not quite sure whether or not we should expose such information to libc-using programs. But the magic in version.inc should definitely be removed. I also stumbled over it while doing my packaging experiments.

Incorporating the information into the binary at compile-time is surely not a good way to go. It merely tells the program the Genode version that was used for compiling the libc. This does not necessarily correspond to the Genode version used to compile the binary, nor the version that is actually running.

@ehmry Can you tell us how this information is used in practice? Is is merely needed for uname, or are there other programs that rely on it? I wonder, couldn't we let the libc read this information from the sysctl file system? This way, the user can decide what information to supply by the means of configuring the VFS. E.g., by manually placing an `<inline>` or `<rom>` vfs node named /sysctl/os/version (or something similar).

**Comment by ehmry** [comment]
I did it for looks and to add just enough information for ``uname -a`` to work, but I would agree its not worth the hassle. I've replaced the builtin values with zero length strings at fbc8987, but this information was and still is overridable at the VFS.
