### ISSUE TITLE
vbox: add ahci model

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2006]

**Comment by alex-ab** [comment]
The ahci model works. The commit 'vbox: try to cache ..." is optional and may be skipped.

**Comment by chelmuth** [comment]
Did you notice any performance gain when switching from IDE to AHCI?

**Comment by alex-ab** [comment]
Without ''vbox: try to cache ...' - no. With it i got - unstable - peaks above 100MB/s writing data.

**Comment by chelmuth** [comment]
Merged to staging. I left out acc1947 for now because I was not sure if it should enter mainline.
