### ISSUE TITLE
Supplement base/log.h with raw output function

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2012]
The new `base/log.h` interface features functions for printing log messages, warnings, and errors. For low-level debugging, it would be convenient to also have a `raw` function that targets the platform-specific kernel debugger, if available. This would spare us the hassle with dealing with archaic kernel interfaces directly when working on low-level framework code.

**Comment by m-stein** [comment]
:+1:

**Comment by skalk** [comment]
Maybe we can use this also within core's bootstrap code, thereby making a core-specific log implementation superfluent?

**Comment by nfeske** [comment]
The core-specific log backend is still needed (because core does not open a LOG session like normal components so) but by using the new raw_write_string function, the log backend could be implemented in a kernel-agnostic way. The only problem is NOVA where the function is empty at the moment. Here the current log backend (base-nova/src/include/base/internal/core_console.h) uses a serial driver because the kernel has no syscall to output text.

**Comment by skalk** [comment]
I see, thanks for the explanation.
