### ISSUE TITLE
add noux-pkg/less

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2014]

**Comment by alex-ab** [comment]
Running noux_bash.run and entering
```diff -u home/diff_me_a.txt home/diff_me_b.txt | less ```
leads to a message
```Missing filename ("less --help" for help)```
;-( - Still,  ```less --help```  "works", but that is not what i wanted ... Any ideas ?

**Comment by chelmuth** [comment]
less seems to check `isatty(fd0)` in *edit.c:697*, which should return false in case of input from a pipe. Either noux or the libc seem to lack correct handling input from pipes vs. tty.

**Comment by ehmry** [comment]
Yes, ``isatty`` doesn't always behave as expected, I think noticed this when tar spawns gzip and attaches a pipe.
