### ISSUE TITLE
Command not found:create_builddir

### ISSUE THREAD

**Issue by rishabhcemica** [genodelabs/genode#2015]

**Comment by nfeske** [comment]
Can you please post the complete output that you see after executing the command?

Please check that you have all the packages installed that are mentioned at the beginning of Section 2 of the documentation (http://genode.org/documentation/genode-foundations-16-05.pdf).

**Comment by rishabhcemica** [comment]
now problem is solved thank you for replying

**Comment by nfeske** [comment]
What was the problem?

**Comment by rishabhcemica** [comment]
some packages were missing.

**Comment by rishabhcemica** [comment]
sorry for disturbing you , i am new to genode.

**Comment by nfeske** [comment]
No problem. Would you mind closing the issue?

**Comment by rishabhcemica** [comment]
ok
