### ISSUE TITLE
make run/demo from build directory is not working

### ISSUE THREAD

**Issue by rishabhcemica** [genodelabs/genode#2017]
/bin/bash: /home/rishabh/genode-16.05/tool/run/run: /usr/bin/expect: bad interpreter: No such file or directory
Makefile:261: recipe for target 'run/demo' failed
make: *** [run/demo] Error 126

**Comment by nfeske** [comment]
The error message is literally telling you what is missing: "/usr/bin/expect: bad interpreter: No such file or directory". Please install the "expect" package.

Please note that the required installed packages are documented in Section 2 of the documentation. I kindly request you to follow the documentation and to carefully read the error messages before you consider to open an issue at GitHub. The issue tracker should not be mistaken as a support forum.

Regarding assistence while exploring Genode, let me refer you to our mailing list, which is the preferred place to discuss the use of the framework. Please subscribe to the list before posting: http://genode.org/community/mailing-lists
