### ISSUE TITLE
usb: update to recent Genode APIs

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#2019]

**Comment by chelmuth** [comment]
@cnuke could you please have a look at the merged e9ceba6c7b8e6be6df04d82628caaf688ead7486. I had to look twice to understand that the class variable has to be instantiated in the usb driver.

**Comment by chelmuth** [comment]
@ssumpf we need a fix for the following link error
```
    LINK     usb_block_drv
main.o: In function `Usb::Packet_handler::wait_for_packet()':
.../repos/os/include/usb/packet_handler.h:76: undefined reference to `Server::wait_and_dispatch_one_signal()'
```

**Comment by ssumpf** [comment]
@chelmuth: Please review commits:  3949bd2, 8013285, 40952e7 and possibly move them to staging.
