### ISSUE TITLE
Valgrind wrapper for Genode/Linux

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#202]
As a first step for solving #200 I created a configurable Valgrind wrapper based on @myrkr's example code that can be used to run Genode applications in Valgrind on Linux:

https://github.com/cproc/genode/commit/f0a0ed961d1f83bae955333271b9b11fa89ebbb3

The configuration looks like this:

```
<config>
	<parent-provides>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<start name="valgrind_wrapper">
		<resource name="RAM" quantum="4M"/>
		<config>
			<arg value="valgrind"/>
			<arg value="./test-valgrind_wrapper"/>
		</config>
	</start>
</config>
```

The <arg> nodes are the command line arguments for Valgrind.

Valgrind needs to be installed in either ```/bin``` or ```/usr/bin```, because that's the only places where ```execvp()``` is looking by default. The Valgrind wrapper program doesn't actually do anything Valgrind-specific besides executing "valgrind", so it could be generalized even more for running other Linux applications that need command line arguments if that would be useful.

**Comment by nfeske** [comment]
Let us close this issue until we ever plan to incorporate such a feature into the mainline of Genode.
