### ISSUE TITLE
vbox: add configuration option to force IOAPIC use

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2029]
The virtual PCI model delivers IRQs to the PIC by default and to the IOAPIC only if the guest operating system selected the IOAPIC with the '_PIC' ACPI method and if it called the '_PRT' ACPI method afterwards. A Genode guest never calls these functions, so IRQs can end up at the wrong interrupt controller (for example when using the USB driver on NOVA). A VirtualBox configuration option to enforce PCI IRQ delivery to the IOAPIC can help in this case.

**Comment by cproc** [comment]
Depends on #2028.

**Comment by ssumpf** [comment]
@cproc: :+1:  very good work, especially the finding it out part!
