### ISSUE TITLE
check report donation and buffer_size at report_rom

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2036]
Clients may acquire sessions with zero-length report buffers.

**Comment by ehmry** [comment]
This patch applied against the #1787 changes.

**Comment by nfeske** [comment]
Nice! However, as the patch broke the clipboard I had to add a corresponding fixup. I added both commits to staging.

**Comment by ehmry** [comment]
I made a small escaping error in a log message, fixed at 6e898861586b8bfaeb2da888a74cc618cf87e2fc

**Comment by chelmuth** [comment]
The fixup did not make it into the master-branch update. @ehmry do you agree that 1c2ae00488ec916e9679d61d947753dcbf39d35b qualifies to close this issue?

**Comment by ehmry** [comment]
Yes, I think so.
