### ISSUE TITLE
Additional pixel format support

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2045]
Supporting 32bit RGB would be nice, and it would also be nice if the Framebuffer session could support arbitrary formats, which would eventually be converted to the driver format.

My immediate use case is to serve a 32 bit format session, upscale the buffer, then convert down to 16 bits.

**Comment by NobodyIII** [comment]
I need this too. Here's my commit: 6940b28dc5e4167b21b8003d36705eab0d7b73d5

**Comment by nfeske** [comment]
Fixed by ef741ef80d477ae7052fca1d1bb7272c40ae4d6e in master.
