### ISSUE TITLE
Avoid absolute paths to host utilities in build system

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2047]
I don't have a /usr directory on my machine, which causes problems, but is actually not very hard to work around. I usually cherry-pick a patch onto each of my branches so this patch would make my life a bit easier :-)

**Comment by chelmuth** [comment]
I wonder if (as a better alternative to your patch) the shebang lines should be fixed by using `#!env <tool>`. Admittedly, I've no experience with the portability of this approach.

**Comment by cnuke** [comment]
Using `env` works in case there is no follow argument to the invoked program since you can only have one argument an in the shebang line.

**Comment by ehmry** [comment]
Which would not work in the case of 'make -f'.

**Comment by chelmuth** [comment]
That's a pity.

**Comment by chelmuth** [comment]
Rediscovered this just now. I'm not convinced to merge the patch. IMO `/usr/bin` is a UNIX'ism but always there, and, many tools depend on it.

**Comment by ehmry** [comment]
Yea, I can live with that assumption, I'm switching to Arch.
