### ISSUE TITLE
NOVA: keep revoked object in mapping database only if a sub node exists

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2048]
Currently, a capability received by a Genode component remains in the NOVA mapping database if the capability is deleted in the component. This is necessary to prevent the unwanted revocation of the capability from other components if the corresponding mapping database entries are further down the mapping tree. But it is not necessary to keep the deleted capability in the mapping database if no sub nodes exist.

**Comment by cproc** [comment]
@alex-ab: please review and integrate https://github.com/cproc/NOVA/commit/ce248a3669f9125637cc61a576b1ba7e7e1c9fce

**Comment by alex-ab** [comment]
done, please have a look
