### ISSUE TITLE
add virtualbox 5 support

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2059]

**Comment by alex-ab** [comment]
@nfeske: please use the last 3 commits of [issue_2059_staging](https://github.com/alex-ab/genode/tree/issue_2059_staging)

**Comment by nfeske** [comment]
Merged to staging just now. :-)

**Comment by cnuke** [comment]
@chelmuth or @nfeske please merge 12903b7 and 4467f0a to staging.

**Comment by nfeske** [comment]
@cnuke Thank you! The include guard of needed a small additional adjustment though ;-)

**Comment by cnuke** [comment]
Shame on me — it was the first thing I thought about and still missed it at the end :-)

**Comment by chelmuth** [comment]
Merged with 57b90e8.

**Comment by ehmry** [comment]
I'm having an issue with network slot labeling, there is a bit of patch missing from the previous version that I can foward...

**Comment by chelmuth** [comment]
Put in #2081 for post-release merge.

**Comment by alex-ab** [comment]
@chelmuth: please consider d72d38d40a05cd762d16e901259e4906a26a539d for staging if it fits

**Comment by alex-ab** [comment]
@chelmuth: sorry, forget about it - not ready yet because it breaks vbox4

**Comment by alex-ab** [comment]
@chelmuth: commit 85347a557916d71948ec82d1c7c27b340c5f5a44 is better

**Comment by alex-ab** [comment]
5.1.10 is on master
