### ISSUE TITLE
terminal clipboard support

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2079]
I have been thinking more about an Acme editor clone for Nitpicker and I've decided the sensible way to go about it would be to share code with the current terminal server and initially draw everything using a character cell display. I want to recreate the mouse driven interface and using highlighted text from a char-cells as editor commands would be a good first step.

@nfeske I see the terminal server has not been upgraded to the new entrypoint model, are there plans for an refactor of terminal?

**Comment by nfeske** [comment]
Indeed, there are several plans for the terminal such as making it resizable (with proper line rewrapping), adding mouse support, making the cursor blink (#608), adding clipboard support, or providing a smoothly scrolling history buffer. But unfortunately, those plans remained lower down on my priority list so far.

That said, when pursing the plans, the notion of the cell array will most likely stay as a basic mechanism and will probably receive a few optimizations. So it is certainly a good idea to take it as a starting point for your idea. You can simply ignore all the other character-screen stuff. If you have further suggestions for making other parts of the terminal better reusable for your purpose, I am all for it!

(Btw, I think that we should offer a port of QTerminal or at least the QTerminalWidget in addition to Genode's simple terminal for regular end users. So we could accommodate users who need proper UTF8 support and other modern features without pushing these requirements onto our simple terminal.)
