### ISSUE TITLE
Page-faults in thread context area invisible

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#2082]
On the kernels: SeL4, Pistachio, Fiasco, OKl4 we do not see when a thread issues a page-fault due to a stack overrun. On Fiasco.OC there is no identity shown, but at least the page-fault address and instruction pointer. On HW and NOVA you can see the page-fault (including thread identity) in differently layouted messages.

It would be very nice to have corresponding messages on all kernels. It would be even nicer to unify the page-fault reporting.

**Comment by chelmuth** [comment]
I really like this patch and it will enter staging in a second, but I still have one additional concern: Could you please have a look at *repos/base/src/core/region_map_component.cc* lines 171, 189, and 225? It seems their exists a platform-specific `print_page_fault` utility, which looks rather different on various kernels. It would be great to have a fixup commit that unifies these log outputs too.

**Comment by skalk** [comment]
@chelmuth thanks for the review and improvement proposal. Fixup 23afcfc42f3444b366c8813f28ed88779d91cef8 tries to unify also the `print_page_fault` utility.
