### ISSUE TITLE
core: page faults during rm_faulter::dissolve_from_faulting_region_map

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2086]
nova_x86_32 in qemu - run/platform

```
89 MiB RAM assigned to init
[init] Error: Could not open ROM session for "ld.lib.so"
[init -> test-platform] testing base-nova platform
[init -> test-platform] Warning: pager: created
[init -> test-platform] mapper: hello
[init -> test-platform] mapper: request mapping 0x9000
[init -> test-platform] Error: pager: got map request
page fault, pd='init -> test-platform' thread='mapper' cpu=0 ip=0x100091c address=0x9000

PAGE-FAULT IN CORE (READ pf_addr=6d0d4 pf_ip=15bc98 from 00 'unknown':'unknown')

stack pointer 0xa01febb0, qualifiers 0x4 irUwp
faulter utcb 0xa01ff000, last message item count 0
  #1 0xa01febb0 0x0015bc98
  #2 0xa01febbc 0x0016586d
  #3 0xa01febfc 0x0013c64e
  #4 0xa01fed3c 0x00104103
  #5 0xa01fee3c 0x001072c8
```

**Comment by alex-ab** [comment]
Please have a look, the "core: ..." issue solves the issue for me.

**Comment by alex-ab** [comment]
Hm, the fix avoids core to crash but scenarios like ```run/rm_nested``` don't work anymore.

**Comment by alex-ab** [comment]
56cec43c474242b3ba256f80a0e25517747ea806 avoids the core crash and let the nested region test pass - as stop gap solution

**Comment by chelmuth** [comment]
@alex-ab which commits of your topic branch are ready for staging?

**Comment by alex-ab** [comment]
474e982a01009c6ffc82ab2c5450e49f5ff90bba and 39d09150e0ca9f708f4438312baf98d618d67ac6

**Comment by alex-ab** [comment]
f47feeb696759435702312ea2a18de8a35f5079f contains the suggested weak_object and weak_ptr version.

**Comment by nfeske** [comment]
Yes! :-)

**Comment by chelmuth** [comment]
Merged as 4629371.

**Comment by alex-ab** [comment]
@chelmuth, @nfeske: please consider 6bd0e48938f17872cc45f7f7805485a24ccbf227 for staging (and 47d377a5a0b606cfb84245c98617800969cbe1c4). The commit on master 99fbb23ec53bd5f10038890c4d9986613b4548f7 which uses Weak_ptr/Weak_object (as discussed here) in a wrong way (re-)introduced  a deadlock in core.

**Comment by chelmuth** [comment]
Nice, merged both commits into staging.
