### ISSUE TITLE
create_iso error in help

### ISSUE THREAD

**Issue by cgrothrock** [genodelabs/genode#2093]
running the command ./tool/create_iso  shows the script parameters available.  In this instruction, the message "A sample directory tree can be found in the tool/boot/genode."  The issue is in the tool/boot/ directory, there is no genode directory.

**Comment by nfeske** [comment]
The commit https://github.com/genodelabs/genode/commit/a2f729bc5a5ad2a1051e28d28b729c937c910606 removes the outdated message. Thanks for pointing out this issue.
