### ISSUE TITLE
Make GNU build-system wrapper usable for non-Noux programs

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2094]
The ports/mk/noux.mk wrapper for the GNU build system is very handy to port software that is based on the GNU build system to the Noux runtime. However, there are many applications that come readily equipped with support for the GNU build system but don't require actual Unix features (i.e., fork). Right now, porting such applications requires us to express their build rules via the Genode build system. In most cases, this is fairly easy but still requires manual labor. It would be nice to be able to use the build-system wrapper as used by noux packages for such applications as well.

**Comment by chelmuth** [comment]
The build fails with
```
  CONFIG   vim
Error: configure script of vim failed
.../contrib/vim-460a4a30deb93fee494a17ff6e64afaf813a37dd/src/noux-pkg/vim/configure: 6: cd: can't cd 
```
Is this related to d603adc?

**Comment by nfeske** [comment]
Yes, thanks for the notice. I added a fixup for the original commit.

**Comment by nfeske** [comment]
Commit c500f6657c415c0ef8cd05f84576c29079a20519 should fix the issue along with the warnings during the clean rule about the disappearing current working directory.
