### ISSUE TITLE
hw: remove kernel unit test framework

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#2096]
Currently, the kernel unit tests, originally a framework to test certain kernel data-structures, stands in the way on certain levels:
* within the kernel initialization
* when building core
* when building the boot-image
On all these levels, we need special solutions for either starting the "normal" kernel, or a unit test. This additional complexity stands in the way, e.g., when implementing issue #2095. On the other hand, the unit tests aren't really used in an automated fashion. I therefore vote for removal. When we want to test certain features, I would like to test kernel/core API. If you want to test certain data-structures in a unit test, this can be done in a self-contained user-land component.

**Comment by nfeske** [comment]
I agree.
