### ISSUE TITLE
Genode/seL4 example scenario - where is the source?

### ISSUE THREAD

**Issue by dckc** [genodelabs/genode#2102]
How is the sel4.iso built? Is there a config file for the qt+noux+nano3d setup?

I hope I'm not missing something obvious...

**Comment by nfeske** [comment]
Please refer to the following posting on the mailing list:

https://sourceforge.net/p/genode/mailman/message/35358699/

**Comment by dckc** [comment]
ok... [sel4.run][] is what I was looking for. Thanks!

d6bbc5c62ca0203af44e35f0a808e1aa9761e9bc

[sel4.run]: https://github.com/alex-ab/genode/blob/sel4_screenshot/repos/libports/run/sel4.run
