### ISSUE TITLE
Remove placement new operators

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2106]
We should use the `construct_at` function (util/construct_at.h) wherever possible.

The biggest offenders are the net headers at `os/include/net`.

**Comment by chelmuth** [comment]
Don't forget `repos/os/src/drivers/platform/spec/rpi/*.h`.

**Comment by trimpim** [comment]
I will rebase my IOMUX patch to the newest framework next week, I could do this then.

**Comment by nfeske** [comment]
Commit https://github.com/genodelabs/genode/commit/f26cacad803bf4dd622b04a4a3a9540aabe254a8 adjusts the Rpi platform driver.

**Comment by nfeske** [comment]
Commits https://github.com/genodelabs/genode/commit/57ebd947eda73e81080b594885cd3616454b1fb5 and https://github.com/genodelabs/genode/commit/36e7c64b448037fffc2bca357a907e82bc902c94 wrap up this issue.
