### ISSUE TITLE
 dde_ipxe: increase RXD and TXD for Intel NICs

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#2108]
Using the `nic_drv` while AMT is enabled can lead to the PHY getting stuck for all but the AMT traffic. For that to happen it does not matter if AMT is actually used (SOL); it is enough to have it enabled. This behaviour was observed on a Thinkpad X250 which uses a I218-LM device. On a Shuttle DS57U which does not support AMT but also features the same device the issue does not exist.

iPXEs Intel driver sets the RX and TX descriptor number to low values (8 and 16). Increasing those to 16 and 32 solves the AMT issue. Although the spec gives indeed 8 as the minimum descriptor number, most other OS drivers, i.e., Linux and OpenBSD, use 256 as default.

I have adjusted the values accordingly and tested it on various systems (X220, X250, DS57U, macho) and they work fine.

**Comment by ssumpf** [comment]
@cnuke: :+1:

**Comment by chelmuth** [comment]
Thanks for your extensive investigation!
