### ISSUE TITLE
usb_drv: fix policy parsing

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2112]
According to the README file, the policy supports 'vendor_id' and 'product_id' attributes, but the policy parsing code looks for 'vendor' and 'product'.

**Comment by chelmuth** [comment]
I see that you went for `vendor_id` etc. @cnuke should usb_block also be adapted accordingly?

**Comment by cnuke** [comment]
@chelmuth yes, for consistency (the usb_block_drv does not use this attributes directly but generates a report that contains `vendor` instead of `vendor_id`).

**Comment by chelmuth** [comment]
May I ask why you like `vendor_id` more than `vendor`?
