### ISSUE TITLE
Adjust the nic_drv's memory requirements

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#2121]

**Comment by cnuke** [comment]
@nfeske please merge 76a5e9a and  bba30d3 to staging.

**Comment by cnuke** [comment]
While here, let's get rid of some unused code. Those tests remained unused for several years and adjusting the quantum brought them back to my attentation.

@nfeske please also merge 455c1aa to staging (it depends on “Increase nic_drv RAM quantum”).

**Comment by nfeske** [comment]
It's my pleasure.
