### ISSUE TITLE
base: add Binary Output helper class

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#2134]
I'm not sure if it is necessary to have this helper in base but since it saves me some time while debugging somebody might put it to good use, too.

**Comment by chelmuth** [comment]
I hesitate to merge you patch because it copies a dozen lines of code and changes about a dozen characters in the copy only... Do you think the redundant parts can be refactored?

**Comment by nfeske** [comment]
I would prefer not to merge it because the base framework does not depend on it.
