### ISSUE TITLE
vfs: strange hang when filesystem is full

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#2138]
I stumbled across this problem when using the Heeselicht scenario. When copying into a filesystem, in this case ext2 with rump_fs, where there is not enough space left, the copy operation of the bash never stops, and produces a lot of garbage escape sequences on the terminal.

**Comment by skalk** [comment]
above commit contains a more workable run-script than Heeselicht to reproduce the issue.

**Comment by chelmuth** [comment]
@cnuke IIRC you have additional information regarding this topic.

**Comment by cnuke** [comment]
Yes, @skalk already tried the quick-and-dirty fix-attempt (*written > 0 ? OK : ERROR*) but it did not help. So we have to investigate further.

**Comment by nfeske** [comment]
I'm closing this issue because it has become stale.
