### ISSUE TITLE
Port and integrate Lua for script-based testing

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#214]
[Lua](http://lua.org) is a clean scripting language with excellent portability capabilities (just ANSI C) and a tiny runtime implementation. These properties recommend Lua as base for test scripting or rapid prototyping. After the inital port of the language runtime, essential Genode interface should be made available to Lua scripts as libraries or classes.

**Comment by nfeske** [comment]
I doubt that we will follow this approach. Let us reopen this issue, if we ever decide to pick it up.
