### ISSUE TITLE
Complications with USB legacy support and PCI bus scanning

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2146]
On a Lenovo x201, when USB legacy support is enabled in the BIOS setup and a connected USB mouse is moved while the platform driver or the seL4 kernel scans the PCI bus, the machine can hang.

The modification of the platform driver in commit cproc@acc1db9f71d82cdbc9c8eb86eb0b2a60d001b8a8 demonstrates the problem, for example when running the 'framebuffer.run' test.

The problem does not occur on NOVA, because the USB mouse is disabled after the NOVA kernel writes the 'ACPI enable' command into the 'SMI command' I/O port.

**Comment by nfeske** [comment]
No longer relevant for us.
