### ISSUE TITLE
Server may get stuck if using the Log_connection late the first time

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2147]
I using a scenario with nitpicker and multiple VMs and getting the whole setup stuck after some minutes (~5) of normal use. The last message is

```
Warning: Insufficient quota for transfer: init -> report_rom
Warning:   have 0, need 8192
[init] Warning: not enough quota for a donation of 8192 bytes
[init] Error: quota_exceeded - requesting for LOG args=ram_quota=8K, label=""
```

It seems after some while the report_rom service wants to open the first time a log connection, but has no sufficient memory quota anymore. Shortly after the message everything seem to get stuck. The mouse pointer does not move anymore. 

According to some debug messages of the kernel and of some sporadic log messages of drivers, like usb, the system is still alive.

If one adds an explicit first log message call in the Component::Main report_rom service the issue goes away. Obviously initializing the log session late (if a server is already under memory pressure) causes this issue.

**Comment by chelmuth** [comment]
That looks rather strange as the LOG connection is explicitly initialized in `init_main_thread`.

**Comment by chelmuth** [comment]
I was wrong with my assumption that the instantiation of `Log` also creates the LOG connection. If I enforce also the connection creation at the end of `init_log` by calling `stdout_write` I get the following
```
Genode 16.08-35-gc1e4a77 <local changes>
211 MiB RAM assigned to init
[init] ENFORCE
[init] Error: Could not open ROM session for "ld.lib.so"
[init -> report_rom] ENFORCE
[init -> acpi_drv] ENFORCE
[init -> acpi_report_rom] ENFORCE
[init -> platform_drv] ENFORCE
[init -> fb_drv] ENFORCE
[init -> ps2_drv] ENFORCE
[init -> timer] ENFORCE
[init -> nitpicker] ENFORCE
[init -> pointer] ENFORCE
[init -> cpu_load_display] ENFORCE
[init -> trace_subject_reporter] ENFORCE
[init -> cpu_burner.2] ENFORCE
[init -> dynamic_rom] ENFORCE
[init -> report_rom] resource_request: ram_quota=36864
[init -> report_rom] used before freeing emergency=573440
[init -> cpu_burner.1] ENFORCE
[init -> report_rom] used after freeing emergency=557056
signal receiver sm is not valid
```
It seems report_rom cannot recover from this state.

**Comment by alex-ab** [comment]
Above commit also avoids the problem (thx @nfeske for the hint) - so it is a chicken/egg issue - avoiding doing log output if the log connection can't be established.

**Comment by chelmuth** [comment]
@rite the patch ca99c58cd10fbadc2624ecdcf1d6bdde60500e82 above circumvents the report_rom issue but we're still looking for a proper solution.

**Comment by alex-ab** [comment]
With 16.11 release (specifically commit cfdbccc5c2cdbbeb76c2d20f93e34322c9bb3478) the log session is already opened by the parent and the child just has to request the session capability and instantiate the Log session client. That means that now the resource request is visible (no invisible 'hanging' of report_rom) and one may adjust the report_rom quota accordingly.
