### ISSUE TITLE
vfs: block_file_system client crashes because of unhandled Packet_alloc_failed

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2154]
Seen with vbox using ahci model. The exception is not handled here:

https://github.com/genodelabs/genode/blob/master/repos/os/include/vfs/block_file_system.h#L77

**Comment by alex-ab** [comment]
Does this commit qualify as stopgap fix ?

**Comment by chelmuth** [comment]
@ehmry I have the feeling this will be silently fixed with the new async VFS?

**Comment by ehmry** [comment]
It should, but so far I have neglected to write a proper async plugin.

**Comment by alex-ab** [comment]
I have now the confirmation that the two commits fixes the issue of a customer. If the commits go not online, which I can understand, please make sure that the Packet_alloc_failed case during alloc_packet is handled properly.

**Comment by ehmry** [comment]
If there is a problem I say push the fixes until the new block client is ready.

**Comment by alex-ab** [comment]
@chelmuth, @nfeske: please consider the commit for staging, if the async vfs does not make it to the release

**Comment by chelmuth** [comment]
I merged 16d55d1f83a7fb711aa9b4361736549eeb260f2c. @alex-ab please check if I resolved the merge conflicts correctly.

**Comment by alex-ab** [comment]
Looks good, thx
