### ISSUE TITLE
run tool support for Genode hosted Linux development

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2157]
I would like to pass a run scenario from Linux in Virtualbox down to a Genode host, my motivation is network testing with full routing.

It should be possible to copy binaries and configuration thru a shared folder, and start a execute a the scenario by triggering a configuration reload in a running init instance. I will find out.

**Comment by ehmry** [comment]
On second thought, better to control an instance of cli_monitor through a terminal file.

**Comment by nfeske** [comment]
Would you like to keep the issue open or is it obsolete?

**Comment by ehmry** [comment]
I would like to keep it open, I want to get ROM support and notifications into the VFS server, and then that should handle all the necissary configuration pushing and updating.

**Comment by ehmry** [comment]
No, I close this and reopen later.
