### ISSUE TITLE
base: iterator for AVL tree

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#2159]
While implmenting issue #2092, again I hit the problem to iterate over an AVL tree. I think we need this very basic functionality several times, so I would like to integrate it into the AVL tree itself. Thereby we can also replace the current debug print utilities within Allocator_avl.

**Comment by m-stein** [comment]
@skalk I've also needed such an iterator for the NIC routrer and implemented it in  https://github.com/m-stein/genode/commit/2dc1901ea79291b3432b466fe2fc59ec84230abd

**Comment by m-stein** [comment]
@skalk Your code implements an in-order traversal while mine implements a post-order traversal. For my use case it isn't relevant in which order the tree is traversed but I would suggest to name the iterator according to the traversal type in general.

**Comment by skalk** [comment]
Ok, I've added a comment, changed the template type's name, and reworked Rom_fs to use the new 'for_each'. @nfeske: would you mind to review it once again?

**Comment by skalk** [comment]
No problem! I will change it.

**Comment by skalk** [comment]
@nfeske ok, finally done.
