### ISSUE TITLE
nova: support asynchronous delegate

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2173]

**Comment by alex-ab** [comment]
@chelmuth: please consider last 3 commits of issue_2173 branch for staging

**Comment by alex-ab** [comment]
@chelmuth, @nfeske: the last commits of [branch](https://github.com/alex-ab/genode/commits/issue_2173_staging) may get to staging, (but has not to) - mainly improvements to vbox speed (if used with multiple vcpus) and additionally implicitly reduced kernel memory resource usage

**Comment by alex-ab** [comment]
@nfeske, @chelmuth: please consider/review the last two commits of [the 2173 branch](https://github.com/alex-ab/genode/commits/issue_2173) for closing this issue for now

**Comment by chelmuth** [comment]
Merged.
