### ISSUE TITLE
SD card: clean up and i.MX6 support

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2206]

**Comment by m-stein** [comment]
@nfeske My branch ``2206_SD_card_clean_up_and_i_MX6_support`` fixes the issue and updates the components sd_card_drv and sd_card_bench to the new Genode API.

**Comment by m-stein** [comment]
@nfeske I've updated the branch to work without the MMIO-wait-for commit.

**Comment by nfeske** [comment]
Fixed in Genode 17.02
