### ISSUE TITLE
base-hw/x86_64: Translation_table fails when PML4 is used

### ISSUE THREAD

**Issue by senier** [genodelabs/genode#2210]
In a custom application I'm using the Translation_table implementation from base-hw/x86_64 to manage an 48-bit address space. When inserting a translation that makes use of PML4 (i.e. an address  >= 2^39), the operation fails with page fault.

Example code fragment:

```
   Translation_table *ppgtt;
      if (!gpu_allocator.alloc (sizeof (Translation_table), (void **)&ppgtt)) throw -1;
    ...
    addr_t va = 0xdeadbeef000;
    Genode::log ("Mapping va=", Genode::Hex(va), " to pa=", Genode::Hex((addr_t)scratch_pa),
                 " (base of scratch=", Genode::Hex((addr_t)scratch_addr), ")");
    ppgtt->insert_translation (va, (addr_t)scratch_pa, 4096, scratch_flags, &gpu_allocator);
```

Output:

```
Mapping va=0xdeadbeef000 to pa=0x3382000 (base of scratch=0x7000)
no RM attachment (READ pf_addr=0x23d58 pf_ip=0x100b9a6 from pager_object: pd='init -> intel_fb_drv' thread='ep')
page fault, pd='init -> intel_fb_drv' thread='ep' cpu=0 ip=0x100b9a6 address=0x23d58
```

Apparently, calculating the PML4 table index is wrong, leading to an out-of-bounds access.

**Comment by skalk** [comment]
@senier : thank you very much for investigating the problem. We already discussed yesterday in a coffee break that we have to get rid of this manual bit-shifts by using appropriated helper functions to avoid these recurring wrong integer type problem. Unfortunately, we cannot apply a patch without a signed contributor's agreement.

**Comment by senier** [comment]
I'll hand one in tomorrow.
