### ISSUE TITLE
dde_rump: Transition to new base API

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#2224]

**Comment by ssumpf** [comment]
Note in 78a1c1a rump_cgd and the VFS plugin are not converted or tested as of now.

**Comment by ehmry** [comment]
I have the VFS plugin ready at e390cbd0e4eae5ad99cbd7ca9ed3380b81619343 and e69ced1744a40f7ea8330115e6a5a536d26b7afe.

**Comment by nfeske** [comment]
Cool! I merged your commits to staging.

**Comment by ssumpf** [comment]
@nfeske:  d438307 rebases to staging

**Comment by nfeske** [comment]
@ssumpf thanks a lot! I merged your commit to staging.
