### ISSUE TITLE
FB Block Adapter: Request for removal

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2245]
The FB Block Adapter in ``os/src/test`` visualizes a block session via a Framebuffer session. As far as I can see, it is not a test but rather the base for a bump-in-the-wire component. However, for this role it currently lacks a Block back-end. As it also would have to be updated to use the new base API I'd like to remove it instead, leaving only its git history as inspiration if someone needs such a component in the future.

**Comment by m-stein** [comment]
@skalk Do you have any objections?

**Comment by skalk** [comment]
I'm fine with removing it.
