### ISSUE TITLE
hw: SMP issue when having more than three cores

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#2254]
When enabling more than three core, we relatively reliable see a page-fault when running the mp_server test during early initialization of the test:
```[init -> test-server-mp] Detected 4x1 CPUs.
no RM attachment (READ pf_addr=0xd8dd0020 pf_ip=0x6b870 from pager_object: pd='init -> test-server-mp' thread='rpc en')
Warning: page fault, pager_object: pd='init -> test-server-mp' thread='rpc en' ip=0x6b870 pf-addr=0xd8dd0020
Warning: core -> pager_ep: cannot submit unknown signal context
```
It happens always at the same point with the same page-fault address. It doesn not happen when artificially limit the concurrent threads to three. It does not happen when using the affinity test.

**Comment by m-stein** [comment]
Fixed by:
71d6607 hw & arm: write whole SPSR in mode transition
35c069b run: provide core image with path information
