### ISSUE TITLE
Enforce build of jitterentropy library with -O0

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#2256]
If `CC_OLEVEL` is set in a build directories *etc/tools.conf* the jitterentropy library is not built with `-O0` despite a corresponding directive in *jitterentropy.mk*.

**Comment by chelmuth** [comment]
While fixing this bug I discovered similar fragments at the following places.
```
repos/dde_linux/lib/mk/usb.inc:CC_OLEVEL = -O2
repos/dde_linux/lib/mk/lxip.mk:CC_OLEVEL = -O2
```
@cnuke and @ssumpf do you have any opinions if these can be removed or adapted accordingly?

**Comment by cnuke** [comment]
According to @ssumpf its purely a debugging artifact and can be removed.
