### ISSUE TITLE
Trace test must be revised

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#2260]
The test in *repos/os/run/trace.run* has several issues.

1. The test requires *rpc_name*, which can't be built for riscv as the linker chokes with a segmentation fault. The planned tool-chain update should resolve this.
2. The core `Trace::Session_component` does not use the `Session_policy` and, therefore, does not support `label_prefix`. This can easily be fixed.
3. The core implementation of the trace-policy handling uses a slab cache for policy objects but the types for slab dimensioning and the actual object instance seem to mismatch.

That's what I found out this morning, but as I did not fix 3) there may be more hidden issues.

**Comment by cnuke** [comment]
5ffc7f1 makes the test work again, although I'm puzzled why the explicit namespace has to be used for the compiler to calculate the right size.

**Comment by cnuke** [comment]
I reworked the test and now the run script uses the `null` policy module (so we can enable the test in the autopilot).

**Comment by ValiValpas** [comment]
for the record: this is related to #1508

**Comment by cnuke** [comment]
@ValiValpas thanks for the reminder, I completely missed this old issue :+1:

**Comment by chelmuth** [comment]
If I understand it correctly dc6247d qualifies as fix for #1508, right?

**Comment by cnuke** [comment]
4fd130e should fix it but I did not verify it.

**Comment by nfeske** [comment]
Fixed in master.
