### ISSUE TITLE
Genode::String x(Genode::Hex(value)) produces not expected output

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2265]

**Comment by alex-ab** [comment]
The commit above triggers the issue:

```
[init -> test-log] hex range:          [0e00,1680)
[init -> test-log] empty hex range:    [0abc0000,0abc0000) (empty!)
[init -> test-log] hex range to limit: [f8,ff]
[init -> test-log] invalid hex range:  [f8,08) (overflow!)
[init -> test-log] negative hex char:  0xfe
[init -> test-log] positive hex char:  0x02
[init -> test-log] multiarg string:    "parent -> child.7"
[init -> test-log] snprintf replacement: 0x
[init -> test-log] Test done.

Line 7 of output is unexpected
 expected: '[init -> test-log] snprintf replacement: 0x3'
 got:      '[init -> test-log] snprintf replacement: 0x'
```

**Comment by alex-ab** [comment]
@nfeske: have two different ways to solve the issue, however I'm unsure which of the commits are the right one. I would guess variant 1 and variant 2 just workaround the issue ?

**Comment by nfeske** [comment]
@alex-ab thanks for uncovering and fixing this issue. I agree that the variant 1 is the better fix. I'd like to add the test case to the log test. However, as a minor detail, would you fix the horizontal alignment by adding one space to the previous lines or by shortening the new line accordingly?

**Comment by alex-ab** [comment]
@nfeske: Ok, done.
