### ISSUE TITLE
Remove special-case libc_resolv library

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#2273]
The resolv library should become an inherent part of our libc and the socket-fs approach. This enables us to work out #2204 and #1463 in a clean manner.

**Comment by ehmry** [comment]
@chelmuth fixed at 395ce5bfcd18104501939d34f29a2b6a37ed6358

**Comment by ehmry** [comment]
I have more symbols to add at 2bd15fc9b36ead9a1c1fdf1f4b412edcd37930ef
