### ISSUE TITLE
base: rom_logger outputs line feeds twice

### ISSUE THREAD

**Issue by ValiValpas** [genodelabs/genode#2279]
I noticed that from 16.11, the rom_logger outputs an additional empty line after each line. I suppose the reason for this is because it uses the print_lines() function, which keeps line feeds, in conjunction with the log() facility, which adds a line feed.

**Comment by ValiValpas** [comment]
11485fe might be a solution for this

**Comment by nfeske** [comment]
Thanks for the fix! I merged it to staging.
