### ISSUE TITLE
for a fist full of deprecated env warning fixes

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#2280]

**Comment by nfeske** [comment]
Thanks for this comprehensive commit series! Merged to staging.

**Comment by cnuke** [comment]
@nfeske please merge to staging.

**Comment by cnuke** [comment]
@nfeske please merge 8c5c625 and 216ad2c to staging.

**Comment by cnuke** [comment]
@nfeske 19cd0b1, 6df8f98,  97972b5, af844a0 and 9b01b45 remove global env usage from the libc.

**Comment by cnuke** [comment]
@nfeske please consider 56bb15e, 3f79400, 809f24e and 3d34d28 for staging.

**Comment by cnuke** [comment]
@nfeske please consider 5d9469c, 8572f0a, 8458af7 and f05222d as well for staging; nothing fancy — just less compiler warnings.

**Comment by nfeske** [comment]
@cnuke Thanks a lot!
