### ISSUE TITLE
signal_test: `Wait_and_dispatch_test` does not return

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#2284]

**Comment by ssumpf** [comment]
@nfeske: please move 8eb29ed and 8f0cccd to staging.

**Comment by m-stein** [comment]
@nfeske Please merge when things have settled:
98dcbbe hw: fix race in signal dispatching

**Comment by nfeske** [comment]
The patch looks too good to be not merged right away. ;-)

**Comment by ssumpf** [comment]
@nfeske: Please merge 21e6c66 to staging

**Comment by m-stein** [comment]
@nfeske Added another commit:
8d71b47 signal test: add stressful nested test

**Comment by nfeske** [comment]
Fixed in master.

**Comment by cnuke** [comment]
@chelmuth or @nfeske please merge 0b4443f to staging.

**Comment by cnuke** [comment]
@chelmuth or @nfeske please merge d5dc9c1 to staging (second time is the charme).

**Comment by alex-ab** [comment]
@nfeske, @chelmuth: please consider bd8a903f41312a560dc555a4dc79cdf6b335b210 for staging, it fixes issues during destruction to the 9th test

**Comment by alex-ab** [comment]
@chelmuth: please consider 7810decfbf238d082b4897c53aa94d19d8a5bbb0 for staging instead of the previous commit

**Comment by chelmuth** [comment]
Nice, merged to staging just now.
