### ISSUE TITLE
gdb_monitor: kernel-agnostic build support

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2292]
Currenly, the 'gdb_monitor' binary is statically linked against a kernel-specific 'gdbserver_platform' library, which makes the 'gdb_monitor' binary itself kernel-specific.

The problem can be solved like it was done with 'ld.lib.so', by making the 'gdbserver_platform' library a shared library with a symbol file and renaming the platform-specific 'gdbserver_platform-nova.lib.so' and 'gdbserver_platform-foc.lib.so' files as 'gdbserver_platform.lib.so' when creating the boot image.

**Comment by nfeske** [comment]
That's very cool!
