### ISSUE TITLE
livelocks in cxa guard when using threads with various priorities

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2299]

**Comment by alex-ab** [comment]
I extended the showcase test to also trigger multiple cxa guards concurrently in use by several threads.

**Comment by alex-ab** [comment]
The attached fix uses a Genode Semaphore to handle the contention cases, where the blocked threads gets waken up/resumed in a stacked way one by one.
I will try to come up with another variant, as discussed with @chelmuth, which will instead resume all at once. Then you may vote for your favorite ;-)

**Comment by alex-ab** [comment]
As promised, a second version. Both commits solve the issue for me. Choose wisely - 53048b755625dc3cf40dc98871744883f3098ad8 vs 91dfdd93f6f96c2b7ee482dd600fd1d3d4b08cdb.

**Comment by alex-ab** [comment]
Sorry, wrong commit referenced.

As promised, a second version. Both commits solve the issue for me. Choose wisely - 6d323690030619a8a66983a51f1492b576c4e06b vs 91dfdd93f6f96c2b7ee482dd600fd1d3d4b08cdb.

**Comment by alex-ab** [comment]
I added another version which uses the newer Registry class instead of manually List/Lock combination.

**Comment by chelmuth** [comment]
I merged variant B into staging because of the open issues with C.

**Comment by alex-ab** [comment]
@chelmuth: please consider the last 4 commits of https://github.com/alex-ab/genode/tree/issue_2299_c_staging for staging
