### ISSUE TITLE
test/cpu_quota: tolerate errors in session quota 

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2304]

**Comment by m-stein** [comment]
@chelmuth please merge
3f2af3d test/cpu_quota: tolerate errors in session quota

**Comment by m-stein** [comment]
@chelmuth I added another commit
17df3f5 x86 cpu_quota: lower error tolerance

**Comment by m-stein** [comment]
A better solution:
260652f fixup "x86 cpu_quota: lower error tolerance"

**Comment by chelmuth** [comment]
@m-stein please check if current master contains all changes and close this issue if appropriate.

**Comment by m-stein** [comment]
Seems so.
