### ISSUE TITLE
vbox4: hangs sometimes during early boot

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2306]
On NOVA: win7_64 VMs are affected (independent of count of vCPUs)
On Muen/hw: win7_32 VM (single vCPU).

Part of the issue is, at least for the NOVA case, issue #2299 and #2300.

**Comment by alex-ab** [comment]
@nfeske, @chelmuth: please consider 9f0e83f78aec15a9d9cd6bb372ecf06dbf18963d, 8615e47ebc9f894687a35b33d2ce0327df523b91 and 17921acddbca0cf6b9dd37b5bb960e58949b0db6 already for staging

**Comment by chelmuth** [comment]
Please revisit this issue with current master containing all commits above.

**Comment by alex-ab** [comment]
@reet-, @Kensan: may you please re-check for muen-hw. For nova it looks like before the release, so there still issues if multiple VMs concurrently are started and some of them don't manage to come up into a usable state (the vbox_auto_multiple case).

**Comment by Kensan** [comment]
The status of **vbox_auto_win7** on base-hw/Muen remains the same: black screen after the initial VirtualBox boot screen is shown.

**Comment by nfeske** [comment]
Is this issue still valid? Or may we close it?

**Comment by alex-ab** [comment]
We may close it.
