### ISSUE TITLE
trace_subject_reporter: show cpu_load per cpu via log

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2307]

**Comment by alex-ab** [comment]
Added another version which is standalone (so - not part of trace_subject_reporter).

**Comment by nfeske** [comment]
I like your last commit. ;-)

In my opinion, we may even call the component just `top` instead of `top_log` because according to our server naming scheme, `top_log` would wrongly suggest that the component provides a log service. @alex-ab what you you think?

**Comment by alex-ab** [comment]
I'm fine, will change it.

**Comment by alex-ab** [comment]
Done. Please check.

**Comment by skalk** [comment]
@alex-ab is it necessary to run the trace test as SMP test? On qemu, we get horrible effects with SMP on hw because off spin-lock's during kernel initialization, which is no problem when using real hardware.

**Comment by skalk** [comment]
and on the zynq platform we get this error: `Number of SMP cpus requested (2), exceeds max cpus supported by machine `xilinx-zynq-a9' (1)`

**Comment by alex-ab** [comment]
smp would be good to test, but it would be sufficient for x86 or nova

**Comment by skalk** [comment]
ok, thanks! I'll incorporate it.

**Comment by skalk** [comment]
@nfeske @chelmuth : please consider commit 24fc11f for staging. It fixes all the currently broken trace tests triggered by the buildbot.
