### ISSUE TITLE
pthread_cond_timedwait: timeout calculation inaccuracies may lead to endless loop in vbox

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2311]

**Comment by alex-ab** [comment]
Please consider 25178c5de78c5ef32294e60d884adfbdf704b104 also for staging, if the dde_rump maintainers agree, so maybe @ssumpf, @cnuke and @cproc (as he added condwait support added).

**Comment by cnuke** [comment]
:+1:

**Comment by ssumpf** [comment]
@alex-ab: Please go ahead.
