### ISSUE TITLE
libc walks config twice to 'libc'

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2313]
[First](https://github.com/genodelabs/genode/blob/master/repos/libports/src/lib/libc/task.cc#L79)
[Second](https://github.com/genodelabs/genode/blob/master/repos/libports/src/lib/libc/vfs_plugin.cc#L92)

This causes a failure in configuring things like the RTC device.

**Comment by chelmuth** [comment]
Doesn't 72d59719409070684d267487e8c3e0485b80e3e3 fix the issue?

**Comment by ehmry** [comment]
Yes it does, I was just working off master.
