### ISSUE TITLE
base: Registry class not thread-safe

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2320]

**Comment by alex-ab** [comment]
With the commits, the _c variant of issue #2299 using the Registry class, succeed. Nevertheless, it is currently possible to use the Registry::Element class in a wrong way, so that I added a commit which tries to detect it and warn about. This happens to the original 2299 _c implementation. Please check.

**Comment by chelmuth** [comment]
If a718b28 should become the guard implmentation on staging, I'd like to ask you to rebase the branch.
