### ISSUE TITLE
dosbox: require x86

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2327]
Avoid compile errors when trying to build for an ARM platform.

**Comment by chelmuth** [comment]
I was curious why we did not experience this error each night but then discovered the ports repo is not enabled for the pbxa9 complete build. My question is: Is there a strong argument to skip ports for ARM?

**Comment by chelmuth** [comment]
Okay, I interpret the silence as lack of knowledge and, therefore, enabled the ports build for pbxa9.
