### ISSUE TITLE
run/qt5: move to '<config> <vfs/>'

### ISSUE THREAD

**Issue by rite** [genodelabs/genode#2328]
To reproduce, make run/qt5 (x86_64, KERNEL=nova) and play some rounds of tetrix :)

**Comment by chelmuth** [comment]
@rite thanks for the patch but could you please explain how it is connected to the issue subject? Did you forget to post another one?

**Comment by rite** [comment]
@chelmuth I wasn't sure whether it's worth opening two issues. I did it now, see #2329.
