### ISSUE TITLE
read_rtc: rtc not configured, returning 0

### ISSUE THREAD

**Issue by rite** [genodelabs/genode#2329]
To reproduce, make run/qt5 (x86_64, KERNEL=nova) and play some rounds of tetrix :)
042dafc doesn't resolves the issue, but removes some unrelated clutter in the log.

**Comment by ehmry** [comment]
You wil want to apply the fix at 72d59719409070684d267487e8c3e0485b80e3e3.

**Comment by ehmry** [comment]
This is the same issue as *libc walks config twice to 'libc'* #2313.

**Comment by rite** [comment]
I applied 72d5971 (and 042dafc) on master but read_rtc still returns 0. What am I missing?

**Comment by chelmuth** [comment]
A look into *var/run/qt5/genode/config* reveals that the scenario misses the rtc_drv and the corresponding VFS/libc configuration.

**Comment by alex-ab** [comment]
In the configuration of <dir name="dev"> at least a <rtc/> and additionally the rtc_drv must be loaded and build, repos/libports/run/qt5_drivers.inc seems to be a good place to add.

**Comment by chelmuth** [comment]
Commit f347cb90 addressed the immediate issue by configuring all examples with a static RTC value and libc config. The rtc_drv is still not part of *repos/libports/run/qt5_drivers.inc*, though. Still closing this issue as fixed.
