### ISSUE TITLE
Check Registered base class provides virtual destructor

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#2331]

**Comment by chelmuth** [comment]
Commit  db14841 represents my take on the issue and also fixes the timer test. There are other code places where the compiler whines (e.g., input_filter) that I'm going to eliminate in a fixup commit.

**Comment by chelmuth** [comment]
Commit 33dedc8 fixes the issue for me. @nfeske any remarks?

**Comment by nfeske** [comment]
Now that you are asking for any remark, superb! ;-)
