### ISSUE TITLE
vbox5: enable all features available also in our vbox4 port

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2338]

**Comment by chelmuth** [comment]
@alex-ab feel free to notify me if commits from this developments should be merged into staging early (resp. before the final issue is fixed).

**Comment by alex-ab** [comment]
@chelmuth: I cleaned up and squashed some commits, so now you may add them to staging. Feature wise SMP support got added.

**Comment by chelmuth** [comment]
Merge all commit incl. 8f49fe4 resp. 7824b0b

**Comment by alex-ab** [comment]
09860a6457efb13c4829f094a4a34862d76829b0 (+ the fixes of #2362) enables the xhci model for vbox5

**Comment by alex-ab** [comment]
shared folder test now also succeeds for vbox5

**Comment by alex-ab** [comment]
The guest additions version 5* are now working also properly. Beforehand solely vbox guest addition of version 4* in vbox 5 were actually running fine.
