### ISSUE TITLE
acpica: fix: Uncaught exception of type 'Platform::Session::Out_of_metadata'

### ISSUE THREAD

**Issue by MartijnVerschoor** [genodelabs/genode#2343]
After updating a scenario to 17.02 that includes acpica I get the following error (on nova x86_64 / x250):

[init -> acpica] detected - ec
[init -> acpica] Error: Uncaught exception of type 'Platform::Session::Out_of_metadata'
[init -> acpica] Warning: abort called - thread: ep

The acpica.run test script gives the same error (log attached). I tried updating the x86 platform session quota to 64K, but this did not help.

Any clues?

[acpica_log.txt](https://github.com/genodelabs/genode/files/851114/acpica_log.txt)

**Comment by alex-ab** [comment]
Please try following commit, it solves it for me on a X201.

**Comment by MartijnVerschoor** [comment]
This solves the issue for the X250 too.

Thanks! I'll close the issue.
