### ISSUE TITLE
hw core: generic timer driver interface

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2347]

**Comment by m-stein** [comment]
@skalk Could you please have a look at these commits. I had some spare time these days and this is what happened ^^ I don't know if they clash with your current base-hw development. If they do, we can also delay them.
0a0301b hw core: generic timer driver interface
f626ea4 hw cortex-a9 timer: raise translation precision

**Comment by skalk** [comment]
@m-stein: indeed it would be really nice if we delay the re-structuring commit. The Cortex A9 timer fix of course can be applied immediately of course

**Comment by chelmuth** [comment]
Merged 481660e89e197b766ed79e1a545c99b92fec0ef0 just now.

**Comment by m-stein** [comment]
Solved a bug in the new kernel timer driver:
8385f1d fixup "hw cortex-a9 timer: raise translation precision"

**Comment by m-stein** [comment]
This commit
29ab328 hw core: merge Kernel::Clock and Kernel::Timer
is the rebased version of the original fix that adds further simplification and a good diff-stat-karma.

**Comment by m-stein** [comment]
@chelmuth A little clean-up:
ea1710c base-hw: Rename 'tics' 'ticks'

**Comment by m-stein** [comment]
@chelmuth There's a fixup for muen
ad1cd93 Fixup "hw core: merge Kernel::Clock and Kernel::Timer"
