### ISSUE TITLE
libc: cannot override stack size

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2354]
The test program in commit https://github.com/cproc/genode/commit/c5b54e1716107c77ba256250b56fe576b9e9ca2a overrides the weak 'Libc::Component::stack_size()' function, but it doesn't get called. The 'nm' tool doesn't even show the symbol in the binary.

**Comment by chelmuth** [comment]
The following patch fixed the issue for me.
```diff
diff --git a/repos/base/lib/symbols/ld b/repos/base/lib/symbols/ld
index 11b6568..0814126 100644
--- a/repos/base/lib/symbols/ld
+++ b/repos/base/lib/symbols/ld
@@ -38,6 +38,8 @@
 # under the terms of the GNU Affero General Public License version 3.
 #
 
+_ZN4Libc9Component10stack_sizeEv W
+
 _Unwind_Complete T
 _Unwind_DeleteException T
 _Unwind_Resume T
```
The reason is that *libc.abi.so* does not declare its implementation of `Libc::Component::stack_size()` as weak and, so, it's not looked up in the binary. Finally, the link of the target garbage collects the unused function in *test-libc_stack_size*.

**Comment by chelmuth** [comment]
Thanks for the correct patch ;-)
