### ISSUE TITLE
themed_decorator: not properly updated to new API, causes incorrect behaviour

### ISSUE THREAD

**Issue by BorisMulder-CSL** [genodelabs/genode#2370]
Related: https://github.com/genodelabs/genode/issues/1987

I was converting an old scenario to 17.02 that used xray_trigger in the same manner as one of the old turmvilla scenarios. In there, I found out that themed_decorator does not respond to config changes properly. Somehow the main.cc was updated to the new API but the parts that actually handle the config (gems/src/app/themed_decorator/config.h) were not. Because of this (it uses the deprecated constructor of Genode::Session_policy) it does not respond properly to config updates. This way, the color of the window bars is not changeable.

It looks like it was fixed in decorator, but you have not finished updating themed_decorator yet.

**Comment by nfeske** [comment]
I'm closing this issue since it is stale for such a long time. During the daily use of the decorator, I have not encountered the problem because the decorator is in not reconfigured in practice (on Sculpt) but rather restarted.
