### ISSUE TITLE
acpi: do not out-of-bound read path array

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2371]
In os/src/drivers/acpi/acpi.cc we access a 1-item register-array named Path beyond it's boundaries. This is because the real size of the array can be determined only dynamically. Access beyond the boundaries of a register array definitely gets ignored / returns 0. If we know the maximum array size at compile time and it is safe to access the region between real and max size, we could declare the register array to be of the latter size (instead of size 1). Otherwise we could use the ``Mmio``-array approach that was suggested in #2369.

**Comment by alex-ab** [comment]
@chelmuth: please consider for staging
