### ISSUE TITLE
tool chain update for release 17.05

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2372]
Current update state:

- binutils 2.28
- GCC 6.3.0

TODO:

- add RISC-V support
- define 'size_t' as 'unsigned long' for both 32-bit and 64-bit architectures
- enable ADA support
- consider updating to GCC 7.1.0 when it's released (for the included RISC-V support)

**Comment by chelmuth** [comment]
While skimming over last night's test results I think we're almost there except the issues with foc, fiasco, and nova as well as *run/ldso*. Thanks @cproc for your great work!
