### ISSUE TITLE
base-hw: comparison of 'this' with 'NULL'

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2382]
When building core for the 'hw' kernel with GCC 6, the following warning occurs:

```
/.../repos/base-hw/src/lib/base/thread_bootstrap.cc: In member function ‘Genode::Native_utcb* Genode::Thread::utcb()’:
/.../repos/base-hw/src/lib/base/thread_bootstrap.cc:67:2: warning: nonnull argument ‘this’ compared to NULL [-Wnonnull-compare]
  if (this) { return &_stack->utcb(); }
  ^~
```

and the compiler likely optimizes the comparison out.

Possible solutions: refactoring of the code or adding ```__attribute__((optimize("-fno-delete-null-pointer-checks")))``` to the function which does the comparison.

Ref #2372

**Comment by chelmuth** [comment]
Reading all issues with `-fno-delete-null-pointer-checks` I wonder if GCC reliably warns when removing code just because it may be *undefined behavior*.  I got the feeling we should always declare this compiler flag instead of fixing code on a case-by-case basis.
