### ISSUE TITLE
hw: separate bootstrap and core strictly

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#2388]
For strict separation and more clarity we have to separate core and bootstrap. Therefore, all code that is shared should reside at a common place, like src/lib/hw.

**Comment by chelmuth** [comment]
Beside my single comment I'm for a merge as soon as possible.

**Comment by skalk** [comment]
@chelmuth : I've added two fixup commits, see above, for easier review. The one fixes all mistakenly rebased old licence headers, the second fixes a problem for Cortex A9 that was  unfortunately overlooked by me, when changing the last platforms.

**Comment by chelmuth** [comment]
Thanks, merged into staging.

**Comment by chelmuth** [comment]
It seems the timer on imx53 is not working anymore. I suspect the commits in this issue but did not check thoroughly. Could you please have a look?

**Comment by skalk** [comment]
@chelmuth here is a fixup eee42a035ef53173b7c8c2c33445317d2b121da0, actually not for the commit introducing the problem, but a fixup for the original commit bites the one that follows up. That's why the fixup addresses the follow-up commit.

**Comment by skalk** [comment]
Fixed in release 17.05
