### ISSUE TITLE
Entrypoint::wait_and_dispatch_one_io_signal() must be solely called by the entrypoint thread

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2399]
which is not the case everywhere (e.g. fs_file_system.h).

If a thread, e.g. a pthread of vbox on hw/muen,  issues write requests, the pthread may wait for the acknowledgements of the write requests.
If the pthread has to wait, it calls ``ep().wait_and_dispatch_one_io_signal()``. It will never return respectively wakeup, since the internal implementation will send the wakup to the entrypoint and not to the pthread (see ``repos/base-hw/src/lib/base/signal.cc  Signal_receiver::unblock_signal_waiter()``).

The generic implementation plays a bit better for the other platforms, e.g. vbox on nova (``repos/base/src/lib/base/signal.cc Signal_receiver::unblock_signal_waiter()``). There a Genode semaphore is used to block and unblock threads, so that the right thread will be woken up. That explains why vbox on nova still performs ok.

Nevertheless, ``Entrypoint::wait_and_dispatch_one_signal()`` in ``repos/base/src/lib/base/entrypoint.cc``, will fail to work as soon as the entrypoint and several pthreads call ``wait_and_dispatch_one_signal()`` concurrently.

**Comment by chelmuth** [comment]
@alex-ab dc866e8 logs a diagnostic message for this case.
