### ISSUE TITLE
Consolidate core's RAM and PD services into one

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2407]
Traditionally, Genode's core component decouples the management of RAM from the notion of protection domains (PD). Both concerns are provided as separate core services. While nice from an academic point of view, in practice, however, this separation did not provide any tangible benefit. As a matter of fact, there is a one-to-one relationship between PD sessions and RAM sessions in all current Genode systems (with the platform driver being the only exception).

Hence, the current superficial flexibility is needless complexity. Merging the RAM session functionality into the PD session has the potential to simplify core as well as framework libraries.

Since the implementation of capability-quota accounting (#2398), PD sessions have already become "accounts" for resources (i.e., capability resources), which was previously a distinctive feature of RAM sessions. That includes the support for trading resource quotas between sessions, and the definition of a reference account. The only unique functionality provided by the RAM service is the actual allocation and deallocation of RAM. So the consolidation is a natural step to take.

**Comment by cnuke** [comment]
@chelmuth @nfeske please merge 1b7a5f8 to staging.
