### ISSUE TITLE
Part_blk: added partitions reporting

### ISSUE THREAD

**Issue by BorisMulder-CSL** [genodelabs/genode#2417]
During the Hack n' hike 2017 I worked on a feature in part_blk that enabled it to report the partitions.
The commit for it can be found at: https://github.com/nlcsl/genode/tree/part_blk_report, commit 9d719db9a0c7a163d5f936576ab1a6f5994162cc
Feel free to make comments and changes, and use it in any way you want.

Boris

**Comment by chelmuth** [comment]
@ehmry Sorry, I was not aware that you implemented this feature in 24ee00c02b8aed30a08c21844a784e83ce33e563 already. Do you have something to add to @BorisMulder-CSL work?

**Comment by chelmuth** [comment]
The topic branch refers to #2226.

**Comment by ehmry** [comment]
@chelmuth I had an issue with bad checksums on the primary header and good checksums on the secondary and wanted a fallback feature, but that is it. I say move ahead with this issue.

**Comment by chelmuth** [comment]
This is the second time I hear about checksum errors - are you also referring to GPT? I couldn't reproduce the issue and was wondering what is causing this.

**Comment by ehmry** [comment]
Yes, this was a problem with tables created by ``sgdisk`` but I am not able to reproduce it, so it must have been fixed.

**Comment by chelmuth** [comment]
@rite do you still experience `Error: Wrong GPT header checksum`? Did you use older versions of sgdisk?

**Comment by rite** [comment]
I noticed this error a few months ago but couldn't reproduce it either. I guess the partition table was created by gparted on Ubuntu 14.04... Newer saw this error with partitions created with sgdisk on Ubuntu 16.04.02 LTS.

**Comment by chelmuth** [comment]
With ca2243c, I added my AHCI port report feature to staging.

**Comment by nfeske** [comment]
Included in Genode 17.05

**Comment by ehmry** [comment]
There is a small issue that I have come across, the MBR partition types are printed in decimal, but hexadecimal representation is more common.

**Comment by chelmuth** [comment]
@ehmry if you're referring to the report, this is pretty clear IMO as the numbers are not prefixed with `0x` which leaves them in decimal representation. But, I wouldn't mind to report hex numbers incl. the prefix.
