### ISSUE TITLE
LDSO makes multiple calls to ROM::dataspace()

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2418]
Requests for shared object dataspaces should be coalesced to a single call to ``Rom_session::dataspace`` for any given ROM session. This prevents a ROM service from invalidating a previously returned dataspace that is currently mapped.

See #2397

**Comment by ehmry** [comment]
Fixed at cfd70f3e42c0e56930c5e6e11c16053e774a0a16.

**Comment by nfeske** [comment]
Thanks a lot for uncovering the root cause of the issue!
