### ISSUE TITLE
server/fs_report

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2422]
I want to try and visualize the init reports so I probably need to access reports via the file-system.

**Comment by ehmry** [comment]
Rebased against 17.05, added a src recipe.

**Comment by nfeske** [comment]
Very cool! This is exactly what I needed as well. ;-)

**Comment by nfeske** [comment]
This works very well in my current scenario, except for one minor issue: The server always appends ".report" as suffix.

In my current scenario, I combine it with ram_fs and fs_rom to supply a configuration to a dynamic init instance. With the current built-in-policy, the configuration ends up being named "dynamic.config.report", which is a bit awkward. @ehmry Would you consider to remove the suffix? One can still easily append a suffix where it makes sense by using the label-rewriting mechanism on init.

**Comment by ehmry** [comment]
The reason for the suffix was the same as ``fs_log``, if ``a -> b`` reports to ``/a/b``, then ``a -> b -> c`` will have problems reporting to ``/a/b/c``.  But unlike logs, not every member of the hierarchy will report and those that do append a label, so it should be safe to drop the suffix.

**Comment by ehmry** [comment]
Fixed at 4da79e6e9769f84c512c1b35c3907e12279ef9f0

**Comment by nfeske** [comment]
Cool! Thanks @ehmry :-)
