### ISSUE TITLE
depot: binary archives for libraries cannot be published

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2438]
When trying to publish binary archives of the `backdrop` pkg recipe, the libpng, libc, and libz cannot be found in the depot. The `./tool/depot/dependencies` produces the following output:

```
~/s/genode> ./tool/depot/dependencies genodelabs/pkg/x86_32/backdrop-2017-06-06
Error: incomplete or missing archives:
       genodelabs/bin/x86_32/libc-2017-06-06
       genodelabs/bin/x86_32/libpng-2017-05-31
       genodelabs/bin/x86_32/zlib-2017-05-31
make: *** [checked_completeness] Error 1
```

The problem seems to be the install location of the build results of libraries that are - in contrast to regular targets - hosted in a subdirectory of the library's API. The `dependencies` tool (which is internally used by the publish tool) fails to distinguish both cases.

**Comment by NobodyIII** [comment]
I ran into this issue too. The issue seems to be with the version numbers being inconsistent. For example, src/zlib-2017-05-31 compiles to bin/.../zlib-2017-04-24. It's the same for libpng.

**Comment by nfeske** [comment]
Commit 718a0b012ca1fa87bfef32e0b893640525897d5f addresses the problem.
