### ISSUE TITLE
squash Rom_connection_failed exception to Service_denied

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2439]
The ROM connection constructor prints an error before throwing any exception, so if this causes a regression anywhere it will be noticeable in the logs.

**Comment by nfeske** [comment]
What is your motivation behind the patch?

Frankly speaking, I won't urge to change it. Since `Rom_connection_failed` inherits `Service_denied`, client code that catches `Service_denied` implicitly covers the `Rom_connection_failed` exception.

**Comment by ehmry** [comment]
In that case it doesn't matter to me, I must just be suspicious of exception inheritance.
