### ISSUE TITLE
Porting a JVM

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2445]

**Comment by m-stein** [comment]
For now, I decided to give the HotSpot JVM from OpenJDK a try. I use the ``jdk9/jdk9`` branch of the GitHub mirror https://github.com/dmlloyd/openjdk.

**Comment by skalk** [comment]
:+1:

**Comment by nfeske** [comment]
Fixed by https://github.com/genodelabs/genode-world/issues/136.
