### ISSUE TITLE
libc: Opening a symlink with O_CREAT|O_NOFOLLOW results in infinte loop

### ISSUE THREAD

**Issue by senier** [genodelabs/genode#2458]
See https://github.com/Componolit/componolit/commit/f8ad9d55f2c54166b05f438392ce6cdcabb3d22c for a minimal failing example.

**Comment by senier** [comment]
Here is how I'd fix that: https://github.com/senier/genode/commit/92cd3b30279878def86b53bff7490eac26bf4d75

I'm not sure, though, whether testing for O_NOFOLLOW is sufficient to determine whether an ELOOP error is appropriate.

**Comment by chelmuth** [comment]
I merged your fix but was wondering if it should adhere to the man page of `open`, which states

> ELOOP  pathname was a symbolic link, and flags specified O_NOFOLLOW but not O_PATH.

Must admit that I've no idea about the semantics of `O_PATH`...

**Comment by senier** [comment]
I looked into this. The semantics of O_PATH is fairly simple in FreeBSDs libc - it doesn't exist ;-) So I guess we are safe.
