### ISSUE TITLE
vfs: symlink content silently dropped when above 1024 bytes

### ISSUE THREAD

**Issue by senier** [genodelabs/genode#2462]
When creating a symbolic link using symlink(), the remainder of the link target gets silently dropped when the length of the target exceeds 1024 bytes.

The expected behavior is

1. Return a 'Filename too long' error when link target exceeds some internal limit
2. Support a link length of ~4096 bytes (the typical PATH_MAX size on Linux)
3. Expose an API to retrieve the respective limit (like `getconf PATH_MAX /` on Linux)

See [this test](https://github.com/Componolit/componolit/tree/master/src/test/mfe/symlink_length) for a reproducer (run script [here](https://github.com/Componolit/componolit/blob/master/run/mfe/symlink_length.run)).

**Comment by ehmry** [comment]
For what its worth the maximum support symlink length within the VFS is pegged at Vfs::MAX_PATH_LEN and the ``ram_fs`` symlink length is pegged at ``File_system::MAX_PATH_LEN``.
https://github.com/genodelabs/genode/blob/master/repos/os/include/vfs/types.h#L29

I will fix the libc to return an error when the link gets too long, but I am on vacation with intermittent network so it might be a few more days.

**Comment by ehmry** [comment]
Fixed at 55c8ee2b3269a70c7f86fea75259af67758aa17d.

@senier as you find problems feel free to add tests to ``repos/libports/src/test/libc_vfs/main.cc``, this test is regularly run against multiple VFS plugins.

**Comment by senier** [comment]
I tested again with the fix in https://github.com/genodelabs/genode/commit/55c8ee2b3269a70c7f86fea75259af67758aa17d and it resolves the issue of an undetected excessive symlink. 'File name too long' is now signaled as expected when the symlink target exceeds MAX_PATH_LEN. Thanks, @ehmry .
Thanks also for the pointer to the vfs test case. I will consider adding future tests there.

**Comment by chelmuth** [comment]
@ehmry why do you overload the length return value with an error case? May it possibly be better to just throw an instance of `File_system_session::Name_too_long`?

**Comment by ehmry** [comment]
Yes, but this error happens during async packet write, and there is no return path for an error type.
