### ISSUE TITLE
IOzone filesystem benchmarking

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2467]

**Comment by ehmry** [comment]
@chelmuth My ``issue2467_iozone`` branch contains IOzone tests for RAM, Rump, and FatFS VFS plugins. The tests are in ``port/run`` and write data into ``run/data/iozone``. The ``run/iozone_plot`` script will display a visual plot of the data it finds there.

In short, RAM is always fast, Rump has fast reads, and FatFS is too slow to compare against the other two.

Ref #2410

**Comment by chelmuth** [comment]
I skimmed over your branch and like the feature. For a merge, it needs to be rebased to staging (e.g., f5fd7a8aa64f44ac7f35a1ee7a8cf3156be9f5b8 and sync()).

**Comment by ehmry** [comment]
Rebase.

**Comment by chelmuth** [comment]
Does this deserve an issue branch rebased on current master ee4ee6a8ac91592065cbf7a96872a95acb926b17?

**Comment by ehmry** [comment]
I expect so, I will ping you when it is ready.

**Comment by ehmry** [comment]
@m-stein I've rebased my `issue2467_iozone` branch against staging.

**Comment by m-stein** [comment]
Thank you! :)

**Comment by nfeske** [comment]
There is no current plan to work on this issue.
