### ISSUE TITLE
Workman layout description for input_filter

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2473]
http://workmanlayout.org/

I switched from Dvorak to Workman last year and I have been using this chargen file for some time.

Workman is fringe, but it is also officially supported by the Ubuntu installers.

**Comment by ehmry** [comment]
Fixed at f18ef8ab7903c9d1beca528558f78c1aa5eac0c9.

**Comment by nfeske** [comment]
Funny. I'm using workman myself since about one year. ;-) Merged to staging.

**Comment by ehmry** [comment]
Hehe, yea the backspace at capslock is nice.
