### ISSUE TITLE
Utility for sequencing components

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2476]
I would like to run tests in sequence such that one component starts, produces output, exits, and another component starts, and processes the output of the first component.

My initial thought was that a special "wrapper" component would sequence execution and maintain a pool of resources for children. An ``init`` parent is sufficient to handle all routing logic.

The configuration would look like so:
```
<start name="sequence">
	<resource name="RAM" quantum="32M"/>
	<route>
		...
	</route>
	<config>
		<start name="test-A">
			<config>
				...
			</config>
		</start>
		<start name="test-B">
			<configfile name="test-B.config"/>
		</start>
	</config>
</start>
```

Does this seem reasonable or is there a better Genodism? My present use case is a simple test but I would anticipate using something like this for a installer subsystem.

**Comment by nfeske** [comment]
This sounds very useful and I actually like everything about your commit: documentation, illustrative scenario, very compact in terms of code, the clear-cut feature set. Cool! :-) It is also nice to see how far init's session routing can take us in such nested scenarios and how the depot helps to keep the run script tidy and neat.

Regarding your question, functionality-wise, there may be a bit of overlap with one scenario (called depot_query) of my current development branch (https://github.com/nfeske/genode/commits/nitro). But your app/sequence approach is different enough and less complex than my scenario (which depends on a depot at runtime). I sense that both approaches are good for different purposes.
