### ISSUE TITLE
run tool support for mutable FAT boot images

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2510]
I have a appliance-style run scenario that writes back to the boot media so I would like some run modules that would allow building and testing images for USB sticks with QEMU.

My initial implementation creates a bare yet bootable FAT image with Syslinux without a using partition table. My plan is to next create an 'image/mbr' module that would wrap ``[run_dir].partition`` with a MBR partition containing the Syslinux boot sector.

**Comment by ehmry** [comment]
Implemented at 37fb0af7b5cedcfeacc252f52ead73656e0baab1.

**Comment by chelmuth** [comment]
@ehmry and @alex-ab could you both please discuss how to merge this feature with #2526 which is almost ready for staging?

**Comment by ehmry** [comment]
I still want to be able to build images for USB sticks but I am unsure that my patch here is best way to do this, so I am fine with yielding to @alex-ab's patch.

**Comment by alex-ab** [comment]
In principle the both commits could coexist.

**Comment by nfeske** [comment]
I wonder, what is the state of this issue? Basic support for FAT on boot media was added to the run tool in the form of the image/uefi backend (based on mtools). It may not address @ehmry's use case though. What would be the appropriate steps for this issue?

**Comment by ehmry** [comment]
I will close this for now. What I was interested in was making mutable images for USB sticks and then booting QEMU from them.
