### ISSUE TITLE
tool: extend xmllint by Genode XML schema to check (offline) for known Genode config XML nodes/attributes

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2513]

**Comment by chelmuth** [comment]
This is nice! Does the solution work with inline content like in *netperf_lwip_wifi.run*?

**Comment by alex-ab** [comment]
I did not specify what the config node elements/attributes of the start nodes, so yes it will work (by ignoring/not checking). Of course, here we would need to add some component specific .xsd extensions, if you would like also to check that.

**Comment by alex-ab** [comment]
I restricted the checking for now just to the install_config proc, otherwise other .config file would also be checked, which contains e.g. for the launcher launcher specific config formats, not understood for the moment.

**Comment by chelmuth** [comment]
I did not want to extent the scope beyond the init configuration, but I want to make sure that inline content does not
- break the check with a failure
- disable the check completely due to weird syntax
Thanks anyway for the feature and the explicit limitation to the install step.

**Comment by chelmuth** [comment]
Are your patches fit for merging already?

**Comment by alex-ab** [comment]
In principle yes.

**Comment by chelmuth** [comment]
Okay, as soon as you mark it `fixed` I'll merge the commits (preferably merged into one).
