### ISSUE TITLE
Use GRUB2 for iso/usb boot (non UEFI) on x86

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2526]

**Comment by nfeske** [comment]
Very cool! Until now, I was not aware that the use of GRUB2 alleviates the need for isolinux as well. That is another plus.

**Comment by chelmuth** [comment]
From an offline discussion: The patch above fixes this issue but will be reworked by fetching the grub2 binaries via our port mechanism.

**Comment by alex-ab** [comment]
64ecf6d8356f94e0720f8d7840986ce442ce67b3 contains a proposal to use our port mechanism to fetch the grub2 binaries

**Comment by nfeske** [comment]
Thank you for the fixup, which is exactly what I had in mind!

**Comment by m-stein** [comment]
@alex-ab @chelmuth What do you think about this little addition:
dabf9ec tool/run/grub2: user-friendly missing message

It allows the user to simply copy/paste the instruction that prepares grub2 and makes the message conform to the according messages of the common build system.

**Comment by chelmuth** [comment]
thanks, merged it to staging.
