### ISSUE TITLE
signal: fix starvation by fast signal contexts 

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2532]

**Comment by chelmuth** [comment]
Fixed on master by b811ef4331386fe4601fd751d2a826b0365a28d8

**Comment by skalk** [comment]
When bisecting to find the commit that introduced the regression that noux_tool_chain_auto does not work on several architectures anymore, I struck commit b811ef4
@m-stein @chelmuth any ideas?

**Comment by chelmuth** [comment]
Sorry, I've no hint, but think it's time to reopen the issue.

**Comment by m-stein** [comment]
@chelmuth A bug fix for the framework:
4b875fd signal: fix bug in context list by using a ring

**Comment by skalk** [comment]
@m-stein, @chelmuth  : it seems to fix the problem, at least on hw/x86_64 noux_tool_chain_auto runs again with the patch

**Comment by m-stein** [comment]
@chelmuth I tested this with ``timeout timer signal nic_router`` on several machines and kernels so I hope it doesn't break too much: 
c5458cf fixup "signal: fix bug in context list by using a ring" (for-each lambda)
6b0fcb4 fixup "signal: fix bug in context list by using a ring" (head is next)
1415b6c fixup "signal: fix bug in context list by using a ring" (naming)
57652ef fixup "signal: fix bug in context list by using a ring" (naming)

**Comment by skalk** [comment]
To me it seems the issue is now finally fixed, isn't it?

**Comment by m-stein** [comment]
Yep.

**Comment by m-stein** [comment]
@chelmuth I created a fix in agreement with @alex-ab:
4c1c2c5 signal: fix race in Signal_receiver pending_signal
