### ISSUE TITLE
Make recipe for modified Nim toolchain

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2545]
I propose keeping a makefile for building the Nim compiler with my Genode patchset in the `tool` directory.

Building Nim components isn't perfect, there are issues with how makefiles are generated from JSON recipes and there are some memory management things that need to be fixed in the compiler.

**Comment by nfeske** [comment]
Sorry for the delay. I merged your commit to staging now. I like the way how you followed the patterns we use for the other tools.

**Comment by ehmry** [comment]
Good, in the future I will be updated the port recipes.
