### ISSUE TITLE
gems: add file system start-up manager

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#2558]

**Comment by nfeske** [comment]
Very cool, @cnuke! I am happy that the driver manager turned out to be a suitable blueprint for solving such kind of problems.

**Comment by cnuke** [comment]
@chelmuth @nfeske the following commits are ready for staging IMHO:

8291382 (lx_block)
7263cae (rom_filter)
2fd545d (rump_fs atime)
e625f49 (rump_fs session)
f26c896 (rump_fs dry mount at startup)
9a0529a (non-noux e2fsck)

**Comment by nfeske** [comment]
I merged the commit series to staging. Thanks @cnuke!

**Comment by cnuke** [comment]
@chelmuth @nfeske please merge f2f1e06 to staging.

**Comment by nfeske** [comment]
The patches entered the master branch.
