### ISSUE TITLE
sel4: update to branch with our merged uefi patches

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2562]
to get rid of some of our seL4 kernel patches

**Comment by alex-ab** [comment]
If #2563 gets fixed, the issue can be merged.

**Comment by alex-ab** [comment]
@nfeske: please also consider for staging, since it was the trigger for #2563.

**Comment by nfeske** [comment]
It's my pleasure! Merged to staging.

**Comment by alex-ab** [comment]
There are still some in the pipe up-stream, so removing fixed for now.

**Comment by alex-ab** [comment]
@chelmuth: fc590e3efa7c6328b188eb042260b787a2731ed9 updates to the latest 7.0 release + all our submitted patches - please consider for merging
