### ISSUE TITLE
timeout api: attempt to insert alarm twice

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2570]
While working with the sculpt scenario, I observed the following problem when interactively reconfiguring the input filter. The reconfiguration works several times but eventually, the input filter seems to die. In the log, I see suspicious messages:

```
Error: trying to insert the same alarm twice!
```

This points at an issue related to the key-repeat timeout handling. Whenever the input filter is reconfigured, most objects of the component - in particular the entire filter chain - are destructed and rebuilt. In this process, the timeouts as instantiated by the chargen filter should also vanish without any trace. However, when reconstructing the new filter chain, there seems to be a remains from the previous one referenced in an alarm scheduler(?). I guess that this problem culminates in the eventual hang of the component when the reconfiguration happens several times.

**Comment by nfeske** [comment]
I managed to reproduce the problem with a modified input_filter.run test in commit https://github.com/nfeske/genode/commit/90bae257d51d5982950e98d20684d447c62c65aa

**Comment by nfeske** [comment]
@m-stein Could you have a look?

**Comment by m-stein** [comment]
Sure. I'm at it.

**Comment by m-stein** [comment]
@nfeske: I think that's it:
cc63d8a input_filter: add missing virtual Source::~Source

**Comment by nfeske** [comment]
@m-stein Thanks a lot for solving this mystery! Now I feel a bit bad about bothering you with such a silly bug of mine. ;-)

**Comment by nfeske** [comment]
I can confirm that your fix solves the input-filter reconfiguration problem in the sculpt scenario. So now, one adjust all input-filtering parameters without any fear.
