### ISSUE TITLE
x86 platform driver does not fully constrain session capability quotas

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2576]
To begin with, I have a problem with `intel_fb_drv` when booting from UEFI on my T420. The driver seems to do a lot of probing and then `platform_drv` blocks with a resource request to its parent for more capabilities, which blocks the boot process. The framebuffer driver is pushing the platform driver harder than usual, but the first concern is to protect the platform driver. I added some ram and cap quota guards in the platform session component and replaced the `Ram_session_guard` with a `Constrained_ram_allocator`. This moved the resource problem to the framebuffer driver, and seems to reduce the number of capabilities to be accounted directly to the platform driver.

A log of `intel_fb_drv` initializing on my T420 after apply the patch: http://sprunge.us/Gahe

**Comment by ehmry** [comment]
Patch at eaf0868a5f00a923028daec1697c62e3e89e4baa.

**Comment by nfeske** [comment]
Looks good to me. @alex-ab Could you also take a look?

**Comment by alex-ab** [comment]
I'm fine with it, thx @ehmry

**Comment by nfeske** [comment]
Merged to staging.
