### ISSUE TITLE
timeout: fix bug in duration + duration testing

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2581]

**Comment by m-stein** [comment]
a27cd19 timeout: fix bug in duration + duration testing

**Comment by m-stein** [comment]
Added another commit:
35631bb timeout: replace Duration operators by methods

**Comment by nfeske** [comment]
Merged both commits to staging. I had to add the fixup 6170ac39ac741734dd4b86ddf71b11a6edae10f3 to fix build errors on nova and hw, ok?

**Comment by m-stein** [comment]
Oh, sorry, thought I had added this already. Yes, of couse this is fine.
