### ISSUE TITLE
init.run hangs from time to time

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2584]
Nightly tests trigger it reliable on seL4, x86 as ARM. From time to time also on OKL4. The issue also got reported via the mailing list https://sourceforge.net/p/genode/mailman/message/36107852/

```
...
[init -> test-init] step 34 (init_config)
[init -> test-init] step 35 (expect_log)
[init -> test-init] [init -> application] config 1: Version A (expected)
[init -> test-init] step 36 (init_config)
[init -> test-init] step 37 (expect_log)
[init -> test-init] [init -> application] config 2: Version B (expected)
no RM attachment (READ pf_addr=0x7dd3e pf_ip=0x7dd3e from pager_object: pd='init -> init -> application' thread='ep') 
```

**Comment by alex-ab** [comment]
One source @nfeske and I could track down was that in core that a 'pager' thread holds a region_component lock while trying to send a signal to the Core's 'entrypoint' thread. The 'entrypoint' thread already served another call of a client, which wants to get the very same lock for the same region_component object.

**Comment by alex-ab** [comment]
All platform using the generic 'Signal_transmitter::submit' are affected. base-hw and base-nova use specific implementation directly using kernel mechanisms, therefore they are not affected.

**Comment by chelmuth** [comment]
I merged both commits to staging.
