### ISSUE TITLE
pointer: custom pointer shape support

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2585]
Currently, the 'vbox_pointer' component supports drawing of custom pointer shapes for VirtualBox guests. Qt applications in general make use of custom pointer shapes, too, for example when hovering over a text input field, so there is another use case for this feature and the plan is to make a revised version of the 'vbox_pointer' component the new 'pointer' component.

By default, the revised 'pointer' component behaves the same as the current one (showing a default pointer shape) and existing run scripts using the 'pointer' component don't need to be modified.

When configured with ```<config shapes="yes"/>```, the 'pointer' component announces a 'Report' service for custom pointer shapes and requests 'ROM' sessions for Nitpicker's "hover" and "xray" reports.

The mapping between hovered Nitpicker sessions and applications can be achieved with report session label rewriting:

```
<start name="shape-arrow">
	<binary name="test-pointer"/>
	<resource name="RAM" quantum="2M"/>
	<config shape="arrow"/>
	<route>
		<service name="PD">     <parent/> </service>
		<service name="ROM">    <parent/> </service>
		<service name="CPU">    <parent/> </service>
		<service name="LOG">    <parent/> </service>
		<service name="Report" label="shape">
			<child name="pointer" label="test-label-arrow -> testnit"/>
		</service>
	</route>
</start>
```

In the example above, which is from 'pointer.run', the 'shape-arrow' component reports an arrow shape with the label "shape". By rewriting the label of the report, the shape will be drawn for the 'test-label-arrow' component, which is reported by Nitpicker with the label 'test-label-arrow -> testnit' when hovered.

When configured with ```<config shapes="yes" verbose="yes"/>```, the 'pointer' component prints the labels of hovered Nitpicker sessions and received shape reports to the 'LOG' service.

**Comment by nfeske** [comment]
I just tried to integrate the new pointer into the sculpt scenario and stumbled over the following problem:

The routing of the "shape" report sessions (from the runtime subsystem to the pointer) is based on "-> shape" as session-label suffix. But the pointer expects the label of the report to perfectly match the label of the incoming report.

To solve this issue, I have two ideas:
* We could weaken the matching criterion such that for a hovered session label, any report matches where the label begins with the hovered session label. So the client could append a " -> shape" to it's report label without a problem.
* We could make the pointer always assume that the shape report has the suffix "-> shape". It could strip off this suffix and then apply a perfect match.
