### ISSUE TITLE
hw: kernel text segment should be read-only

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#2592]

**Comment by chelmuth** [comment]
The patch seems to be x86_64-specific - is this already implemented on ARM?

**Comment by skalk** [comment]
Well, in fact it is not. It enables read-only kernel mappings for all platforms (first lines of the patch in bootstrap code), but on x86 some assembler code (in .text section) stood in the way, because it was written to some variables inside of it. Namely, within the TSS the interrupt stack pointer was changed to the current thread context to save relevant registers on kernel entries.
