### ISSUE TITLE
openvpn; update to 17.11

### ISSUE THREAD

**Issue by MartijnVerschoor** [genodelabs/genode#2595]
Recently I continued with the update of the openvpn component for more recent Genode versions (using with_libc) and lxip. The intermittent result is a working openvpn scenario that is based on [17.11](https://github.com/nlcsl/genode/commits/openvpn_17.11).

The udp/tap openvpn setup runs stable as far as I can tell. Over the course of two weeks I tested on NOVA x86_64 with real hardware and physical LAN. During this period we ran various iperf tests (averaging about 30 Mbit of throughput without optimizing). No failures are registered so far. Note that the version we tested was based on staging 01a328dc5f144fb890b4f8af9a74e869bca3ebda.

I would like to share the update and discuss our findings and modifications to get it to work. In particular, I introduced two workarounds that I believe should not be required; see further down below.

The work is uploaded to our github [fork](https://github.com/nlcsl/genode/commits/openvpn_17.11). The first commit 0ea17063128665b7f834acf6b7c5aa5ba2c89065 is a reworked version of our first attempt to rebase openvpn to Genode 17.05 in June. We discussed this work on the [mailinglist](https://sourceforge.net/p/genode/mailman/message/35908946/) . At that time @chelmuth  contributed a speedy refactoring introducing an additional entrypoint 7bc0620ada266f2c86d01dfb6cf9ffef89076cd3. This was a step in the right direction, but, as described on the mailinglist, there were some remaining problems. There were also other projects and summer holidays, so I paused the work.

About 6 weeks ago I was able to pick it up again. I noticed that the new entrypoint @chelmuth introduced was not forwarded to the ``Nic::Session_component``. In fact there is no option to pass a specific entrypoint in the constructor of the ``Nic::Session_component``. Instead the constructor retrieves the (rpc) entrypoint from the env argument. I added another constructor to fix this 18edaef8ddeb6dd7dce3d3d01f4eb722f161780b and refactored openvpn to forward the appropriate entrypoint 086f5f152b7c92c869a863588e9263b9690ae2b5.

Next I ran into some troubles related to the socket_fs_plugin with which I'm less familiar. Specifically with the ``select`` function and the use of ``recvfrom``. The wait function in the event loop of openvpn relies on ``select`` to be notified about events on sockets. The configured wait function registers the file descriptors and the selected events it wants to be notified of. It appears that ``select`` works as expected, i.e. when a socket has data available to read, openvpn tries to read it using ``recvfrom``. I noticed that the call to ``recvfrom()`` repeatedly returns EAGAIN, indicating that there is nothing to read, eventough select indicates that there is. I traced the origin of EAGAIN to the ``read`` call embedded in ``read_sockaddr_in`` which is called from ``recvfrom()``. I noticed that the file descriptor used in the ``read`` call differs from the file descriptor that is registered at select. I'm not sure if its correlated, but under the hood in the filesystem session layer, the data and sockaddr are represented by different nodes. Would this pose a problem? I fiddled a bit to force the read in ``read_sockaddr_in`` and eventually got it working 77c3b83366358dff05ab1faeacabc6ee02686315. Of course this is not the proper solution.

Another issue we found is that openvpn no longer writes packets to the tun interface implemented in the Genode component (i.e. write received packets to the client over the Nic session interface). When data can be written to the tun interface, the openvpn loop registers an ready-to-receive event on the file descriptor associated with the tun interface. This event never triggers thus openvpn is never signaled that it can write to the tun interface. A mechanism to apply back pressure from the client was never implemented, but before Genode 17.02 openvpn could always write. I introduced this 2aba8d68a5523d350dc4c5b624d0b8c046e5dd18 workaround in openvpn to circumvent this. See also the text in the commit message.

**Comment by chelmuth** [comment]
I had a closer look at 2aba8d68a5523d350dc4c5b624d0b8c046e5dd18 because it bothered me that it is still required to tweak is this regard after all the sweat to get the `select()` semantics right. For me it looks like the current implementation still suffers from the fact that the VFS was not available at the time of the initial port. Now, I would suggest to implement the file-to-nic-session mechanics as a VFS plugin, which automatically renders it fit for all the libc magic including select. This direction will not completely remove the OpenVPN tun backend implementation as the the VFS plugin should not be tainted by libc (or even Linux) specifics like ioctl defines. What do you think?

**Comment by chelmuth** [comment]
Regarding 77c3b83366358dff05ab1faeacabc6ee02686315 I am not completely certain about the scenario that may trigger the flawed behavior. Do you see a chance to reproduce it in the netty example?

**Comment by MartijnVerschoor** [comment]
@chelmuth, thanks for picking this up. Regarding your comment above on 77c3b83366358dff05ab1faeacabc6ee02686315, I have written a small test scenario that roughly models openvpn's UDP socket use 5434c047ea8cd509853126be0aca342ee8c5e48b. It reproduces the problem I encountered. I also added a test program for Linux for comparison.

The program opens a socket for UDP and sets the O_NONBLOCK flag on its file descriptor with fcntl.

You'll see that ``select`` returns when there is something to read from the socket (correct), while the subsequent call to``recvfrom`` returns EAGAIN (incorrect) . On Linux ``recvfrom`` reads the data as expected.

The test program sends a UDP packet to the configured server and waits until a UDP packet is returned. A simple UDP echo server will suffice to test the scenario. I used ncat (from nmap):

```
ncat -vvv -e /bin/cat -k -u -l 10000
```

**Comment by MartijnVerschoor** [comment]
Hi Christian, 

> For me it looks like the current implementation still suffers from the fact that the VFS was not available at the time of the initial port. Now, I would suggest to implement the file-to-nic-session mechanics as a VFS plugin, which automatically renders it fit for all the libc magic including select. This direction will not completely remove the OpenVPN tun backend implementation as the the VFS plugin should not be tainted by libc (or even Linux) specifics like ioctl defines. What do you think?

I agree. It makes perfect sense.

I would say the goal shouldn't be to get rid of the Genode tun implementation. In fact it's perfectly fine to have a Genode specific implementation. There is no way around it as OpenVPN's tun.c is full of OS specific code. It would not make sense to try to emulate one of the already supported OS.

The goal should be to support ``select`` and friends on libc file descriptors backed by the file-to-nic-session mechanism. This would be a more natural fit for OpenVPN and (if I'm correct) would eliminate the need to pass semaphores over the additional libc pipe. It should yield bidirectional back-pressure on the tun and a leaner implementation of the Genode tun implementation.

Right now the Genode OpenVPN component is setup to provide the tun/tap nic as a service. I'm not sure how this fits in the VFS framework. For our purposes, we identified that requesting the tun/tap nic as a client is desirable since it enables us to start, stop and restart the OpenVPN component within a compound Genode network architecture. Thus I would promote implementing the VFS tap (or nic) plugin simply as client.

**Comment by nfeske** [comment]
I'm closing this issue as it has become stale. In the meanwhile, we decided to relocated OpenVPN to the Genode-world repository (#3737).
