### ISSUE TITLE
Update Nim toolchain recipe

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2599]
Asynchdispatch is now much faster.

https://github.com/nim-lang/Nim/pull/6821

**Comment by ehmry** [comment]
Fixed at df75303e0df9fdcbd9b34d117d8531ee17b7ea4a

**Comment by chelmuth** [comment]
I just discovered that the permissions in the generated Nim tool chain are not quite right as the compiler is not world executable after *tool/tool_chain_nim install*. Could you please have a look?

**Comment by chelmuth** [comment]
Also, the make rules seem to hide fatal errors like "exec permission denied" above and also `/bin/bash: jq: command not found`. The make execution is still successful but for diagnosis it should fail.
