### ISSUE TITLE
run: target-specific config schemata

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2600]

**Comment by m-stein** [comment]
This is first fully working version:
3a1044a nic_router: add config schema
84a0d07 run: target-specific config schemata

@nfeske I'm not so sure yet with the changes made to the build system that are the link between the run tool and the XSD files in the source directories in 84a0d07 . Could you please have a look at this?

**Comment by nfeske** [comment]
It looks very elegant! I very much like your idea of tying the xsd-file with the target.mk.

**Comment by m-stein** [comment]
Fixed some minor flaws of the initial version. So, @chelmuth please consider merging:
6fc37a6 nic_router: add config schema
2dfab0b run: target-specific config schemata

**Comment by m-stein** [comment]
There's a little fixup that came up when using only depots in a run script:
260c40d fixup "run: target-specific config schemata"

**Comment by m-stein** [comment]
I just found out that we can do this also with xmllint only, so, xmlstarlet is not required anymore:
903539d run: avoid dependency for xmlstarlet

**Comment by m-stein** [comment]
... 903539d may be used as fixup for:
bff23f3 run: target-specific config schemata

**Comment by m-stein** [comment]
Another fixup: d29c374 fixup "run: target-specific config schemata"
