### ISSUE TITLE
noux_tool_chain_auto: compile zlib source archive instead of core

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#2601]

**Comment by chelmuth** [comment]
@ssumpf please rebase on current staging as I'd like to merge the commit.

**Comment by ssumpf** [comment]
@chelmuth: a0ce037 is the rebase to current staging with @m-stein patches incorporated/updated (#2605)

**Comment by chelmuth** [comment]
Merged to staging. Please note I skipped a696c14 as the real commit is already on staging and this one only includes hash updates we handle by separate commits.

**Comment by chelmuth** [comment]
Fixed in master by 9e93ea3e1cb9be53e0cf98bb5a02cb40119f85b5
