### ISSUE TITLE
noux_tool_chain.inc: don't use '&' in XML values

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2605]

**Comment by m-stein** [comment]
@chelmuth Should fix the current nigthly problems:
ab7db48 noux_tool_chain.inc: don't use '&' in XML values

**Comment by m-stein** [comment]
@chelmuth Adapted according to the suggestion:
6eaefa5 noux_tool_chain.inc: don't use '&' in XML values

**Comment by chelmuth** [comment]
Great, merged instantly.
