### ISSUE TITLE
VFS hangs on hard-link loops in tar archives

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2611]
This seldom happens but causes problems that are extremely frustrating to diagnose. For some reason GNU tar is dependably creating an archive for me that the VFS plugin loops within but can be untared by GNU tar just fine.

**Comment by ehmry** [comment]
Fixed at 6177c16d5996c46d9cef2419c3722d66203041bf.

**Comment by nfeske** [comment]
That's a very elegant solution - hats off! :-)
