### ISSUE TITLE
nic_router: report some useful information

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2614]

**Comment by m-stein** [comment]
I would much appreciate if you help me defining the term "useful information" and the granularity in which the reporting shall be configurable. Up to now, I have the following suggestions for the report subjects:
1) The routers IP-config at a domain (address, gateway, subnet mask (dns-server, ...?) )
2) RX bytes, TX bytes (per session | per domain | for the whole router ?)
3) Dropped packet count (for the whole router | per domain (source) | per session (source) )

**Comment by m-stein** [comment]
This is a first try:
0b53501 nic_router: report some useful information

With this, one can let report TX bytes, RX bytes, IPv4 interface, and gateway. Each per domain.

**Comment by m-stein** [comment]
A fixup:
88a1676 fixup "nic_router: report some useful information"

**Comment by chelmuth** [comment]
Merged to master by edf1f9d84953e7ca5b5bdb9bf1c66c07d3d3772c.
