### ISSUE TITLE
fetchurl: create compound directory of downloaded file

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2623]
The current version of fetchurl fails of the `path` of a `<fetch>` node refers to a non-existing directory. It should better create the hierarchy of compound directories as needed.

**Comment by nfeske** [comment]
Implemented in 7f4d3cc660945d4ea35d4a0d274f06e720e40b0e

**Comment by nfeske** [comment]
Note also the commits f5703322e333e48cc6ceeadc539b00f8f2402f62 and 22440467a8d0c0dae24ac95cbd3b2f85ad9f9f43.

**Comment by chelmuth** [comment]
Merged all three to staging.
