### ISSUE TITLE
libc: prevent unconditional creation of timer session by `clock_gettime`

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2625]
When a libc-using program calls `clock_gettime` the first time, the libc tries to obtain an initial time value by asking the real-time clock (RTC) and by creating a timer session. Subsequent calls are answered based on the elapsed time of the timer session only. Even though one can deliberately leave out the `rtc` attribute of the `<libc>` unconfigured or let it point to `/dev/null`, the libc will still try to create a `Timer` connection. This is unwanted for programs like `untar` (provided along with libarchive) that always calls `time()`. For extracting a tar archive, no timer session should be needed.

To make the libc behavior better configurable in this respect, `clock_gettime` should request the libc timer only of the RTC is defined. Otherwise, `clock_gettime` should back out with an error (EINVAL).

**Comment by chelmuth** [comment]
We should adapt `gettimeofday()` accordingly.
