### ISSUE TITLE
Libc stdio file descriptors not reserved

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2628]
When a libc component is started and stdin, stdout, or stderr are configured the descriptors 1, 2, and 3 are assigned like any other Unix environment. But if any are not configured, the descriptor gap is used for normal files or the stdio descriptors become misaligned. This currently causes problems with the Nim asynchronous event dispatcher, and is a potential source of confusion elsewhere.

**Comment by ehmry** [comment]
Fixed at 076f2d0a6564a319b6e0a6180464800fa17ce225.

**Comment by chelmuth** [comment]
Thanks for filling this gap!
