### ISSUE TITLE
nic_router: cannot re-use a "domain" session

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#2637]
Yesterday, I could repeatedly reproduce the following problem:

I have several VMs that are routed to different "domains" of the nic_router. I restarted a VM, which had a working network setup in the first place. After restarting the VM, I still get a DHCP response from the nic_router (including DNS settings), but no network requests are handled apart from that. I tried to connect to the given DNS server and directly to an IP address of the local network, both did not work. After a fresh cold host reboot, I could reproduce the problem with two VMs that got a working network setup after a first boot, but not after a reboot. A constantly running VM, which did not reboot, always had network access through the nic_router at all times.

**Comment by m-stein** [comment]
I'll have a look. Thanks for the description :)

**Comment by skalk** [comment]
@m-stein did you really destroyed the subsystem containing Virtualbox or did you reboot within the virtual machine? I expect it can be reproduced by re-starting Virtualbox only, not be rebooting Linux inside.

**Comment by m-stein** [comment]
@skalk This should do the trick:
7c4a855 nic_router: fix use of outdated ARP-cache entries

Does it fix your problems?

**Comment by skalk** [comment]
@m-stein at least after restarting the VM I'm using for web-browsing just now, I'm able to write by re-using the nic_router domain of it. Thank you very much for looking into this!

**Comment by nfeske** [comment]
Merged to staging.
