### ISSUE TITLE
Tcl shell for noux

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2648]
Since we added the tcl-based abi-checking tool in #2639, the tool chain depends on tclsh. Hence, we need tclsh on noux to build Genode on Genode.

**Comment by nfeske** [comment]
The commit series above fixes the issue. The `tclsh` depot archive contains only the subset of contrib sources that are needed for tclsh but not any tcl packages. It should hopefully suffice for our build-system needs.

**Comment by cproc** [comment]
depends on #2660
