### ISSUE TITLE
`uname -a` displays odd characters

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2657]
The uname utility from coreutils expects all string buffers processed by the `sysctl` call to be zero-terminated, even if `sysctl` returns a zero-length result. WIthout placing a zero at the front of the client buffer `uname` will display artifacts from the buffer.

**Comment by ehmry** [comment]
Fixed at ae951ec27624bc79032f25b36e2d8215c8ae8c3b.

**Comment by nfeske** [comment]
Thanks for looking into it. Would you mind assigning the null termination via `Genode::strncpy` with src="" and size=1 ? This will implicitly handle the case where the destination-buffer length is zero. Or can we rule out this corner case otherwise?

**Comment by ehmry** [comment]
This corner case is handled earlier, but I after some more tests I think it is better to just to zero the whole buffer before handling any cases. New patch at c77991294765725347177dd7e0605298309a3c7a.

**Comment by nfeske** [comment]
All the better! Thank you. Merged to staging.
