### ISSUE TITLE
vfs: starvation of file_system session adapter on heavy writes

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2664]

**Comment by chelmuth** [comment]
What a catch! Does this fix the VM install corruption @skalk and you experienced?

**Comment by alex-ab** [comment]
Partly, I'm still investigating. The commits solve the issue that the guest complains about a stuck device model and trying to reset it and finally to fail after some attempts. This typically happens during installation and/or download of new packages within the guest.

I have now a setup where the guest content (growing vdi) is written to two file system servers. On a read the delivered content is compared between both. Unfortunately, they disagree sometimes ...

**Comment by chelmuth** [comment]
Hui, this sounds like lock-stepping file systems. Thanks, for your efforts!

**Comment by alex-ab** [comment]
Set to fixed, commits fixed starvation as far as I can tell.

**Comment by nfeske** [comment]
Great! I merged them to staging just now.
