### ISSUE TITLE
vfs: file_system session adapter (client) drops silently data on partial (server) writes

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2672]
Beginning with commit b0935ef9b27edbb74da8d7c7345d78e5e22119d5 the return length of a file session packet write is ignored

**Comment by alex-ab** [comment]
The original [code](https://github.com/genodelabs/genode/commit/b0935ef9b27edbb74da8d7c7345d78e5e22119d5#diff-8309a9a3742915d2bd51d59b4a46c51aL220) has no appropriate equivalent, e.g. in the [write ack](https://github.com/genodelabs/genode/commit/b0935ef9b27edbb74da8d7c7345d78e5e22119d5#diff-8309a9a3742915d2bd51d59b4a46c51aR525) the actual written length would need evaluation, but it seems there are no metadata (the original size) to compare to.

**Comment by ehmry** [comment]
One solution would be to set an error flag on the file handle and return something like ERR_IO from sync.

**Comment by ehmry** [comment]
I could implement forwarding errors to the next sync in a short amount of time, in fact I may already have a patch that does this.

**Comment by alex-ab** [comment]
0e29cbfe9c9d974bf498a7404c472b31d923bd16 showcases the bug. I adjusted all file system server (I'm aware of) to not acknowledge a succeeded packet if the written length is not the expected one. Already the ram_fs server returns errors for the libc_vfs.run test.

**Comment by alex-ab** [comment]
Updated it according to the offline discussion.

**Comment by nfeske** [comment]
Very good. Would you like to keep the individual "handle result propagation better" commits or should we squash them to one? (I'd like to add a few words of background info in the commit message)

**Comment by alex-ab** [comment]
I'm fine with squashing.

**Comment by nfeske** [comment]
Merged to staging. @alex-ab are you fine with my commit message?

**Comment by alex-ab** [comment]
Yes, thanks!
