### ISSUE TITLE
Update Fatfs library to v0.13a, depot recipe

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2673]
~~The fatfs VFS plugin, and perhaps the fatfs_fs server as well, corrupts large writes to files.~~

**Comment by ehmry** [comment]
I have had problems with the Fatfs plugin in the past, but after an update and some tests I no longer find corruptions. I am now booting from EUFI and updating my boot image from sculpt with the Fatfs plugin, so if there is a problem again, I should notice.

**Comment by ehmry** [comment]
Patch at 27377aeb2871e27104dfe04d5c6925f7ad4d82b5.

**Comment by nfeske** [comment]
Cool that you added depot recipes along the way. Merged to staging.
