### ISSUE TITLE
Dedicated handle type for File_system notifications.

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2678]
This is the first step in my patch series for #1934.

**Comment by ehmry** [comment]
I have a newer, cleaner, patch at 63375ee75bacc9fa23bf50f9d52bc6f8703073de. This patch has no effect on the VFS server or library. It is ready for staging, and I am in the process of testing it with sculpt.

**Comment by nfeske** [comment]
The patch looks tidy and neat indeed. :-)

When test-driving run/fs_report on base-linux or base-nova, however, the test gets stuck at the 4th step.

**Comment by ehmry** [comment]
Fixed at 86dff6491715715367233d4cd8db2c3786c1f255, I was not aware of `run/fs_report`, but I got pretty close anyway.

**Comment by nfeske** [comment]
I can confirm it works now. Merged to staging. I am also going to test it in sculpt...

**Comment by ehmry** [comment]
I have the same issue with nitpicker, but with none of the other configs.

**Comment by ehmry** [comment]
There is an issue here with ``bool Rom_session::update()``.

**Comment by ehmry** [comment]
I have the Nitpicker issue fixed, fixup at 3d20debb795624ca840b56af9701ff9b69ebb0a2.

**Comment by nfeske** [comment]
Thanks for the update. I'll test drive sculpt with the new version just now.

**Comment by nfeske** [comment]
Looks good in Sculpt on Qemu! :-)

**Comment by nfeske** [comment]
I merged your fixup to both the genodelabs/staging and nfeske/sculpt_next branch.

**Comment by nfeske** [comment]
Fixed in the master branch.
