### ISSUE TITLE
vfs_lxip: UDP connect is broken

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2683]

**Comment by ehmry** [comment]
UDP connect with Lxip is failing. Fixed at 5903961deb984a6f9145b996b272542ace81234e.

**Comment by ehmry** [comment]
@nfeske A have a patch to quiet the output of lxip at 2ab850207c41f7587406338307e045f467e90526.

**Comment by chelmuth** [comment]
Could you please elaborate a bit more why you propose to not inform the lxip stack about the connected UDP state? Doesn't this change the processing of incoming UDP packets that originate from not connected peers?

**Comment by ehmry** [comment]
I suspect that the internal connect hook will always fail for UDP and that this case is instead handled in the Linux libc. But you are right to point out that connect should filter packets from unconnected peers, which would now not happen. I will look into what Linux is really doing.

**Comment by ehmry** [comment]
The real problem is that UDP connect uses `ip4_datagram_connect`, which is currently a dummy stub.

Fixed at 2ca90e3d0a35596af2c700c67c417cc896e07afc, the previous patches for this issue should be reverted.

**Comment by chelmuth** [comment]
Thanks for the fix!
