### ISSUE TITLE
base: give an error if session_args or session_label becomes too long

### ISSUE THREAD

**Issue by BorisMulder-CSL** [genodelabs/genode#2689]
In a systems with a lot of inits stacked on top of each other, session request labels can grow very long. Depending on the length of the label, this produces a lot of undefined behaviour and unrelated error messages, such as service_denied errors, infinite retries, component crashes and full-system freezes. Naturally, rpc args cannot grow indefinitely, so it would be nice to actually perform some kind of bounds checking on them when appending to it.

For instance, if a child of init issues a session request to the parent (init) and it is forwarded to the grandparent, init always prepends its own label to the session label using the Genode::prefixed_label method inside the Child::session method. 

Maybe inside prefixed_label a check could be done if it fits, and maybe it could give a warning or an error if it does not. Right now, it looks like the last part is just discarded.

**Comment by nfeske** [comment]
I'm closing this issue because it is not relevant in (our) practice.
