### ISSUE TITLE
rom_filter: clarify input rom name attribute

### ISSUE THREAD

**Issue by BorisMulder-CSL** [genodelabs/genode#2690]
Rom_filter has the functionality to paste a node of an input rom entirely into the output rom. For this, it uses the <input> node inside the <output> node (https://github.com/genodelabs/genode/blob/staging/repos/os/src/server/rom_filter/main.cc, line 347-365). However, if I define this input ROM using <input name="foo" rom="bar"/>, I have to define this <input> node inside the <output> node using <input name="bar" sub_node="..."/> instead of <input name="foo" sub_node="..."/>. This is quite confusing. This is the case because the input_rom_registry only keeps track of the rom names, not the input names, and the input_name is implicitly converted from an Input_name to an Input_rom_name on the line 391 of input_rom_registry.h:
`Entry const *e = _lookup_entry_by_name(input_name);`

Therefore I suggest either to keep track of the Input_names inside the entry (which means more code), or as a workaround to change the sub-input node into something like `<output> <input rom="bar" sub_node="..."/>`.

To implement the latter I suggest changing main.cc, line 350-351 from
```
Input_name const input_name =
node.attribute_value("name", Input_name());
```
into
```
Input_rom_name const input_rom_name =
node.attribute_value("rom", Input_rom_name());
```
and the corresponding function call `Input_rom_registry::xml()` to also take a `const Input_rom_name&` as an argument.

This is all a very minor detail but I had to debug the code in order to find out why my configuration wasn't working. Better to prevent others from having go through the same!

**Comment by nfeske** [comment]
This issue is stale for one year now and I'm not planning to pick it up anytime soon.
