### ISSUE TITLE
fetchurl: fail on error

### ISSUE THREAD

**Issue by BorisMulder-CSL** [genodelabs/genode#2692]
When curl fails with some error, It would be nice if the fetchurl component exited with the same error value using the CURLOPT_FAILONERROR option. This allows other components that manage fetchurl to handle these errors based on init's state report which contains the exit_value. I implemented a fix here: https://github.com/nlcsl/genode/commit/bfd487bfcda16f6f90d2ed515a5821a4e438a694

**Comment by chelmuth** [comment]
Fixed by d15b39620207924d7903090761ff0a638002cf85 on master.
