### ISSUE TITLE
Race condition when lseek()ing newly created file

### ISSUE THREAD

**Issue by senier** [genodelabs/genode#2695]
When creating a new file using `open()`, writing data to it using `write()` and seeking to the end of the newly created file using `lseek(fd, 0, SEEK_END)`, there is a race condition. In the major number of cases the result is the length of data written, as expected. Sometimes `lseek()` returns 0.

When performing an `fsync()` after writing, the issue does not happen. This does not happen on Linux either.

[This](https://github.com/Componolit/componolit/tree/android_runtime/src/test/mfe/lseek_after_write) is a reproducer.

**Comment by cnuke** [comment]
@senier please give c962d40 a try.

**Comment by senier** [comment]
This fixes the issue (not unexpectedly, as a manual fsync() had the same effect). Thanks @cnuke for the quick resolution!

**Comment by chelmuth** [comment]
I merged @cnuke's commit and also added another sync before ftruncate(). @senier do you approve?

**Comment by senier** [comment]
Yes, I can confirm that the issue is fixed in staging. Thanks!

**Comment by chelmuth** [comment]
Fixed on master branch.
