### ISSUE TITLE
Expose a Timer::Timeout_scheduler thru Libc::Env

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2698]
I expect using one timer source and multiple timeout handlers to perform better than using multiple timers and multiple signal handlers. If this is the case, why not add a timer accessor to the `Libc::Env` object?

**Comment by chelmuth** [comment]
From the background of #2777 I doubt the libc-internal timer connection should be used from application/component code. If a component needs `App` level timer signals it needs to instantiate its own timer connection while the libc will use `Io` level.

**Comment by ehmry** [comment]
Ok, agreed.
