### ISSUE TITLE
hw: avoid arm cache maintenance code duplication

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#2699]
As @m-stein thankworthy recognized there is a huge code duplication in between `repos/base-hw/src/core/spec/arm_v7/cpu.cc` and `repos/base-hw/src/lib/hw/spec/arm/arm_v7_cpu.cc` that can be avoided.

**Comment by skalk** [comment]
Related to this issue, Tomasz Gajewski kindly remarked on the mailing list that there are some artefacts in the usage of invalidate_*_cache currently use. Actually, we do not need the cache maintainance functions related to the whole cache in core/kernel anymore. A selective cache-flush is enough, now that the corresponding address-space is still the active one. Therefore, we can safely remove those functions, and only need to leave them in bootstrap to invalidate the whole cache in the very beginning.

**Comment by m-stein** [comment]
Really cool. more than 200 LoC less in base-hw :)
