### ISSUE TITLE
fetchurl progress report

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2702]
The #2684 patch removed progress logging from fetchurl and now the utility is too opaque about what is happening. The log session should be for logging events, not status, so a status report would be more appropriate.

**Comment by ehmry** [comment]
Fixed on my **issue2702_fetchurl_progress** branch following @BorisMulder-CSL's patches.

**Comment by ehmry** [comment]
Fixed to use standard `<report progress="..."/>` pattern at  516777f881cac5c09b00e20f075863765a95b974.

**Comment by chelmuth** [comment]
Thanks, merged your commit (plus one from @BorisMulder-CSL). I skipped the assert/remove commit, though, as I still fancy the truncate solution more.

**Comment by ehmry** [comment]
@chelmuth I have a small fixup for printing failed URLs with error messages at b03fcd7b839753eeabfa2f6dc00488bba4f0c0ae.

**Comment by ehmry** [comment]
I have a minor commit 077818d284d8c8f03cc1f05bdc56c255428715bd to fix the fetchurl package.
