### ISSUE TITLE
Link EGL with the Mesa library

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2711]
The EGL library allows application to avoid explicit knowledge or requirements of Mesa with the `eglGetProcAddress` procedure.

**Comment by ehmry** [comment]
Components that use GL headers still need to list `mesa` in LIBS or use `INC_DIR += $(call select_from_ports,mesa)/include/mesa`. Perhaps this can be solved with a header-only GL library?

**Comment by chelmuth** [comment]
@ssumpf @cnuke opinions?

**Comment by ssumpf** [comment]
@ehmry : It should suffice to add `mesa_api` to `LIBS` in order to get access to the OpenGL headers.

**Comment by ehmry** [comment]
In that case the commit message should probably be changed to say something like
> Components may wish to list 'mesa_api' in LIBS to access OpenGL headers.

**Comment by chelmuth** [comment]
Adapted the commit message and force-pushed staging 98ad7961eefcbb51112fc4b6cc415260b8cf4c26.

**Comment by ehmry** [comment]
Cool, staging now supports the libretro frontend passing a GL context to cores.
