### ISSUE TITLE
libc: distinct read from regular file and pseudo devices

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2714]
The current version of the libc maps read operations directly to VFS read operations. In the general case, the VFS cannot read a file as a whole. E.g., when the file is fetched over a file-system session, the dimension of the packet-stream buffer forces the VFS to read the content in chunks. Right now, the read of each individual chunk is reflected to the libc-using application. This is unfortunate because such an application may reasonably expect that a regular file can be read in one step as long as it fits into the read buffer.

Since this expectation does not hold, one is forced to implement a loop around `read`, e.g. as done here: https://github.com/genodelabs/genode/blob/master/repos/gems/src/lib/file/file.cc#L49 Even though, the current behavior of `read` is semantically compliant to POSIX, it contradicts with the usual practice to *not* wrap read calls into a loop. Hence, I argue that we should move the loop into the libc.

However, the loop cannot be applied to each `read` operation but only on regular files. When reading from a pseudo file like a terminal or a UDP socket, read should return immediately after the reception of the first chunk of data. Therefore, we need to distinguish both cases in the VFS and also the file-system session.

I propose the following steps to implement the desired behavior:

1. Extending the `File_system::Status::mode` with a new `MODE_DEVICE` flag, which tells the client that the node is not a regular file.

2. When the libc opens a file, it issues a `stat` to determine whether the file is a regular file or a device and stores this information in the file-handle. Actually, stat is already performed by the libc to follow symlinks. So we don't necessarily need to introduce additional overhead here but instead let the `resolve_symlinks` function return the gathered information.

3. The read implementation checks this information to distinguish files from pseudo devices. For files, it implements the loop that fetches the file content chunk by chunk from the VFS.

**Comment by nfeske** [comment]
Please note the updated issue description.

**Comment by ehmry** [comment]
This seems like a good time to raise the issue of **st_blksize**, if the VFS were to support this information it could inform the behavior of the internal read loop as well as the application. How much it would effect performance, I'm not sure.

> The size-related fields of the struct stat are as follows:
>   st_size	 The file size in bytes.
>   st_blksize	 The optimal I/O block size for	the file.
>   st_blocks	 ...

https://www.freebsd.org/cgi/man.cgi?query=stat&sektion=2&manpath=FreeBSD+11.1-RELEASE+and+Ports

**Comment by cnuke** [comment]
It stands to reason if we need to fix it at all and how to do so. The underlying file system session does not provide any means to gather this information currently and would need to be extended. Besides ported POSIX programms. e.g. `cat(1)` adjusting its buffer size, I see no immediate use-case to justify the change and programms that deal with block devices will probably revert to using the ioctl interface anyway. From what I can tell, other systems choose a somewhat arbitrary value  (Linux uses `4K` while OpenBSD sets it to `16K`) that is a multiple of the block size. That being said, increasing the default I/O block size to `4096` as well on our part should not do any harm.

**Comment by ehmry** [comment]
This is maybe something for another issue, but the Fs_file_system write implementation in the VFS does not gracefully handle the case where the size of a write buffer exceeds the size of the packet buffer. The Fs_file_system is the case where *blksize* information would be most useful.

**Comment by ehmry** [comment]
I like the idea of bigger read ops, when dumping large data into terminal sessions I've noticed that each operation can be quite small, less than 4KiB.

**Comment by nfeske** [comment]
Superseded by #3507
