### ISSUE TITLE
Framebuffer has_alpha() function

### ISSUE THREAD

**Issue by NobodyIII** [genodelabs/genode#2723]
Currently, the method of checking whether a framebuffer has an alpha channel is by comparing the dataspace size to the size required by the pixel format and framebuffer dimensions. To reduce code duplication and to simplify framebuffer use, I propose that we add a has_alpha() function to the Framebuffer::Session_client class.

**Comment by NobodyIII** [comment]
Or we could modify Framebuffer::Mode to indicate whether an alpha channel/image exists.

**Comment by nfeske** [comment]
I'm closing this issue because it does not address a real problem. Once we pick up the work on the graphics interfaces, we may consider such an acessor.
