### ISSUE TITLE
Gems: magic ring buffer

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2725]
I have a ring buffer that I use in some of my side projects that I would like to have in the Gems repo.

**Comment by ehmry** [comment]
Patch at 3edeaa96fd99e2e00c73d24d3bc39d129f196fcc.

**Comment by nfeske** [comment]
That's a cool idea. It would fit well in the gems repository. I have the following remarks about the commit.

* It would be good to apply the common indentation style where the `public:` and `private:` section labels are indented.
* Each of both `attach_at` may fail with an exception (e.g., when multiple threads interact with the address space concurrently). To make the code more robust, it should be wrapped in a try-catch block. The handling code should revert the (potentially successful) first attach before re-throwing the exception.
* In the error case, the constructor just throws an `Exception`. How about throwing a more descriptive exception type like `Region_map::Region_conflict`? It would be good to document the exception in a comment of the constructor (using the `\throw` notation).
* I would prefer to avoid the term `PAGES` at the API level. Couldn't the user of this utility just specify a number of bytes as template argument instead?

**Comment by chelmuth** [comment]
It seems `PAGES` is just an artifact and should read `SIZE` as in the implementation.

It may sound like overkill but the ring-buffer region could be reserved by using a managed dataspace and attaching the RAM dataspaces in the nested `Region_map`.

**Comment by ehmry** [comment]
Yes, PAGES was an artifact. This utility is a bit dangerous because if the size TYPE is not a power of two the buffer becomes trashed after SIZE bytes have been written.

Fixup at e31cd054cc9efe90d3cf327d5c1b0dca5a32c0ed.

**Comment by nfeske** [comment]
@ehmry Thanks for the quick overhaul.

**Comment by nfeske** [comment]
Merged to staging.

**Comment by ehmry** [comment]
@chelmuth do you have an example of reserving address space with managed dataspaces?

**Comment by chelmuth** [comment]
@ehmry The *sub_rm* test seems to be a good starting point. Please refer to https://github.com/genodelabs/genode/blob/master/repos/base/src/test/sub_rm/main.cc#L64

**Comment by ssumpf** [comment]
@ehmry:
`Rm_connection _rm_connection { env };`

/* create region map (reserve address space */
`Region_map_client _rm { _rm_connection.create(<size>);`

/* attach map to global region map */
`env.rm().attach(_rm.dataspace());`

/* attach something into region map */
`_rm.attach(ds);`

**Comment by ehmry** [comment]
I have a patch to improve the buffer at 86e1abd1f5db52c9c22060965ffa5294127b15d2. The buffer now uses a region map to reserve space and comes with a test.
