### ISSUE TITLE
authenticated depot history

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2734]
Distributing a signature with every package is the obvious first step in package authentication, but is a bit dangerous without a means to permanently revoke a key or packages in the event that a secret key is compromised.

I suggest to consider using signed, append-only logs to store and transmit depot histories. Each depot user would first publish a signing key and then start building a a chain of messages. Each message contains a sequence number, the hash of the previous block, and a payload (not necessarily in that order). The log is capped with a new signature each time a message is added, and signatures would be periodically stored in messages. This log need not be specific to depot, but there should be schema for a handful of primitives for mutating depot history. Using a signed log allows untrusted third-parties to forward histories. It also would allow offline or air-gaped machines to update themselves using physical media containing depot logs and depot packages, in roughly the same manner that a networking machine would.

My draft depot primitives would be:
 - `announce(name, description)` - announce a new package
 - `release(name, version, description)` - release a new package version
 - `revoke(name, version, description)` - revoke a package version, perhaps for vulnerabilities or misbehavior
 - `deprecate (name, description)` - deprecate a package series, perhaps for incompatibilities or end of maintenance

For a network protocol I would initially use a simple file-system layout served by HTTP. For encoding the log I would use [CBOR](http://cbor.io/), which is an easy to understand binary encoding that defines a reproducible canonical encoding for any given data. For signing the log I would try the [SPHINCS+](https://sphincs.org/) hash-based signature scheme. SPHINCS+ signatures are a bit large, but the scheme has post-quantum security, which would be a favor to OS archeologists. In the event that a key was compromised a special revocation message would be published that would revoke log messages, either the entire log or everything after a given sequence number.

Managing the size of logs is an open issue, but probably involves a combination of a methods for different users.

**Comment by nfeske** [comment]
I feel admittedly a bit overwhelmed by this issue because I don't yet have a good grasp of the kind of problems that it addresses, let alone the solutions. A lot of questions pop into my mind:

* Is it meant as an optional supplement or do you intend to replace the OpenPGP-based verification entirely?
* If it is supplemental, what does post-quantum-cryptography offer? As far as I know, OpenPGP signatures do not have this trait.
* Do we want to support key revocation in the first place? Couldn't we just create new identifies instead. So once `nfeske/pubkey` is compromised, I would need to create `nfeske-2/pubkey` and tell my users to use the new identity.
* How to propagate the information about compromised keys? Do we enter the realm of decentralized consensus protocols here? I am hesitant going there, fearing from becoming too much consumed by this complex topic.
* What happens for the user when a key is revoked?

Please don't get me wrong. I don't want to dismiss this topic. I encourage you to explore it further. But right now, I feel unable to contribute to it in a qualified manner.

**Comment by ehmry** [comment]
What I didn't mention is that this is idea is something that I have talked about with some friends for over a year, so it has become quite developed in my head, and there are different motivations for different parties. My personal motivation is to try and build a package distribution system that can work over sneakernet because, presumably, most people in the world don't have persistent network access.

To answer your questions:
* This would be an optional supplement to PGP verifications. Log messages pertaining to depot package releases would likely contain a hash of package content, but there is no impediment to making PGP signature available with each package tarball.
* Post-quantum, hash-based signatures are interesting because they are actually quite simple to implement, or at least understand, compared to RSA. The drawback is that they are large, 8KiB when using a 256-bit hash function. In this case size is not a concern, as the log need only contain the most recent signature.
* Key-revocation is always nice to have, and of course PGP does this. So its not fair to portray this is a new feature.
* Propagating revoked keys would not need to require consensus, whatever package version management would be built on these logs would simply need to support revoking package histories when they encounter a log with a revocation message. The benefit is that revocation comes in-band with log messages. Its not my intention to come up with a network protocol soon, I just want some scripts to fetch log updates, and potentially destroy package histories if the author wishes. Censoring the log author is of course a problem, but out of scope. I certainly don't want this to be confused to with blockchains, which is the most expensive and least efficient consensus algorithm ever deployed.

**Comment by ehmry** [comment]
For what its worth, the first thing I want to make is a command line tool to append log messages, and the second would be a CGI program to generate an RSS feed.

**Comment by ehmry** [comment]
I'm closing this issue as I do not have the time or motivation to see it through.
