### ISSUE TITLE
Copy-on-write VFS plugin

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2745]
With #2701 cleared it is time for the anticipated copy-on-write VFS plugin. This is a general purpose plugin that has many uses. An immediate use-case would be to define an static, early file-system in a boot image that seeds a mutable file-system in local, persistent storage.

**Comment by ehmry** [comment]
I have a trivial implementation on my **issue2745_vfs_cow** branch. I say trivial because files are copied on open, not on write, and because the union directory behavior is roughly the same as the `Dir_file_system`. That is, the number of entries in a directory is the sum of a copied directory and the original, with the copied entries stacked ahead of the original.

I have a test at `run/fs_report_cow` that tests same use-case as `run/fs_report`, but I would like a more robust test to be confident in the COW behavior. Are there any suggestions for a use-cases to test?

**Comment by ehmry** [comment]
@nfeske cow plugin removed with 797792570345b9d2bfd35bf1e568cb1d5cdd34fd.

**Comment by nfeske** [comment]
Thanks @ehmry. I merged the removal commit to staging.
