### ISSUE TITLE
net: safer access to packet data

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2751]

**Comment by m-stein** [comment]
Fixed:
48ac695 nic_router: use default Ethernet_frame constructor
0ca214d ping: use default Ethernet_frame constructor
31bdbef net/udp.h: safer access to data
6d9fa61 net/ethernet.h: safer access to data
59cfa8e net/ipv4.h: safer access to data

@nfeske I hope this first step complies with your idea of how to rework the net lib?

There exist future plans to further adapt the net lib:
* get rid of the non-standardized c++ bit indicators like in ipv4.h: ``unsigned _header_length : 4;``
* consider Ipv4 options
* re-think concept of size guards (they also may be used in reinterpret_data analogous to their use in construct_at_data)

**Comment by m-stein** [comment]
Added 3 minor fixes that came up while fixing this issue:
31be3c1 test/lwip clients: exit with error code
7fc9dbe test/lwip/udp/client: handle missing attributes
4bf193c nic_router: more descriptive errors in DHCP server
Previous history:
c7aa72f nic_router: use default Ethernet_frame constructor
14d9b32 ping: use default Ethernet_frame constructor
6d7f895 net/udp.h: safer access to data
87e9135 net/ethernet.h: safer access to data
fa4ecd0 net/ipv4.h: safer access to data

**Comment by chelmuth** [comment]
IMO fa4ecd0, 87e9135, 6d7f895, 14d9b32, and c7aa72f should be merged into one commit as all address the same issue. After that and the use of the original `data()` naming, I'm ready to merge the commits into staging.

**Comment by m-stein** [comment]
@chelmuth I've updated the commits according to the suggestions:
ca8086d nic_router: use default Ethernet_frame constructor
15b9d72 ping: use default Ethernet_frame constructor
421eeb9 net: safer access to packet data

**Comment by m-stein** [comment]
Sorry, this is the final commit that contains all five original commits:
5353d86 net: safer access to packet data

**Comment by chelmuth** [comment]
Should be merged to staging now, please check.

**Comment by m-stein** [comment]
Yes, as far as I can see it's all merged. Thanks!
