### ISSUE TITLE
part_blk: handle config update

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#2754]

**Comment by nfeske** [comment]
@cnuke That's great! Thanks for this cool feature.

**Comment by nfeske** [comment]
As discussed offline, we'd like to defer the config-update handling until we have figured out the desired semantics of policy changes. I.e., what should happen when a policy for an existing session vanishes or changes.

**Comment by cnuke** [comment]
I will close this issue b/c selecting the partition is realized differently. As for updating the config, so far there was no need to implement it.
