### ISSUE TITLE
Microcode updates

### ISSUE THREAD

**Issue by senier** [genodelabs/genode#2762]
Microcode updates can be essential for stability and security of a system as demonstrated by the mitigations rolled out to counter the recent Meltdown and Spectre vulnerabilities. While microcode updates should be done in the BIOS, we do not want rely on BIOS vendors who may not provide timely updates or no updates at all. Hence, microcode must be updated by the OS.

There are a number of restrictions when to apply microcode updates. Generally, this should be done [as early as possible](https://gitlab.com/iucode-tool/iucode-tool/blob/master/README). The goal of this issue is to investigate what is required to update microcode from within Genode and what mechanisms are required.

*(moved from [here](https://github.com/Componolit/componolit/issues/114))*

**Comment by alex-ab** [comment]
Pushed a fixed version which works also with microcode updates larger than 64k (it makes me sad) for very recent CPUs.

**Comment by nfeske** [comment]
@alex-ab I merged your commit series to staging.
