### ISSUE TITLE
Update FatFS port

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2766]
As discovered by @rite, the hash of FatFS source has changed. It turns out there is a new version, so this can be fixed on staging with an update.

**Comment by ehmry** [comment]
Fixed on my **issue2766_fatfs_port** branch.

**Comment by chelmuth** [comment]
@NobodyIII reported on the [mailing list](https://lists.genode.org/pipermail/users/2018-September/006304.html) that the hash sum of the downloaded file changed again. This is the third time we face this issue. One option would be to self-host a blessed version on our own web server.

**Comment by chelmuth** [comment]
Hm, the situation with bzip2 is quite different... the domain bzip.org expired.

**Comment by ehmry** [comment]
Works for me.
