### ISSUE TITLE
SHA1 deprecation

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2767]
https://shattered.io/

It is known to be practical to forge SHA1 checksums on files without a bruteforce attack, so it would be wise to move to a different hash function for verify ports in the near future.

I would volunteer to add support for an additional verification method in the `prepare_ports` tool. I think SHA-256 would be the least disruptive alternative.

**Comment by nfeske** [comment]
Thanks for bringing up this issue and for volunteering. SHA-256 sounds good to me.

**Comment by ehmry** [comment]
Patch at c03ab9d8a95a693568c67aca6df03f2b2c32bd09. This adds support for 'SHA256' in port files and leaves the port and depot versioning intact.

**Comment by ehmry** [comment]
Yes, new patch at 3b3fae6dd7ea68aa63c806cd22db0d448b4c006d to keep the `SHA` variable name, yet still refusing to check SHA1 during `CHECK_HASH=no`.

**Comment by nfeske** [comment]
Thanks for the new commit, that's very good!

**Comment by ehmry** [comment]
I have two more commits for this series, b85b00014f4cb60dd4f58a73b40302aa5f9265d5 replaces SHA1 file digests with SHA256 and 2f4a8bf55831dc9ef598c06afe4d4b821866201c removes SHA1 verification.

**Comment by ehmry** [comment]
Fixed in 18.05.
