### ISSUE TITLE
depot: qoost recipe

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2771]

**Comment by NobodyIII** [comment]
What about recipes for Qt libraries? Doesn't qoost depend on those?

**Comment by chelmuth** [comment]
This issue as wells as #2785, #2784, and so on are preparations exactly for this purpose. So, please be patient as this endeavor is no cinch and @cproc is working hard to finish it for the release.

**Comment by NobodyIII** [comment]
Okay. But won't the recipe for qoost need to be modified to state its dependencies?
