### ISSUE TITLE
Nova: Ipc_error in a client after another client died

### ISSUE THREAD

**Issue by BorisMulder-CSL** [genodelabs/genode#2774]
I have the following scenario:
- a server has an RPC call, which, among other things, can stop and start a subsystem S. on top of init.
- it supports multiple clients. One of these clients called s lives on top of S; another one, called c, is a sibling of the server.
-Now the following sequence of actions happen:

1. S is running.
2. if c does an RPC call now, everything goes well.
3. s issues the RPC call that stops S; so s kills itself indirectly.
4. S is restarted, so is s.
5. if s does the same call again, all goes well.
6. However, if c does any call now to the server, this call will throw a Genode::Ipc_error.

I looked where Ipc_errors can be thrown, and I found out that it was thrown here: https://github.com/genodelabs/genode/blob/master/repos/base/include/base/rpc_client.h#L144
The exception type is invalid. I put print statements and a generic try/catch on my server code, checking if it throws any strange exception there over RPC it shouldn't throw. No success. The server code is not reached at all.

I checked why this rpc_call function returns an invalid exception code. It happens here: https://github.com/genodelabs/genode/blob/master/repos/base-nova/src/lib/base/ipc.cc#L81
So the Nova::call function returns with an error. I stopped delving further, but I suspect something in line of the following might be at hand:

When s is killed while still in the process of an RPC call, somehow this client enters some kind of zombie state where it is still known by the kernel. While in this state, the kernel is in a 'bugged state' regarding this server (it still hasn't delivered back the return value, in this case void, of the RPC call to s) and fails to handle new IPC calls of other clients, like c, to the same server.

Does this ring a bell? Any ideas as what could be happening?

**Comment by BorisMulder-CSL** [comment]
Note that the server does not live on S, but is a sibling of the init that contains S.
Also, if one client dies, another client's capability should not be invalidated. They are separate capabilities, right?

**Comment by alex-ab** [comment]
> Note that the server does not live on S, but is a sibling of the init that contains S.
This does not matter. The kernel destructs the complete server S, thereby destructs all capabilities to this service - independent on whether c is a sibling or not. The service is gone, so the capability becomes invalid.

**Comment by BorisMulder-CSL** [comment]
The server is not destructed, only the client s.
neither the client c nor the server live on S, and only S is destructed.
No capabilities to the service should be destructed, except that of client s, because s is destructed.

**Comment by chelmuth** [comment]
Maybe a picture (even if hand-drawn) tells more than thousand words, we say in Germany...

**Comment by BorisMulder-CSL** [comment]
we have four components:
[server]
[client_1] (here called 'c')
[init] (hosting a subsystem called 'S')
[init -> client_2] (here called 's')

long story short: when [server] writes to [init]s config, killing [init -> client_2], not only [init -> client_2] but also [client_1] fails to issue RPC calls to [server] and throws an Ipc_error.
When restarting [init -> client_2], [init -> client_2] can issue RPC calls to [server] again by opening a new connection, but [client_1] still cannot issue any RPC calls to [server] over the same old connection.

Is this more clear? If not, let me know.

**Comment by alex-ab** [comment]
I would suggest to check that the [server] really hands out per client a new capability and would check what   [server] does during the closing/removal of a session (that it really just closes the requested session and not all or from other clients).

**Comment by BorisMulder-CSL** [comment]
The server code is pretty straightforward:
```
class Session_component : public Genode::Rpc_object<Session>
{ ... }
class Root_component : public Genode::Root_component<Session_component>
{
		private:
			Session_component _component;

		protected:
			Session_component *_create_session(const char *)
			{ return &_component; }

			virtual void _destroy_session(Session_component *) override {}

		public:
			Root_component(Genode::Env &env,
			               Genode::Allocator &alloc)
			:
				Genode::Root_component<Session_component>(env.ep(), alloc),
				_component(env, alloc)
			{}
};
```
I guess that overriding the _destroy_session method should do that. There is only 1 RPC object, and it is handed out to other components.
The capability should not be destroyed at all, but perhaps all caps in possession of a component that is destroyed are invalidated automatically by the kernel? That would explain it.

**Comment by BorisMulder-CSL** [comment]
I tried rewriting the server code to return a new Session_component on _create_session.
The issue does not pop up now.
For me it feels strange that when a component delegates a capability to multiple other components, and one of these components ceases to exist, that the capability is also invalidated for the other components.
Is this intended?

**Comment by alex-ab** [comment]
I think your use-case is not covered/supported by root/component.h. Looking at https://github.com/genodelabs/genode/blob/master/repos/base/include/root/component.h#L364, the capability for the single component gets told to be destroyed (by ep.dissolve()). At this point no distinction between clients is possible (since you decided to have just one component with exactly one cap for all clients).

**Comment by alex-ab** [comment]
Due to https://github.com/genodelabs/genode/blob/master/repos/base/include/root/component.h#L183 and https://github.com/genodelabs/genode/blob/master/repos/base/include/root/component.h#L199 the session cap is identical for all sessions and  therefore all clients and therefore it explains your observation.

**Comment by alex-ab** [comment]
@nfeske pointed out that https://github.com/genodelabs/genode/blob/master/repos/os/include/os/static_root.h may also fit your needs.

**Comment by BorisMulder-CSL** [comment]
Ok, well static_root seems to support single clients only. For me the issue is that I have multiple clients listening on a server, but all the clients can do exactly the same and there is no real distinction between different session components. Moreover, having different session components in my case means I have to pass all kinds of references to them, as all clients operate on the same server-side objects.
This in practice means duplicating the session interface onto the session component, which just becomes a facade, and onto the actual server object, to which each session component must contain a reference.

The code becomes something like this:

```
class Session_component : public Genode::Rpc_object<Session>
{
	private:
		Server_object &_obj;

	public:
		Session_component(Server_object &obj) : _obj(obj) {}

		virtual void foo() override {
			_obj.foo();
		}

		virtual void bar() override {
			_obj.bar();
		}
		// etc for each function in the session interface
}
```

while the Server_object class implements the real functionality. Is this the best way to do this, or is there a better way?

**Comment by chelmuth** [comment]
Your observation is wrong: `Static_root` supports multiple clients and hands out one and the same `Capability<SESSION> _session` on each session request. Nevertheless the pattern is obscure as `Session::close` does nothing, so the closed session is still usable after close. In Genode, the revocation of sessions only happens if the capability is invalidated by dissolving the RPC object from the entrypoint.

**Comment by BorisMulder-CSL** [comment]
Ok, then maybe the comments in the code of static_root are a bit misleading:
```
/**
 * Root interface that hands out a statically created session
 *
 * Many components, in particular device drivers, support only one client
 * at a time. In this case, one single session may be created right at the
 * start of the program and handed out via the 'Root::session' method.
 */
```

**Comment by chelmuth** [comment]
The comment has the current wording because of the second part of my posting above. The comment does not exclude the optional support of multiple clients while it does not encourage the developer to do so at the same time.

**Comment by BorisMulder-CSL** [comment]
Anywat in my case, Static_root would just be a shortcut to doing the same as I did with the singleton Session_component. It would not solve the problem, or am I mistaken?

To come back to the issue at hand, how to support multiple clients opening and closing sessions, but have the server share all datastructures among the clients? Is duplicating the interface as in my last snippet the best way to solve this?
I have seen this pattern in at least four servers I developed so far. I would like to hear your opinion on this.

**Comment by chelmuth** [comment]
`Static_root` implements the `Root` interface for `SESSION` and is an Rpc_object (manageable at an entrypoint, accessible via RPC). Therefore it is an replacement for `Root_component` removing all the manage/dissolve magic happening transparently. `Static_root` as well as the singleton session object must be `manage()`'d manually at the entrypoint. So, it indeed solves your original problem that the capability you handed out is invalidated behind your back (by the `Root_component` implementation).

But, my suggestion is to construct a session component for each session if you at some time in the future like to rely on effective revocation of capabilities on `Session::close()` as done by init. I did not get your issue of *passing all kinds of references* but trust you can solve it by passing just one reference to a compound singleton.
