### ISSUE TITLE
nic_router-nat: ICMP NAPT and DNS info forward

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2775]

**Comment by m-stein** [comment]
Fixed and added improvements for Net lib and Ping:
16409b1 ping_nic_router: support real hardware
53ac4fa net: use generic internet checksum
a1f1988 ping: dynamic IP configuration
43130a6 nic_router: fix typo in Nat_rule::print
1555762 nic_router-nat: ICMP NAPT and DNS info forward

**Comment by m-stein** [comment]
Updated the commits in a way that ICMP error through NAPT is also tested:
d0389cd ping tests: test also UDP and on hardware
6996edb ping: support UDP
dc42612 net: implement Udp_packet::checksum_error
69733a3 net: use generic internet checksum
08b6cb7 ping: dynamic IP configuration
0c17030 nic_router: fix typo in Nat_rule::print
16f1aa3 nic_router-nat: ICMP NAPT and DNS info forward

**Comment by m-stein** [comment]
@chelmuth I fixed the problems with pbxa9 + foc/hw and a bug in the UDP support of Ping:
20fd4bb net: consider tail of Ethernet frame
f15bd1f ping tests: test also UDP and on hardware
49568d9 ping: support UDP
c8d3a22 net: implement Udp_packet::checksum_error
92b70e5 net: use generic internet checksum
4d4640b ping: dynamic IP configuration
50045f2 nic_router: fix typo in Nat_rule::print
e11e2bd nic_router-nat: ICMP NAPT and DNS info forward

**Comment by chelmuth** [comment]
fea0822214282ac04325b146029065e9828c2acd makes no sense now that ping it only contains the ping changes, please merge with c8779f349169afa97e0f7c534750c1bdbb10da6e. I know it's not easy to keep track of individual commits on rebase but that's also true for me merging features from several sources.

**Comment by m-stein** [comment]
Have re-ordered my merge_to_staging.
