### ISSUE TITLE
net: use Size_guard in packet data accessors

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2788]

**Comment by m-stein** [comment]
Fixed:
db58150 net: use Size_guard for packet-data accessors
898f98e ping_nic_router.run: faster DHCP for PandaBoard
59c7a68 autopilot.list: add nic_bridge
da3222a nic_bridge.run: don't execute on hardware
07d15d3 ping tests: support USB NIC
f65530f nic_bridge.run: remove posix.lib.so

**Comment by chelmuth** [comment]
Please rebase on current staging so I can have another look. Note, I cut out the ping DHCP part from the commit series and like the feature to be added on top.

**Comment by m-stein** [comment]
Have re-ordered my merge_to_staging.

**Comment by chelmuth** [comment]
@m-stein can we close this issue?

**Comment by m-stein** [comment]
Yep.
