### ISSUE TITLE
Noux deadlocks when loading ROMs from File_system

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2789]
Noux can load child binaries fine from local TAR archives using its `Vfs_io_channel`, but it cannot load them from asynchronous VFS plugins like File_system on the initial entrypoint without blocking the VFS signal handlers and deadlocking.

**Comment by ehmry** [comment]
Fix at b70d854d762a9aad230a604b95480293e5fbc33a. I tried to keep the `Vfs_io_waiter` in place and move the read process to the `Noux::Child` `Rpc_entrypoint`, but found no simple way to do it.

**Comment by nfeske** [comment]
Since we are phasing out Noux, this issue won't get further attention.
