### ISSUE TITLE
part_blk: automatic distinction between MBR and GPT-based partition tables

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2803]
Currently, part_blk considers GPT only when explicitly configured with the `use_gpt` attribute. If this attribute is not set but a GPT-based block device is encountered, part_blk aborts:

```
Error: Aborting: found protective MBR but GPT usage was not requested.
Error: Uncaught exception of type 'Mbr_partition_table::Protective_mbr_found'
Warning: abort called - thread: ep
```

I would prefer part_blk switching automatically into GPT mode in this situation. @cnuke Would that be possible?

**Comment by cnuke** [comment]
Sure, that is possible.

**Comment by cnuke** [comment]
@nfeske please give 176234e a try.

**Comment by cnuke** [comment]
@nfeske please check if 511e848 fixes your use-case.

**Comment by cnuke** [comment]
@nfeske please give 11990a7 a spin.
