### ISSUE TITLE
test/trace_logger does not terminate on fiasco, okl4, pistachio, foc_pbxa9, and sel4

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#2809]
I suspected the timeout of the test from #2735 may be to tight in 00b12ee65e942a350b9f4c5134e65e8219473241 which did not help. Now, we have two options for each of the platforms, disable the test as the issue will not be addressed or fix it. Opinions, @m-stein @ValiValpas ?

**Comment by m-stein** [comment]
I'll hav a look at it and try to fix it.

**Comment by chelmuth** [comment]
The test case moved into depot_autopilot and no longer fails.
