### ISSUE TITLE
title and scheme of documentation links incorrect

### ISSUE THREAD

**Issue by mewmew** [genodelabs/genode#2818]
The documentation links to sculpt (and other related documentation material) are not correctly converted from markdown to HTML.

From https://github.com/genodelabs/genode/blob/master/doc/news.txt#L20:
```
*Printable version (pdf)* [https:/documentation/sculpt-ea.pdf]

*Online version* [https:/documentation/articles/sculpt-ea]
```
Converts to the following HTML (as displayed at http://genode.org/news/sculpt-for-early-adopters):
```html
  <p>
   <b>Printable version (pdf)</b> <a href="../documentation/sculpt-ea.pdf">https:/documentation/sculpt-ea.pdf</a>
  </p>
  <p>
   <b>Online version</b> <a href="../documentation/articles/sculpt-ea">https:/documentation/articles/sculpt-ea</a>
```

Expected:
```
  <p>
   <b>Printable version (pdf)</b> <a href="https://genode.org/documentation/sculpt-ea.pdf">https://genode.org/documentation/sculpt-ea.pdf</a>
  </p>
  <p>
   <b>Online version</b> <a href="https://genode.org/documentation/articles/sculpt-ea">https://genode.org/documentation/articles/sculpt-ea</a>
```

Note, when navigating to http://genode.org (notice the HTTP scheme) and and clicking on the scult new item, the link scheme (https) suggests that the target of the link should be HTTPS, however, the relative link stays on the HTTP scheme.

**Comment by chelmuth** [comment]
Thanks for the hint and the wishes. You're right the link text and the `href` should always be aligned. Maybe we should force HTTPS in our web server via redirects (or whatever the appropriate mechanism is nowadays) anyway.

**Comment by N8Fear** [comment]
I think the most sensible way is 301 all http://... requests to https://... - afaik that's also what most sites do, that try to enforce https only.

**Comment by chelmuth** [comment]
Our web server redirects to HTTPS now.
