### ISSUE TITLE
check_port_source for file download may download whole file

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#2819]
As with the now obsoleted nim-csources the jdk port uses a file download from GitHub, which ends in the following command line in check_port_source.
```
 curl -f -L -k -r -2 --max-time 15 --retry 2 https://api.github.com/repos/dmlloyd/openjdk/tarball/64892f1c9874938dfcdc235b5c051dd761cdd833
```
Unfortunately, GitHub does not support the range header and just serves the whole file which takes its time and may result in a timeout.

**Comment by chelmuth** [comment]
Unfortunately, the JDK port #2791 again breaks our port checker. It seems GitHub's web servers now fall into the following category (from the curl man page).

> NOTE:  The  file  size is not always known prior to download, and for such files this option has no effect even if the file transfer ends up being larger than this given limit. This concerns both FTP and HTTP transfers.

**Comment by chelmuth** [comment]
@nfeske noted that we may change our HTTP download availability test to inspection of the response headers (e.g., status code and `Content-Type`) of the final download location as `-max-file-size` and also `Range` seem to be a compatibility dead-end.

**Comment by nfeske** [comment]
There is no work planned for addressing this issue.
