### ISSUE TITLE
platform_drv: don't disable PCI bus master DMA of devices during platform_drv bootstrap

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2835]
Some devices are in use by the BIOS/UEFI, e.g. USB. For such devices explicit protocols (handover) exist to pass control to the operating system. By switching of PCI bus master DMA without following the protocol the whole machine may get stuck and hang hard. Observed on a AMD board.

**Comment by alex-ab** [comment]
@chelmuth: based on our discussion please review 40c41b393c2210e1ab220b059df332a8bdc30749

**Comment by chelmuth** [comment]
I like the commit but hesitate to merge it the next two weeks, as long as I'm not convinced that we achieve reasonable test coverage before the sculpt image release. Opinions anyone?

**Comment by alex-ab** [comment]
I understand, in principle. ;-) But ...

The argument against waiting goes as follow:
- The commit fixes hard hangs during boot due to USB handover protocol violation by Genode on some (few) machines - which would be a bad Sculpt experience ...
- By adding it early on sculpt_next, we actual would get the test coverage on all of our machines.
- If it turns out to break things on some of our machines, we can drop it immediately. 

But we may wait of course, I fully understand why. I will not insists ;-)

**Comment by chelmuth** [comment]
I merged 0ba5fc0b59b6c6e590b0602bfa5747eb9fff0a34 and appreciate any feedback regarding regressions.

**Comment by alex-ab** [comment]
Works for me on 7 native machines (Sculpt 18.05 + this patch)

**Comment by nfeske** [comment]
@alex-ab thanks for the elaborative testing. I have also switched my installation to the most current version.
