### ISSUE TITLE
Preserve hybrid MBR

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#2851]

**Comment by alex-ab** [comment]
sculpt + bios/legacy now boots also after a expand on real hardware

**Comment by chelmuth** [comment]
Beside this improvement, is it impossible for gpt_write to write a consistent hybrid mbr without any options/configuration requirements? Are there other use cases currently that are incompatible to this?

**Comment by cnuke** [comment]
There is no technical reason, just that there is currently neither a heuristic for selecting a potential boot partition nor is there code for writing a hybrid MBR.

**Comment by cnuke** [comment]
I am going to close this issue for now because the commits are in and how we want to deal with the hybrid MBR with regard to installing Sculpt on disk from within Sculpt should be the topic of another issue.
