### ISSUE TITLE
run: add '/sbin' to the 'PATH' environment variable

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2853]
On some Linux distributions, for example Debian, the '/sbin' directory is not included in the 'PATH' environment variable by default and tools like 'gdisk' are not found.

**Comment by cproc** [comment]
Fixed

**Comment by ssumpf** [comment]
@cproc: The `check_installed` function also searches /sbin.

`set gdisk_cmd [check_installed gdisk` in a run script should also work.]

**Comment by nfeske** [comment]
@ssumpf good to know. That said, I find the following code more obvious

```
exec gdisk args...
````

compared to

```
exec [check_installed gdisk] args...
```

Don't you agree? Or do you see any potential problem with extending the PATH environment variable?

**Comment by ssumpf** [comment]
@nfeske: Until now the workflow has:
`set gdisk [check_installed gdisk]`
`exec $gdisk args`
The other one is:
`requires_installation_of gdisk`
`exec gdisk`
I think we should get rid of one version. If the PATH way is preferred, we should also add '/usr/sbin' and '/usr/local/bin' since both have led to the same issue in the past.

**Comment by nfeske** [comment]
Thanks for clarifying. I agree with everything you said. The former approach has the benefits of not relying on a global side effect (PATH env variable) and of doing the check implicitly (it does not require the discipline of adding the `requires_installation_of` call). Only the name of the function `check_installed` is unintuitive. It wrongly suggests that is returns the result of a check whereas it actually performs a lookup similar to the `which` command. Maybe the name `installed_command` would be a better fit? The following version looks more intuitive to me:

```
exec [installed_command gdisk] args...
```

**Comment by chelmuth** [comment]
It's worth to mention that `check_installed` always exits with failure if the tool is missing. *tool/run* also provides `have_installed`, which returns true or false and currently does not check the additional paths.

**Comment by chelmuth** [comment]
@ssumpf any updates regarding this issue?

**Comment by ssumpf** [comment]
@chelmuth: Not yet, but I have it on my TODO list.

**Comment by ssumpf** [comment]
@chelmuth: Please have a look at 4a7712f if this is the right path to proceed.

**Comment by chelmuth** [comment]
After a quick look I like it - will review if you're finished.

**Comment by ssumpf** [comment]
@chelmuth:  d62f388 and  3667454 should resolve the issue.

**Comment by chelmuth** [comment]
@ssumpf  Could you please rebase d62f388bbec430b3039ddb52cfe260643f6d8477 onto staging (resp. 2e1e9241611f9ad14d43e577ca7725ea55c0173f) as there some non-trivial merge conflicts.

**Comment by ssumpf** [comment]
@chelmuth: Done with a889e3ec4e7110e0f17bc3b3711b8bb781c1c531
