### ISSUE TITLE
nova: update used kernel branch to r10

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2854]
[r10](https://github.com/alex-ab/NOVA/tree/r10) is the intermediate result of [Cyberus Technology](https://www.cyberus-technology.de) and of [Genode](https://www.genode.org) to harmonize the independently developed NOVA kernel branches. We hope to benefit from the NOVA evolution from each other in the long run by forming a common trunk branch [r_gc](https://github.com/alex-ab/NOVA/tree/r_gc) on which r10 is based.

We plan to go ahead and extend r_gc (the common part) and reduce the project specific commits (r10, r11, ...) where it seems beneficial for both sides.

From Genode's perspective r10 differs from the currently used r9 branch in the following ways:
- Reordering and cleanup (squashing together) of commits to form a common branch shared by others
- Add right bit to deny portal usage for cross-core IPC
- avoid GP when switching on AMD SVM if disabled by UEFI/BIOS

**Comment by alex-ab** [comment]
c691c9bd315cfd31311ec587e139f50faa0d3f7b faces the lazyFP named vulnerability

**Comment by alex-ab** [comment]
Just for the archives some number regarding FPU eager/lazy switching introduced by this update. noux_tool_chain_auto does finish in the same time (so no measurable performance hit). 

| counter | lazy | eager |
| --- | --- | --- |
| scheduled SCs | 276585 | 297517 |
| EC helping | 530 | 500 |
| EC switches | 2682562 | 2704089 |
| FPU switches | 7511 | 2704089 |
| ECs count | 38 | 38  |
| PDs count | 9 | 9 |

**Comment by nfeske** [comment]
Fixed in master.
