### ISSUE TITLE
libc: remove VFS header dependency in 'component.h'

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2870]
The pthread library now includes the `libc/component.h` header (issue #2865), which includes a VFS header, which is only available for depot packages using the pthread library if they declare to use the VFS API. Forward-declaring `Vfs::File_system` in `component.h` instead of including the VFS header avoids this problem.

**Comment by ehmry** [comment]
I have a small fixup at 5e1906d08659788be2af882b0edec7c21450f961, `vfs/file_system.h` needs `util/xml_node.h` included.
