### ISSUE TITLE
libc: socket peeking

### ISSUE THREAD

**Issue by jklmnn** [genodelabs/genode#2875]
While using the libc `recv` call with the `MSG_PEEK` flag I noticed that it isn't supported and according to the mailing list this also won't be supported in the future.

An idea would be a special file in socket_fs as suggested by @ehmry.

**Comment by chelmuth** [comment]
I suggest we broaden the discussion more in the direction: Should we really provide `MSG_PEEK` in the socket-fs or could those use cases be fulfilled by other means? I'm a bit hesitant to jump right into designing new POSIX-influenced features as POSIX definitely has its dark corners (think of `ungetc()`).

(Original discussion started at the [mailing list](https://lists.genode.org/pipermail/users/2018-June/006128.html).)

**Comment by jklmnn** [comment]
Of course we can broaden the issue. `MSG_PEEK` was just the example to start the discussion (I could have phrased it better). My initial problem was a mechanism to react on available bytes on a socket and transform this into an asynchronous API.

**Comment by ehmry** [comment]
I have a simple PEEK implementation on my `issue2875_peek` branch, I'm a bit on urlaub, so not yet well tested.

**Comment by chelmuth** [comment]
PEEK already sneaked into staging with #2335, hm.

**Comment by ehmry** [comment]
Yes, if you know the file is there and how to use it.

**Comment by cproc** [comment]
qtwebengine uses this feature as well (to check if a socket is connected). I rebased @ehmry's commits to staging and made some corrections in the lxip implementation and checked with a modified version of the 'libc http client test' [1] and it appears to work now with both lwip and lxip.

[1] https://github.com/cproc/genode/commit/d73bf77

**Comment by chelmuth** [comment]
What a pity but at least it's just the legacy world. Any chance to support MSG_PEEK in lwip too?

**Comment by cproc** [comment]
@chelmuth: lwip has the peek file already
