### ISSUE TITLE
foc: update to most recent kernel version

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#2884]
Quite recently, there was some movement inside the Fiasco.OC development to target the kernel object destruction problems we encountered for a long time. Thanks to Jakub @jermar for hinting us!
I've tested it, and it seems promising. Therefore, we shall raise the kernel version used by Genode.
Ref #1495
Ref #2659
Ref #2848

**Comment by jermar** [comment]
Hm, r79 does not contain all the potentially interesting fixes as it is older than the version on GitHub.

**Comment by skalk** [comment]
Well, in fact the commit updates to r79 + all recent Fiasco.OC commits from the Github repository.

**Comment by skalk** [comment]
Genode now references this Fiasco.OC/L4Re version: https://github.com/skalk/foc/commits/r79
