### ISSUE TITLE
thread.run: test successive thread creation and destruction

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2887]

**Comment by alex-ab** [comment]
Is this similar to repos/os/run/thread_join.run ? If yes, we may want to remove this os test.

**Comment by chelmuth** [comment]
You're right, the thread_join test should be merged into @cproc's addition. Also, the code would work perfectly without `Constructible` if the `Create_destroy_helper` becomes a local variable in the loop.

**Comment by cproc** [comment]
I replaced the `Constructible` and merged the join test in 81d1acac7c11ee6012cf45a74f0bbe34d38951f7.
