### ISSUE TITLE
sculpt: manual assignment of USB devices to clients / VMs

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2890]
In the current version of Sculpt, the driver manager automatically configures the USB driver such that USB storage devices can be assigned to VMs. However, this built-in policy does not cover non-storage devices. To make Sculpt more flexible, it would be nice to give the user a way to manually express a device-assignment policy.

**Comment by nfeske** [comment]
Commit be52d806595f0069875a5945d95dfa35dcd9e43b adds the policy hook.

**Comment by nfeske** [comment]
Actually, I just noticed that the example entry of the usb policy cannot not work because - unfortunately - the teensy microcontroller used in the ergodox reports being a HID device. As Sculpt uses the USB driver's built-in HID support, the device is always claimed by the USB driver internally. So we might better use another example (like an USB-serial adapter).

**Comment by ehmry** [comment]
Yes, this is also a problem with my Bitcoin hardware wallet, HID seems to be the recommended abstraction for USB devices now.

**Comment by nfeske** [comment]
Fixed in master, albeit not generally useful until we remove the current eager grabbing of HID devices by the USB driver. Unfortunately, a lot of devices (like arduino device) present themselves as HID device, which makes it practically impossible to assign it to a VM. However, reworking Sculpt's USB driver approach is a different issue.
