### ISSUE TITLE
pthread: 'pthread_join()' improvements

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2892]
Make `pthread_join()` work in more situations and support passing the thread return value.

I moved the `pthread` object destruction into `pthread_join()` to be able to retrieve the thread return value from the object. If it turns out that calling `pthread_join()` is uncommon in applications, we might need to store the return values separately or separate the destruction of the Genode thread from the destruction of the 'pthread' object to save some resources if many threads are created. But at least POSIX [1] and the Linux manual pages for `pthread_join()` [2] and `pthread_create()` [3] suggest that `pthread_join()` should be called for 'joinable' threads (the default state) to release remaining resources.

[1] http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_join.html
[2] http://man7.org/linux/man-pages/man3/pthread_join.3.html
[3] http://man7.org/linux/man-pages/man3/pthread_create.3.html

**Comment by nfeske** [comment]
Merged to staging.
