### ISSUE TITLE
nic_router: update tests to current state

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2899]

**Comment by m-stein** [comment]
These should already fix a bunch of tests:
b6f79ba nic_router: log ARP decisions when verbose
db7ead9 nic_bridge: verbose mode
c6fe88a netperf tests & router: update IP match string
cdeb6ab nic_router.run: fix invalid uplink

**Comment by m-stein** [comment]
(of course, the 2 verbosity commits are not relevant for fixing the tests)

**Comment by nfeske** [comment]
I merged the first two commits to staging. For staging, I'd like to focus on fixes right now to update the master branch as soon as possible. Let us keep the other two commits for the next cycle, ok?

**Comment by m-stein** [comment]
No problem.

**Comment by nfeske** [comment]
After updating master today, I merged your two verbosity commits to staging.

**Comment by m-stein** [comment]
There are still problems on some platforms. I leave the issue open and look deeper into the problems tomorrow.

**Comment by chelmuth** [comment]
As this issue misses a description: What's the issue about and what's the current state?

**Comment by m-stein** [comment]
Hm, there are still 5 platforms on which the nic_router test fails. I think the last time I investigated, the problems were related to vfs/socket stuff and not to the test or the nic_router itself. I don't know if this is still the case but maybe we should move this to a dedicated issue?

**Comment by chelmuth** [comment]
I agree that the issues are most certainly not related to the nic_router implementation and, therefore, close this collection basket in favor of potential concrete future issues.
