### ISSUE TITLE
trace: initialize trace control in Thread::start

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2901]

**Comment by m-stein** [comment]
Should fix all current fails with the trace_logger test:
da53f08 trace: initialize trace control in Thread::start

**Comment by nfeske** [comment]
Cool! Merged to staging and crossing fingers. :-)

**Comment by nfeske** [comment]
Unfortunately, many trace_logger tests are still failing.

**Comment by m-stein** [comment]
Sorry for that, I tested first and beautified afterwards, thereby removing the generic code without noticing that there are platform-specific versions of base/thread_start.cc . This time, I tested right before pushing:
cd1ac98 fixup "trace: initialize trace control in Thread::start"

**Comment by nfeske** [comment]
Thanks for the fixup. Merged to staging.
