### ISSUE TITLE
Add vfs file size detection to ROM modules 

### ISSUE THREAD

**Issue by ValiValpas** [genodelabs/genode#2903]
Due to the fact that a ROM's size is given by its dataspace (and not the actual content), mounting a ROM into the vfs inevitably leads to an inflated file.

As ROMs typically contain strings. I suggest to let the `Vfs::Rom_file_system` detect the 0-termination to calculate the file size if `binary="no"` is added to the vfs config, e.g.:

`<vfs>
   <rom name="foobar" binary="no" />
</vfs>
`

Do you think this is a useful addition?

**Comment by ValiValpas** [comment]
Great. What do you think about the referenced commit?

**Comment by ValiValpas** [comment]
Nice.

What default do you prefer? If true, the previous behaviour remains unchanged if the binary attribute is not specified in the config.

**Comment by nfeske** [comment]
The default should be true. I was a bit sloppy in my sketch. Thanks for pointing this out.

**Comment by ValiValpas** [comment]
@nfeske Thanks for you quick feedback and your cool suggestions. I just pushed a fixup.

**Comment by nfeske** [comment]
Very nice! I just added both commits as a single one to staging.
