### ISSUE TITLE
os: file system stress test

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2905]

**Comment by m-stein** [comment]
I had a look at the following candidates for a port:
* genio/doio
* bonnie++
* I read about fs tests with netperf but didn't found much
* iozone

I tend to give bonnie++ a try as source code and build system not seem complex to me, it's GPLv2 licensed, and it seems to be actively used and maintained.

**Comment by ehmry** [comment]
I did this a year ago with IOzone, see #2905. From this experience I decided it would be better to record a trace of actual file-system activity and play it back without any pauses between operations, but didn't complete the trace or playback component.

**Comment by chelmuth** [comment]
> I read about fs tests with netperf but didn't found much

I think you're referring to *netbench* which seems to be a commercial product. But there is (dbench)[https://www.systutorials.com/docs/linux/man/1-dbench/] which simulates a netbench run. I doubt this dusty *file-server* scenario is of much use for your stress test, so suggest to ignore it.

**Comment by cnuke** [comment]
There is also [xfstests](https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git).

**Comment by nfeske** [comment]
The topic has become stale. There is no plan to pick it up in the foreseeable future. Hence, I'm closing it.
