### ISSUE TITLE
VFS initial population

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2906]
If the VFS were populated in a manner similar to the `ram_fs` server, this would allow `ram_fs` to be replaced with the `vfs` server. It may be easier to understand and implement than the COW plugin as well.

**Comment by ehmry** [comment]
@nfeske I have an initial implementation on my `issue2906_vfs_init` branch. See d8ef5adf83c2f209eb3c683f0399f6d35c6a5e9e and f916dca2f994e7b998c767b74ef8c8e7ee08b616.

**Comment by chelmuth** [comment]
That looks pretty handy to me. I have one question only: Did you already set on the name *init*? It sounds pretty generic in my ears.

**Comment by ehmry** [comment]
I'm not attached to the name, but I think the name should not imply that this is something that you can look into and find things, because this is the first completely empty plugin.

**Comment by nfeske** [comment]
@chelmuth I can see your point about the term `<init>` as it is not immediately clear that it actually refers to the content instead of another aspect of the VFS initialization procedure. In the ram_fs, we called the node `<content>`. But this does not fit too well either because in most cases, the content of the VFS comes from mounted `<fs>` sessions (which was not the case for the ram_fs).

How about naming the plugin after what it actually does: `<copy>`?

**Comment by nfeske** [comment]
Another idea would be `<import>`, which already implies the direction of the copy.

**Comment by ehmry** [comment]
Rebased on my `issue2906_vfs_init` branch, see `1fe04c42013d04539a05cc3d886736a4977be933` and `a34f0e6f360c085608d091c0ac1bc4021b187237`. Next step is to add symlink support to the Vfs::Directory utility and get the TAR plugin to clean up after itself when destructed.

**Comment by nfeske** [comment]
Thanks Emery!

**Comment by nfeske** [comment]
Are you ok with the fixup 911e3fcf37ec5723dcf401b7c0056f0299bf02a4?

**Comment by ehmry** [comment]
Thanks for the recipe, I have another patch for symlink support at 1ddd7315aad6553179f56274874fefe1dae15e13.

**Comment by ehmry** [comment]
Make that bc769559acf3906e9b64cff1f7d955afa5aa30a5.

**Comment by ehmry** [comment]
@cnuke I have a fixup commit for staging at ac95f41b6b5b10038d724bea9d3dd7b4e8fee253, this adds an VFS import plugin test to autopilot.

**Comment by cnuke** [comment]
@ehmry merged, thanks.
