### ISSUE TITLE
fs_report: support verbose flag

### ISSUE THREAD

**Issue by throwException** [genodelabs/genode#2917]
To debug sculpt it's useful to get logs of submitted reports.

**Comment by nfeske** [comment]
Even though I'm intensively developing Sculpt, I haven't had a use case for this feature yet.

Whenever I'm interested in the reports generated by components, I'm either using the `verbose` option of the report-rom server, or I'm looking interactively at Sculpt's report file system (via the inspect window).

@throwException If you can life without this feature, I'd prefer to close this issue.
