### ISSUE TITLE
okl4: elfweaver tool missing when executing run script which uses depot packages

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2918]
When executing a run script which uses depot packages (for example run/wm) for OKL4 in a clean build directory, the 'elfweaver' tool is missing:

```
...
genode build completed
checking configuration syntax
  CHECK init
using 'core-okl4.o' as 'core.o'
couldn't execute "./tool/okl4/elfweaver": no such file or directory
    while executing
"exec "./tool/okl4/elfweaver" merge --output "[run_dir]/image.elf" "[run_dir].weaver.xml""
    (procedure "run_boot_dir" line 35)
...
```

As a workaround until this problem gets fixed, a run script which does not use depot packages, like 'run/log' can be executed first to get the 'elfweaver' tool built.

**Comment by chelmuth** [comment]
Addressed by a fix in #3329
