### ISSUE TITLE
acpica port: update to version 2018-08-10

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2935]

**Comment by nfeske** [comment]
On my x260, the new version of acpica gives the following error:

```
[runtime -> acpica] Error: AcpiOsReadPciConfiguration unknown device - segment=0 bdf=00:1f.4  reg=0xe width=0x8
[runtime -> acpica] Error: AcpiOsDeleteSemaphore:128 called - dead
```

**Comment by chelmuth** [comment]
From the background of the error above it may be worthwhile to investigate ACPI_SINGLE_THREADED, which has a pretty simple implementation in osunixxf.c for semaphores.

**Comment by m-stein** [comment]
I'll try this, thanks for the hint.

**Comment by alex-ab** [comment]
Seems reasonable, ack.

**Comment by m-stein** [comment]
:+1:

**Comment by alex-ab** [comment]
@chelmuth: the AcpiOsDeleteSemaphore fix did not get to the release somehow

**Comment by chelmuth** [comment]
This is because I did not commit it. I just created the patch for discussion, sorry for the confusion.

**Comment by alex-ab** [comment]
Please add d73ee020c06b016b83a7dd77e1db1343d53c55e5 to staging, which fixes the reported regression and another one happening on "poweroff". 
@nfeske: Please consider 9806e50f142c83274f7960230c7a12f0d63e0dcb (or similiar) for sculpt, to enable (ease) the poweroff/reset support
