### ISSUE TITLE
move Shared_pointer from noux to os or base

### ISSUE THREAD

**Issue by NobodyIII** [genodelabs/genode#2940]
Noux has a Shared_pointer implementation that has no apparent noux dependencies. This would be useful outside of noux, especially given its support for Genode allocators. Shouldn't this be moved to either os or base?

**Comment by nfeske** [comment]
The shared pointer does not qualify for the official API. Therefore it remained local to noux. Please refer to the comments https://github.com/genodelabs/genode/issues/2898#issuecomment-401778923 and https://github.com/genodelabs/genode/issues/2868#issuecomment-397605000 for the reasoning.

If you need a shared pointer, I recommend using a broadly used implementation, or - if you really really want to use my one - keep a copy of the corresponding header local to your component.

You may also reconsider using a shared pointer in the first place. A shared pointer is useful only in situations where the ownership of a dynamically allocated object is uncertain. But why should that be? There are very few situations where this uncertainty cannot be avoided.

I would appreciate you closing the issue.
