### ISSUE TITLE
rtc_drv: wrong binary taken for Linux or Microkernel on x86

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2951]
When using the same build directory, e.g. build/x86_64, for KERNEL=linux and KERNEL=some_micro_kernel, the rtc_drv will be not rebuild in all situations. This may lead to the issue that on Linux the rtc_drv, build for native x86, tries to open IO_PORT session, which ultimately fails.

**Comment by chelmuth** [comment]
Prior discussions lead us to the follow procedure.
1. Rename the drivers appropriately, e.g. *x86_rtc_drv* and *linux_rtc_drv*.
2. Use depot packages containing appropriate drivers for the selected platform in run scripts.

**Comment by chelmuth** [comment]
This issue is closely related to #2190 and #2403.

**Comment by alex-ab** [comment]
Does 0c6cca72faf5f53245f94e14cc78f72fdd7c5dcf qualify ?

**Comment by chelmuth** [comment]
That's unfortunately the wrong direction as the *binary_name* run-script mechanism should not be scaled to more drivers.

**Comment by jklmnn** [comment]
> Prior discussions lead us to the follow procedure.
> 
>     1. Rename the drivers appropriately, e.g. _x86_rtc_drv_ and _linux_rtc_drv_.
> 
>     2. Use depot packages containing appropriate drivers for the selected platform in run scripts.

I'd prefer the first variant since it allows to specifically use use the `x86_rtc_drv` with #2829. Otherwise one needs to patch out the Linux specific parts.

**Comment by chelmuth** [comment]
I'm afraid you got me wrong, 1) and 2) are steps of one procedure. Unfortunately, my patch is only half-baked and still needs some fixes.

**Comment by jklmnn** [comment]
Oh, well that would still solve the problem since I would be able to select the correct driver manually without needing to patch it.

**Comment by chelmuth** [comment]
@skalk your work to release 19.05 fixes this issue, right?

**Comment by skalk** [comment]
Now, Linux driver is named `linux_rtc_drv`, but the x86 native driver is still named `rtc_drv`. So, yes the drivers are named unambigously and can be build independently in the same build directory.

**Comment by skalk** [comment]
That being said, there is no package refering the rtc_drv component.

**Comment by chelmuth** [comment]
So, we should finish the renaming for *x86_rtc_drv* too.

**Comment by skalk** [comment]
I did not do this in the past to not break run-scripts outside without a need, now that there are no name clashes anymore. BTW. the same applies to, e.g., usb_drv.

**Comment by nfeske** [comment]
I'm with Stefan here. The name rtc_drv and usb_drv is fine with the background that the x86 versions are the most commonly used ones (used across all PCs including AMD and Intel).

**Comment by chelmuth** [comment]
Under these circumstances... I close the issue as fixed.
