### ISSUE TITLE
No compile-time checks for fs::File_io_service::Insufficient_buffer handling

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2954]
The VFS import pluging does not handle the `Vfs::File_io_service::Insufficient_buffer` exception thrown by the `File_system` client when the packet buffer congests with write packets. I would prefer to replace this exception with an error value, but I'm not familiar with the history of the exception.

**Comment by ehmry** [comment]
Fix at 4a81139a02a9af8a52a2ac77be0806f514def5c5.

**Comment by ehmry** [comment]
Disregard this fix, there is also a problem with selecting write buffer sizes here.

**Comment by nfeske** [comment]
BTW, I was wondering why your patch blocks for exactly one signal in the exception case.

**Comment by ehmry** [comment]
There is a loop, so its a block and retry.

**Comment by ehmry** [comment]
I have a rather massive patch at 7ad04e63969f0ebe23a3eb3fac34008bd9452bcc as discussed offline. This cleans up the errors and exceptions, as well as some of the VFS server packet handling.

**Comment by ehmry** [comment]
Rebased at 0fe3c6747962f2abc748c6621bb7706584330cd3 with the addition of a `WRITE_OVERSIZED` error to fix #2971.

**Comment by chelmuth** [comment]
With commit 5d7b8321e6e082d980d4d41689639fad67cf3a46 I get

```
repos/libports/src/lib/libc/vfs_plugin.cc:463:9: warning: enumeration value ‘WRITE_OVERSIZED’ not handled in switch [-Wswitch]
```

**Comment by ehmry** [comment]
@chelmuth fixup for that and libc_noux at 354a6b1b2ec685fe6c312b850e664a1f7327b6d9.

**Comment by ehmry** [comment]
@chelmuth and an lwip fixup at 53d687786baa88d2f809d1717d7bd51ecddc0a0b.

**Comment by chelmuth** [comment]
Another issue where I'm not sure about the state.

**Comment by ehmry** [comment]
If we want to remove the `Insufficient_buffer` exception from the VFS, this is the issue to work from.

**Comment by nfeske** [comment]
The topic has become stale.
