### ISSUE TITLE
Remove noux/net

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2955]
Noux networking was not well tested and not in practical use. Remove noux/net would also get us closer to removing `lwip_legacy` and `alarm` libraries.

**Comment by ehmry** [comment]
Fix at ab578a5f8bce27ae770eb8bdadeabdb225ae59e5.

**Comment by cnuke** [comment]
@chelmuth please merge to staging (fixes building noux and remove noux/net related ports).
