### ISSUE TITLE
intel_fb.run: problem with docking station and external monitor

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2956]
There may be problems with the intel_fb test with external monitors at laptops with docking stations. Normally, when a docking station is plugged in or out, one of the display interfaces of the laptop has to be switched between the external ports of the laptop itself and those of the docking station. This may be the responsibility of the ACPI depending on the hardware.

**Comment by nfeske** [comment]
@m-stein you labeled this issue as bug. It would be nice to name the issue after the problem/symptom you observe and add a brief description.

**Comment by m-stein** [comment]
This commit is a quickfix for the problem:
0cc2a4520d9ce8874066142ae1c6ac9561acfc34 intel_fb.run: add acpica and poll

However, with this commit it is still necessary to let the intel_fb poll as there is yet no communication between ACPICA and intel_fb about DS state changes. Furthermore, it is known that the test sometimes hangs for half a minute when the DS state changes but it returns to normal operation afterwards.

**Comment by nfeske** [comment]
@m-stein is now the time to finally merge this commit? I'm uncertain.

**Comment by m-stein** [comment]
I'm so much out of this topic now that I cannot say what are the implications of this commit. Unfortunately the affected run script doesn't seem to be tested regularly. Maybe @alex-ab can help out here?

**Comment by alex-ab** [comment]
I also can't say anything about the implications. It is up to you @m-stein, who worked at the topic intensively.

**Comment by m-stein** [comment]
> I also can't say anything about the implications.
Thanks for the quick feedback.

> who worked at the topic intensively.
Sorry, didn't mean to bother you.

@nfeske I think we shouldn't merge the workaround as it targets a use case that we don't test regularly while it adds overhead (polling) and strange behavior (freezes).

**Comment by nfeske** [comment]
Ok, I will close this issue then.
