### ISSUE TITLE
Remove legacy lwIP libraries

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2958]
Now that the lwIP VFS plugin has been released, I think it is time to drop the old lwIP libc plugins.

**Comment by ehmry** [comment]
Initial patch at 216d4566e1118096def55734f75180525d897440. I've pruned what I could find, and would like to see what the nightly tests report about the rest.

**Comment by ehmry** [comment]
I was overzealous and wipe out an extra makefile, see d035bee8ee78eab89857aa9248b1ccd30c3d6877.

**Comment by chelmuth** [comment]
Ah I see, thanks.

**Comment by ehmry** [comment]
Fixup for tcp_terminal at 1a0f4b93c2dac18b9c908afe20ddfee7b64719da.
