### ISSUE TITLE
Convert Lxip to timeout framework

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2961]

**Comment by ehmry** [comment]
Fixed at 621036e3b2b926ef0cb47d10bb92381e90d954d1.

**Comment by chelmuth** [comment]
AFAICT this cleanup makes much sense but did not make it into staging. @ehmry could you please rebase it and leave a note here?

**Comment by ehmry** [comment]
Yes, rebased at 94ded60349687e4604621e5a398b744090c23807.
