### ISSUE TITLE
sculpt: LwIP socket_fs package

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2983]
I am starting to run native services that I connect to from my VM and it is nice to have them available at single IP address on different ports.

**Comment by ehmry** [comment]
Fix at 603a01f0db0ecd3179d7cbcee28013f506253e9e

**Comment by nfeske** [comment]
I'd defer the inclusion until there is an actual use case for Sculpt users, e.g., a launcher of a service that depends on it. Otherwise, people may wonder what the menu entry is about and we cannot give an easy explanation.

**Comment by ehmry** [comment]
Agreed, I have not been using this package.
