### ISSUE TITLE
Simple bulk TCP test

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2989]
We need a test for bulk TCP transfers that is simple to understand.

**Comment by ehmry** [comment]
New test for Lxip and Lwip at `issue2989_bulk_tcp`. On staging Lxip works, Lwip chokes when the send buffer is full.

**Comment by chelmuth** [comment]
Merged to staging but I get strange behavior when the test components are about to finish. For example with `KERNEL=linux`

```
[init -> recv] close client
[init -> recv] Illegal instruction (signum=4), see Linux kernel log for details
```

or

```
[init -> send] close server
[init -> send] Segmentation fault (signum=11), see Linux kernel log for details
```
