### ISSUE TITLE
Libc: close all open VFS handles at exit

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2996]
When a libc application is closed, the libc runtime is more-or-less immediately halted and freed. This may cause unexpected behavior for data that is buffered in the VFS. Writes to disk are safe, but TCP packets may be lost and un-acked when the Nic packet buffer is removed.

Closing all open handles should solve most of these issues, should close implicitly flush handles.

**Comment by ehmry** [comment]
Ref #2989

**Comment by ehmry** [comment]
I have two patches to implement this on my `issue2996_close_on_exit` branch.

**Comment by ehmry** [comment]
Rebased against staging with cleaner patch to `Allocator_avl`. I am unsure of the implications of this patch, but this replicates behavior added to Noux as part of #2919.

**Comment by chelmuth** [comment]
I wonder if this may interfere with code using atexit() with functions accessing file descriptors. Does libc close file descriptors explicitly before exiting the program? Does it use a final atexit functions for this purpose?

**Comment by ehmry** [comment]
I expect that it would in some cases, and the solution would be to maintain the list of `atexit` functions within the libc to call before cleanup rather than outsource it to `genode_atexit` as it is done in `repos/libports/src/lib/libc/atexit.cc`.

**Comment by ehmry** [comment]
@chelmuth I have a patch at c9340b516247b65eb37fe7fadd99b52bb7231dba to revert this until the libc atexit handlers can be called before close everything.

**Comment by nfeske** [comment]
Fixed by cd92b326220f1839a0885ad3d1f253ec3b3cbd18 in master.
