### ISSUE TITLE
qt5: cleanly handle case where close event is ignored

### ISSUE THREAD

**Issue by NobodyIII** [genodelabs/genode#2997]
When the close button is clicked on a Qt5 window, its application may choose to ignore the close event, e.g. when a file has been modified but not saved. Currently, when this happens on Genode, the window will remain open, but will become unresponsive, because Qt attempts to resize the window to 0x0.

I have fixed this with commit b74ebdc2b9541ec1a2238ff5767d7ee00d2f44c1.

**Comment by NobodyIII** [comment]
Is there anything that needs to be fixed with this commit, or anything I can do to help get this bugfix merged faster?

**Comment by chelmuth** [comment]
Until the window seems to be closed forcefully because of the some historical policy. As I'm not fully sure about this policy I'd like to to ask @cproc and @nfeske to shed some light on this.

**Comment by NobodyIII** [comment]
Sounds good. Thanks for reviewing and merging my commit.
