### ISSUE TITLE
Nitpicker: handle global background if destroyed (was mantis id 29)

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3]
Currently, a global background can be assigned by a client. This way, the backdrop program can supply a background image. However, there is no proper handling of the case that this session gets closed. Right now, it never happens (for backdrop started by init) but in general, this should be fixed.

**Comment by alex-ab** [comment]
@nfeske: is still valid ?

**Comment by nfeske** [comment]
Yes. Mea culpa! ;-) Let's keep it open.
