### ISSUE TITLE
base: support to place Entrypoint on specific cpu

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3008]

**Comment by nfeske** [comment]
This looks good. Maybe we can do without the default argument? Since we almost never create `Entrypoint` objects manually, there should only be very few places to adjust.

**Comment by alex-ab** [comment]
I see. I will lookup all places and change the commit accordingly.

**Comment by alex-ab** [comment]
I hope I found all places - 671458ddc51933f32adcda33abd8faede5395575.
