### ISSUE TITLE
Error with VirtualBox OVA

### ISSUE THREAD

**Issue by chicagskivolk** [genodelabs/genode#3010]
Hello!

I have the following error when I try to run the VirtualBox appliance:
```
RawFile#0 failed to create the raw output file log.txt (VERR_ACCESS_DENIED).

Result Code: | NS_ERROR_FAILURE (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}
```

Running this on the latest version of virtualbox on macOS. Haven't tried on any other systems yet.

**Comment by alex-ab** [comment]
Please disable the Checkbox "Enable Serial Port" in the Settings->Serial Ports.

**Comment by alex-ab** [comment]
Please reopen if needed.
