### ISSUE TITLE
Debug: text console in grub on nova causes boot loop

### ISSUE THREAD

**Issue by jklmnn** [genodelabs/genode#3013]
When I enable the text console in Grub2 with Nova, I get stuck in a boot loop. Bender boots but Nova seems to crash and then reboots. This happens also without bender.

This can be reproduced by applying https://github.com/genodelabs/genode/commit/1ae2e1c7c1ac13b574762da7ce0498d82aff6048 to master (as in #2880) and running e.g. run/log on Nova.

**Comment by jklmnn** [comment]
This issue has been introduced with https://github.com/genodelabs/genode/commit/3824ad47566fe4331453585ed3db03fa0706cf9f.

**Comment by alex-ab** [comment]
Thanks for reporting. Please try c66408d0d7a5e982e7d5b7e44b76ff1706af1650

**Comment by jklmnn** [comment]
That fixes it.

**Comment by chelmuth** [comment]
Is c66408d the aspired fix?

**Comment by alex-ab** [comment]
No, please use 1c569534776277bb10afea4ef7b0672565b3ba40 which is adjusted to apply for staging - thx.
