### ISSUE TITLE
gems: add interactive SSH Terminal component

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#3014]

**Comment by chelmuth** [comment]
Despite the fixed label your topic branch looks funny. Which commits should I pick?

**Comment by chelmuth** [comment]
Argh, and please reshuffle the update commits with _libssh: add async event bind patch_ because it produces merge conflicts.

**Comment by cnuke** [comment]
@chelmuth please merge 0ace2ab to staging.
