### ISSUE TITLE
trace buffer entries are not aligned sufficiently

### ISSUE THREAD

**Issue by ValiValpas** [genodelabs/genode#3015]
I stumbled upon an alignment issue with the trace buffer. I have trace events with a constant size of 0x24. Occasionally, my trace_logger reads a size of 0x2400 for the first entry in the buffer. Only after the buffer wrapped, the correct size may be read (or stays the same). Aligning the buffer entries to an 8-byte boundary seems to fix this issue on Cortex-A9. Commit will be available soon.

**Comment by chelmuth** [comment]
This may be related to @skalk's current investigations regarding cache and other low-level configuration issues.

**Comment by nfeske** [comment]
Fixed in master.
