### ISSUE TITLE
dde_linux: improper input event handling semantics 

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#3019]
The Linux input subsystem reports events (to evdev) in a stream augmented by EV_SYN events. I did not find any precise documentation of the semantics but assume input state transitions are finished at those points in the stream only. I take the implementation of the pointer emulation for touch devices as strong indicator because it reports the button before updated absolute coordinates followed by an EV_SYN event.

**Comment by nfeske** [comment]
Let's revive this issue once we work again on USB-touchscreen support.
