### ISSUE TITLE
VFS: add modification time, access time, and executable bit

### ISSUE THREAD

**Issue by NobodyIII** [genodelabs/genode#3030]
As I mentioned in issue #3029, file/directory modification time is used by some programs (e.g. Git, Qt5CT) to determine whether a file has been modified. I propose adding this information, along with the access time and the executable bit, to the VFS interface (in Vfs::Directory_service::Stat). After that, it will be easy to add it to libc's VFS plugin. In order to add it to the VFS server, it also needs to be added to the File_system RPC interface. (Issue #3029)

**Comment by nfeske** [comment]
Fixed in master.
