### ISSUE TITLE
Sculpt Terminal session routing

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3034]
A `<provides> <terminal/> </provides>` specification is not applied from package runtime descriptions to the deploy runtime.

**Comment by ehmry** [comment]
Ref https://github.com/genodelabs/genode-world/pull/120

**Comment by ehmry** [comment]
A simple fix at 1c490ac8faa9b1c23e28ab7e4108ffddd1013377, it builds but I haven't tested it.

**Comment by nfeske** [comment]
Looks good to me.

**Comment by nfeske** [comment]
Merged to staging
