### ISSUE TITLE
lwIP 2.1.1 released

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3035]
https://savannah.nongnu.org/forum/forum.php?forum_id=9285

**Comment by ehmry** [comment]
Fix at 1d290eb0692b61fab79262b26dbc5aef5e8a5b6d.

**Comment by ehmry** [comment]
Time to upgrade to 2.1.2, https://savannah.nongnu.org/forum/forum.php?forum_id=9299

> all users of 2.1.0 or 2.1.1 are strongly suggested to upgrade! 

See e90042cfd5378bbfbd5e0992410f1a8433362737.

**Comment by nfeske** [comment]
@ehmry's commit staccato continues. Merged to staging.
