### ISSUE TITLE
nic_bridge: fixed MAC addresses

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#3040]
Enable configuration of a fixed MAC address for each client.

**Comment by m-stein** [comment]
Fixed:
48b61f9 nic_bridge: fixed MAC addresses

@cnuke I'm curious whether your setup now works.

**Comment by cnuke** [comment]
@m-stein thanks for the commit, I'll keep you posted.

**Comment by chelmuth** [comment]
The commit above breaks the `netperf_l*ip_bridge` tests. @m-stein please investigate.

**Comment by chelmuth** [comment]
Reopen because of 

> The commit above breaks the `netperf_l*ip_bridge` tests. @m-stein please investigate.

**Comment by m-stein** [comment]
I'm at it.

**Comment by m-stein** [comment]
As fixup or selfstanding commit (see commit message):
9c5a967 Fixup "nic_bridge: fixed MAC addresses" (bug when policy missing)

**Comment by nfeske** [comment]
I just stumbled upon this issue and see that the patch hasn't been merged yet. I'm wondering, is it related to the noise created by the nic_bridge in our nightly tests?

Now looking at the patch with the background of the API renovation, I propose to change it in the following ways:

* We should demand the definition of a policy. If the user explicitly does not want to express a policy, an empty `<default-policy/>` should be provided. With this in place, the `Session_policy` constructor is never supposed to throw in the good case (when the session becomes established). The exception of the said constructor should not be handled inside the `_create_session` method. It is handled by the root component (`Service_denied`) already. This simplifies the code of the `_create_session` method.
* The `mac` should be obtained from the policy by using `Xml_node::attribute_value`, which alleviates the need to catch any `Nonexistent_attribute` exception.

**Comment by chelmuth** [comment]
Isn't the patch merged as 82ded858aae8ca2e13354baa774b9617feccbec3 ?

**Comment by nfeske** [comment]
Ok, than I have completely missed the picture. Sorry.

**Comment by m-stein** [comment]
@nfeske Your suggestions are something that was already on my todo list. I'll apply them now.

**Comment by m-stein** [comment]
How about this:
4ef7caf511 nic_bridge: simplified session request handling
?

**Comment by nfeske** [comment]
@m-stein I like it! It looks much more logical now. Thanks for the overhaul.

**Comment by nfeske** [comment]
@m-stein I merged your commit to staging.

**Comment by m-stein** [comment]
Thanks.

**Comment by nfeske** [comment]
The patch went to master. Unfortunately, there are still several run-script adjustments outstanding. @chelmuth is investigating...
