### ISSUE TITLE
smp: add a test to detect TLB maintainance failures

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3041]
Recently, I observed that base-hw on x86_64 doesn't do a cross cpu-core TLB shootdown. Sadly, we do not detect such problems until now. Therefore, I'd like to add a corresponding test.

**Comment by tomga** [comment]
In 36fe50ebadece03ae3d3e0f831dab80ba56fe6f7 affinity test was merged to smp, but repos/base/run/affinity.run left. I found that when I tried to run this test.

**Comment by chelmuth** [comment]
Thanks for the hint, I removed the run script with f79ebd2ad0d442062432e1ad455fe202ea118d07.
