### ISSUE TITLE
test/rm_nested: uncaught exception

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#3045]
There's an uncaught exception ``Signal_receiver::Context_not_associated`` that is thrown because in ``Component::construct`` the test does something like:

1. create entrypoint ``ep``
2. create signal handler ``sigh``, thereby binding it to ``ep``
3. manually call ``ep.dissolve(sigh);``
4. destruct ``sigh``, the destructor unconditionally calls ``ep.dissolve(sigh);``, throws exception

The manual call to ``dissolve`` is not expected neither by ``Signal_handler`` nor by ``Entrypoint``. So, we can either remove the manual call to ``dissolve`` (the test works without and I don't know what was the reason for doing it in the first place), introduce a ``catch`` statement in the implementation of``Signal_handler`` or ``Entrypoint``, or replace the ``throw`` statement with a warning/error.

**Comment by m-stein** [comment]
Any opinion?

**Comment by nfeske** [comment]
The dissolve is a legacy from a time when signal contexts were managed manually. The modern `Signal_handler` alleviates the need for manually dissolving the handler. Hence, I'd consider the manual call of `dissolve` as a bug. Let's just remove the call.

**Comment by m-stein** [comment]
Ok, thanks for the explanation :)

**Comment by m-stein** [comment]
Fixed:
a295a19 test/rm_nested: fix EP double dissolve
