### ISSUE TITLE
vfs:  implement 'complete_sync()' in Single_file_system

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3047]
Currently, ```Log_file_system::complete_sync()``` assumes that the given ```Vfs_handle``` pointer is a ```Log_vfs_handle``` pointer, but it can also be a ```Single_vfs_dir_handle``` pointer (for the "/" directory). I moved the ```complete_sync()``` implementation into the ```Single_file_system``` to have ```Log_vfs_handle::sync()``` be called for file handles only. There's currently no implementation for syncing the "/" directory (all open files).

**Comment by nfeske** [comment]
Merged to staging.
