### ISSUE TITLE
Libc: use strictly typed Microseconds for timeouts

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3050]
I did an audit of `select` these past few days and it stood out to me that timeout durations are passed internally as `unsigned long` values in miliseconds. I propose to use the `Genode::Microseconds` class instead for the sake of readability and type checks.

**Comment by ehmry** [comment]
Implemented with ff5c0c93c520f0f96ac2a70605ca7469ff9eb95b and 714043bd322739db64e350a517612ec2ed3ddd82.

**Comment by chelmuth** [comment]
This commit breaks `run/fetchurl_lwip` on sel4 at least. I conducted no further investigation but reverting just this one commit rendered the test successful again. I discovered only one suspicious line in the log of `fetchurl_lxip`, which also needs cleanup of the `us us`.

```
[init -> fetchurl] Warning: libc: limiting exceeding timeout of 5000 us us to maximum of 4294 us us
```

**Comment by chelmuth** [comment]
@ehmry good question after all those month. I'd assume there some upper bound in the libc itself or the base lib I liked to comply with.

**Comment by chelmuth** [comment]
No, it's the mere maximum of microsends that fits into `unsigned long` https://github.com/genodelabs/genode/blob/master/repos/libports/src/lib/libc/task.cc#L230-L233

**Comment by ehmry** [comment]
I have a new patch to implement this at 4554a9347e023354c9e9a61957fa5d63def91ee1, the former patch was expiring timeouts too early.
