### ISSUE TITLE
Merge pthread library into libc

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3054]
Pthreads can be merged into the libc without affecting the semantics of either.

**Comment by ehmry** [comment]
Patch at 1ac972a8888e70f66e8ee79f445810aa8fff3aaf.

**Comment by NobodyIII** [comment]
My understanding is that pthread is a separate library because Noux doesn't support multithreading within a single process.

**Comment by ehmry** [comment]
Noux is working ok, Vbox needs a bit of massaging.

**Comment by ehmry** [comment]
I have a fixup for Virtualbox at 465d024fa231f2d605ee6e32e0fcb7444a795c23 on my `issue3054_pthread` branch, the package builds but I do not have time to test it at runtime today.

**Comment by ehmry** [comment]
Commit 4faaef2bea93ed5ecf97718fd135e95c6a041ccf restores patches to libc, which are still necessary.

**Comment by nfeske** [comment]
Merged to staging.

**Comment by ehmry** [comment]
@nfeske fixup for libports at 5544bea1166848f847de04e7c410b2406a457c56
