### ISSUE TITLE
chroot: configure both root prefix and auto-prefixing

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3056]

**Comment by NobodyIII** [comment]
Please describe what you envision here.

**Comment by ehmry** [comment]
@NobodyIII Just to allow the `chroot` server to be configured to apply an explicit root path as well as apply the label-to-path conversion.

Fixed at 9aa55bd5aa908643774d91fff6ea18bb7e1db3b6

**Comment by NobodyIII** [comment]
Okay, that's what I was suspecting. Thanks. I'll probably use this in the
near future.
