### ISSUE TITLE
jdk: move to Genode world

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#3060]
* remove JDK from Genode main
* add JDK to Genode world
* enable compiler back end on arm/x86_64 platforms

See also: genodelabs/genode-world#123

**Comment by nfeske** [comment]
Merged to staging. Btw, what was your intention behind labeling the issue as "rejected"?

**Comment by ssumpf** [comment]
@nfeske: There was simply no right label that said "move to world" or "does not belong here". So I figured to "reject" it here and "feature" it in world. Maybe we can add a label for these cases, which will not be very common of course.

**Comment by nfeske** [comment]
Alright. I think the label "cleanup" may be alright in this case. In contrast, the "reject" label is really meant for issues that we won't consider (it refers to the issue itself, not the content of the issue).
