### ISSUE TITLE
hw: noux_tool_chain_auto test hangs

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3063]
At least on x86_64, the test hangs sooner or later. Commit https://github.com/cproc/genode/commit/779017e145cf2912337f4ea2098a64409c78e780 adds debug messages regarding signal context destruction and when the test hangs, the last messages usually look like:

```
...
[init -> noux] Signal_receiver::_platform_begin_dissolve()
_call_kill_signal_context()
_call_kill_signal_context() finished
[init -> noux] Signal_receiver::_platform_begin_dissolve() finished
[init -> noux] Signal_receiver::_platform_begin_dissolve()
_call_kill_signal_context()
_call_kill_signal_context() finished
```

So it looks like the syscall is finished, but Noux does not continue.

**Comment by skalk** [comment]
@cproc thank you for sharing your investigations, I will have a look into this

**Comment by alex-ab** [comment]
In issue #2873 is a duplicate now of this, and #2873 already contained some analysis by @cproc. Maybe this is helpful.

**Comment by skalk** [comment]
Ok, I've found the problem. Within the combination of base-common and base-hw userland signal base library. The thread which tries to dissolve a Signal_context locks it. Then it call the kernel that it likes to destroy the Signal_context. The kernel will block that thread as long as there are already signals put into the UTCB of a receiver until the receiver acknowledges it. But the reciever will try to lock the context too to mark the pending signal before acknowledging anything to the kernel. Therefore, it deadlocks.
In general I would prefer to simplify the signal handling. But for the moment I see a workaround in above commit.
