### ISSUE TITLE
VFS lwIP delays outgoing TCP

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3067]
The lwIP plugin is queing data from the application but not actually sending it until the next periodic timer event. This behavior was introduced in 3e31e2ba53ee25dcd8f9781e7b9f0a2c7c7be371 when I removed calls to `tcp_out`. I made this change to fix some intermittent page faults in lwIP, but I suspect now that the original problem was calling `tcp_out` with no data queued. To send data over TCP one first calls `tcp_write` to queue data and then `tcp_output` to send it. This is to gather small writes into more reasonably sized packets. If `tcp_output` is not called a packet is sent on the next timeout, so it may seem that `tcp_output` is optional.

**Comment by nfeske** [comment]
Is this related to the 9p throughput issue you investigated in #3057?

**Comment by ehmry** [comment]
Fix at ae9d34838337ebdc08136bf2a5da2d794d0414e3.

**Comment by ehmry** [comment]
@nfeske, yes, because 9P is a request-response protocol the delay was the source of the problem.
