### ISSUE TITLE
OPENDIR_ERR_NODE_ALREADY_EXISTS does not propagate

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3083]
Applications that use the libc may have difficutly creating directories becasue the `Dir_file_system` does not return `OPENDIR_ERR_NODE_ALREADY_EXISTS` in the event that a directory already exists.

**Comment by ehmry** [comment]
Fix at 8b7bdb5c4a5a901d42a39e7f77c1168ae0c320a7.

**Comment by ehmry** [comment]
This is still a problem, code that tries to create directories from the root to the destination fail.  Rebased patch at d048cdd09b1931fa966a3489badf042eee9c0620.

**Comment by alex-ab** [comment]
Set the label of this issue to "Fixed", so that it is possibly picked up next time.

**Comment by ehmry** [comment]
I cannot label, I can only open and close my issues.
