### ISSUE TITLE
sel4: test-libc always fails

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3086]
Due to the big amount of RAM used by the libc test to stress malloc, this test always leads to a resource problem on all Sel4 platforms we support. Either we skip that test right now on this platform, or make the test configurable, or fix the resource problem.
To silent the jitter of the test-infrastructure I would vote for the first option in the first-place, then open up an issue to make the test-libc configurable for platforms with less resources (rpi, foc_pbxa9,...), and in the long-term fix the resource problems of Sel4. Other opinions?

**Comment by nfeske** [comment]
I agree with everything you just said.

**Comment by m-stein** [comment]
:+1:

**Comment by skalk** [comment]
For hw/rpi the RAM resources are also not enough.
