### ISSUE TITLE
hw: test-rust failed due to broken instruction-pointer

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3087]
The test for Rust failed tonight on hw/rpi due to the following page-fault:

```
[2018-12-12 03:20:44] [init -> depot_autopilot] --- Run "test-rust" (max 20 sec) ---[0m[0m

[2018-12-12 03:20:44] [init -> depot_autopilot] [0m[0m

[2018-12-12 03:20:45] [34mWarning: init -> dynamic -> test-rust -> test-rust -> ep: undefined instruction at ip=0x10000ec[0m

[2018-12-12 03:21:04] [init -> depot_autopilot] [0m[0m

[2018-12-12 03:21:04] [init -> depot_autopilot]  test-rust                       failed    19.986  timeout 20 sec[0m[0m
```

**Comment by skalk** [comment]
I could track this down to a broken test-rust binary taken out of the depot.tar by the vfs_tar plugin. THis is reproducible even when starting the depot_autopilot with that single test only.

**Comment by nfeske** [comment]
@skalk Thank you for investigating! Does that mean that the test works when you specify the TEST_BUILD and TEST_MODULES env variables (bypassing the depot for the binary)?

**Comment by skalk** [comment]
Exactly!

**Comment by m-stein** [comment]
@skalk Hm, cool that you found that, I could have a look at the package if you're not already into it!

**Comment by m-stein** [comment]
I assume I'm the one who created the mess ^^

**Comment by skalk** [comment]
Sorry, I was comparing apples with pears all the time. I was used to take the binary `test-rust` in my build directory not the one in my depot for comparision with the TAR content. But the actual point is that the binaries (first instructions text section) in between depot build directory and my directory are different. So it seems the correct content is read by the VFS TAR plugin. But the produced depot binary fails, and the non-depot binary succeeds.

**Comment by skalk** [comment]
BTW. I do not have any additional setting (e.g., OLEVEL etc.) in my build directory.

**Comment by skalk** [comment]
The rust compiler in the depot case produces an Armv7 binary:
```
readelf -A depot/genodelabs/bin/arm_v6/test-rust/2019-03-18/test-rust
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "ARM v7"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_GOT_use: GOT-indirect
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_optimization_goals: Prefer Debug
  Tag_CPU_unaligned_access: v6
  Tag_ABI_FP_16bit_format: IEEE 754
```

**Comment by skalk** [comment]
It was a bad selection expression in the `repos/libports/lib/import/import-libcore-rust.mk` file that looked for SPEC `rpi` to select armv6 and otherwise checked for SPEC `arm` and took armv7 then. In the depot package case it sets for architecture only dependent files correctly `arm` and `arm_v6`, and that rule then used armv7.

**Comment by m-stein** [comment]
Nice!
