### ISSUE TITLE
sel4: sel4_Fault_UserException

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3088]
Although, FPU is now enabled on sel4/wand_quad, we regularily observe above exception type. Possibly still an alignment issue? We see it nightly in the depot_autopilot in the following test:
* test-ada_exception
* test-ada_secondary_stack
* test-libc
* test-libc_vfs_*
* test-log
* test-stdcxx
* test-gcov

**Comment by alex-ab** [comment]
The FPU patch was not effictiv tonight, according to the log:

> [2018-12-12 06:54:08] Info: Not using supported FPU as FPU is disabled in the build configuration

**Comment by skalk** [comment]
Ok, then I resign my statement, lets wait for a second try.

**Comment by alex-ab** [comment]
6a3165f4db8d7571619f314f7510c4e8eaf74575 helps
