### ISSUE TITLE
test-libc: make RAM usage configureable

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3089]
Currently, we are not able to run this test on Raspberry Pi, Sel4 kernel, Fiasco.OC/PBXA9 and HW/i.MX53/TrustZone. Either due to limited RAM resources of the platform or due to kernel restrictions. To test it anyway, we need to be able to either configure the test parameters from outside, or by evaluating the platform info within the test, and use acceptable size parameters accordingly.

**Comment by nfeske** [comment]
With the migration of this test to the depot autopilot, this issue has become obsolete.
