### ISSUE TITLE
vfs_stress_ram test stresses some kernels

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3090]
This test produces a kernel-fault on Pistachio. It results in a seL4_Fault_userException under Sel4/x86:
```
Error: unexpected exception during fault 'seL4_Fault_UserException' - thread 'ep' in pd 'init -> dynamic -> test-vfs_stress_ram -> vfs_stress' stoppedError: Unknown fault
```
and it times out under Okl4. Interestingly all faults only occur on hardware not under Qemu.

**Comment by nfeske** [comment]
Fixed in master
