### ISSUE TITLE
socket fs: support nonblocking 'connect()'

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3113]
This feature is used by the Arora web browser (and QtNetwork in general). Some implementation details: from the libc user's perspective the connection is ready (or aborted) when ```select()``` reports that the socket is ready for writing. This information request is mapped to the ```read_ready()``` function in the VFS, since there is no ```write_ready()``` function and the read-readiness information has not been of interest during the connecting phase so far. When the 'connect' file is ready for reading, it contains the state of the connection in text form, like "connected" or "connection refused". In the libc, this information is then mapped to the corresponding return values and errno codes.

**Comment by ehmry** [comment]
I would say this is related to #3036, a replacement for the current `Io_response_handler` could include "write_read" notifications.
