### ISSUE TITLE
Documentation of Socket FS

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#3116]
With #3113, another feature (support for non-blocking connect) makes it into the socket fs, which still lacks a documentation of its structure and semantics. This issue is a collection point for all information of the current state of supported socket semantics, files in the fs, and maybe known shortcomings.

**Comment by ehmry** [comment]
I have some initial documenation at df22ccbec2db21a5cb441293d41a0ff1a4d31096. Could use cleaner formating and TCP examples.

**Comment by chelmuth** [comment]
As @ehmry answered to my commit comment the initial documentation is just a reference manual for the directory structure and the file semantics. We have to add a section about exemplary use of the file system from network client and server perspective, which

- can leave out some details in a simple example
- may provide more complex example(s) for multi-connection servers/clients
- can be extended example(s) for blocking vs. non-blocking

**Comment by nfeske** [comment]
This issue has become stale.
