### ISSUE TITLE
run/depot_autopilot: less interactive mode

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#3120]
This should avoid that one missing package is causing all tests of a platform to fail:
bc2f8b0e48 run/depot_autopilot: less interactive mode
51fe1137fd run/depot_autopilot: check all archives at once

**Comment by nfeske** [comment]
@m-stein Can both commits merged into one or do you deem their separation as important?

After yesterday's chat with @senier about the work flow of integrating and running tests manually, how do you think about condensing this work-flow practice into a posting for genodians.org? This would be very valuable for others too (including me).

**Comment by m-stein** [comment]
No problem, you can squash them together. Sure, I try to write some lines.

**Comment by nfeske** [comment]
Thanks. I merged all three commits squashed together as https://github.com/genodelabs/genode/commit/dfcd4142a4a86c867ee513e808bbe9e7e0d54fce to staging.
