### ISSUE TITLE
core: replace pointers by references wherever possible

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3135]
Core is Genode's oldest component, which is evident with many C-isms still found in the code. In contrast to all regular components, which received renovation work during Genode's API update (#1987), core pretty much stayed untouched by these modernization efforts. As a step in the right direction, core should be changed to avoid the use of C pointers whenever possible.

**Comment by nfeske** [comment]
Updated the commit in 310a1f9b26ca540f3c4095087da69c358760c29d with the removal of manual noncopyable declarations if possible now (with the removal of pointers from class members).

**Comment by m-stein** [comment]
:+1: :+1:

**Comment by ehmry** [comment]
I have a patch related to this issue, cleanup of the `Genode::Fifo` class, eb350d853a4fbbe2a2e29d042b7612f39ada2733.

**Comment by nfeske** [comment]
@ehmry your patch looks fantastic! I very much like the new `Fifo` interface, i.e., the `destroy_all` method is great because it helps the calling code to clearly expresses its intent. I very much appreciate that you carefully went through all the users of this data structure and modernized those places instead of keeping the old interface around.

It is very good that you removed the base-hw-internal version. @m-stein Could you please have a look at this part of the patch? I think you are the best to recapture the original rationale behind the base-hw-internal version.

**Comment by ehmry** [comment]
@nfeske I have a fixup at 68469fc707338606f33e95258dc01fbdd467b446 to address your comment on eb350d853a4fbbe2a2e29d042b7612f39ada2733.

**Comment by m-stein** [comment]
@nfeske I appreciate the commit of @ehmry and apart from my inline comment about minor style stuff, It seems fine to me. The only rational for the local 'Fifo' was the 'for_each' method that is now also provided by the global version.

**Comment by nfeske** [comment]
@m-stein Thanks for the prompt review and for answering my question so quickly.

**Comment by nfeske** [comment]
I just updated the master branch and added my big commit to staging. To isolate potential problems with this big overhaul, I'd like to wait with merging the fifo patch until the tests have swallowed the big patch, ok?

**Comment by nfeske** [comment]
Merged the commit with the two fixups to staging.

**Comment by nfeske** [comment]
The change breaks the build of libc (the timed semaphore that is used internally uses the fifo).
It's also worth checking the use of the same mechanism in dde_rump (include/rump/timed_semaphore.h).

@ehmry Could you please have a look?

**Comment by ehmry** [comment]
@nfeske fixup at 29866b653305157698e9741fbcb90081c79f6f50.

**Comment by nfeske** [comment]
@ehmry Thanks a lot. Added to staging.

**Comment by nfeske** [comment]
@ehmry another build issue: `make core KERNEL=linux`

**Comment by ehmry** [comment]
@nfeske fix for Linux and Foc at 5aec9ac37ce358917509c1b7f9441a48f98cadbe.

**Comment by nfeske** [comment]
@ehmry We are not completely there yet: `make LIB=qemu-usb`

**Comment by ehmry** [comment]
@nfeske qemu-usb fixup at 677495beb0440b33d5e047c102002faab0568f83.

**Comment by ehmry** [comment]
Fixup for sel4 core at 42c84a484932899856ba56221e6bfb41f297635d

**Comment by nfeske** [comment]
@ehmry  The creation of the seoul-nova binary archive apparently still fails because of the Fifo API change.

**Comment by ehmry** [comment]
@nfeske Yes, this gets a bit complicated because the Fifo is in the contrib code and the removal of `Genode::printf` causes linking to fail as well.

https://github.com/ehmry/seoul/commit/28c7eb2d42f3d6df4e12def1e9501f781e0a2347

**Comment by nfeske** [comment]
Can you check back with @alex-ab about it?

**Comment by ehmry** [comment]
I have a patch for seoul at 117335a6eac8d03f303390126d80d610c06364f7, this temporarily points the Seoul port to my Seoul repo, and @alex-ab can move it back at the next Seoul update.

**Comment by nfeske** [comment]
Should 117335a6eac8d03f303390126d80d610c06364f7 go to staging?

**Comment by nfeske** [comment]
Fixed in master.
