### ISSUE TITLE
base-nova: remove diagnostic message about signal-delivery failure

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3136]
On NOVA, the base library currently prints a diagnostic message on the attempt to submit a signal to a signal context that no longer exists:

```
Warning: submitting signal failed - error 4 - context=cap<36268>
```

This message occurs in particular when destructing a signal handler for timer signals while the timer session is instructed to trigger periodic timeouts. Since the messages are printed by the timer, which usually runs at a very high priority, the costs of printing the messages can significantly starve the progress of large parts of the system. In the worst case, this is an denial-of-service attack vector. Hence we should remove this message.

@alex-ab do you agree?

**Comment by alex-ab** [comment]
@nfeske: The message was just meant as debugging feature, but this should be not the default at all. So, yes, please remove it.
