### ISSUE TITLE
usb_hid.run: enable BIOS handoff

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3140]
The handoff is needed on our 32-bit autopilot test machine.

**Comment by alex-ab** [comment]
Please don't disable it by default, this is not want we want to test nor to encourage other which may have a look into the run script. Please make it conditional depending on the autopilot switch and 32 bit with a comment about we need it.

**Comment by alex-ab** [comment]
Sorry, my comment was wrong.

**Comment by chelmuth** [comment]
@alex-ab I assume you had something like 62430c944d0ca5aac181a58b6a1466ad899f41e7 in mind with your previous comment.
