### ISSUE TITLE
Removal of VirtualBox 4

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3141]
All regular users of Genode's VirtualBox port use version 5 since a long time now. Version 4 is still sitting there because this is the only version supported on Muen. For me, however, it presents a maintenance burden. E.g., I'm in the middle of removing the use of deprecated Genode interfaces throughout the code base. Many changes I make for VirtualBox 5 must also be backported and tested for VirtualBox 4. I wonder, is this worth the effort?

@Kensan and @reet- What is your opinion? As far as I can see, VirtualBox 4 isn't too attractive for you as well but the adaptation of VirtualBox 5 is too costly to pursue. I guess you are eying on our plan to support VT with the base-hw kernel? Would you give us green light to drop VirtualBox 4 now even if that means that VirtualBox won't be usable on Muen until base-hw can be used as a nested virtualization layer on Muen?

**Comment by reet-** [comment]
On 2/6/19 3:21 PM, Norman Feske wrote:
> @Kensan and @reet- What is your opinion? As far as I can see, VirtualBox 4 isn't too attractive for you as well but the adaptation of VirtualBox 5 is too costly to pursue. I guess you are eying on our plan to support VT with the base-hw kernel? Would you give us green light to drop VirtualBox 4 now even if that means that VirtualBox won't be usable on Muen until base-hw can be used as a nested virtualization layer on Muen?

@nfeske: We agree to your assessment of the situation with vbox 4/5 and
Muen. Please got ahead with the removal of VirtualBox 4.

**Comment by nfeske** [comment]
Thanks for the prompt feedback, @reet- .

@alex-ab Would you please go forward by removing the version 4 (removal of the code, port, run scripts, update of the autopilot list)?

**Comment by alex-ab** [comment]
@nfeske: i will do, based on staging I assume ?

**Comment by nfeske** [comment]
Yes.

**Comment by alex-ab** [comment]
@nfeske: addressed by 61f6507bdbd0df91db098d74f90c47d801d083bc

**Comment by nfeske** [comment]
Very good. Thanks @alex-ab for providing the commit so quickly.

**Comment by alex-ab** [comment]
@nfeske: please remove the commit and use 29101a3207a8db4fce02953261688db16c87b84f - some files got lost

**Comment by nfeske** [comment]
@alex-ab I merged your second commit to staging.
