### ISSUE TITLE
netperf: review patches and update/remove if applicable

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#3143]
The current port of netperf 2.6.0 comes with two patches, which should be reviewed.

#### omni.patch

- adds `setsockopt(SOL_SOCKET, SO_SNDTIMEO/SO_RCVTIMEO) which is currently not supported in our libc and socket fs

  Rationale from sources: We don't support setitimer which uses signals. Instead set timeouts on the send and recv socket functions to be able to terminate if the host went away.

  From my understanding, the _host went away_ issue cannot be solved with the pthread-based `times_up` from #3122 as it does not induce `send/recv()` to return with `EINTR` and, thus, the netserver may hang. Any opinions?

- fixes some compilation issues (warnings I assume)

#### netlib.patch

- includes a fixup for an unsupported `sysconf(_SC_NPROCESSORS_ONLN)` which is now implemented in our libc

- disables the netperf-internal implementation of `start_timer(int time)` which uses `sigaction()` and `alarm()`

Also, a more actively maintained netperf 2.7 branch is available from https://github.com/HewlettPackard/netperf.

**Comment by nfeske** [comment]
@chelmuth instructed me to close this issue.
