### ISSUE TITLE
Sculpt lacks AZERTY support

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3149]
Sculpt is missing support for the [AZERTY keyboard](https://en.wikipedia.org/wiki/AZERTY), both in the pre-defined character generators for `input_filter` and in the terminal unicode handling. Maybe in the font as well.

**Comment by ehmry** [comment]
Patch at ff69d32a871e3c057978b72962eecb6af223fb52. I would refer to this as *azerty* and not *fr* because I have buiit the chargen using key labels on a keyboard that is not described as specific to any regional variant.

**Comment by chelmuth** [comment]
Not quite according to https://en.wikipedia.org/wiki/AZERTY#Differences_between_the_Belgian_and_French_layouts_of_the_AZERTY_keyboard

**Comment by ehmry** [comment]
Well its french then, I put the `+=}` key on the top row, french style.

**Comment by ehmry** [comment]
I'm worried about getting in an argument with someone french about the details...

**Comment by nfeske** [comment]
I have not quite followed the back and forth. ;-) Should the patch be cherry-picked to staging as is, or are there any adjustments planned?

**Comment by ehmry** [comment]
I have no further improvements, but perhaps the name should be changed to *fr.chargen*.

**Comment by nfeske** [comment]
@ehmry Is "perhaps" a yes or a no? ;-)

**Comment by ehmry** [comment]
Yes, for consistency lets name it *fr*, patch for staging at 8a62870d77ee5922752b585bfc8856d310415f90.

**Comment by nfeske** [comment]
Merged the fr-commit to staging.
