### ISSUE TITLE
Clipboard package

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3150]
How to properly route the *focus* ROM in Sculpt is an open issue, but the clipboard is usuable.

**Comment by ehmry** [comment]
Patch at 6d6c90aebd5554adcc764af4fe8b73a9f2d77dc6.

**Comment by nfeske** [comment]
Thanks @ehmry for this welcome addition. This could actually also work for Qt applications.

**Comment by nfeske** [comment]
Merged to staging.

**Comment by ehmry** [comment]
@nfeske fixup for staging at 6edc9f48c2225c45c2ba631ddc7199249a88b6ba.
