### ISSUE TITLE
base: timer driver utility only fits 32-bit

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3155]
The template function `timer_ticks_to_us` in `repos/base/include/drivers/timer/util.h` does not work properly for non-32bit types. You can test it, by trying the following code-snippet on a 32bit platform:
```
  enum { FREQ = 33333 }; 
  uint64_t tics = 0xffffffff;
  uint64_t ret = timer_ticks_to_us(tics, FREQ);
```
The return value will be zero although it should be ~128850307.

**Comment by skalk** [comment]
The problem is the recurring wrong pattern of doing such casts:
```
  (RESULT_T)~0UL
```
Obviously, here a 32-bit type of value 0xffffffff gets casted to the result type (e.g. 64-bit). What is actually intended is having the maximum value of the result type. I've found the same misleading casts already in the hw-kernel at some points of the timer subsystem.

**Comment by m-stein** [comment]
Hm, it is indeed a bit of a surprise to me that (unsigned long)~0UL should not produce 0xffff'ffff'ffff'ffff with 64 bit. When I run something like ``log("Test ", Hex(~0UL));`` (on x86_64 nova qemu) it yields ``Test 0xffffffffffffffff``.

**Comment by skalk** [comment]
Yeah, on a 64-bit machine UL is 64-bit, on a 32-bit machine it is 32-bit.

**Comment by skalk** [comment]
If your result type shall be 64-bit, you cannot use unsigned long as generic term, but e.g.: `~(RESULT_T)0`

**Comment by m-stein** [comment]
Thanks for the explication and the commit :+1:

**Comment by nfeske** [comment]
Thanks @skalk for tracking down this issue. I merged your commit to staging.
