### ISSUE TITLE
base: infinite loop in timeout calibration function

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3156]
When having a coarse granular timestamp, the `_update_real_time` function in the Timer::Connection of the timeout framework can loop infinitely. At initialisation time that function gets called repeatedly in quick succession. If the timestamp did not change in between those calls, a loop in the function is executed infinitely. Thanks to @m-stein, we could find the wrong statement. It was however, quite dificult to understand what is going on. First of all the algorithm expressed in that function is quite complex. On the other hand it should be split into functional programming style subfunctions especially regarding its loops.

**Comment by nfeske** [comment]
Merged to staging.
