### ISSUE TITLE
hw: schedule on demand

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3157]
Until now, the model of the kernel was not tracking whether it is necessary to to make a new scheduling decision and thereby re-program the timer. Instead this was done whenever the kernel was executed (page-faults, syscalls, irqs, etc.).
Surely, this is a performance issue. In discussion with @nfeske, he thought it might be a cause for the heavy time drift on hw (see issue #3081). Actually, this was not the root-cause but introduced additional burden, which worsens the time drift.
Anyway, it is much better to: just inform the scheduler whenever a thread/vm got blocked or runnable again, or when a timer interrupt occurred. Then, invoke the scheduler and timer just once at the end of a kernel pass when there is the need to.

**Comment by nfeske** [comment]
I merged your commit to staging, my small (inline) question notwithstanding.

**Comment by chelmuth** [comment]
I reverted the commit over the weekend as there's no fix for the strange effects currently.

**Comment by skalk** [comment]
@chelmuth @nfeske: I've identified and solved the remaining issue with riscv. The commit is ready for another run on staging.

**Comment by chelmuth** [comment]
Merged the commit to staging.
