### ISSUE TITLE
Add -Wsuggest-override to strict warning flags

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3159]
The `-Wsuggest-override` warning complains about implementations of virtual functions that lack the `override` keyword. We should enable it by default to prevent problems like bd9fbebd0e3a87698c4303b3dd12661475d93739 in the future.

**Comment by nfeske** [comment]
The two commits above add the missing override annotations and enable the -Wsuggest-override warning.

**Comment by nfeske** [comment]
Merged to staging.

**Comment by ehmry** [comment]
I have another Seoul patch at a704aacdc57890e8308e047cfc58d5ea4eaeef66.

**Comment by nfeske** [comment]
The change entered the master branch.
