### ISSUE TITLE
Configure buffer size of VFS File_system client at runtime

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3167]
The JDK class loader was having problems because it was not checking for short reads caused by a small packet buffer at the VFS File_system client. This is a quick fix for this issue, a deeper investigation should be made in to the semantics of `read` and `fread`.

**Comment by ehmry** [comment]
Patch at 7b48a7220d1d37597ca937c081cf82d017fc72e7.

**Comment by nfeske** [comment]
That looks good - almost. ;-) If you wrap the default buffer size into a `Number_of_bytes` object, one could use the K/M/G suffixes in the attribute value. Would that be worth adding, @ehmry?

**Comment by ehmry** [comment]
Yes, thats what I would prefer, new patch at 6ce7c2d1dbde65bbc8d95e54a1e344789b83ee1d.

**Comment by nfeske** [comment]
Thanks for the new version. Merged to staging.
