### ISSUE TITLE
lwIP VFS plugin misuses internal pbuf library

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3169]
The lwIP VFS plugin is not correctly shifting the head of the TCP receive buffer chain.

**Comment by ehmry** [comment]
Fixed at 815cb3d721afd7fa2d38333cd0ac9eed08113499.

**Comment by nfeske** [comment]
Just for the record, according to @cproc, this patch fixes sporadic issues of the tcp_bulk_lwip test. Thanks @cproc for investigating!

Merged to staging.
