### ISSUE TITLE
Print Rump file-system stats at mount

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3174]

**Comment by ehmry** [comment]
Patch at dc431d9452c10759df93ad9d78ee779229f6048a.

**Comment by nfeske** [comment]
Merged to staging.

**Comment by ehmry** [comment]
As @cnuke pointed out, using `Number_of_bytes` may truncate to 4 GiB on 32 bit machines, so I have a fixup 67464ff30452543f87ddc1098fee35ef6473bd9e to use floating point numbers here.
