### ISSUE TITLE
Block session: clarification of info() method

### ISSUE THREAD

**Issue by jklmnn** [genodelabs/genode#3185]
https://github.com/genodelabs/genode/blob/46a29532a9b38ffc2144b30579f0f1b8c17ff298/repos/os/include/block_session/block_session.h#L139-L148
This comment states that `blk_size` returns the total size which in my opinion could be misunderstood to return the size of the whole block device (as `blk_count` returns the total number of blocks for the whole device). I'd suggest
```C++
* \param blk_size  will contain block size in bytes
```
for this line.

**Comment by chelmuth** [comment]
Do you mean *block size in bytes*?

**Comment by jklmnn** [comment]
> Do you mean block size in bytes?

Of course, I adapted the issue text. Otherwise it wouldn't make any sense.
