### ISSUE TITLE
sculpt: pkg/vbox5-nova-sculpt runtime request 8G

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3197]
which is to much for a "normal" machine. Beforehand it has been capped to 4G by the launcher/vm (see 7921834b1d322d2eb45a408e945fa23cd53df68f) but it got removed.

**Comment by alex-ab** [comment]
The commits resets to the previous status quo.

**Comment by nfeske** [comment]
Thanks @alex-ab for spotting the issue and for the fix. Merged to staging.
