### ISSUE TITLE
Update Arora default bookmarks

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3198]
The default bookmarks of the Arora web browser are embarrassingly outdated. I propose to change them to the following list (in this particular order):

* https://genodians.org
* https://genode.org
* https://github.com/genodelabs/genode
* https://lists.genode.org/pipermail/users/
* https://reddit.com/r/genode
* https://www.genode-labs.com

Are there any further suggestions or opinions? E.g., what about @cnuke's hardware-compatibility list, or Genode's Wikipedia article, or microkernel.info, or the respective kernel's project pages (seL4, NOVA, Muen, Fiasco.OC), or Genode-covering news sites (phoronix.com, pro-linux.de)?

**Comment by nfeske** [comment]
BTW, the bookmarks are defined at https://github.com/genodelabs/genode/blob/master/repos/ports/src/app/arora/patches/arora_bookmarks.patch

**Comment by cproc** [comment]
Sounds good.
