### ISSUE TITLE
Window layouter: permit floating windows to resize themselves

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3200]
Right now, the window layouter enforces that window size never exceeds the bounds as defined by the user, which is the desirable behavior when using tiled windows. However, for foating windows, the application knows best, what window size is appropriate. Right now, the application can specify the initial window size but it cannot change it after the fact. Whenever the application resizes the window's nitpicker view, the window can only become smaller but not larger.

To fix this issue, the window layouter should become less strict about enforcing the user-define window size when a window is floating.

@alex-ab I have noticed that this effect is very much in the way of your new version of top_view when routing it to the window manager.

**Comment by nfeske** [comment]
Fixed by https://github.com/genodelabs/genode/commit/0609285c19ad26701bf3fb107765427f708f6c1e on staging.

**Comment by nfeske** [comment]
Unfortunately, my fix interacts badly with issue #3227. With the fix in place, a user-resized window snaps back to the original window position. :-/

**Comment by alex-ab** [comment]
> @alex-ab I have noticed that this effect is very much in the way of your new version of top_view when routing it to the window manager.

Thanks for the heads up. I will take with the next update of top_view.

**Comment by nfeske** [comment]
Commit https://github.com/genodelabs/genode/commit/7430541a39c829977f3cc79a755c794fb149f821 (on staging) fills the gap I mentioned in my previous comment.
