### ISSUE TITLE
timeout framework: limitation of ~1hour on 32-bit systems

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3208]
Currently the timeout framework still is using the `trunc_to_plain_us` method internally (like some other components as well, e.g., depot_autopilot or libc), which returns a machine-word wide type that limits the microseconds value to something about an hour on a 32-bit system.

An minor issue related to this is that `Duration` objects can be constructed only out of machine-word wide milliseconds or microseconds, which is limiting the construction of greater values on 32-bit platforms. This is relevant when handling absolute timer values of long running machines. But this gets relevant only when the internal timeout calculation does not use above mentioned limited microseconds types in the first place.

**Comment by al-sharp** [comment]
I am suspicious this is related to the QTimer issue noted (April 1, 2019) on the User list, (repeated below). This is intended to be a long running application btw (months). One puzzle is that the issue seems to persist for me with 64-bit builds. 

See also: https://forum.qt.io/topic/100981/qtimer-seems-to-just-stop  (that's me).

> I tripped across a situation where one of my Qt5 applications
> that used a periodic QTimer stops receiving timeout signals
> after 1 hour 10 minutes of normal operation. 
> 
> (This is in Genode 18.08, x86_32 and x86_64, nova and seL4.)  
> 
> The same application keeps on ticking (for many hours at least)
> when compiled and run under Linux.
> 
> A Qt Forum participant speculates "a 2^32 wraparound? Because 
> 4294967296 (2^32)  microseconds is 4295 seconds." This is just
> about the observed time.
> 
> The Qt5 documentation suggests that some Qt timers on some platforms
> can have this problem--it depends on the underlying clock source.
>

**Comment by ehmry** [comment]
See #3281 for a libc fix.

**Comment by skalk** [comment]
@al-sharp when you experience the exactly same symptoms on a 64-bit platform, I doubt it is related to this issue.

**Comment by ehmry** [comment]
As per the offline discussion I have a list of places where an abstract duration is converted to concrete representation, excluding the timer framework itself:
- repos/ports/src/noux/syscall.cc:837 - GETTIMEOFDAY, CLOCK_GETTIME
- repos/os/src/test/timeout/main.cc:388
- repos/os/src/test/net_flood/main.cc:373 - conversion to seconds
- repos/os/src/server/nic_dump/interface.cc:36 - milisecond durations
- repos/os/src/app/ping/main.cc:274 - print miliseconds with microsecond granularity
- repos/libports/src/lib/lwip/platform/sys_arch.cc:96 - monotonic milisecond time
- repos/libports/src/lib/libc/time.cc:61 - clock_gettime
- repos/libports/src/lib/libc/task.cc:22 - suspend timeouts
- repos/libports/src/app/fetchurl/component.cc:102 - One_shot_timeout needs microseconds, does not take duration
- repos/gems/src/app/depot_autopilot/child.cc:183 - track running time in microseconds
- repos/dde_linux/src/lx_kit/timer.cc:29 - update_jiffies()
- repos/dde_linux/src/lib/lxip/timer_handler.cc:166 - usecs_to_jiffies

**Comment by ehmry** [comment]
Places where the Milliseconds and Microseconds objects are used:
- repos/ports/src/noux
- repos/os/src/test/timeout
- repos/os/src/test/net_flood
- repos/os/src/test/fs_report
- repos/os/src/server/nic_router
- repos/os/src/server/input_filter
- repos/os/src/server/nic_dump
- repos/os/src/drivers/*
- repos/os/src/app/ping
- repos/os/src/app/block_tester
- repos/libports/src/lib/lwip
- repos/libports/src/lib/libc
- repos/dde_linux/src/lib/lxip

**Comment by m-stein** [comment]
In an off-line discussion regarding this issue, we agreed on a plan of two steps so far:

1. Consistently use ``uint64_t`` for time values (including the values in Microseconds, Milliseconds). This should fix the problem behind https://github.com/genodelabs/genode/commit/d5f9a108ad75790331c6d66a60ef0d4d2be46fec and therefore render the commit unnecessary. If we should introduce the ``Duration::seconds`` method anyway, the return value should be wrapped in a new ``Seconds`` type. I'd like to assign myself to the implementation of this step.

2. Successively try to adapt the places where we currently use ``Duration::trunc_to_plain_*`` to use the ``Duration`` object directly instead. This will generate use-cases that require the ``Duration`` interface to be extended. Especially, this will raise the need for arithmetic operators, these shall not be implemented by overwriting the C++ standard operators but by adding normal methods (e.g. ``Duration Duration::subtract(Duration const &, Duration const &)``). How such methods should treat specific situations like range violations will be discussed separately.
3. Re-consider whether parts of the current (old) state of Duration/Milliseconds/Microseconds can be removed with the results of steps 1 and 2 in place.

**Comment by nfeske** [comment]
That sounds very good!

**Comment by al-sharp** [comment]
> @al-sharp when you experience the exactly same symptoms on a 64-bit platform, I doubt it is related to this issue.

@skalk that is a good point, and it has been bothering me.  After checking my x86_64 build's specs.conf, I found it to be defective (copy-paste considered dangerous), and it was actually still building 32-bit (!)  On a real 64-bit build, I don't have any problems with QTimer halting.  So, I think the proposed strategy above should help.

**Comment by chelmuth** [comment]
I skimmed over the patch and have two remarks.
- when adding `Duration::seconds()` in the final patch the `Duration::trunc_to_plain_*()` functions should be renamed to `Duration::milliseconds()` resp. `Duration::microseconds()`
- anything matching *hours* case-insensitive can be removed

**Comment by m-stein** [comment]
Ah, thanks for this feedback!
I'll apply your suggestions.

**Comment by m-stein** [comment]
May I also replace the Kernel::time_t in base-hw (which is always uint64_t) ? If yes, this could be done in a separate commit. Or shall it be part of the "uint64_t"-commit?

**Comment by m-stein** [comment]
Furthermore, there is the Kernel::timeout_t in base-hw which is always uint32_t and should definitely become a uint64_t.

**Comment by chelmuth** [comment]
Changing the base-hw kernel interface is a completely different work item and should not be addressed in this issue.

**Comment by skalk** [comment]
@m-stein there are good reasons for the differentiation of time_t and timeout_t being 64-bit and 32-bit respectively. On the Kernel syscall API level: time_t denotes the absolute time-value returned by the kernel, whereas timeout_t is a relative timeout value. Both values represent microseconds. The timeout_t type is limited to 32-bit, otherwise we have to introduce additional 64-bit arguments to the syscall API of 32-bit platforms. I hesitated to do so. On the other hand, it is perfectly fine to limit the relative timeout to 0xffffffff microseconds (a bit more than an hour) maximum timeout value on the kernel level. Having higher timeout values is already implemented on the (user-land) timer service level.

**Comment by skalk** [comment]
@m-stein To always know what kind of value you operate within the kernel, it is good to have aliases for uint64_t and uint32_t in the form of time_t and timeout_t.

**Comment by m-stein** [comment]
@skalk Thanks for this clarification!

**Comment by m-stein** [comment]
With https://github.com/m-stein/genode/commits/3208_timeout_framework_limitation_of_1_hour, I can successfully call make for base and os on x86_64 again.

**Comment by m-stein** [comment]
My merge_to_staging branch contains a re-based version that should succeed in ``make`` on all platforms/kernels with repos base, os, demo.

**Comment by m-stein** [comment]
Now, libports and ports succeed in ``make`` with my merge_to_staging branch.

**Comment by m-stein** [comment]
@chelmuth This fixes the first step:
fb2703b timeout: use uint64_t for all plain time values

I was able to build all repos except world with the combinations x86_64+sel4, x86_32+nova, imx6q_sabrelite+hw on this commit.

**Comment by m-stein** [comment]
The most recent version:
b90abb5 timeout: use uint64_t for all plain time values

**Comment by m-stein** [comment]
Thanks to an inline comment of @skalk, I realized that b90abb5 is missing the code removal that I was most happy about. It can be added as self-standing commit:
65be1defb6 Timer::Connection: simplify curr_time

But it can also be added as fixup to b90abb5 if desired.

**Comment by nfeske** [comment]
Thanks @m-stein. I merged both as separate commits to staging now.

**Comment by skalk** [comment]
@m-stein: commit 74a7ce2 breaks test-libc_connect_lxip on all 32-bit base-hw platforms in the `depot_autopilot` nightly tests.

**Comment by m-stein** [comment]
@skalk I'm at it.

**Comment by m-stein** [comment]
It's a bad idea to have a time value type with a greater bit width than the timestamp type in the timeout framework. The interpolation algorithm silently assumes that this is not the case and may cause endless loops otherwise. Using ``uint64_t`` instead of ``Timestamp`` (only in the timeout framework) fixed it:

a8ef18c Fixup to "Timer::Connection: simplify curr_time" and then to ...

Any objections or may we merge this?

**Comment by cnuke** [comment]
I am okay with that. Since the topic came up during coffee break today, I think the `Trace::Timestamp` should not be used in the timeout framework at all. At least in the beginning it was meant as a free-standing _event stamping_ tool purely used by the Trace framework and its trace-policy (which is why it should not depend on anything). If _time-stamping_ is required in the timeout framework it should be implemented with its own types.

**Comment by nfeske** [comment]
@cnuke 

> If time-stamping is required in the timeout framework it should be implemented with its own types.

The timestamp (tsc) values are used as a cheap and precise (but non-calibrated) time source used for estimating the current time in-between accessing the (costly but calibrated) real timer. Whenever glancing at the current time ought to be cheap and precise, it is needed.

@m-stein I think https://github.com/genodelabs/genode/commit/a8ef18cac7ecfc2b7fe1bf5223879ebf2c2a48d9 is not the right approach. Timestamp values should not end up in plain uint64_t values. The timestamps are not guaranteed to use 64 bit but the values are platform-dependent. E.g., if I remember right, the timestamps used on ARM on the Rpi are only 32 bit. But that precision is completely ok for the timeout framework because the values are only used for short intervals. Consequently, it might be sensible to narrow the value range on all platforms, but not to widen it. The wrapping of tsc values _must_ be handled by the timeout framework.

**Comment by cnuke** [comment]
@nfeske yes, I know how and why they get used. I am just saying that since _time-stamping_ is a different use-case than _event-stamping_ (after all ARMv7 AFAIU does not has something like the x86's TSC which is why we use performance-counters for `Trace::Timestamp` that depending on the SoC might be only 32Bit as well as stops counting when the CPU is idle) which does not need time precise, it stands to reason if both should be treated the same. For better or worse we can use the TSC on x86 for both use-cases.

**Comment by skalk** [comment]
@nfeske In the timeout framework the ARM performance counters are not used for quite some time now (see commit 685f509a4335a63680cd1ce7d508900d0c95ac08). The only kernel that supports intermediate timestamp values on ARM is hw, but that returns the actual kernel time (`uint64_t` value). Unimportant side-note: all modern performance counters will be 64-bit too.
However, I see in @m-stein's commit that the library-internal used timestamp values get replaced to be compliant to the absolute time, which is now always represented and calculated using `uint64_t`. Isn't it natural to transform a value you get from different sources into the (wider) type that is used to caclulate the actual time anyway? Obviously, there is a calculation error hidden due to implicit conversion of the 32-bit vs. 64-bit types.

@m-stein On the other hand, what I miss in the commit is the adaption of the `repos/base/src/lib/timeout/timer_connection_timestamp.cc` file, the only place where `Trace::timestamp()` gets used in this library.

**Comment by nfeske** [comment]
To clarify my intent behind the use of `Timestamp` vs. `uint64_t`, the former should be used whenever timestamp values are obtained, propagated (as arguments, return values), or stored (as member variables). The latter should of course be used during the actual computation. The conversion from `Timestamp` to `uint64_t` should happen locally in the computation function.

**Comment by m-stein** [comment]
@nfeske So, if I understand you right, it's ok that we replace Timestamp with ``uint64_t`` inside the timeout framework? For me, this makes the algorithms also more clear.

**Comment by m-stein** [comment]
@skalk I've updated and tested the commit according to your annotation:
e5bdd89 Fixup to "Timer::Connection: simplify curr_time" and then to "timeout: use uint64_t for all plain time values"

Btw. the commit message should be interpreted in the way that I'd suggest to fixup the two mentioned earlier commits and this third commit all together into one commit. If we, however, want to keep the earlier two commits separate I have to adapt them.

**Comment by m-stein** [comment]
@nfeske Sorry, I read your first mail too late. So please ignore my question.

The current problem with narrowing the timestamp is not the wrapping of timestamps, it is that the loops in the interpolation algorithm assume that the type in which timestamps are stored is not smaller than those that is used for time values. I'll have to think about this once more.

**Comment by m-stein** [comment]
This is a minimal version of the fixup:
714fe77 Fixup to "Timer::Connection: simplify curr_time" and then to "timeout: use uint64_t for all plain time values"

Would this be ok for all?

**Comment by nfeske** [comment]
I'm very comfortable with https://github.com/genodelabs/genode/commit/714fe7758155d198bbe1c3adf2c42f6c4993f168 :-) Thanks for taking my remark into consideration.

**Comment by nfeske** [comment]
I tried to (quickly) validate if https://github.com/genodelabs/genode/commit/714fe7758155d198bbe1c3adf2c42f6c4993f168 fixes the libc_connect_lxip issue via the test.run script on Qemu/pbxa9. Ssee https://github.com/nfeske/genode/commit/544158f6bef448b559fd6462d0aad287a8f8ce50 for the quirk needed to make test.run compatible with libc_connect_lxip. Unfortunately, I get a fault like this:

```
[init -> test -> test-libc_connect] Testing nonblocking connect (timeout)
[init -> test -> test-libc_connect] Error: freeing non-empty slab block
attempted exec at non-executable memory (EXEC pf_addr=0xd9828 pf_ip=0xd9828 from pager_object: pd='init -> test -> test-libc_connect' thread='ep') 
Warning: page fault, pager_object: pd='init -> test -> test-libc_connect' thread='ep' ip=0xd9828 fault-addr=0xd9828 type=exec-fault
```

Without https://github.com/genodelabs/genode/commit/714fe7758155d198bbe1c3adf2c42f6c4993f168, the test times out - as originally reported by @skalk.

@skalk May you investigate this further?
