### ISSUE TITLE
pcsc-lite: read vendor id and product id from USB device

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3211]
Currently, the vendor id and product id of the smartcard reader to be used must be stated both in the policy of the USB driver and for the pcsc-lite library in the configuration of the application. Using libusb, the pcsc-lite library can read this information from the device instead.

**Comment by cproc** [comment]
@chelmuth: I added the reader access documentation in 70626d9.

**Comment by chelmuth** [comment]
Thanks, merged to staging.
