### ISSUE TITLE
fetchurl: update README

### ISSUE THREAD

**Issue by trimpim** [genodelabs/genode#3213]
The configuration example in the README doesn't work any more.

**Comment by skalk** [comment]
Thank you for very much your maintainance work! As a small general hint: if you think your commit is ready solve the mentionend issue, you can mark it as fixed (see the labels). So it will get more attention to be picked up for staging.

**Comment by trimpim** [comment]
I have tried to set the labels, but was not able to (at least in the WEB-UI).

**Comment by skalk** [comment]
@trimpim ah ok sorry, I did not know that this is not possible to non-organization members, I'll do it for you.

**Comment by chelmuth** [comment]
Merged to staging.
