### ISSUE TITLE
sculpt ce: leitzentrale gui popup non functional after a while

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3218]
```
[leitzentrale -> gui -> popup] resource_request: ram_quota=377056
[leitzentrale -> gui] child "popup" requests resources: ram_quota=377056
```

**Comment by alex-ab** [comment]
Probably related, in the log beforehand one can see:
```
[leitzentrale -> gui] Warning: popup assigned RAM (12M) exceeds available RAM (6596441)
[leitzentrale -> gui -> popup] tar archive 'menu_view_styles.tar' local at 0x158000, size is 102400
```

**Comment by nfeske** [comment]
Does this occur depending on the time running (which would hint at a memory leak) or triggered by the popup becoming larger than before? I hope that it's the latter case so we can just tune the quotas.

**Comment by ssumpf** [comment]
I had the same issue and could trigger it by copying `deploy` to `/config` and starting/configuring the `vbox5-nova-sculpt`. When choosing File System (wm) the popup would cause the resource request. Increasing the quota in `Sculpt::Gui::_gen_menu_view_start_content` did work for me and the behaviour has not occurred this week.

**Comment by alex-ab** [comment]
Thanks for the hints, @ssumpf. After giving the popup the requested memory (12M), I could not reproduce it.

**Comment by nfeske** [comment]
Thanks for the fix. Merged to staging.
