### ISSUE TITLE
part_block: fix handling of chained EBR's

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#3223]

**Comment by cnuke** [comment]
The issue was reported by @valerius2k on the mailing list and will post-pone adding the *fixed* label until e95e0d1 was acknowledged as fix for the encountered problem.

**Comment by valerius2k** [comment]
I acknowledge that the above commit fixes incorrect partition table parsing. Now I see all my partitions with correct sizes. Thank you very much for the fix!

**Comment by chelmuth** [comment]
Thanks for the bug report and fix. I'm going to merge it with the accompanied test case (as discussed offline).

**Comment by cnuke** [comment]
@chelmuth commit 833ab4b contains the updated disk image, without the fixing commit the last two partition would be missing.
