### ISSUE TITLE
sculpt ce: leitzentrale does not perform downloads after an error

### ISSUE THREAD

**Issue by tomga** [genodelabs/genode#3224]
I've built sculpt ce with:
```
RUN_OPT += --depot-user tomga
```
After starting, selecting filesystem for use and enabling network connection I can try to select from ``shared_fs`` from menu and that triggers an error:
```
[leitzentrale -> manager] tomga/pkg/chroot/2019-02-25 incomplete or missing
```
which is probably ok because currently I don't have any place where I could publish my depot to be available to sculpt machine.
What I think is an error is that subsequent attempts to install something or just enable depot do not cause downloading but just queueing donload with message:
```
[leitzentrale -> manager] add to download queue: alex-ab/index/19.02
```
As a workaround it is possible to start download with disabling and reenabling network. Then queued downloads start.

**Comment by nfeske** [comment]
Thank you for the excellent bug report. I can reproduce the problem. Working on a fix right now.

**Comment by nfeske** [comment]
Commit https://github.com/genodelabs/genode/commit/6be5c8623dbd49d592fbc3bfcb4014212ffa7c50 should solve this issue.

**Comment by tomga** [comment]
With the above fix I cannot reproduce this anymore. Thanks.

**Comment by nfeske** [comment]
Thank you for giving the patch a try! :-)
