### ISSUE TITLE
hw riscv: do not interfere bbl machine calls and kernel syscalls

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3230]
When introducing non-blocking signal delivery in the hw kernel to solve issue #3217, the enumeration of the syscall ids changed. Thereby, it came up that the bbl (contrib code) riscv machine mode firmware depent hard-coded on the syscall id of the Kernel::print_char method. By changing the syscall ids, riscv port of hw did not work anymore.
It is much better to not mix up both worlds especially not without using common headers, to prevent such magic surprises.

**Comment by skalk** [comment]
@chelmuth above commit re-enables the nightly riscv runtime test

**Comment by chelmuth** [comment]
Great, merged into staging.
