### ISSUE TITLE
No FOCUS_ENTER events received

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3233]
I am receiving the `FOCUS_LEAVE` input event from Nitpicker but not `FOCUS_ENTER`.

Perhaps this would be an "easy-fix" issue for newcomers?

**Comment by nfeske** [comment]
There is no FOCUS_ENTER because the next MOTION event is implicitly a FOCUS_ENTER.

That said, I appreciate that you keep the "easy-fix" topic in the back of your head!

**Comment by ehmry** [comment]
Ok, that was silly of me.
