### ISSUE TITLE
seoul: add PS2 mouse wheel support

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#3234]
For better browser VM handling.

**Comment by alex-ab** [comment]
Thanks @ssumpf, i added your patch to the contrib sources as fixup.

**Comment by chelmuth** [comment]
Should 6267f5324b2069e1203104bf65992a3b9c8e7aa5 be merged too?

**Comment by ssumpf** [comment]
@chelmuth: No, 6267f53 is just for testing.
