### ISSUE TITLE
driver_manager: increase block driver memory

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3243]

**Comment by nfeske** [comment]
What is the background of this issue?

**Comment by alex-ab** [comment]
The ahci driver requests memory on sculpt ce (T460) and the system hangs.

**Comment by nfeske** [comment]
I wonder what's the difference to systems like mine (also using ahci) where this memory is not needed. Do you happen to have multiple AHCI devices connected?

Intuitively, assigning 10 MiB to a disk driver seem already quite generous. I have nothing against your patch but I'd like to understand why we need to bump up this value even higher (14 MiB according to your patch).

**Comment by alex-ab** [comment]
> Do you happen to have multiple AHCI devices connected?

No.

I will have to take time to investigate since this is my working machine. I will report back when I knew more.
