### ISSUE TITLE
rpi: sd_card driver is not working anymore

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3246]
The sd-card driver tests seem to fail for Raspberry Pi 1 since 26.10. within its early initialization:
```
[init -> sd_card_bench] Error: command timed out
[init -> sd_card_bench] Warning: Send_if_cond command failed
[init -> sd_card_bench] Error: Uncaught exception of type 'Sd_card::Host_controller::Detection_failed'
[init -> sd_card_bench] Warning: abort called - thread: ep
```
When I understand the driver code correctly, it already issues successfully the `Go_idle_state` command, but for second command there is no interrupt arriving in time (driver is polling for it).
Maybe one of the different authors of the driver with more background knowledge can have a look at it?

**Comment by nfeske** [comment]
I presume that we won't ever fix the original sd-card driver. For using SD-cards on the Rpi today, one would pick the route taken for i.MX, which is the porting of the Linux driver using DDE. I'm closing this issue as rejected.
