### ISSUE TITLE
fetchurl_lxip: hangs sporadically

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3248]
Every night, we can see the `fetchurl_lxip` test to hang on several platforms. Moreover, some of us already experienced a hanging fetchurl when installing packages in Sculpt. Maybe, that hits the same issue.

**Comment by ehmry** [comment]
For the record I always prefer lwip over lxip.

**Comment by nfeske** [comment]
Why must this information be recorded? ;-)

**Comment by ehmry** [comment]
Lwip has a worse reputation than it deserves.

**Comment by cnuke** [comment]
A similar behaviour is observable in the *genodians.org* appliance where sometimes a download is stuck (no progress is made which can be checked by looking at the progress report) until eventually some internal timeout is triggered and the download attempt is aborted.

**Comment by nfeske** [comment]
This issue has become stale. I'm closing it.
