### ISSUE TITLE
test/spark_real_time: relax accuracy expectation

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#3258]
Multiple platforms fail in this test because the initially chosen accuracy expectations cannot be met.

**Comment by m-stein** [comment]
Fixed by:
38b13131ab test/spark_real_time: relax accuracy expectation

**Comment by nfeske** [comment]
Since this issue is about a side effect of #3225, I'd like to close it and continue the discussion there. @m-stein do you agree?

**Comment by m-stein** [comment]
Of course.
