### ISSUE TITLE
nitpicker: issue mode change signal after domain config update

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3259]
After a domain configuration update of nitpicker, no mode change signal is sent to clients in case the dimension got restricted or extended regarding width/height. Without the signal clients can't adjust to new size.

**Comment by nfeske** [comment]
Thank you for the fix. I must admit that I totally forgot that the size constraint is already implemented in nitpicker. Recently, jus for fun, I tried specifying the `width` attribute in Sculpt's config/nitpicker to no effect and assumed that the feature does not exist. Now, I know better. ;-)
