### ISSUE TITLE
libc: fix storing TIOCGWINSZ result

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#3266]

**Comment by nfeske** [comment]
Merged to staging.

@cnuke Would you mind sharing the background of this fix? By looking at the commit, I am unable to infer the situation where the previous implementation was a problem.

**Comment by cnuke** [comment]
@nfeske it used `arg` to store the information (which at this moment points to the memory location `0). Now it uses `argp` that points to the user allocated memory.
