### ISSUE TITLE
Shift Sculpt Leitzentralle CPU affinity

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3268]
Would pinning the Leitzentralle and depot management components to a different CPU reduce the amount of scheduling interference between user-depoyed system and the administrative system? I assume that the first CPU has better performance than the second due to cross CPU RPC, but if the Leitzentralle is only used occasionally then I expect it would be fine to push it back to a second core?

**Comment by nfeske** [comment]
Indeed. I vaguely remember that I already did this in the past (to a quite positive effect - at least regarding the fading). But I apparently missed to merge this change to upstream.

**Comment by NobodyIII** [comment]
I'm interested in this as well. Has it been merged yet?

**Comment by ehmry** [comment]
It probably won't happen until we start building Sculpt for the next release, which will happen towards the end of the month.

**Comment by NobodyIII** [comment]
Ah. I'd like to see it in the 19.05 release if possible, but I can
understand the decision to wait.

**Comment by nfeske** [comment]
Fixed in 1f96b4bc9a3136215a4a553d5c2a57e10351cd91.
