### ISSUE TITLE
Noux: add time facilities

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#327]
Certain programs, e.g. ping(1), need gettimeofday() etc. For now the time does not
need to be accurate or right at all. All we need is a little progress. So at the moment
it is enough to use a simple timer which counts ms.

**Comment by cnuke** [comment]
Already fixed by 837f913094cf56562e5487ac98845de5b639d046.

**Comment by chelmuth** [comment]
What do you think about adapting the libc approach of getting an initial time from RTC if available and falling back to 0? Have a look at read_rtc() and where it's used in libc.
-- 
Christian Helmuth
Genode Labs

http://www.genode-labs.com/ · http://genode.org/ · /ˈdʒiː.nəʊd/

Genode Labs GmbH · Amtsgericht Dresden · HRB 28424 · Sitz Dresden
Geschäftsführer: Dr.-Ing. Norman Feske, Christian Helmuth

**Comment by cnuke** [comment]
That is a good idea and already on my todo list. We will need the proper time, i.e., when handling E-Mail with noux.

**Comment by chelmuth** [comment]
:ok_hand:
