### ISSUE TITLE
Update depot content implicitly via run script

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3270]
As remarked by @ehmry in https://github.com/genodelabs/genode/issues/3261#issuecomment-478034969, the interplay of the depot with the run scripts can become frustrating because the creation of missing or outdated depot content requires manual steps. To accelerate our work flow, it would be nice if the execution a run script automatically triggered the creation of depot content and update depot-archive versions as needed.

Until now, I was hesitant to implement such a feature into the build system because this would be a violation of the layering of tools: Everything done from within the build directory should stay in the build directory. The build process should - in particular - never modify the source tree.

Well, layering is good and all, but at the end of the day, users don't care about nice layering, but about a smooth operation of the tools.

To make the tools more convenient, I'd like to add a new `--depot-auto-update` option to the run tool. When added to the `RUN_OPT` variable, this option triggers the depot/create operations as needed by the run script. This includes version updates and the build of packages.

**Comment by nfeske** [comment]
@ehmry would you like to give https://github.com/nfeske/genode/commit/e18cfd44248d0e59035f24da5f0d3c6bbe488618 a try?

**Comment by ehmry** [comment]
Yes, much better.

**Comment by ehmry** [comment]
Now it seems everything gets rebuild on every run - `UPDATE_VERSIONS=1 FORCE=1 REBUILD= KEEP_BUILD_DIR=1`.

**Comment by ehmry** [comment]
I take it back, just the api and source archives.
