### ISSUE TITLE
Add SYNC and TRIM as async I/O operations to block session

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3274]
The current block-session interface should be improved in the following respects:

* The `sync` operation is currently an RPC function. It should be an asynchronous operation to ensure the consistent ordering of sync operations with pending read/write requests. This change would also simplify server implementations if they depend on asynchronous I/O for implementing sync. An blocking RPC is bad in this situation because it blocks all other clients until the sync of one client has completed.

* In addition to READ, WRITE, and SYNC, we should add an asynchronous TRIM operation to mark a range of blocks as no longer needed.

* The alignment of the request payload is currently set to 2 KiB by default. As far as I remember, the value was originally chosen to accommodate the ATAPI driver. In general, however, the alignment depends on the server implementation, e.g., it may be dictated by DMA-buffer alignment constraints of a zero-copy block driver. For non-device block servers, the alignment (beyond the block size) should better be avoided to avoid fragmentation of the payload buffer. Consequently, we should introduce a new RPC function `block_alignment` that should be called by the client to request the proper alignment from the server.

**Comment by nfeske** [comment]
Until now, each packet of the block session could be uniquely identified by its offset into the payload buffer because each packet - by definition - owns a disjoint part of the packet-stream buffer.

The new operations SYNC and TRIM do not have any payload. Hence, the offset does no longer suffice to uniquely identify packet descriptors. E.g., when a client issues two consecutive SYNC requests, both packet descriptors would look the same. When receiving the acknowledgements, the client cannot know which ack belongs to which request.

For this reason, we should equip the packet descriptor with a client-defined _tag_ value that enables the client to associate requests with their acknowledgements, independent from the other packet-descriptor arguments. The server would preserve the tag as an opaque value.

@m-stein and @cnuke, this topic is related to your current discussions. Some days ago, I argued against adding the `tag` member to the `Block::Request` but now I came to the contrary realization. Please give me a short notice if you are with me.

**Comment by cnuke** [comment]
Fine with me.

**Comment by m-stein** [comment]
Fine with me too.
