### ISSUE TITLE
block_session: remove Block::Session::Operations

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3275]
The `Block::Session::Operations` class was meant for the negotiation of the block session's features between client and server. But some years down the road, it turns out that the only meaningful distinction exists between read-only and read-writeable sessions. Still, all block servers are bothered with the clunky `Operations` definitions.

As a preparatory step for issue #3274, I'm going to replace the `Operations` with a straight-forward `writeable` RPC function.

**Comment by nfeske** [comment]
Instead of introducing a new `writeable` RPC function, I'm going to change the current `info` RPC function to return a structured type, which includes the `writeable` attribute.

**Comment by cnuke** [comment]
Not that I have specific use-case in mind but maybe it is reasonlable to also add a `readable` attribute (I'm thinking along the lines of a append-only block device). Than again such a attribute could be added when the need arises.

**Comment by nfeske** [comment]
In principle, it is easy to add further attributes but I'd wait for the actual use case.

**Comment by nfeske** [comment]
Commit https://github.com/nfeske/genode/commit/f3579460851efb69cd497f89f84f0836634a148b implements this idea.

**Comment by nfeske** [comment]
Commit https://github.com/nfeske/genode/commit/a11da5d784a72cc2896efd13be31dab6ba237365 presumably covers all block components in the source tree. @cnuke, could you please have a glance?

**Comment by cnuke** [comment]
@nfeske thanks for updating the components. So far it looks good. I'm only wondering if we should break the compatibility of Block components immediately without prior notification.

**Comment by nfeske** [comment]
@cnuke your remark to be careful about the API change is appreciated.

After sleeping over it, I think that the risk to disrupt Genode users should be acceptable as users rarely deal with the development of block-level components directly. So most breakage happens within our tree where we can take care. In genode-world, there are two components (lwext4 and blk_shred) that I will adjust once the commits enter the master branch.

Nevertheless, once the commits enter the staging branch, I'll post a heads-up message to the mailing list. The adjustment to the API changes is not complicated - rather cosmetic - after all.

The removal of the block/component.h API would be a different story. Here we would need a proper API-deprecation plan.

**Comment by ehmry** [comment]
Solo5 fix at 2d9ef64a86fc82eab171cc975794c438b8a01c45.

**Comment by ehmry** [comment]
Fixup for solo5 at dfaafa5bbe91c94f79ad03dd35ad6df0437ebc96.
