### ISSUE TITLE
hw: nic_router test triggers kernel re-entrance

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#3277]
On imx53qsb and x86_64, we got the following log last night.
```
Kernel: Cpu 0 error: re-entered lock. Kernel exception?!
```

**Comment by skalk** [comment]
@chelmuth I will have a look.

**Comment by skalk** [comment]
Again, the kernel tried to print using `warning`, but core's console log was held by a core thread at that time. We have to find a general solution here, but for the time-being I've eliminated all direct calls of log/warning/error in the kernel and replaced it by `raw`, which is lock-free.

**Comment by skalk** [comment]
@chelmuth please, consider commits 356eab2 and 5130c1f for staging, it fixes this issue for the time being. A solid, general fix for the log/lock problem in base-hw is necessary, but should be part of a separate issue.
