### ISSUE TITLE
vmm_arm.run: independance from drivers

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3278]
The current exemplary automated run-script to test the ARM virtualization extension support in base-hw is dependent on a UART driver of the corresponding Arndale board - the only hardware we used for this until now. In preparation to move the test to other hardware as well (imx7d_sabre), and because it is no good idea in general to share the same UART device in between kernel and userland driver. I'd like to make the example independent of that driver.
Currently, it is used to expect for a kernel prompt of the VM and then send the `ls` command to it, and check for the returned output.
We can easily take away the driver dependency when waiting for the VM UART output on target instead of doing this remotely. The paravirtualized UART interface uses Genode's Terminal service as backend. So a terminal client expecting some input and then sending a corresponding line should do the trick. VMM and that new terminal client can get combined via terminal_crosslink.

**Comment by nfeske** [comment]
That's a cool idea!
