### ISSUE TITLE
Modernized block-session client API

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3283]
Currently, block-session clients have a hard time implementing asynchronous I/O correctly because the framework does not aid the client-side implementation. Many clients use the interface in a synchronous fashion to keep things simple. The rare places where the client works asynchronously (part_block), the code is quite complicated. To improve the situation, we should introduce a new API in the spirit of the server-side block-request stream. This API should take care of the following:

* Simplify the manual handling of corner cases like a congested submit queue or an allocation failure within the packet-stream buffer.
* The bookkeeping needed for managing multiple outstanding requests.
* The batching of requests whenever possible to loose the coupling between client and server.

**Comment by nfeske** [comment]
Commit https://github.com/nfeske/genode/commit/6415fdf3edb05213f12d43a806d6c9b73a5ca978 implements the new client-side API.

Commit https://github.com/nfeske/genode/commit/a568bf9762a8ceca01d6be7815922f0590803c3f adjusts the block tester to the new API.

**Comment by nfeske** [comment]
Thanks to @chelmuth's help with troubleshooting one last corner case, the implementation is complete now. I merged the commit series to staging now.

Now it would be nice to revisit the various block-session-related components. Clients should use the `Block::Connection::Job` interface provided by `block_session/connection.h` whereas servers should use the `block/request_stream.h` interface. The most interesting component is probably part_block, which plays both roles.

**Comment by nfeske** [comment]
@ehmry BTW, Solo5 needs an adaptation again. Maybe you could take this as an opportunity to exersice the new API? ;-)

**Comment by ehmry** [comment]
Solo5 updated at ca6382b58e603f35ebceeb84c32cf599e5966645.

**Comment by ehmry** [comment]
I have a new port pin for Solo5, I'm still using the old style because I only need synchronous transfer, and would wait for a synchronous wrapper to jobs.

**Comment by nfeske** [comment]
@ehmry just as inspiration, a synchronous wrapper should look like this (just a sketch):

```
void write(uint64_t block_number, size_t count)
{
  Block::Operation const operation {
    .type         = Block::Operation::WRITE,
    .block_number = block_number,
    .count        = count };

  /* job as local variable */
  Job job(_block_connection, operation);

  do {
    _entrypoint.wait_and_dispatch_one_io_signal();
  } while (!job.completed());
}
```

**Comment by nfeske** [comment]
Oh. I forgot one the call of update_jobs in the example, updating...

**Comment by nfeske** [comment]
Now the sketch above should hopefully be more useful. ;-)

**Comment by chelmuth** [comment]
Issue marked fixed, commits entered master. Can we close this now?
