### ISSUE TITLE
sel4: all tests on imx7d_sabre fail

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3292]
The kernel configuration is missing some values and a user-level timer is missing.

**Comment by skalk** [comment]
@chelmuth @nfeske be aware that the timer won't work without recent changes of @alex-ab regarding the mapping code of base-sel4 (refer to commit a85888c96fd6c879546fc6944cf9c3b5298f60bc)

**Comment by nfeske** [comment]
Merged to staging.
