### ISSUE TITLE
Update e2fsprogs

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3314]
The e2fsprogs port should be updated to version 1.45.0 for compatibility with the next FreeBSD libc.

Ref #3289

**Comment by chelmuth** [comment]
If my remark was addressed we could mark this issue as fixed.

**Comment by ehmry** [comment]
I would defer e2fs until the libc has settled, unless someone else would like to update it.

**Comment by nfeske** [comment]
mkfs.ext2 works fine on Sculpt with the current libc. There is no work planned regarding this issue.
