### ISSUE TITLE
Deprecate board-specific build directories

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3316]
Now, that we have issue #2190 solved, we can use architecture-specific build directories only, to build all components. This stays in line with the depot packages which are only dependent on the hardware architecture too. The only issue left is that the majority of run-scripts is dependent of the board's SPEC. To solve this, we could use a BOARD variable analoque to the KERNEL variable, like:
```
build/arm_v7> make run/demo KERNEL=hw BOARD=pbxa9
```

**Comment by tomga** [comment]
Do I correctly understand that for this issue you will implement building distinct bootstrap and core for hw kernel in one build directory? Will the be differently named similarly to driver binaries in #2190?

**Comment by skalk** [comment]
@tomga you are right that bootstrap and core libraries have to be named according to the used board when sharing one build directory. The actual core and bootstrap binaries for hw are carrying the boot modules used in a scenario and end up in the `var/run` directory of the corresponding scenario. They get overriden whenever the run-script gets invoked, so I think we do not need to name them differently in there.

**Comment by chelmuth** [comment]
Beside my remark about muen I'm fine with both commits and like to enter the integration phase. @nfeske do you object? @skalk AFAICS we do not have to adapt our CI as the changes are backwards-compatible, right?

**Comment by nfeske** [comment]
No objection from my side. Thanks a lot @skalk for this huge effort!

**Comment by skalk** [comment]
@chelmuth @nfeske: thanks for the review, and sorry for overseeing that I commited a preliminary result. I've now updated my merge_to_staging branch accordingly. Now, everything should work, and should be downward compatible. Please, re-read especially the first of the two commits again.
