### ISSUE TITLE
platform_drv (x86): having too many PCI devices results in empty report

### ISSUE THREAD

**Issue by NobodyIII** [genodelabs/genode#3317]
I recently installed an NVMe 1.2 M.2 SSD in my AMD Ryzen-based desktop computer. I discovered that Sculpt doesn't detect it, and that with it installed, the platform driver fails to report any PCI devices, which also makes the WiFi option unavailable. What might be causing this, and what can I try to diagnose/fix it?

**Comment by NobodyIII** [comment]
To clarify, I do get the pci_devices report, but all it has is `<pci/>`.

**Comment by NobodyIII** [comment]
I examined this further, and found that along with USB working, I could get the NVMe driver to detect and mount my SSD when I force-enabled the driver. So the problem seems to be some slight difference between the PCI detection when reporting devices and when the drivers search for the devices.

**Comment by NobodyIII** [comment]
It turns out that the error was actually a simple variable scope issue. The platform driver uses an Expanding_reporter, which regenerates the report if it was larger than the initial report size. The device BDF counters were initialized outside of the lambda function used to generate the report, so they weren't reset when the report was regenerated, which made the new report start after the last PCI device. This led to an empty report.

So the only real difference that adding the M.2 SSD made was adding another PCI device to report, which made the report too big. Which, ironically enough, made the final report completely empty.

**Comment by NobodyIII** [comment]
By the way, I realized that I had spaces instead of tabs. For my job, I'm expected to use spaces. For Genode, I'm expected to use tabs. I created a fixup commit: 5fa6a103674babaa05adb8e1a74ecfe1f0fe8353

**Comment by nfeske** [comment]
Thank you for reporting, investigating, and fixing this issue. I appreciate it a lot!

**Comment by NobodyIII** [comment]
You're welcome. I'm glad to have it working now. :)
