### ISSUE TITLE
Cache performance benchmark

### ISSUE THREAD

**Issue by ValiValpas** [genodelabs/genode#3321]
When I recently enabled L2 on the zynq boards, I implemented a simple cache performance test. The test accesses continous memory regions of different size and uses the `Trace::Timestamp` to measure the access time per KB. I used this test to compare the performance before/after enabling the cache. However, I think it could have a more general use as it reveals the number and size of cache levels.

**Comment by chelmuth** [comment]
Merged into 19.05.
