### ISSUE TITLE
hw: implicit non-architectural SPEC include path interference

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3336]
The existence of non-architectural SPEC include pathes like `include/spec/imx53` in different repository locations leads to problems in the imx53_platform_drv building. Because of the different board-specific platform_session APIs (see issue #3299) and the need to build the platform drivers by the depot tools (with architectural dependencies only), a workaround in the form of:
```INC_DIR += $(call select_from_repositories,include/spec/imx53)```
was used. But as long as those pathes exists in other repositories than os as well, this does not work. In base-hw there was such a path used to export the normal world's RAM portion for ARM TrustZone.
In general, there is no need to implicitely include all kinds of APIs. If the component is dedicated to the specific API, we can explicitely use a corresponding path.

**Comment by nfeske** [comment]
I welcome this change. It makes the used headers straight-forward to see.
