### ISSUE TITLE
Qt5 run scripts are incompatible to image/disk in QEMU_RUN_OPT

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#3340]
The run scripts add two disk devices - test.hda and the run disk image - and Qemu (version 3.1.0 in my case) tries to boot test.hda only which fails.

**Comment by chelmuth** [comment]
I'll close this issue as we can easily fall back to other image types.

**Comment by cproc** [comment]
@chelmuth: it looks like this issue was fixed by 2954abb
