### ISSUE TITLE
nova: remove 'register' keyword from utcb.hpp

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3350]
The 'register' keyword is not allowed anymore with C++17 and removing it did not show a difference with the generated code.

**Comment by cproc** [comment]
@alex-ab: fixed in https://github.com/cproc/NOVA/commit/6f6498c4f4dc19892fc35ef5f5868c967248a1af

**Comment by alex-ab** [comment]
@cproc: added to my r10 branch (4276528a5c01f0429e5f1d204b80860547c8fa12), do you create a genode commit ?

**Comment by cproc** [comment]
Thanks @alex-ab. Genode commit is bdd7817.
