### ISSUE TITLE
ada-runtime: update to GCC 8.3.0

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3362]
The current 6.3.0 version of the runtime appears to work with the upcoming Genode 19.05 tool chain with some small adjustments [1], but it might be useful to update the runtime files to version 8.3.0.

@senier, @jklmnn: would you be interested in doing this update? My issue3307 branch [2] can be used as basis for testing with the new tool chain.

[1] https://github.com/cproc/genode/commit/07078f96a0c518647532f87fe26e5a0607648983
[2] https://github.com/cproc/genode/tree/issue3307

**Comment by senier** [comment]
We plan to do this. There is an [upstream ticket](https://github.com/Componolit/ada-runtime/issues/26) already.

**Comment by jklmnn** [comment]
I created a pull request for the latest ada-runtime.

**Comment by chelmuth** [comment]
Fixed in master.
