### ISSUE TITLE
pdf_view: copy URIs to clipboard

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3364]
I have a demo for a presentation that involves clicking on links in a PDF.

**Comment by ehmry** [comment]
Patch at 1fc53ee8d2477b92157a4aab1df68931177350d8.

**Comment by chelmuth** [comment]
I'm willing to merge this patch. Any objections?

**Comment by nfeske** [comment]
I object the probing of the report-session creation. The Pdf_view should instead act according to its configuration. E.g., constructing the clipboard reporter when `<config clipboard="yes">` is set. As another suggestion, I'd recommend using the `Expanding_reporter`.

**Comment by nfeske** [comment]
I'm closing this issue because its relevance and state has been undecided for a long time now.
