### ISSUE TITLE
sculpt: inprecise documentation about making customizations persistent

### ISSUE THREAD

**Issue by tomga** [genodelabs/genode#3381]
Missing information about GPT being a required type of partition table.

**Comment by nfeske** [comment]
Thanks for improving the documentation. I merged https://github.com/genodelabs/genode/commit/6675776f0d85c1769a52a28e23e8e2fcc020c26a to staging. I just shortened the first line of the commit message to fit into 50 characters (good practice). Are you fine with this tweak?

**Comment by tomga** [comment]
Yes, of course.
