### ISSUE TITLE
tool/run: power_on with external command

### ISSUE THREAD

**Issue by tomga** [genodelabs/genode#3385]
I'm preparing to run automated tests on my raspberry pi boards. I have setup an Arduino like board that (with addtional module with relays) allows mi to perform resets of rpi. I can control this from linux with a python script using firmata library. This description is mostly to show that it is a custom non-generic solution.

To intergrate with run tool I implemented a simple power_on/command extension that calls external command that perfoms a device reset. and can be used with something like:
```
RUN_OPT += --include power_on/command
RUN_OPT += --power-on-command-cmd /script/do_reset.sh
RUN_OPT += --power-on-command-param device1
```
Maybe it may be useful to someone else.

**Comment by chelmuth** [comment]
Let me reopen this for consideration after the release.

**Comment by tomga** [comment]
@chelmuth, currently it is about after release, so maybe you could consider it? There is no need to have it open, I think, unless you are interested in it but with some changes.

**Comment by chelmuth** [comment]
@tomga merged to staging
