### ISSUE TITLE
libc: silence noncritical dummy implementations

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#3389]
The same behaviour, i.e. return true for all fds, existed in the old libc as well but without the warning. We will have to provide a proper implementation eventually but for now it prefer to keep the noise down.

**Comment by chelmuth** [comment]
With the libc update I also experienced lots of
```
posix_fadvise
sysctl for [6][10])
```
warnings. Could those also be silenced like above?

**Comment by cnuke** [comment]
I have not looked at `posix_fadvise` but the sysctl is warning is the `HW_FLOATINPT` query  (see 87b58fd).

**Comment by chelmuth** [comment]
@cnuke thanks for reminding me of the `sysctl(HW_FLOATINGPT)` patch. I renamed this issue appropriately and stashed both commits. I also learned `posix_fadvise()` was already silenced. but looking at noux_tool_chain_auto there are still many warnings about `signal not implemented`. May we mute this too or is it some WiP?

**Comment by cnuke** [comment]
Since we return `SIG_ERR` in the dummy implementation and all test-cases currently seem to work fine I don't mind making it silent too. When we enable signal handling in the libc we'll have to change it anyway (which hopefully will happen in the next release cycle).

**Comment by cnuke** [comment]
@chelmuth please merge 2b28997 (fixes ieee754 test) and 642d1e5 (silence signal) to staging.

**Comment by cnuke** [comment]
@chelmuth please merge f9d5d33 (vim calls sigaction repeatedly).
