### ISSUE TITLE
Sculpt version string handling

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#3403]
The Sculpt version string, used to generate a suitable index path and URL, is limited to 6 bytes, i.e. just enough to store `YY.MM\0`. It is populated by reading the `VERSION` ROM module that is normally created at integration time in *sculpt.run* (where `\n` is deliberately added to the string). If the content of the ROM module is longer it will be silently truncated. If it is shorter the `\n` becomes part of the path and URL and will break deployment.

For obvious reasons it is up to the integrator to make sure to provide a proper version string and I just stumpled upon the limitation because I used to add a suffix to my Sculpt version, e.g. `19.06-p1` for testing purposes before CE which I also did now for the current testing build. I don't mind using another scheme for tagging testing builds as handling abitrary sized version strings (or rather merely increasing the length) comes with its own bag of subtleties and probably could be post-poned until it is needed (so far there was no breaking sub-month release). That being said, I think it makes sense to document the constraint in the run script.

**Comment by nfeske** [comment]
Thanks for improving the documentation. Merged to staging.
