### ISSUE TITLE
hw: support for ARM64

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3405]

**Comment by skalk** [comment]
Current state comes to the point where the kernel wants to proceed the first time with the first core-thread.

**Comment by skalk** [comment]
The fundamental things are running on Qemu/Rpi3, therefore I mark this issue as done.

**Comment by nfeske** [comment]
Fantastic!

**Comment by skalk** [comment]
Now, it also works on Raspberry Pi 3 hardware.

**Comment by m-stein** [comment]
:-)

**Comment by nfeske** [comment]
I have to express my deep respect for @skalk's work here again. The code is simply a pleasure to read and a poster child of Genode's API building blocks at work. It is so carefully crafted that it has a certain text-book quality to it. I also appreciate the separate commit for the interface change preceding the actual 64-bit commit. It is nice to see interface changes decoupled from large additions.

Thanks Stefan for your great care!

**Comment by m-stein** [comment]
Thanks also, the code is indeed enjoyable to read! I wonder whether it would be a desirable to have an back-end for the ``Register_set`` template that targets ARM co-processor registers? These registers are widely used and currently, the most convenient way to access them are macros, a new back end would eliminate the need for macros.

**Comment by skalk** [comment]
Thank you for your nice compliment!
