### ISSUE TITLE
Modernize graphical-terminal color palette

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#3406]

**Comment by nfeske** [comment]
Very nice! Going to try this out in Sculpt...

**Comment by chelmuth** [comment]
Fixed the leitzentrale.config adaption in ac95dd2fb0823fab129879c8be9e6a52cb754e84

**Comment by nfeske** [comment]
Merged to staging. The merged commit includes an additional fix for the inspect window of Sculpt's Leitzentrale.

**Comment by ssumpf** [comment]
That is really great!

**Comment by m-stein** [comment]
:+1:
