### ISSUE TITLE
depot_autopilot: enable for ARM 64-bit platforms

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#3407]

**Comment by skalk** [comment]
I've rebased @ssumpf work on top of staging and my work regarding issue #3405, and added the necessary package to run depot_autopilot also on base-hw rpi3.

**Comment by m-stein** [comment]
@skalk @ssumpf It's really cool to see that you've managed to make almost the whole depot autopilot "suite" run on ARMv8 in such a short time.

**Comment by chelmuth** [comment]
It's integrated in our nightly.
