### ISSUE TITLE
rtc_drv is unreliable on okl4 and pistachio

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#3413]
Both microkernels use the RTC (I/O ports 0x70/0x71) internally for timing at runtime (not only intiially). Therefore, the rtc_drv may produce wrong results if it is preempted while interacting with the CMOS.

The timing source is configurable in both kernel, but it is unknown if this helps.

**Comment by chelmuth** [comment]
I'm curious how #3438 will affect this issue...

**Comment by chelmuth** [comment]
I'm no longer curious as *run/rtc* fails on both kernels frequently with `Error: Test execution timed out` after setting the RTC to 2069.

**Comment by nfeske** [comment]
We will not fix this issue for OKL4 and Pistachio.
