### ISSUE TITLE
resize2fs: denies to expand fs on sculpt image (based on 19.05 master)

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3416]
```
resize2fs 1.42.9
The filesystem is already 5696 blocks long.  Nothing to do!
```

Expanding is denied with the above message. I used a "golden" stick on a x250. The same stick on the same machine with sculpt-ce works flawlessly.

**Comment by nfeske** [comment]
Fixed by https://github.com/genodelabs/genode/commit/97f634d80f9630911f1cba88a372d50c3b2ab992
