### ISSUE TITLE
util/print_lines: don't skip end of long lines

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#3422]
The print_lines utility currently just skips the end of over-sized lines. It should rather split-up an over-sized input line to multiple consecutive output lines.

**Comment by m-stein** [comment]
Fixed:
952d7b0de7 util/print_lines: don't skip end of long lines

**Comment by m-stein** [comment]
I've adapted the commit according to the suggestions of @nfeske and tested it for correct output with different line lengths:
b2d87facaf7 util/print_lines: don't skip end of long lines

**Comment by m-stein** [comment]
I've tested the version suggested by @nfeske and added documentation. The documentation may as well be removed:
a90165d46c util/print_lines: don't skip end of long lines

**Comment by m-stein** [comment]
@nfeske I have to correct myself: Your version does print an extra empty line for each line that is <= MAX_LINE_LEN. This is because the '\n' now gets copied to the buffer and is not overwritten with a '\0' as before. I was not able to quickly find a solution that is not as complicated as my second suggestion.

**Comment by m-stein** [comment]
@nfeske maybe this one?
63103eaaa1 util/print_lines: don't skip end of long lines

**Comment by nfeske** [comment]
The latest version looks good. Thanks for the welcome improvement. I merged the commit to staging.
