### ISSUE TITLE
hw: i.MX8M Quad Evaluation Kit support

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3426]

**Comment by skalk** [comment]
Ok, interrupts are not working correctly yet. But I pushed it so that @ssumpf and @alex-ab can take over.

**Comment by cproc** [comment]
With commit 8b653a3, the lwip test succeeds on i.MX8.

@ssumpf: not entirely sure about the 'Ctlr' structure change, but this version matches the one described as "When access is Non-secure, in a system that supports two Security states" in the GIC manual.

**Comment by ssumpf** [comment]
@cproc: Good work! I to have misinterpreted the `ITEMS` field of an `Register_array`. Yeah, the secure non-secure thing is annoying. To my knowledge I thought we are secure in bootstrap on imx8, but who knows.

**Comment by cproc** [comment]
@ssumpf: I changed the structure only because the comment says "(non-secure access)". It didn't seem to make a difference though.

**Comment by cproc** [comment]
So, it is secure access on i.MX8. I reverted the struct change and changed the comment accordingly.
