### ISSUE TITLE
tool/depot/publish: use multiple threads in xz

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#3431]
Publishing all archives takes a considerable amount of time in our nightly CI because `xz` is used single-threadily[sic] and we cannot take advantage of the beefy build machine. However, it features support for multi-threaded (de-)compression for some time now, so let's switch it on by using `--threads`. AFAICT it is a no-op in older versions (*5.1.0alpha* as used in Ubuntu 16.04 LTS) but the options is still recognized.

**Comment by cnuke** [comment]
@chelmuth please add 7628918 to staging. I'll add a more recent `xz` version to the build environment on the build machine.

It should be noted that using threaded `xz` will lead to larger archives (the vbox5 src archive is about ~1% (400KiB) larger).

**Comment by nfeske** [comment]
I wonder, have you tried invoking the publish tool with `-j` and let make do the parallelization?

**Comment by cnuke** [comment]
No, I worked with the (presumably) out-dated knowledge that the `publish` does not support jobs.

**Comment by nfeske** [comment]
Maybe you are right. Admittedly, I haven't checked if -j works. I'm not aware of a fundamental reason why if shouldn't.

**Comment by cnuke** [comment]
I stand corrected, using jobs works after all. I changed the CI tools and now feed the list of to-be-published archives via `xargs` to `publish -j32` - let's see how that works out.

**Comment by cnuke** [comment]
Unfortunately publishing *pkg* archives failed because of missing dependencies, which prevented the archives from being published at all as the *keep-going* flag was missing.
