### ISSUE TITLE
Add abstract Audio_out frontend

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3435]
As I see it, a prerequisite for reversing the audio drivers and re-engineering the audio services (#2858) will be creating frontends for audio so that simple audio applications may avoid working directly with packet streams. This allows packet streams to be refactored without affecting high-level application code.

**Comment by ehmry** [comment]
Patch at ac853252c34c25aa69c6613cc476b27dee24b53b. I have a branch where drivers use the same class, but that must wait.

**Comment by nfeske** [comment]
Superseded by the OSS plugin.
