### ISSUE TITLE
Sculpt clipboard support

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3437]
There exists a clipboard component (Issue #1712) for Genode since a long time. This component should be integrated into Sculpt to allow users to copy and paste text between VMs, terminal instances, and Qt5 applications.

**Comment by cnuke** [comment]
@nfeske please see my fixup for *machine.vbox* in 3e1b9659d59b6841e.

**Comment by nfeske** [comment]
Merged to master.
