### ISSUE TITLE
rtc_drv: allow setting the RTC

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#3438]

**Comment by cnuke** [comment]
As mentioned during lunch, naming stuff is difficult - so feedback regarding this is appreciated.

**Comment by nfeske** [comment]
This looks good to me.

**Comment by chelmuth** [comment]
Looks good to me too beside my inline comments and the suggestion to rename *set-rtc* to *set_rtc* as we still try to stick to the underline resource-naming convention.

**Comment by cnuke** [comment]
79bee22 addresses the remarks.
