### ISSUE TITLE
arora browser does not load websites since libc update

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3439]
There's a new warning in the log, but it might not be related to the problem.

```
[init -> arora] Warning: getifaddrs: getifaddrs not implemented.
```

**Comment by ehmry** [comment]
I added `getifaddrs` to dummies because it was a missing during the port transition, so this really could be the problem.

**Comment by ehmry** [comment]
I have `getifaddrs` implemented at d7f24d8bca3790a819c2b5974614e2a48d26bd63, though I have not tested it with Arora.

**Comment by cproc** [comment]
With Arora, 'getaddrinfo()' still failed, apparently because the 'IFF_UP' flag was not set in the 'ifa_flags' struct member.

**Comment by ehmry** [comment]
Fixup at 34b042158333e8108a91f6214b37ce41a8de35f7, from what I can see IFF_UP is the only flag that can be reasonably set.
