### ISSUE TITLE
hw: derive timer, pic, and cpu  from board.h

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3445]
Analogue to other SoC/Board relevant resources the concrete devices should be referenced explicitely by the board header instead of transparently putting them into the include pathes. Thereby, we lower the burden for developers that integrate new boards, and do not need new directory structures for each shared device, like generic ARM timer, gicv2, or gicv3 etc.
As a side effect, the semantic equivalent implementation of the generic timer for imx7 and rpi3 can be unified.
I favor this cleanup efforts before adding the next ARMv8 platform (i.MX8), because it will bring in the next PIC implementation and share the generic timer too.

**Comment by m-stein** [comment]
@skalk It's really cool to see that you keep simplifying the kernel code. Sums up again to -200LoC. Thanks!

**Comment by skalk** [comment]
@m-stein thanks for the kind words.
