### ISSUE TITLE
acpica: successively growing RAM usage on repeating calls to _BIF

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#3454]
On Fujitsu S936, evaluating the _BIF method on each battery-info update successively increased the RAM usage, while  _BST (dynamic battery status) and _STA (generic status) did not show this behavior. The root cause for the increased RAM usage is still shady. While it could just be normal that it grows until a certain yet unknown limit, there may also be memory leak in contrib code or some strange AML on the designated notebook.

The commit below mitigates the current effect for _BIF.

**Comment by nfeske** [comment]
@chelmuth told me that the mitigation is sufficient.
