### ISSUE TITLE
[Sculpt OS] Found not added extra VirtualBox HDD drive

### ISSUE THREAD

**Issue by cenapatop** [genodelabs/genode#3459]
When I add an extra device in the Adapter it will not found the correct HDD.

If I add it in the same SATA device, it will show the wrong partition table. Where it only can be formated.

If an extra SATA device will created, it doesn't work too.

And I dont really know how it should be possible to mount an extra device [When I split the ahci-1 device to two partitions with an linux cd. It is not possible to mount two partitions. And it will break if I update the Depot list.

**Comment by chelmuth** [comment]
The standard Sculpt OS does not support concurrent use of multiple storage devices/volumes.
