### ISSUE TITLE
Delete control character isn't correct set!

### ISSUE THREAD

**Issue by cenapatop** [genodelabs/genode#3460]
In /config/special.chargen the KEYDELETE must be replaced with asci="127"

<key name=“KEYDELETE" ascii="127"/>

**Comment by chelmuth** [comment]
You're right, this change qualifies as work-around for the current terminal-bash combination. But DELETE as the other special keys (e.g., HOME) are destined to be handled explicitly by the Input clients as they do not produce real printable characters.

**Comment by cenapatop** [comment]
Any idea how to fix it?

asci="127" doesn't works correct. It deletes on the right, and not on the left.

**Comment by chelmuth** [comment]
@cenapatop sorry for the silence but I'm currently AFK most of the time. If you like KEY_DELETE to act like KEY_BACKSPACE you may just use `ascii="8"`.

**Comment by chelmuth** [comment]
Can we close this issue?

**Comment by cenapatop** [comment]
I think yes. But I'am not sure if this fix really works for every keyboard type!

**Comment by chelmuth** [comment]
According to my recent experience with common PC keyboards this solution is quite sufficient (i.e. all keyboards had the <kbd>Del</kbd> key at the same physical position with is `KEY_DELETE`).
