### ISSUE TITLE
stderr cannot be dup()ed

### ISSUE THREAD

**Issue by senier** [genodelabs/genode#3477]
In a libc application `dup()` fails on `stderr` (fd 2, probably true also for stdin and stdout):

```sh
[init -> test_dup_stderr] Error: dup: dup not implemented
```

Is that supposed to work? Am I missing some particular VFS plugin?

Background: I need that for a (preexisting) test suite that `dup()`s `stderr` to some temporary file descriptor, redirects `stderr` to a file and later restores stderr using the temorary fd. Right now, the initial `dup()` fails and thus `stderr` cannot be restored.

**Comment by nfeske** [comment]
The commits above add a simple test and implement the feature. However, I haven't stressed it so far.
