### ISSUE TITLE
depot_deploy: report when init config is complete

### ISSUE THREAD

**Issue by trimpim** [genodelabs/genode#3482]
I have a use case, where I need to know, when depot_deploy has created the final `init.config`.

**Comment by nfeske** [comment]
I merged your commit along with a fixup 93b2ff91ce5c1b80ef3fa0a21ed1784a88b5da31 to staging. The fixup adjusted the style a bit, removes the exception handling, and makes the reporting dynamically configurable.

@trimpim can you please give the result a retry?

**Comment by trimpim** [comment]
@nfeske my test for this works with your patch.

**Comment by nfeske** [comment]
Fixed in master.
