### ISSUE TITLE
noux: avoid absolute library path names

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3500]
In the current version of ports/mk/gnu_build.mk, the GNU build system is invoked with a list of libraries specified as a list of absolute path names. Unfortunately, those names end up as runtime linking dependencies in the executable binary. In order to determine the name of the ROM module to load, the dynamic linker strips off the leading path.

A cleaner solution would prevent absolute path names ending up in the binary in the first place. This can in principle be achieved by specifying libraries with the `-l` prefix and the library-search path via `-L`.

**Comment by chelmuth** [comment]
Merged into master.
