### ISSUE TITLE
fix compile warnings in test/vfs_stress

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3516]
There are a couple of compile warnings about possibly unintended fall-though cases in switch statements.

**Comment by nfeske** [comment]
Commit https://github.com/nfeske/genode/commit/b13aa8ad626c7e4dfa1dee78ac9ce43f848999c4 removes the warnings. However, I'm not completely sure about possibly intended fall-though cases. @ehmry I wonder, is the patch ok from your perspective?

**Comment by ehmry** [comment]
I believe all these fall-throughs are intentional, so I have a fixup to annotate that at 16cabfa76367720d2a79110108343b7ad0bb16c5.

**Comment by nfeske** [comment]
@ehmry thank you for the quick response and your patch. I'm grateful that you prevented my ill-conceived patch from entering staging. ;-)
