### ISSUE TITLE
block_tester: use heap for scratch buffer

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#3539]

**Comment by nfeske** [comment]
What do you think of doing the `alloc` and `free` of the buffer at the constructor / destructor of the `Scratch_buffer`, roughly following the pattern of `Buffered_xml`: https://github.com/genodelabs/genode/blob/master/repos/os/include/os/buffered_xml.h

**Comment by cnuke** [comment]
Right, thanks for hint - that is indeed a good idea, see fe57bf3.

**Comment by nfeske** [comment]
Thanks for the update. I merged the new commit to staging.
