### ISSUE TITLE
Support a larger number of threads

### ISSUE THREAD

**Issue by taruti** [genodelabs/genode#354]
To support a larger number of threads support upgrading rm and cpu sessions. Patches pending.

For the most platforms the thread context area per process is limited to 256 threads. For base-nova the overall number of client threads in the system is 256, because every client thread needs a pager thread in Core and Core can also only start 256 threads.

**Comment by alex-ab** [comment]
The base-nova specific limitation of 256 threads in the overall system is fixed by #1394.

That no more than 256 threads per process can be created still applies - but should be not a problem. Or do we have  such applications? If not - we should close this issue.

**Comment by nfeske** [comment]
I think we can close it since the limitation in core in gone now. I don't see a concrete use case where the thread limitation outside of core would hurt us.
