### ISSUE TITLE
base: timeout framework not smp-ready

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3548]
The interface of the timeout framework is missing the ability to provide an entrypoint to the Timer::Connection , instead the entrypoint of the provided Env is used implicitely. This is not desired in smp-aware contexts where the timeout handler should be executed on a dedicated entrypoint.
The only way by now to circumvent this, is the construction of another Env with the correct entrypoint. To me this does not seem to be the right approach, instead providing the right Entrypoint to Timer::Connection explicitly is desireable. Opinions?

**Comment by nfeske** [comment]
Merged to staging.
