### ISSUE TITLE
libusb: split port into library and VFS plugin

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#3549]
The current libusb port spawns an additional entrypoint for ACK-signal handling.

https://github.com/genodelabs/genode/blob/4a7b0e99a679f80d00668961e6abaa8605aa9cad/repos/libports/src/lib/libusb/genode_usb_raw.cc#L38-L52

This entrypoint is an alien (i.e., no main thread or pthread) to the libc when calling transitively into POSIX write at https://github.com/genodelabs/genode/blob/4a7b0e99a679f80d00668961e6abaa8605aa9cad/repos/libports/src/lib/libusb/genode_usb_raw.cc#L104 and https://github.com/genodelabs/genode/blob/4a7b0e99a679f80d00668961e6abaa8605aa9cad/repos/libports/src/lib/libusb/genode_usb_raw.cc#L153 resulting in the following recurring error message.

```
[init -> test-smartcard] Error: pthread_self() called from alien thread named 'usb_ack_ep'
```

Splitting the library into code using only the POSIX API and a VFS plugin for the low-level interaction with the Usb_session would solve this quirk in a clean way.

**Comment by nfeske** [comment]
Fixed in master.
