### ISSUE TITLE
depot_autopilot: rework log matching

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#3555]
The current log-matching algorithm has several drawbacks:
* It does sanitizing mixed into the matching loop and only temporarily.
* It doesn't recognize patterns like "AAB" when the input is "AAAB" because on mismatches it doesn't jump back to an earlier character on the input.
* It is hard to grasp and debug because it consists of several nested loops with a lot of character pointers.
* it iterates the input for each pattern anew.

**Comment by m-stein** [comment]
This fixes the core issues:
38e0b722ab depot_autopilot: rework log matching

However, things could get more elegant by, for instance, removing Log_event::Plain_string and re-use Expanding_string instead or by trying to reduce the copy operations (there are more now). But, IMO, this has a low priority for me currently.

**Comment by m-stein** [comment]
@chelmuth Thanks for the detailed review!
I've added a fix-up on my merge_to_staging branch.

**Comment by chelmuth** [comment]
Merged to master.
