### ISSUE TITLE
hw: type mismatch on IRQ kernel object destruction

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3560]
core uses `Kernel_object<User_irq>`, but the kernel code casts the received object pointer to `Kernel_object<Irq>`, which has a different memory layout.

**Comment by cproc** [comment]
casts to `Kernel_object<Irq>` (github removed the template part)

**Comment by skalk** [comment]
@cproc thanks for bringing up this issue and solution. I like to review potential further semantic implications before the fix goes to staging. Therefore, I temporarily remove the fixed label.

**Comment by skalk** [comment]
Related to resolve commit of issue  #3531

**Comment by skalk** [comment]
Ok, it is indeed the only relevant place, I mark it fixed again, thanks!
