### ISSUE TITLE
dde_rump: enable arm_64 support

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3565]
Currently, we cannot run sophisticated scenarios like sculpt on ARMv8 due to missing support of the rump vfs plugin. Unfortunately, our rump version has no aarch64 support, but only much newer once. To lower the risk a backport of aarch64 to our rump version would be fine.

**Comment by skalk** [comment]
Affects #3419

**Comment by nfeske** [comment]
Wow, that was quick! I merged your commit to staging.
