### ISSUE TITLE
hw: add support for Trace::Execution_time

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3572]

**Comment by chelmuth** [comment]
@skalk do you approve these changes?

**Comment by skalk** [comment]
@chelmuth no, the wrong thread's execution time gets updated. Core is accessing a kernel object directly - well that might be ok, because it is reading only. I'll provide a patch for the execution time fixup.

**Comment by skalk** [comment]
I've re-read the commits thoroughly, and have to correct myself: the thread's execution time is accounted correctly. Sorry for the friction.
