### ISSUE TITLE
core: weight calculation not rolled-back on failed thread creation

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3613]
The [_incr_weight](https://github.com/genodelabs/genode/blob/master/repos/base/src/core/cpu_session_component.cc#L49) invocation in cpu_session is not rolled back in the case of an [exception](https://github.com/genodelabs/genode/blob/master/repos/base/src/core/cpu_session_component.cc#L69). This leads to inaccurate schedule parameters for all threads of the same cpu session.

**Comment by chelmuth** [comment]
Unfortunately, the commit breaks even *run/log*.

**Comment by alex-ab** [comment]
I see, added fe9a656109d7926ba1bcbe4194bd622ac3e4fd87 as another proposal.
