### ISSUE TITLE
Virtio device models for console and network in ARM VMM

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3620]

**Comment by skalk** [comment]
@ssumpf there seems to be a minor issue left in the virtio model. when using the modified run-script in my issue#3620 branch, one can connect to a TCP terminal running on the i.MX8 board that listens on port 4321. After that when issueing a constant network flow to the guest, e.g. by opening a telnet connection, or by using netcat, I can observe that after some time obviously the guest OS does not receive any network packet anymore, either ARP, ping or tcp responses, although the nic_router sends them to the vmm.

**Comment by ssumpf** [comment]
@skalk: Okay, will have a look.

**Comment by skalk** [comment]
@chelmuth @nfeske: This feature is finally ready for staging. The following commit series is needed: 8de7138 e3039e3 04db80b 7a5fef6 195e562 8642677

**Comment by nfeske** [comment]
Thanks for posting the commit series. Merged to staging.
