### ISSUE TITLE
hw/x86: add write combining support

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3623]

**Comment by alex-ab** [comment]
@m-stein: please try. I was not able to use the Mt: Bitset_3, maybe you can convince the compiler.

**Comment by m-stein** [comment]
Wow, cool :) I'll give it a try it in an hour when I'm in the office.

**Comment by chelmuth** [comment]
I added the fixed label as d69bf82262ebb7a8c21d8b421e1a93767b263af1 includes the *magic word*. Would you still like to change something (e.g., `Bitset_3`) before merge?

**Comment by alex-ab** [comment]
I plan from my side no changes, I would the decision up to @m-stein.

**Comment by m-stein** [comment]
@chelmuth I made some minor adaptions and pushed it on my ``merge_to_staging``:
f220a54559 hw/x86: use PAT for write combining support
5ccba8a400 hw/x86: add cpuid register macro
b1d5e6b709 hw/x86: implement wrmsr in macro

@alex-ab I didn't change the places were you wanted to use bitset ``Mt`` as I think it's quite understandable this way and I didn't get the point what would be the benefit of using the bitset, to be honest.

**Comment by chelmuth** [comment]
Merged to staging again.
