### ISSUE TITLE
app/ping: fix destination MAC on ARP replies

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#3624]
Thanks to @ssumpf we found that the ARP destination MAC address in ARP replies of the ping app was set to the Ethernet source of the request instead of the ARP source of the request.

**Comment by m-stein** [comment]
Fixed:
49aeef02b0 (HEAD -> merge_to_staging) app/ping: fix destination MAC on ARP replies

**Comment by chelmuth** [comment]
Fixed in master by a73ef9fc062983490addbad61e6ad7910ceaff14
