### ISSUE TITLE
nova: use multi dimensional Genode::Affinity to group hyperthreads in y-axis/height

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3635]

**Comment by alex-ab** [comment]
@chelmuth: i updated the issue_3635 branch according to our discussion

**Comment by chelmuth** [comment]
I rebased the commits on master and created a topic branch in my repo. Still don't know if the test program could just be dropped or renamed (from `aff` which sounds like an insult in Rheinland).

**Comment by alex-ab** [comment]
Thanks, I think the test commit can be dropped.

**Comment by alex-ab** [comment]
Just as note, the top_view packages are not yet prepared in case you want to use it with Sculpt.

**Comment by chelmuth** [comment]
I'd like to merge this soon, but need your acknowledgement that it's tested with Sculpt (or had to add the `TEMPORARY` tag.

**Comment by alex-ab** [comment]
Acknowledged - sending this message from a running Sculpt 20.02 and the patches of this issue.
