### ISSUE TITLE
ahci: switch to Request_stream API

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#3636]
Remove the dated `Block::Driver` front end and update to `Block::Request_Stream` API.

**Comment by ssumpf** [comment]
@everyone: Whoever is brave enough to test this on their hardware box, I would appreciate it. Be aware, it might swipe your hard disk :wink:

**Comment by m-stein** [comment]
@ssumpf I'll give it a try.

**Comment by cproc** [comment]
@ssumpf: I didn't see problems with ahci_block.run anymore with your latest version

**Comment by ssumpf** [comment]
> @ssumpf: I didn't see problems with ahci_block.run anymore with your latest version

Super! Thx for testing! Also thanks to @m-stein for trying out Sculpt with the latest version.

**Comment by ssumpf** [comment]
I have also successfully tested the driver on Sculpt with a Debian VM and Seoul Firefox.

**Comment by ssumpf** [comment]
@chelmuth, @nfeske: Please review 92a0559, 24a7fbb, and 52d7af5 and consider for staging.

**Comment by nfeske** [comment]
The commits look very good to me. I left two minor notes at the commits.

It is really good to see the AHCI driver becoming so tidy and neat. Thanks @ssumpf for the profound restructuring work!

**Comment by ssumpf** [comment]
@nfeske: 2284878 implements our findings

**Comment by nfeske** [comment]
Thanks for the fixup. It does indeed look much better now. Cool!

I merged your commit series to staging now.

**Comment by ssumpf** [comment]
@nfeske: de9f0ab should fix the discovery for x260

**Comment by nfeske** [comment]
Thanks to your fixup, Sculpt works nicely on my x260 again. Merged your fixup to staging.

**Comment by ssumpf** [comment]
I have added `sync` command support to the AHCI driver with 5f8666a, 04696df expands the block tester to support sync for `replay`. With part_block's sync support also enabled (issue #3652), we now support the `sync` operation for block access all the way down to hardware level. Therefore, @chelmuth, @nfeske: Please consider for staging.

**Comment by chelmuth** [comment]
Please reopen the issue or move sync to a dedicated one as this issue was closed by 8a7deae238c1d883b3e0e583a3fff1c3ab14be40.

**Comment by ssumpf** [comment]
> Please reopen the issue or move sync to a dedicated one as this issue was closed by [8a7deae](https://github.com/genodelabs/genode/commit/8a7deae238c1d883b3e0e583a3fff1c3ab14be40).

Thanks for the notice.

**Comment by ssumpf** [comment]
36b2f2a changes `read` to `write` in `Ata::Protocol::submit` in order to make the code more understandable.

**Comment by chelmuth** [comment]
Merged to staging.

**Comment by nfeske** [comment]
Merged to master.
