### ISSUE TITLE
hw: Cortex A9 SMP secondary cores diagnostic regs needs to be initialized

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3639]

**Comment by nfeske** [comment]
Merged to staging

**Comment by skalk** [comment]
@chelmuth unfortunately, this issue is already done and the commit is on staging. However, I could see today that it breaks Pandaboard support. Therefore I prepared commit 1b5d566 as a fixup. Would you mind to put it on staging?

**Comment by chelmuth** [comment]
Done by b7ce704983fa83cee90c8600c4bf762c66d9bc2f
