### ISSUE TITLE
Contribution guidelines Github magic

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#364]
A recent Github [blog post](https://github.com/blog/1184-contributing-guidelines) proposes to provide contribution guidelines via a `CONTRIBUTING` file in the repositories root directory. Should we move `doc/contributions.txt` or an excerpt of it to this file?

**Comment by nfeske** [comment]
Following the GitHub convention does not seem to have any significant effect. I suggest to ignore it and close the issue.
