### ISSUE TITLE
hw: optimize ipc receive capability allocation

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3640]
On each ipc wait or call, when there is the need to potentially receive capabilities, those need to get allocated in advance. Until now this was done simply each time, and unsed ones were freed after it. To limit the burden of frequent allocations, we can instead always hold a level of allocations, and re-allocate new ones next time when a thread waits or calls.

**Comment by nfeske** [comment]
The patch does not seem to apply cleanly to the current staging branch. @skalk could you please check?

**Comment by skalk** [comment]
I had synchronized it with the changes done by @m-stein on his issue #3308 branch. I again rebased those changes with my commit on current staging. You can use my merge_to_staging branch therefore.

**Comment by nfeske** [comment]
Thanks a lot, Stefan. I merged the commit series to staging now.
