### ISSUE TITLE
usb_block: switch to Request_stream API

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#3661]
related to #3652 and #3636

**Comment by ssumpf** [comment]
@cnuke: Do you approve the changes in c66d585? Any suggestions are welcome.

**Comment by cnuke** [comment]
@ssumpf Thanks, much appreciated - the changes LGTM :+1: (the remaining cleanup work, e.g. `static request_executed`, can be dealt with later).

**Comment by nfeske** [comment]
Fixed in master.
