### ISSUE TITLE
timespec_get symbol is missing in libc

### ISSUE THREAD

**Issue by tworaz** [genodelabs/genode#3676]
FreeBSD libc which genode uses does support it and the code is even built on Genode and exposed via libc headers. Unfortunately its not listed in the symbols file for libc so code trying to use timespec_get will fail to link.

**Comment by nfeske** [comment]
@tworaz thank you for the patch. Good to see you on the issue tracker. :-)

I will cherry-pick your commit to our staging branch by the mid of next week. Currently, we have frozen the staging branch regarding any changes that do not affect the immediate Sculpt OS release (planned for Tuesday).

**Comment by nfeske** [comment]
I merged your patch to staging now.

**Comment by tworaz** [comment]
Thanks! It'll make my life a bit easier :)

**Comment by nfeske** [comment]
BTW, it's fine to keep issues open. Since I annotated the commit message with the issue number, the issue will be closed automatically once the commit enters the master branch.
