### ISSUE TITLE
libc: file descriptors are not allocated densely

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#3679]
The POSIX standard guarentees (https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_14) the following.

>  2.14. File Descriptor Allocation
> 
> All functions that open one or more file descriptors shall, unless specified otherwise, atomically allocate the lowest numbered available (that is, not already open in the calling process) file descriptor at the time of each allocation. Where a single function allocates two file descriptors (for example, pipe() or socketpair()), the allocations may be independent and therefore applications should not expect them to have adjacent values or depend on which has the higher value.

This is practically important for instance in lighttpd which ensures to use not more than ~820 open files/sockets. It therefore allocates an `fdarray` which fits this maximum number of pointers and is indexed by the raw file-descriptor value. In libc we use `Bit_allocator` for allocating FDs which did not ensure dense allocation. This resulted in FD values higher than the number of currently open files/sockets and, thus, memory corruption due to an overflowing `fdarray`.

**Comment by nfeske** [comment]
Merged to staging.
