### ISSUE TITLE
nic_router: fix lifetime of DHCP clients

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#3681]
The NIC router currently runs into an uncaught exception when a DHCP client timeout of an interface from a period with dynamic IP config triggers after the interface was re-configured to have a static IP config. The same happens when it receives DHCP reply packets at an interface that has a static IP config (which can also occur due to reconfiguration). The general problem is that the lifetime of a DHCP client is the same as that of the interface that holds it. The lifetime of the DHCP client should be bound to the type of IP config of the interface instead.

**Comment by m-stein** [comment]
@chelmuth Thanks for your review!
I've updated the originbal commit and added another one, both tested with my sculpt + VM + switching uplink:
1c724806dd nic_router: don't call DHCP client on requests
11fef0c351 nic_router: fix lifetime of DHCP clients

**Comment by m-stein** [comment]
@chelmuth I added another commit that adds a simple test for the dhcp renew handshake:
766db9daab ping_nic_router.run: test dhcp renew

**Comment by chelmuth** [comment]
Merged as 672cb57.
