### ISSUE TITLE
Qt5 tool chain: always build without zstd

### ISSUE THREAD

**Issue by ValiValpas** [genodelabs/genode#3687]
**Short version:** When building the Qt5 tool chain, it must be ensured that zstd is not used as the default compression algorithm because the Qt5 port in Genode disables the use of zstd.

**Long version:**
On Archlinux, zstd is the standard compression for packages. Therefore, when I build the Qt5 tool chain on my system, the rcc binary will use zstd as a default. The generated code (by rcc) will thus include a reference to the symbol `qt_resourceFeatureZstd`, which is not available in the Qt libraries because, in Genode, zstd is disabled. I tried adding `--compress-algo none` to the rcc arguments. Unfortunately, there are qrc files that specify the argument `compression-algorithm="best"` for some files which happens to override the command line argument. As zstd is considered better as zlib, it will be selected in these cases.

**Solution:**
Adding the argument `-no-zstd` to the configure call when building the tool chain solves this issue.

**Comment by chelmuth** [comment]
Merged to staging.
