### ISSUE TITLE
os: use Request_stream API in NVMe driver

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#3702]

**Comment by cnuke** [comment]
Commit 11fcffc contains the change. I took the oppertunity to refactor some parts of the driver in addition to the API modification, which leads to the rather large diff.

So far the `nvme.run` tests works well on Qemu as well as on hardware. Yesterday I took the driver for a spin running in Sculpt on my DS57U test machine without any problems, today I deployed on my T470p.

@ssumpf I would appreciate if you could take a look and review the changes, I'll defer adding the fixed label until then.

**Comment by ssumpf** [comment]
@cnuke: LvGTM and the new DMA handling seems to make things easier.
Since you are at it, maybe we could take care of this also:
```
/*
 * XXX For now let the device decide if it wants to deallocate
 *     the blocks or not.
 *
 * b.write<Nvme::Sqe_io::Cdw12::Deac>(1);
 */
```

**Comment by cnuke** [comment]
@ssumpf yeah - the reason we I don't set the bit unconditionally is because AFAICT its not part of the NVMe 1.2 spec and I do not how such devices will cobe with that. At the moment the driver does not care about the version.

So the comment is there as a reminder that we could set the bit in the future. After all I intepret the spec that is merely a hint on how the device should behave.

**Comment by ssumpf** [comment]
@cnuke: Okay, thanks for the explanation. So, everything is fine from my side.

**Comment by cnuke** [comment]
Alright, thanks for taking a look.

**Comment by nfeske** [comment]
Merged to staging.

**Comment by cnuke** [comment]
@chelmuth please merge da60486 to staging.

**Comment by chelmuth** [comment]
Thanks, merged to staging.
