### ISSUE TITLE
hw: abort in core during `Hw_native_pd::upgrade_cap_slab`

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3703]
The `upgrade_cap_slab` RPC function may trigger an `Out_of_caps` exception, which is not reflected to the client.

**Comment by skalk** [comment]
Ouch, thank you for the fix!

**Comment by nfeske** [comment]
This problem triggered during my work on the tool_chain_auto scenario. @skalk could you please have a look at my patch? I fixed the abort but I am not certain that the `Out_of_caps` exception is plausible in the first place.

**Comment by skalk** [comment]
@nfeske: the upgrade_cap_slab method uses the sliced_heap of the pd_session to allocate a new slab block, and adds that to the Tslab, which is used for capability allocation of that PD. I assume that the allocation of a new ram block with the sliced_heap can trigger the 'Genode::Quota_guard<Genode::Cap_quota>::Limit_exceeded', doesn't it?

**Comment by nfeske** [comment]
@skalk that's the answer I just wanted to hear. Yes, this makes perfect sense.

**Comment by nfeske** [comment]
With commit https://github.com/genodelabs/genode/commit/88b643979ebcec34076d60588e9bf2b1110fad9e, the tool_chain_auto.run script runs successfully on base-hw now.

The commit solves a deadlock situation that could occur whenever the upgrade condition triggers during an RPC towards the parent, e.g., a session request. In this situation, the attempt to call `Env::upgrade` as a side effect of the IPC mechanism would attempt to grab the `Env::_lock` another time. The commit fixes this circular dependency by directly issuing a resource request to the parent 
instead of relying on the corner-case handling of `Expanding_parent_client::upgrade`.
