### ISSUE TITLE
part_block: partitions with index greater than 32 unavailable

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3705]

**Comment by ehmry** [comment]
Fixed at 1b8f44e80801bbb8d3dba813b72eed4c6a5a5ca6.

**Comment by ehmry** [comment]
FWIW the problematic line is here: https://github.com/ehmry/genode/blob/1b8f44e80801bbb8d3dba813b72eed4c6a5a5ca6/repos/os/src/server/part_block/main.cc#L337

**Comment by ssumpf** [comment]
@ehmry: I deliberately limited the number of sessions in order to make `_wakeup_clients` faster, but that may be premature optimization. @chelmuth: I am fine with the supposed change for my part.

**Comment by ehmry** [comment]
Does this mean I have to do a benchmark now? :P

**Comment by ssumpf** [comment]
@ehmry: Worse, two benchmarks (old and new) ;)

**Comment by ehmry** [comment]
`Main::_wakeup_clients` is on the hot path but changing the size of the array doesn't have a noticeable effect.

**Comment by ssumpf** [comment]
@ehmry: I know and was just kidding.
