### ISSUE TITLE
libc: setting rtc to year 2100 blocks application startup on 32-bit

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3707]
If changing the rtc setting in ports/run/bash.run from
```
<inline name="rtc">2018-01-01 00:01</inline>
```
to
```
<inline name="rtc">2100-01-01 00:01</inline>
```
bash mysteriously fails to start up, but only on 32-bit platforms. Smells like an integer overflow.

**Comment by alex-ab** [comment]
Just a guess - https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by nfeske** [comment]
> Nevertheless, the diff of the mentioned for-loop looks pretty suspicious and could already fix the infinite-loop issue:

Indeed, with the patch it works. Wow!

Thanks a lot for the impressive forensic achievement.

Would you mind adding the patch to repos/libports/src/lib/libc/patches/? (or me doing this?)

**Comment by nfeske** [comment]
Splendid! Merged to staging.

**Comment by nfeske** [comment]
The fix entered the master branch today.
