### ISSUE TITLE
ahci_drv: misleading error messages for empty ports

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3709]
The AHCI driver prints `Error: rejecting session request, no matching policy for '…' (model= serial= device index=1)` when in fact a policy is matched but there is no device on the port selected by that policy.

**Comment by chelmuth** [comment]
@ssumpf please review the patch

**Comment by ssumpf** [comment]
@chelmuthL Looks good! Somehow @ehmry is ahead of me.
