### ISSUE TITLE
<propagate exit="…"/> missing from init.xsd

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3724]
Fix at 30361492ee746d1c3eefe4e87b5a6c6e83a8ef40.

**Comment by nfeske** [comment]
Can you please share the reasoning behind the following two changes?

- Use a relative path for base_types.xsd
- Allow "label" attributes within `<parent-provides/>`

AFAIK, the latter is not supported by init (respectively the sandbox library).

**Comment by ehmry** [comment]
The relative path allows the XSD file to be used with xmllint without supplying a `--path` argument. The second note is about allowing `<service name="…" label="…"/>` nodes within `<parent-provides>` simply for documentation purposes. When generating deeply nested init configurations I find it useful to attach these labels so that this routing information bubbles up.

For example:
```xml
<parent-provides>
  <service name="ROM" label="core_log"/>
  <service name="ROM" label="kernel_log"/>
  <service name="Platform" label="ahci_drv"/>
  …
</parent-provides>
```

**Comment by chelmuth** [comment]
> The relative path allows the XSD file to be used with xmllint without supplying a `--path` argument.

Sorry but I'm sure `--path "base/xsd os/xsd"` is what we really want. It is equivalent to `gcc -I base/include -I os/include` which we are used to. If your environment poses further challenges with this I'd like to hear about them.

> The second note is about allowing `<service name="…" label="…"/>` nodes within `<parent-provides>` simply for documentation purposes. When generating deeply nested init configurations I find it useful to attach these labels so that this routing information bubbles up.

Readability is a valid concern and I want to support it as much as possible. But in my opinion, the addition of ineffective attributes does not improve the readability of configurations. Quite the contrary is the case: These `label` attributes suggest the wrong assumption that service requests to the parent are limited to the labels noted as with labels in policies. A much better alternative is to use XML comments for this purpose.

**Comment by ehmry** [comment]
A patch with exit only at 332f8fc9cb9d93cba7c213d4c28cd06f826714db.

**Comment by nfeske** [comment]
Thanks @ehmry for the new patch, which I merged to staging just now.
