### ISSUE TITLE
hw: avoid usage of BASE_DIR relative pathes in make targets

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3728]
Due to the firsts hardware targets supported by base-hw within genode-world (namely the zynq series) a pattern entered the base-hw Makefiles: the base-hw directory often got denoted as `$(BASE_DIR)/../base-hw` and not as $(REP_DIR) anymore, because it happened that those Makefiles got included by genode-world Makefiles. This hack was valid for a some time, although somehow ugly. With the introduction of the depot mechanisms this pattern is no longer valid and should be avoided. It hit me while retiring the Exynos5 series in issue #3725.

**Comment by chelmuth** [comment]
Merged to staging.
