### ISSUE TITLE
vfs/File_content: fix end condition in for_each_line

### ISSUE THREAD

**Issue by rite** [genodelabs/genode#3729]

**Comment by rite** [comment]
e48392a fixes the occasional segmentation fault mentioned in [1]. The segmentation fault occurred on ARMv7a/base-linux when the end address of the buffer pointed to the very end of a mapped memory region. In this case `src` happend to point to the first address of an unmapped region.

[1] https://lists.genode.org/pipermail/users/2020-March/007063.html

**Comment by chelmuth** [comment]
Well spotted! You're right that `src` should not be dereferenced if it points beyond the buffer. In my opinion, your current patch seems to lack support for cases where the buffer does not end with `0` or `\n`. Can you confirm this?

**Comment by rite** [comment]
Indeed, good point! In this case, `fn` won't be called for the last "line"...

**Comment by rite** [comment]
- 4f9c487 supports cases where the buffer does not end with `0` or `\n`
- 971cf29 removes the now redundant check whether the buffer is empty

**Comment by chelmuth** [comment]
@rite many thanks for the fixups. I'll merge the complete bugfix as one commit soon.
