### ISSUE TITLE
sandbox: defer requests to forwarded services that do not yet exist

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3733]
While revisiting the stubby_deploy.run script, I noticed that the run script relies on a corner case of init that is apparently no longer supported (presumably since #2542): the client requests a session for a server that does not (yet) exist in the sub init. Upon closer inspection, the problem can be solved by distinguishing two cases which where previously handled by outright denying the request:

- There is no policy defined for the request.
- There exists a matching policy, but the server referred by the policy does not exist.

The former must be denied whereas the latter can be deferred because the policy expresses the intent that a request is welcome in principle but cannot be satisfied at the current time. This distinction should cover the problem of #2542 while also retaining the compatibility to scenarios like stubby_deploy.run.

**Comment by sidhussmann** [comment]
@nfeske funny. I just noticed this problem not too long ago and was about to open up an issue as well.
