### ISSUE TITLE
i.MX53 interactive drivers do not work

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3735]
The i.MX53 interactive drivers (framebuffer, input) are a bit matured. They apply not only to the i.MX53 Quickstart board, as their package name suggests, but to the i.MX53 SABRE tablet too. This is not really useful, because there is a lot of logic inside the drivers to distinguish in between those different boards.
Anyway, due to the difficulties to test these drivers automatically it remained undetected that the framebuffer driver does not show something on the Quickstart board and tablet, and input driver does not even come up on the tablet.
The reasons are diverse. The differentiation of Signal_handlers into Io_signal_handlers got missed here. A hardware structure's layout (packed struct) got violated when introducing effective C++ error messages, and the interplay of timer.msleep, Entrypoint, and wait_and_dispatch_one_io_signal led to endless I2C bus initializations. Moreover, the configuration of the interactice driver package was not sufficient to be used for the tablet.

**Comment by nfeske** [comment]
Thank you very much for investigating and fixing these regressions. I merged your commit to staging.
