### ISSUE TITLE
vfs_lwip: guard 'blocked_handles' Fifo

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3738]
The 'blocked_handles' Fifo can be accessed by different threads and needs to be guarded with a mutex.

**Comment by nfeske** [comment]
Thank you. I merged your commit to staging. It is a bit painful to watch yet another instance where the VFS synchronization has bitten us. Once we have completed the transition of the libc to the monitor mechanism, we will be able to remove the mutex again and solve these kind of issues once and for all.
