### ISSUE TITLE
Remove `Allocator_guard`

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3750]
The `Allocator_guard` is not water-tight as described in #1039. For guarding the resource consumption, there exists the `Constrained_ram_allocator`, which works reliably but at the granularity of dataspaces. So there exists a clean solution but the flaky `Allocator_guard` still exists also.

We should finally retire the old `Allocator_guard` now. However, this requires some work because the utility is still used in a number of places, most notably core, nitpicker, and the platform driver.

**Comment by nfeske** [comment]
Commit https://github.com/genodelabs/genode/commit/f045e7c3a3503c389870037b78618a2f132b7fd0 removes the `Allocator_guard` from all components except for the Intel GPU driver. The latter, I better don't touch because this change would require a quite elaborate refactoring and the need for thorough manual testing. I'd defer this to the time when we pick up the practical work on GPU driver the next time. For now, I have placed a copy of the allocator_guard.h local to the component. @cnuke is that ok from your perspective?

**Comment by cnuke** [comment]
@nfeske that's perfectly fine.
