### ISSUE TITLE
depot_deploy: copy all attributes of the `report` node

### ISSUE THREAD

**Issue by trimpim** [genodelabs/genode#3760]

**Comment by nfeske** [comment]
Merged to staging.

**Comment by trimpim** [comment]
@nfeske while expanding the `deploy` file of our system with more components I have found out, that `init` fails to create the state report  when its size exceeds `4096` bytes.

2e5dc7f8d9e579b95873818b9d63d562a667b4fe also copies the `buffer` attribute that `init` reads for the size of the report buffer.

I'm not sure, if the formating in the new helper lambda is correct. If not, let me know, and I'll update the commit.

**Comment by nfeske** [comment]
@trimpim I added your fixup. No complaint about the formatting from my side. :-)

**Comment by chelmuth** [comment]
Merged to master
