### ISSUE TITLE
automate cpu_bench testsuite

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3785]
There is already a cpu_bench test in repos/os to correlate cpu run-time behaviour in between Genode and Linux as baseline. However, the test is inappropriated, because the code written in C/C++ maps to quite different run-time behaviour corresponding to the used compiler, and to which virtua address it gets linked to. To get reliable numbers we have to rewrite them in assembler.
Moreover, an automated way of detecting regressions here would be nice.

**Comment by nfeske** [comment]
Thanks @skalk for capturing the essence of your micro-benchmarking undertaking (https://genodians.org/skalk/2020-06-18-micro-benchmarking) so well. I've added your commit to staging.
