### ISSUE TITLE
imx8q_evk: increase default CPU frequency

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3788]
Certain scenarios on the imx8q_evk reach the limits of CPU usage. Currently, it runs with 1 GHz as configured by the bootloader-chain. The base-hw bootstrap code should configure it to run them with 1.5 GHz frequency instead.

**Comment by nfeske** [comment]
Cool! Beside the increase of the frequency, it is nice to see the list of magic numbers replaced be meaningful register assignments.

Merged to staging.

**Comment by nfeske** [comment]
Fixed in master.
