### ISSUE TITLE
base-linux: missing `read` seccomp policy for `wait_for_continue` mechanism

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3798]
The `wait_for_continue` mechanism in base-linux is a useful debugging feature that prompts a component to wait for a key press and thereby gives the developer the chance to connect GDB to the program at a suitable time (e.g., once the component has reached a certain state, but before it triggers a page fault). The mechanism perform a simple `read(0)` to wait. Unfortunately, this syscall is no longer permitted since seccomp has come into effect.

@throwException Do you see a risk when permitting `read`? I think it has no implications beyond those of `recvmsg`, which is already permitted. Would you agree to add `read` to the policy, potentially restricting it to FD 0 (stdin)?

**Comment by throwException** [comment]
> @throwException Do you see a risk when permitting `read`? I think it has no implications beyond those of `recvmsg`, which is already permitted. Would you agree to add `read` to the policy, potentially restricting it to FD 0 (stdin)?

I agree, there should be no security implications to adding `read` for FD 0.
