### ISSUE TITLE
tool/seccomp: allow sigreturn on x86

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#3799]
Contrary to the code comment signals are also used on x86, which requires to return from the signal handler.

During my tests I was wondering how the correct syscall numbers are picked up when generating BPF rules cross-platform. @throwException do you have more information on this? Does it work via the pseudo syscall numbers?

**Comment by throwException** [comment]
> During my tests I was wondering how the correct syscall numbers are picked up when generating BPF rules cross-platform. @throwException do you have more information on this? Does it work via the pseudo syscall numbers?

I was wondering the same thing, but came to the conclusion that the pseudo syscall numbers work well.

**Comment by nfeske** [comment]
Merged to staging.
