### ISSUE TITLE
foc: avoid transfer of internal Lock state via RPC

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3809]
Via Foc_native_cpu_client::thread_state a Lock object is copied via RPC.

I noticed the issue during adaptation from Lock -> Mutex, whereby the compiler denies to copy the Mutex object rightly.

**Comment by alex-ab** [comment]
For me it looks like that the values of 
```
        exceptions;   /* counts exceptions raised by the thread */
	bool                  paused;       /* indicates whether thread is stopped */
	bool                  in_exception; /* true if thread is in exception */
	Lock                  lock
```
are internal state and should not be transferred via RPC, please check 334976c285cad27b93a38786e124125e2a7346fc.

**Comment by nfeske** [comment]
Thanks for spotting and fixing this issue. I merged both commits to staging.
