### ISSUE TITLE
vbox5-nova: avoid triggering Blocking_canceled exception

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3810]
The transparent handling of this cancellation state is scheduled to be removed from the Genode Lock implementation and should not be triggered accidentally by the nova specific adaptations in vbox5-nova.

**Comment by alex-ab** [comment]
After a offline discussion with @chelmuth we concluded to try out to come up with a pthread condwait variant.

**Comment by alex-ab** [comment]
> After a offline discussion with @chelmuth we concluded to try out to come up with a pthread condwait variant.

f0def8b2a7dd29c87af0094c7943c9e0083b8ba1 uses pthread primitives to implement the blocking. Tested with vbox5_ubuntu_16_04 run script.

**Comment by chelmuth** [comment]
I merged the pretty slim commit to staging.
