### ISSUE TITLE
Turn framebuffer drivers from servers into capture clients

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3813]
With the capture session (issue #3812) provided by the nitpicker GUI server, all framebuffer drivers must be reworked to act as capture clients instead of framebuffer servers. Those drivers are fb_sdl, vesa_fb_drv, boot_fb_drv, imx8_fb_dv, intel_fb_drv, imx53_fb_drv, omap4_fb_drv, exynos5_fb_drv, pl11x_fb_drv, and rpi_fb_drv. Furthermore, all run scripts for graphical scenarios must be adjusted in the following ways.

* The drivers_interactive subsystem no longer provides a "Framebuffer" service, but it needs a "Capture" route instead. This one must be routed to a nitpicker instance.
* The nitpicker GUI server must be prevented from requesting a framebuffer session. This can be achieved by adding a `request_framebuffer="no"` config attribute.
* The nitpicker GUI server must be instructed to offer a capture service (to be used by the drivers subsystem). This can be accomplished by adding a `<capture/>` sub node its config. In the future, this node will be the natural place for expressing capture-client policies.

**Comment by nfeske** [comment]
Depends on #3812.

**Comment by nfeske** [comment]
The issue is fixed with commits on the branches https://github.com/nfeske/genode/commits/capture_session (genode) and https://github.com/nfeske/genode-world/commits/capture_session (genode-world) respectively.

There are few open tests that are missing. I'd be very happy about helping hands.

* The new version of the imx8_fb_drv has not been tested on the EVK yet. @skalk or @cproc or @ssumpf Could one of you please give the framebuffer.run script a try on this board?
* Although I tried to adjust the various vbox run scripts, I have executed only the bare-bones virtualbox.run scripts on Qemu. There are many more scenarios that rely on more complicated infrastructure (and VDIs). @alex-ab Shall we rely solely on the autopilot do the testing or would you try a few selected manual test runs? The latter may be worthwhile especially for the vm_stress scenarios.
* I tried to adopt and test most scenarios of genode-world. But I have not executed the scrcpy scenario. Could you give it a try with your existing Android setup?

**Comment by alex-ab** [comment]
> * Although I tried to adjust the various vbox run scripts, I have executed only the bare-bones virtualbox.run scripts on Qemu. There are many more scenarios that rely on more complicated infrastructure (and VDIs). @alex-ab Shall we rely solely on the autopilot do the testing or would you try a few selected manual test runs? The latter may be worthwhile especially for the vm_stress scenarios.
> 
> * I tried to adopt and test most scenarios of genode-world. But I have not executed the scrcpy scenario. Could you give it a try with your existing Android setup?

I will run some tests and report back.

**Comment by alex-ab** [comment]
I do not see any output for the vbox5 run scripts. It seems that due to line https://github.com/nfeske/genode/blob/capture_session/repos/libports/src/drivers/framebuffer/vesa/main.cc#L115 the best graphic mode is not tried to detect. With the fixup commit I have output, but maybe you want to fix it differently.

**Comment by nfeske** [comment]
The fixup is cool. Very pragmatic, in a good way. :-)

**Comment by nfeske** [comment]
Merged to staging.

**Comment by cproc** [comment]
framebuffer.run works on i.MX8 EVK board with fixup commit e4bf557

**Comment by nfeske** [comment]
Thanks @cproc for testing and the fixup!

**Comment by alex-ab** [comment]
> I will run some tests and report back.

The vbox5 and vm_stress scripts work now, tested on our nightly test machine.

The scrcpy scenario is not working anymore, will try to find the reason.

**Comment by alex-ab** [comment]
@nfeske: if you run/sdl or run/sdl2 one gets a very tiny window. Do you have an idea ?

**Comment by nfeske** [comment]
Now, the application may start before the framebuffer driver is up. If the application requests the mode once and never responds to mode changes, it will stay with a 1x1 pixel sized mode. I observed the same effect in the flif.run scenario.

The simplest solution would be the pinning the nitpicker domain to a predefined size using the `width` and `height` attributes.

In the longer term, it might be nice to enable SDL2 to gracefully deal with such an initial situation.

**Comment by alex-ab** [comment]
With your suggestion the scenario boots up and is working.

**Comment by nfeske** [comment]
May you share a patch for the run script that works for you (including the specific values)?
