### ISSUE TITLE
USB: Implement support for LTE MBIM modems

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#3822]
This line of work compromises `cdc_mbim`, `cdc_ncm` as ethernet device, and `cdc_wdm` as control channel. There will be two front ends: Genode's NIC sessions for `cdc_ncm` and the Terminal session for `cdc_wdm`.

**Comment by ssumpf** [comment]
@chelmuth: 33fa869 addresses your suggestions

**Comment by chelmuth** [comment]
I merged 8b1f1ba386abe27ec4b4479ae945de5358af63bb and tried to improve the commit message with some info about the driver. If you like you can provide a proper README and enhance the commit message in a squash commit.

**Comment by nfeske** [comment]
With the commits of this issue integrated in master, should this issue be closed?

**Comment by chelmuth** [comment]
> With the commits of this issue integrated in master, should this issue be closed?

This is a kind reminder: Can we close this issue, @ssumpf ?
