### ISSUE TITLE
cpu_sampler: avoid spinning in the server on unavailable state

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3826]

**Comment by chelmuth** [comment]
I merged both commits to staging, but want to double-check that the removal of *repos/base-nova/include/cpu_thread/client.h* in 73c293cb7df0aa8165759d9a43f79a48140b5c66 is intended, @alex-ab?

**Comment by alex-ab** [comment]
> I merged both commits to staging, but want to double-check that the removal of _repos/base-nova/include/cpu_thread/client.h_ in [73c293c](https://github.com/genodelabs/genode/commit/73c293cb7df0aa8165759d9a43f79a48140b5c66) is intended, @alex-ab?

Yes.
