### ISSUE TITLE
tool/seccomp: allow 'restart_syscall'

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3831]
This syscall occurred while debugging with GDB. According to a related mozilla bug tracker issue [1], allowing this syscall should be safe.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=907002

**Comment by chelmuth** [comment]
I merged your commit. The open question is still: Is the system call also needed on x86_32 and ARM? Would you mind to gather the required info?

**Comment by cproc** [comment]
Reopening for the open x86_32 and ARM question.

**Comment by nfeske** [comment]
@cproc What should happen with this issue?

**Comment by cproc** [comment]
@nfeske: the syscall occurred sporadically while debugging on x86_64. To find out if it can also occur on x86_32 and ARM, one would probably need to investigate the Linux kernel source. If it doesn't have a high priority, we could close the issue for now and reopen it if the same problem is observed on x86_32 or ARM in the future.

**Comment by nfeske** [comment]
Thank you for the clarification. So I'll close it for now.
