### ISSUE TITLE
Ada/SPARK: Exp_Int runtime support and strict warnings

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#3848]
The CBE project has raised the need for conventions regarding compiler warnings and style checks and the need for runtime support for the Exp_Int package (exponential function on integers).

**Comment by nfeske** [comment]
Merged to staging.

**Comment by cnuke** [comment]
@nfeske please merge f34a0be, 9a71936 and 3484613 to staging.

Rather than disabling the style checks I opted for fixing the code. After all, those tests are probably looked at first and should reflect the style that is enforced by the flags.

**Comment by m-stein** [comment]
@cnuke Thanks a lot for doing this tedious work! I totally agree with your motivation.

**Comment by nfeske** [comment]
That's very much appreciated. Merged to staging.

**Comment by cnuke** [comment]
@nfeske please also merge e413a98 - apparently I missed adding this change yesterday.

**Comment by nfeske** [comment]
No problem. I merged your fixup just now.
