### ISSUE TITLE
aes_cbc_4k: api recipe and import file

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#3850]
In the context of the CBE project, an API recipe for the aes_cbc_4k library became necessary. Also, dependent targets and libraries should import include directories of aes_cbc_4k.

**Comment by nfeske** [comment]
In contrast to port hashes, recipe hashes should never checked in. They are updated (semi-)automatically when updating the master branch.

I'll remove the hash parts of your commits manually.

**Comment by nfeske** [comment]
Please forget the comment above. ;-) The hashes are new. So they must be part of the commit.

**Comment by nfeske** [comment]
Merged to staging.

**Comment by m-stein** [comment]
@nfeske Thanks for reviewing and merging ;)

**Comment by m-stein** [comment]
@nfeske With that, the CBE can now be built on clean genode/staging, the bash problems in the CBE tests have also disappeared :)

**Comment by nfeske** [comment]
Thanks for the good news!
