### ISSUE TITLE
libsparkcrypto: source recipe, fixes to api recipe and make files

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#3852]
The CBE demo raised the need for a source recipe of libsparcrypto. In the context of creating this recipe, it came to light that the ALI files needed for the corresponding API recipe were not yet hosted online and that there are dependencies in the library Make files to contrib ADB files that do not exist.

**Comment by nfeske** [comment]
Thanks. Merged to staging.

**Comment by m-stein** [comment]
@nfeske Here's a fixup. Sorry for the missing hash.
