### ISSUE TITLE
libc: handle 'MAP_SHARED' flag in 'mmap()'

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3857]
qtwebengine uses shared memory via 'mmap()' to exchange data between threads (which are supposed to run in different processes, but can also run in a single process). To support this mechanism, I added handling of the 'MAP_SHARED' flag in 'mmap()' by requesting the file as dataspace from the VFS plugin and attaching it to the region map. The actual degree of shareability of a file depends on the VFS plugin. For qtwebengine I created a dedicated VFS plugin (not part of this issue) which stores the file content in a dataspace, so process-local sharing by attaching the same dataspace multiple times is possible.

**Comment by nfeske** [comment]
Merged to staging.
