### ISSUE TITLE
libc: add wrapper function for 'Genode::cache_coherent()'

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3858]
qtwebengine needs to flush caches on ARM before executing JIT-compiled JavaScript code. I added a wrapper function 'genode_cache_coherent()' for the base library function 'Genode::cache_coherent()' to the libc, which can be used by POSIX applications. The new files 'libc/genode.h' and 'genode.cc' can be used for other base library wrapper functions in the future, if needed.

**Comment by nfeske** [comment]
Merged to staging.
