### ISSUE TITLE
base_hw: Yield CPU time to specific threads

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#386]
For now the remaining  time slice of a yielding or blocking thread gets lost. When implementing explicit yielding, blocking threads could give their remaining time to a thread that the block depends on. This way IPC, Locks and other operations could get accelerated notable.

**Comment by skalk** [comment]
Isn't this implmented via issue #1102 ?

**Comment by m-stein** [comment]
This is implemented for IPC. It isn't implemented for yield causes that are not known to the kernel (most prominently locks).

**Comment by nfeske** [comment]
@m-stein Is this feature still desired, or can we close this issue otherwise?

**Comment by m-stein** [comment]
There is still the ``thread_switch_to`` which expects that the targeted thread is scheduled with the callers scheduling context AFAIK. Currently, this call does merely wake up the targeted thread if he's in the ``await_resume`` state that a thread enters via syscalls ``pause_current_thread`` or ``pause_thread``. This is not only buggy because these syscalls are not only used in locks but also insufficient because there's no guarantee that the targeted thread gets scheduled with the expected precedence.

**Comment by m-stein** [comment]
So, I would say yes.
