### ISSUE TITLE
platform driver for Raspberri Pi using new platform API

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3864]
For being able to modify existing drivers like usb_host_drv to request its device resources via the platform driver using the latest platform API, we need a specific incarnation for Raspberry Pi too. Because its platform driver needs to power certain domains.

**Comment by tomga** [comment]
@skalk and @nfeske, I have a question about 73d3698e2fe516e48aa4cfc1c79fe9c4ed397268. Some files (`mbox.h`, `property_command.h` and `framebuffer_message.h` in `repos/os/src/drivers/platform/rpi` are exact copies of files from `repos/os/src/drivers/platform/spec/rpi` and those two copies exist in both directories till today.

Do I correctly understand that `platform/spec/rpi` directory should be removed along with this commit? I'd be quite convinced about that unless I found that 8c7d34ff2161c338f072d3015112aaa1eb333dd7 introduces exactly the same modifications to both copies. 

Can you please explain me what is the idea behind it?

**Comment by tomga** [comment]
I think I found the answer. I did not remember that transition to new platform driver for Raspberry Pi is implemented only partially and now found information about it in release notes.
