### ISSUE TITLE
qt5: prerequisites for qtwebengine support

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3867]
qtwebengine itself is going to be part of genode-world, but some changes to the main Qt5 port are needed to make it work:

- update port hash for Qt5 sources with qtwebengine-related patches
- install sqlite Qt plugin
- add qtquickcontrols library

**Comment by nfeske** [comment]
Merged to staging. Note that I slightly modified the src-archive version (removing the "-o" suffix).
