### ISSUE TITLE
i.MX 8M framebuffer driver: sometimes keeps blank when initialized

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3878]
Sometimes the screen keeps blank when this driver is started. This behaviour got obvious since the driver is turned into a GUI Capture client.

**Comment by ssumpf** [comment]
@skalk: I still can reproduce the issue with the OLED display on i.MX8

**Comment by ssumpf** [comment]
@skalk: 98977dd fixes the issue for me.

**Comment by ssumpf** [comment]
@chelmuth: As stated above fcb0ca3 does not fix the issue for me, as with the commit only the scroll bar is displayed on run/demo startup. The rest remains black. The solution was to re-initiate the 'Capture' session during config updates as done in 98977dd. So please consider this one for staging.
