### ISSUE TITLE
okl4: use python2 explicitely in elfweaver tool

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3892]
Recent Linux distros deprecated python2.* and use python3 by default. Therefore, if a system-wide `python` binary exists without an explicit version postfix, it typically points to python3. Okl4's elfweaver tool is bound to python2 and should express this explicitely to not use newer versions by accident.

**Comment by skalk** [comment]
@chelmuth commit c1f9325 fixes the nightly build problems of okl4 on the upgraded build machine.

**Comment by nfeske** [comment]
Thanks. Merged to staging.
