### ISSUE TITLE
tool chain: fix build error on Ubuntu 20.04 (GCC 9)

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3899]
When building the Genode tool chain on Ubuntu 20.04, the error reported in [1] occurs. I added the fix from that bug report to the patch series.

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89349

**Comment by skalk** [comment]
@cproc wow, that was quick, thank you very much! You've saved my day.

**Comment by skalk** [comment]
@nfeske can you please incorporate cproc's patch into the staging branch? I would like to reference it in the build routine to create a Genode development container.

**Comment by nfeske** [comment]
@skalk here you go: 2491eee102b019909ecaacbe5d0cebe3491dc020
