### ISSUE TITLE
base-hw: support out of tree imx8 platforms

### ISSUE THREAD

**Issue by trimpim** [genodelabs/genode#3911]

**Comment by trimpim** [comment]
@chelmuth I think this patch has a low impact. Do you think that it is ready for integration in to 21.02?

**Comment by chelmuth** [comment]
I think so too, but @skalk should have a look and give his approval ;-)

**Comment by skalk** [comment]
@trimpim @chelmuth: I'm fine with the commit.

**Comment by nfeske** [comment]
Fixed in master.
