### ISSUE TITLE
libc: print diagnostic during raise()

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3919]
I have an application calling `raise` and the current dummy does not exit or print a helpful message.

**Comment by ehmry** [comment]
Fixed at dd8bb54f754d1f8678aa7e73ff53efc61f133170.

Before: `Warning: raise: raise not implemented`
After: `Error: raise(ABRT)`

**Comment by chelmuth** [comment]
Thanks for this pragmatic patch. I was shivering while reading the pthread-related semantics at https://pubs.opengroup.org/onlinepubs/9699919799/
