### ISSUE TITLE
base: don't throw exceptions in 'Signal_receiver::pending_signal()'

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3922]
The exceptions thrown in `Signal_receiver::pending_signal()` turned out to be quite expensive when many signals occur, for example when libc monitors are used by multiple threads.

**Comment by nfeske** [comment]
Apart from the minor cosmetic remark that I left inline, the patch is excellent.

**Comment by nfeske** [comment]
Fixed in master.
