### ISSUE TITLE
base: support process-local signal submission

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3923]
If a signal receiver is known to reside in the same process as the signal submitter, for example when using libc monitors, process-local signal submission can noticeably reduce overhead time. The `Signal_receiver` class already supports this feature and this issue is about adding a `Signal_context::local_submit()` function, which can be called instead of using a `Signal_transmitter`.

**Comment by cproc** [comment]
@chelmuth: temporary test commit for staging

**Comment by nfeske** [comment]
The `Signal_context::local_submit` method should not have the `cnt` argument. The count is a legacy that is not (and should not be) used anywhere. In the implementation, when creating the `Data` object, just pass 1 as count value.

**Comment by nfeske** [comment]
Thanks @cproc for implementing this optimization idea so swiftly and cleanly. With the minor change as requested above, I'm very happy with the commit.

**Comment by nfeske** [comment]
Fixed in master.

**Comment by chelmuth** [comment]
@cproc do you approve my analysis and patch above?
