### ISSUE TITLE
platform_drv(x86): ipxe_nic_drv not working with MSI-X for RTL8111/8168/8411 device

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3927]

**Comment by chelmuth** [comment]
Do you have any notes (a reference in the spec maybe) you may add to the commit message why this is required?

**Comment by alex-ab** [comment]
I looked through the spec and couldn't find a hint. In this case it is MMIO provided by a PCI BAR of the device. AFAIK the spec of the device is not public in order to check.

**Comment by alex-ab** [comment]
@cnuke acutally found the datasheet for the realtek device, and there you see that you have to use 2x32bit accesses https://usermanual.wiki/Document/rtl8111cgrrealtekr11.25570219/view.

**Comment by alex-ab** [comment]
Some more references by @cnuke: https://www.illumos.org/issues/4217, http://openbsd-archive.7691.n7.nabble.com/MSI-X-fix-td367604.html
