### ISSUE TITLE
Restructure dde_bsd audio driver

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#3929]

**Comment by nfeske** [comment]
Thanks for this excellent commit series. I merged all commits to staging now.

**Comment by nfeske** [comment]
I'm afraid that the renaming of the driver broke the vbox run scripts. @cnuke could you please have a look?

**Comment by cnuke** [comment]
@nfeske please merge 690d0ef to staging.

**Comment by nfeske** [comment]
Thanks.
