### ISSUE TITLE
driver_manager: update to use componentized usb driver(s) instead of monolithic one

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3943]

**Comment by alex-ab** [comment]
With commit 6db6c8573c4e5d1bcb867d451ab3c2528472011d the componentized usb driver(s) are used by the drivers_manager. I could run it successful on several machines with Sculpt 20.08, e.g. Fujitsu 3/4, X201, T460p.

**Comment by nfeske** [comment]
Thank you for taking this great step towards the deprecation of the old USB driver. Merged to staging.
