### ISSUE TITLE
usb: pagefault on too large memory allocations by usb device drivers

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3953]
```
[init -> usb_hid_drv] dev_info: input: USB HID v1.10 Keyboard [HID 04d9:a067] on usb-usbbus-/input0
[init -> usb_hid_drv] Error: slab too large 262144 requested 245892 cached 2
attempted write at read-only memory (WRITE pf_addr=0x3c073 pf_ip=0x103c140 from pager_object: pd='init -> usb_hid_drv' thread='ep') 
page fault, pd='init -> usb_hid_drv' thread='ep' cpu=0 ip=0x103c140 address=0x3c073 stack pointer=0x407feb40 qualifiers=0x7 irUWP reason=2
[init -> usb_drv] dev_info: USB disconnect, device number 5
``

**Comment by alex-ab** [comment]
After some discussion regarding the allocator for usb_hid with  @ssumpf and @cnuke, I came up with some commits which removes the red error messages and fulfill the allocation requests by the USB HID devices which cause them.

**Comment by alex-ab** [comment]
@nfeske, @chelmuth : please consider 8a302b47c720bf3087c88bb0c9e927fb011a9a13 for staging, which prevents a page fault. The other commits can be also added later (after release), because they just would improve the supported devices.

**Comment by nfeske** [comment]
Thanks for the hint.

**Comment by nfeske** [comment]
Fixed in master.

**Comment by alex-ab** [comment]
There are several follow up commits on this issue still not merged, how to handle them ?

**Comment by nfeske** [comment]
Sorry, I was too eager to close the issue. Let us reopen it then.
