### ISSUE TITLE
sd_card_drv: use the platform API to aquire device resources

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3956]

**Comment by nfeske** [comment]
Thanks a lot! I merged both commits to staging.

**Comment by skalk** [comment]
@chelmuth @nfeske: I've solved the compilation issue with the changed sd_card_drv, and rolled-back the sd_card src package like you asked me to do. Both fixup commits: 8d92e912c0e17b3de4eec6fce6df38b9f827849b and 47d466d421372c1a25a3cc8d30f9bea0e4619b2a need to get applied to staging therefore.
