### ISSUE TITLE
sculpt: add support for i.MX8 Quad EVK board

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3958]

**Comment by nfeske** [comment]
I love the way how you have split the change into two commits. That is perfect for reviewing. Thanks for the great care! I merged both commits to staging now.

**Comment by skalk** [comment]
@nfeske: thank you for the kind words. Unfortunately, the start entry of the rtc_drv needs to be before the "dynamic" driver subsystem, otherwise there is not enough memory left for it. I've fixed that in a dedicated fixup commit 2ef88e9a00efdaab091bcccc34a1678e15216954

**Comment by nfeske** [comment]
I merged your fixup to staging.
