### ISSUE TITLE
rump: use -fcommon for rump_tools

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#3960]
Newer host gcc versions (10) set `-fno-common` as default, which leads to multiple definitions of otherwise common symbols. "The idea of COMMON symbols in Unix is to allow multiple external definitions of a same variable (in different compilation units) under a single common symbol under certain conditions." - which is used by `rump_tools`.

**Comment by nfeske** [comment]
I'm curious, may you share a bit of the background story of this issue?

**Comment by ssumpf** [comment]
@nfeske: https://binarydodo.wordpress.com/2016/05/09/investigating-linking-with-common-symbols-in-elf/ - otherwise a lot of multiple definitions of symbols will occur.

**Comment by nfeske** [comment]
I was unable draw the connection to the practical problem you encountered. I was wondering about a possible runtime effect. Since you speak of gcc-10, I guess it is about a build problem with a more recent Linux distro.
