### ISSUE TITLE
nitpicker: defer hover changes during drag operations

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3973]
When resizing a window with a size constraint using the motif decorator and depressing the mouse button while the pointer is outside the resize handle, the resize handle stays in hovered state.

During the analysis together with @chelmuth, we found that nitpicker updates its internal `_hover` state too eagerly, which indirectly leads to the masking of a leave event to the decorator. This issue may be related to the sporadic "jumping window" effect that sometimes occurs in Sculpt.

**Comment by cproc** [comment]
@nfeske: with your latest commit I could not reproduce the jumping window or resize handle hovered state anymore.

**Comment by nfeske** [comment]
@cproc, thank you for the confirmation. :-)
