### ISSUE TITLE
check_abi is executed on every build

### ISSUE THREAD

**Issue by tomga** [genodelabs/genode#3974]
Target for command that calls `check_abi` is never created so make executes it on each build.

c205fd013f26c8b7537025cd67ff18cb2d32ad47 seems to fix the issue and be safe. I verified that it works for `vfs` and `sandbox` libraries with commands like:

    LANG=C make VERBOSE= VERBOSE_MK= VERBOSE_DIR= -C build/linux BOARD=linux LIB=sandbox

It isn't enough for `ld-linux` due to code in [ld-platform.inc](/genodelabs/genode/blob/1bef11accf650657544b16aac9cd3af62edf0fb3/repos/base/lib/mk/ld-platform.inc#L45-L48). Possibly similar fix with adding `&& touch postprocess.tag` to end of command could be ok but I don't propose it because a don't feel convinced that it would be proper as this rule modifies different file than specified target.

**Comment by nfeske** [comment]
Thanks @tomga for the patch, which I merged to staging.

> It isn't enough for ld-linux due to code in ld-platform.inc. Possibly similar fix with adding && touch postprocess.tag to end of command could be ok but I don't propose it because a don't feel convinced that it would be proper as this rule modifies different file than specified target.

I share your caution. After consulting with @chelmuth, however, we think that your suggestion should be safe. I added c7a2e85397005fccc3e8c60dca086c1640ac4bea to staging to give it a try.

Thank you for sharing your findings and for the welcome solutions.
