### ISSUE TITLE
abi.so generate rule is missing dependencies to linker scripts

### ISSUE THREAD

**Issue by tomga** [genodelabs/genode#3978]
It is in [lib.mk](/genodelabs/genode/blob/1bef11accf650657544b16aac9cd3af62edf0fb3/repos/base/mk/lib.mk#L230-L236) and the missing dependency is for content of `LD_SCRIPT_SO`. 

Mere adding it into dependencies will probably cause build to fail due to usage of `LD_SCRIPT_SO` like in [ld-platform.inc](/genodelabs/genode/blob/1bef11accf650657544b16aac9cd3af62edf0fb3/repos/base/lib/mk/ld-platform.inc#L34).

There is also one more problem in that rule that sometimes linker scripts are passed hidden in `LD_OPT` (possibly to handle proper sequence of them if it matters). Such examples are in `ld-platform.inc` too [here](/genodelabs/genode/blob/1bef11accf650657544b16aac9cd3af62edf0fb3/repos/base/lib/mk/ld-platform.inc#L37) and [here](/genodelabs/genode/blob/1bef11accf650657544b16aac9cd3af62edf0fb3/repos/base/lib/mk/ld-platform.inc#L53). Those linker scripts are not treated as a dependencies and do not cause rebuilds.

Hopefully those linker scripts don't have includes in them - I don't know if it is possible and in case it is if it is used.

And now it occurred to me that `LIB_SO` rule probably does not handle dependencies hidden in `LD_OPT` either.

I'm not sure if this issue can be a real problem. Close it in case you decide it is not important. I have no problem with it.

**Comment by nfeske** [comment]
Addressed by https://github.com/genodelabs/genode/commit/4685ba394ebe1202b2acae11846df58db3a0a7d4
