### ISSUE TITLE
create_builddir: hide muen-specific details in default etc/build.conf

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#3994]
Right now, the default etc/build.conf file as created for the x86_64 architecture contains the following snippet:

```
BOARD_RUN_OPT(muen)   = --include image/muen
BOARD_RUN_OPT(muen)  += --image-muen-hardware hardware/lenovo-t430s.xml
BOARD_RUN_OPT(muen)  += --image-muen-platform platform/lenovo-t430s.xml
BOARD_RUN_OPT(muen)  += --image-muen-gnat-path /opt/gnat
BOARD_RUN_OPT(muen)  += --image-muen-spark-path /opt/spark
BOARD_RUN_OPT(muen)  += --image-muen-system xml/genode-base_hw.xml
BOARD_RUN_OPT(muen)  += --image-muen-components 'libdebuglog libmudm libmutime libxhcidbg dbgserver sm time'
BOARD_RUN_OPT(muen)  += --image-muen-external-build 0
```

These options take a lot of room but are hardly relevant for most users. Hence, I would prefer moving those distracting options to a less prominent place, e.g., a file repos/base-hw/etc/build-muen-t430s.conf. The CI tools could append this content to the build.conf when performing the muen-specific tests.

**Comment by chelmuth** [comment]
Please consider #3995 before fixing this issue.
