### ISSUE TITLE
usb_host_drv: improve error handling

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4005]
Report more different error codes to the client and print an error message if an error occurred which is not handled yet. Also, fix some memory leaks in the lx_kit/lx_emul USB session client headers.

**Comment by nfeske** [comment]
Thanks @cproc! Since I am to too familiar with USB, I'd appreciate @cnuke having a look at the patch, especially about the change of the USB-session interface.

**Comment by cnuke** [comment]
LGTM :+1:
