### ISSUE TITLE
page fault in nitpicker

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4011]
While debugging the Falkon web browser on base-linux, a page fault in nitpicker occurred one time:

```
ld.lib.so[1449]: segfault at 7ffff77b5180 ip 000000000104f877 sp 00000000401ff8c0 error 4 in nitpicker[1000000+5f000]
```

According to objdump, the source code location was:

https://github.com/genodelabs/genode/blob/947fea5632aeb7f8499cd428e6a02aa764c36086/repos/os/src/server/nitpicker/user_state.cc#L437

Maybe `old_hovered` was a dangling pointer for some reason.

**Comment by nfeske** [comment]
Thanks for reporting. Given this information, I was able to spot the potential problem and fix it in https://github.com/genodelabs/genode/commit/6f38f52ccf4a3b89c8c7e3613c1b8c781a9f9de1.
