### ISSUE TITLE
riscv: Update to privileged spec v1.10 and replace Spike emulator

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4012]
* Update base-hw RISC-V support to privileged ISA specification v1.10
* Replace https://github.com/ssumpf/riscv-isa-sim and Berkeley Boot Loader (https://github.com/skalk/bbl-lite) with the Qemu RISC-V virt platform

**Comment by ssumpf** [comment]
@chelmuth: 8bfde36 is the first proposed version of my RISC-V update, could you take a look?

**Comment by ssumpf** [comment]
@chelmuth: 85e2412 fixes the ld segmentation fault (trace policies) and floating point link errors (e.g, nitpicker) we have experienced for a long time.

**Comment by chelmuth** [comment]
Thanks for this update. Besides the usual nitpicking (see my comments to your patch) the switch to a recent ISA spec and Qemu is a great feature. What confused me a bit is the intermixed use of *riscv_qemu* and *risc_virt* for the Qemu board. If both are synonymous, could *riscv_virt* be replaced by *riscv_qemu* throughout the commit?

**Comment by ssumpf** [comment]
@chelmuth, @m-stein: c8a5421 incorporates your suggestions.

**Comment by chelmuth** [comment]
I'm fine with the changes, so, now it's time to update the CI tools (tester, builder, limited package build?).

**Comment by ssumpf** [comment]
> I'm fine with the changes, so, now it's time to update the CI tools (tester, builder, limited package build?).

@chelmuth: I would say so.

**Comment by ssumpf** [comment]
@nfeske: 73c4c43 uses `.rept` for the seven `nop` instructions.

**Comment by skalk** [comment]
@ssumpf I've added my comments in your previous commit. Sorry I did not encountered the fixups you already did. So please ignore any duplicate comments.

**Comment by chelmuth** [comment]
@ssumpf please also consider @skalk's comments abouts board vs. spec in the https://github.com/ssumpf/genode-riscv repository.

**Comment by ssumpf** [comment]
@skalk: e0433e1 implements your suggestions

**Comment by ssumpf** [comment]
> @ssumpf please also consider @skalk's comments abouts board vs. spec in the https://github.com/ssumpf/genode-riscv repository.

@chelmuth: @skalk changes have also been applied to https://github.com/ssumpf/genode-riscv.

**Comment by chelmuth** [comment]
Merged, tested, fixup'd and pushed the current state to genode staging. @ssumpf there's also a fixup for build error of genode-riscv at https://github.com/chelmuth/genode-riscv/commit/325b59a6efb6d6a84eb41fafad8c4ed6dc3a162b

**Comment by ssumpf** [comment]
> Merged, tested, fixup'd and pushed the current state to genode staging. @ssumpf there's also a fixup for build error of genode-riscv at [chelmuth/genode-riscv@325b59a](https://github.com/chelmuth/genode-riscv/commit/325b59a6efb6d6a84eb41fafad8c4ed6dc3a162b)

@chelmuth: Thanks, I have updated "genode-riscv" accordingly.

**Comment by nfeske** [comment]
Fixed in Genode 21.02.
