### ISSUE TITLE
core: freeing non-empty slab block error messages

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#4013]
During running the toolchain on Genode from time to time one gets:

```
Error: freeing non-empty slab block 
```

**Comment by chelmuth** [comment]
I wonder which exception is the reason behind this. The allocator implementation itself avoids exceptions.

**Comment by nfeske** [comment]
I guess, the `Allocator_avl_base::_alloc_block_metadata` method calls `_md_alloc->alloc(sizeof(Block), &b))`, which can trigger an `Out_of_ram` or `Out_of_caps` exception.

@alex-ab to give a definite answer to @chelmuth's question, could you try replacing the catch-all by catching these both exceptions individually instead and print a message for each? Just as a test.

**Comment by alex-ab** [comment]
With debug commit e54f65c6c29605bdff2810cf3f1f43764fc02e05 I see around ~20 Out of caps messages during running ```make KERNEL=hw core``` and no other exception/message.

**Comment by nfeske** [comment]
That makes sense. Thanks @alex-ab for clearing up the question, and of course for fixing the bug! ;-)
