### ISSUE TITLE
libc: setup environ of forked process

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#4015]

**Comment by alex-ab** [comment]
6ad853652ef2c18dd7322e025b9072533ffc97d5 reads in the environ for a clone as done in posix/construct.cc and qt5_component.cc, which helps that collect2 finds the linker.

**Comment by nfeske** [comment]
Thanks for reporting.

Your proposed fix is not a good solution though. First, it merely masks the actual problem, which is that `environ` loses its value during fork despite of being part of the application state. Second, by conveniently reusing `populate_args_and_env`, the memory allocated for `argv` leaks. Granted, the leak is limited to one allocation at start time but it looks sloppy.

Commit 0198034c2ab4be63c69bd65a25ddc334fc9f9999 contains the fix the underlying problem along with a test.
