### ISSUE TITLE
qemu-usb: use bounce buffer to access DMA memory

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4017]

**Comment by cnuke** [comment]
Commit 06f458e fixes the mapping errors where the VMM address does not point to a continous memory range by replacing the mapping attempt by copying the data to a bounce buffer. This trades memory-bandwidth/CPU utilization for a more robust approach (until we found a more performant way).

**Comment by chelmuth** [comment]
Thanks for addressing my comments. I merged the series to staging.
