### ISSUE TITLE
base-hw: streamline packaging

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#4019]
The current depot recipes for the base-hw kernel leave room for improvements:

- Most src archives contain a large superset of the source codes required for the respective boards. E.g., x86-specific code is packaged into the archives for ARM boards. This is not strictly a problem, but it is not clean either.
- Hosting board support in an external repository is not easy. E.g. genode-world hosts this rather convoluted include snippet: https://github.com/genodelabs/genode-world/blob/master/recipes/src/base-hw_content.inc It would be nice to provide infrastructure that alleviates the need for such crutches.

**Comment by nfeske** [comment]
Commit https://github.com/genodelabs/genode/commit/002032e99a7f20de0179dafece61ddfd995c6fb6 improves the mechanism. I tested the build for all packages provided by the base-hw repository and my (not yet published) allwinner repository. Genode-world will need adjustments.

@skalk Do you agree with this change?

I merged it to staging already just to see how all the boards fare.

**Comment by skalk** [comment]
@nfeske: I'm fine with the changes, and appreciate the cleanup work!

**Comment by nfeske** [comment]
Thanks for the prompt feedback!

**Comment by ssumpf** [comment]
@nfeske: 6494235 adjusts the path for the startup library + uses `select_from_repositories` for crt0.s of the same library.

**Comment by nfeske** [comment]
Thank you. I merged your select_from_repositories change to the separate commit https://github.com/genodelabs/genode/commit/635985f542cdb2b4273d2956ac99650866da2766
