### ISSUE TITLE
riscv_qemu: autopilot adjustments

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4021]
- disable unsupported run scripts for autopilot (libc, nic driver are not supported at the moment)
- build base-hw package
- add depot support

**Comment by ssumpf** [comment]
@chelmuth: 649beee re-enables `depot_query`, I have ajusted `ci-tools` accordingly.

**Comment by nfeske** [comment]
I merged https://github.com/genodelabs/genode/commit/649beeec91fbe84263bb0c9be41b21b15cf316b7 to staging.

**Comment by ssumpf** [comment]
@chelmuth: 36b3ca5 fixes `nic_router_dhcp*` and `event_filter` run scripts for `riscv_qemu`.

**Comment by ssumpf** [comment]
@chelmuth: c11c8c3 fixes the timeout test on `riscv_qemu`

**Comment by nfeske** [comment]
Merged to staging.

**Comment by nfeske** [comment]
Fixed in master.
