### ISSUE TITLE
vmm: add virtio block device model

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4025]
To use the ARM vmm in the field a block device model is still missing. Providing a Virtio block device would be the natural fit.

**Comment by skalk** [comment]
@ssumpf you may review commit cdc860b because it restructures the Virtio base device model you've written initially.

**Comment by skalk** [comment]
@chelmuth, @nfeske : apart from @ssumpf review and of course you own one, in my eye you can put it to staging to fasten the test cycle before the release. Of course, according to your own schedule and as occasion demands.

**Comment by nfeske** [comment]
I merged your beautiful commits to staging.

Regarding the review, I'd like to rely on @ssumpf since I'm unfamiliar with VirtIO.

**Comment by ssumpf** [comment]
@skalk: I am fine the changes, the virtio device looks way better now ;)
