### ISSUE TITLE
build system: Improve link times for core

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4027]
Especially on base-hw RISC-V we experience long link times for core and it's debugging version. After some investigation we found that linking the base and core libraries into a large relocatable object file which in turn was linked to core was causing the long link times. A better solution seems to be to create another library archive from base and core libraries which is later linked to core.

**Comment by ssumpf** [comment]
@nfeske: 9bb6207 contains a first version of the link time improvement for core.

**Comment by nfeske** [comment]
Thank you for investigating. This looks very promising!

**Comment by nfeske** [comment]
Upon closer inspection, @chelmuth and me think that the thin archives won't work as they - like you suspected - miss the actual data.

A reasonable way seems to assemble a new archive from the object files gathered via `ar -t` for the various .a files of the link items. I think you mentioned this idea today. It seems legit.

**Comment by chelmuth** [comment]
Another option I discovered just now [1] is to use MRI scripts [2] like follows.

```bash
> cat foo.mri
create sum.a
addlib 1.a
addlib 2.a
save
end
> ar -M < foo.mri
> ar t sum.a 
vm_session.o
trace.o
thread_myself.o
thread_bootstrap.o
...
```

[1] https://stackoverflow.com/a/23621751/453786
[2] https://sourceware.org/binutils/docs/binutils/ar-scripts.html

**Comment by ssumpf** [comment]
@chelmuth: Your suggestion does the job! Thanks. I did a little research on MRI. There is nothing much to find but "Magnetic resonance imaging". It seems to have been a tool chain that was there before the GNU tool chain (https://sourceware.org/binutils/docs/binutils/ar-scripts.html) or as @cnuke mentioned today: "We might have to ask the gray beards".

**Comment by ssumpf** [comment]
@nfeske: I have revised the last commit using @chelmuth suggestion with 706b7ff.  It has been tested on all platforms and all kernels by hand with packages (`run/demo`) and simple `run/log`.

**Comment by nfeske** [comment]
Very cool! I merged your commit to staging.

**Comment by nfeske** [comment]
Fixed in master.

**Comment by ssumpf** [comment]
@nfeske: f68e655 introduced a regression where the debug versions of core and bootstrap are not build any more. 530d76e addresses this issue. Please consider for staging.
