### ISSUE TITLE
libports: openat/fstatat() needed by GNU tar(1)

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#403]
Instead of GNU tar we could also use bsdtar though we will need *at() functions sooner or later anyway.

**Comment by ehmry** [comment]
I made what seems like a silly wrapper around fstat and lstat to make fstatat work, which is used by the even sillier fts_read wrapper, used by **rm**.

I only tested tar a little bit, I really wanted rm to work recursively because it makes Rump much more pleasant to use.

**Comment by ehmry** [comment]
Noux will have to override getdtablesize so that it isn't hardcoded in the library, I've seen a few errors because of this already.

**Comment by ehmry** [comment]
I reverted and moved ``getdtablesize`` to a seperate issue.

**Comment by chelmuth** [comment]
@ehmry your getdtablesize related commits entered master today. Do you have something in the pipe to close this issue too? And even further: Could I then also cherry-pick b99c31f5163694fe27dd049178c8fca663b1f63a on top and fix #403 and #1836 in one batch?

**Comment by ehmry** [comment]
I say cherry-pick 91cefdd74485227a3c4d5bfaecc849897df5245d, 82d6d7ade787af2c1e2f04aedbb8b3cea9721639, and  b99c31f5163694fe27dd049178c8fca663b1f63a

**Comment by chelmuth** [comment]
@ehmry thanks, merged just now
