### ISSUE TITLE
NIC router: fix uncaught bit alloc exception

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#4036]
While updating his Sculpt and trying to apply it's usual network setup with a manually configured NIC router, @nfeske managed to bring his NIC-router instance down with an uncaught exception of type Bit_allocator_dynamic::Out_of_indices. In this incident, re-configuration with several domains, a dynamically IP-configured VM and possibly jumping of the VM between domains through changing policies were involved. The specific use pattern, however, that lead to the issue isn't known.

**Comment by m-stein** [comment]
Tracking all possible paths that could trigger the mentioned exception, I could find two places where the exception should be caught but wasn't by now. The following patch fixes this and adds unconditional log output, so, we will be able to debug the problem a bit more in detail next time:
023dc00a02 nic_router: fix uncaught bit alloc exception

**Comment by m-stein** [comment]
This updated version more correctly marks a domain invalid if the DHCP server creation failed because of the exception:
a68fa655b0 nic_router: fix uncaught bit alloc exception

**Comment by nfeske** [comment]
Merged to staging.

**Comment by m-stein** [comment]
I removed the fixed label as there is new information regarding this issue.

I could reproduce different uncaught IP-allocation-related exceptions with these tests:
9d9e3ba2ac nic_router: tests to trigger uncaught exceptions

Note that test 4 doesn't trigger any exception although it does something similar but with domains switching.

**Comment by m-stein** [comment]
The issue was closed automatically by 25a212a. I reopened it as 9d9e3ba can be used to systematically reproduce uncaught exceptions. I also wanted to add a note that the issue was originally **observed with Sculpt 21.03**.

**Comment by m-stein** [comment]
Commit https://github.com/genodelabs/genode/commit/9d9e3ba2ac22a4c98ace2fe5f78c7a042fb47f66 shows no uncaught exceptions on current staging anymore. I'll therefore close the issue.
