### ISSUE TITLE
init: Uncaught exception of type 'Genode::Bit_array_base::Invalid_clear'

### ISSUE THREAD

**Issue by trimpim** [genodelabs/genode#4039]

**Comment by trimpim** [comment]
f2d054103d77482d20f41718b8458deea6673114 reproduces the uncaught exception described in https://lists.genode.org/pipermail/users/2021-February/007540.html within a few minutes.

Currently I only have tested this on base-linux.

**Comment by nfeske** [comment]
@trimpim thank you very much for your work to make the issue reproducible! I'll investigate this issue today.

**Comment by nfeske** [comment]
I can reproduce this problem after reducing the timeout at https://github.com/trimpim/genode/commit/f2d054103d77482d20f41718b8458deea6673114#diff-a5e200edbb5c25790208fed2dda90ff0976b762865ce26aa8523574e892c8b67R46 to 1000.

**Comment by nfeske** [comment]
Thanks to @trimpim's excellent test and the great help of @chelmuth, I was able to encircle the problem today.

Commit https://github.com/nfeske/genode/commit/a8692620ae6bc1a7a025b1c6cb1038a41498cb1c should fix the issue. I still need to think of a good way to add a regression test for this situation to the test-init package but you may give the fix a try already.

**Comment by nfeske** [comment]
I wonder, can you observe the fault in the scenario you shared with me in https://github.com/trimpim/genode/commit/f2d054103d77482d20f41718b8458deea6673114?

**Comment by nfeske** [comment]
@trimpim please don't invest too much time for testing. Let's first wait for the CI results on my side.

**Comment by nfeske** [comment]
> I can see this issue in Sculpt on NOVA. Investigating...

Fixed by https://github.com/genodelabs/genode/commit/7ba05d04b349f2d6760809e701dc4a97f7a14f25

@trimpim can you give this fixup a try?

**Comment by trimpim** [comment]
@nfeske with both patches applied, our scenario now runs for more than 250 configuration changes whereas before it stopped after a dozen or so.
