### ISSUE TITLE
boot_dir/nova: enable Intel HWP

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4040]
While debugging some other issue I noticed that my target system drives the CPU only with its base frequency, leaving existing performance reserves untapped (cf. #3871). During an offline discussion it was decided to enable the feature unconditionally to reap the benefits when running Sculpt as well as having more test coverage on how different systems might behave.

**Comment by cnuke** [comment]
Commit a710caf sets the required bender option unconditionally when using NOVA.

**Comment by nfeske** [comment]
Thanks @cnuke for the patch. I merged it to staging right away.

**Comment by nfeske** [comment]
Fixup https://github.com/genodelabs/genode/commit/c69d2a0c39847f841bcd8cf86f32d44213b22ffa removes the HWP message from the build log, which is otherwise printed on each build.
