### ISSUE TITLE
mixer: use audible default settings

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4043]

**Comment by cnuke** [comment]
Commit 16c596a changes the default settings that get applied in case there is no valid config and sets the volume to 50%. This allows to diagnose if the mixer works at all and is in line with the default configuration of the `bsd_audio_drv` (so 50% and 50% will hopefully lead to reasonable loud sound).

While there, commit 9706d54 makes the `mixer.run` run-script work again.

**Comment by nfeske** [comment]
Merged to staging.
