### ISSUE TITLE
sculpt: support packages providing Rtc service

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#4046]

**Comment by alex-ab** [comment]
c5008f25b308dedab569bd19d1dac1bd7e2eb455 contains a patch for depot deploy to support ```<provides> <rtc/> </provides>```, which is used by baeec070bb985da410dbe1bc756f2f9f86e007c2 to proxy the RTC driver.

**Comment by alex-ab** [comment]
@nfeske: 2f7985999db636c788979884c42d2d96435a2fb3 and b6b780f5c4c721053450c3d0fc1b7422ce851464 contains the discussed changes.

**Comment by nfeske** [comment]
Merged to staging but with the short description of the menu item changed to a slightly less technical text.

**Comment by alex-ab** [comment]
Ok.
