### ISSUE TITLE
usb_host_drv: support command timeouts and bool properties

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4047]
Implement `mod_delayed_work()`, `reinit_completion()` and `device_property_read_bool()`.

**Comment by nfeske** [comment]
I would appreciate you sharing a bit of the background of this issue. Please let us document the symptom that prompted the need for the change. I can only guess that this issue might be related to #4048?

**Comment by cproc** [comment]
Yes, the issue is releated to #4048. When the XHCI command did not get a response, a timeout was supposed to trigger, but it didn't because of the missing implementations. The device property read function is needed for the quirk property of issue #4048.

**Comment by nfeske** [comment]
Thank you for the explanation.
