### ISSUE TITLE
libc: mmap: use VFS handle as reference for shared mappings

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4050]
Currently, for shared mappings the libc file descriptor gets duplicated to keep the file open if it gets deleted while the mapping still exists. Unfortunately, this limits the number of shared mappings to the maximum number of libc file descriptors, which can easily be reached with qtwebengine. Using a VFS handle instead of a duplicated libc file descriptor solves the problem.

**Comment by cproc** [comment]
@chelmuth: I added the missing monitors in 2aadcb2

**Comment by chelmuth** [comment]
Thanks, I merged the commit to staging.
