### ISSUE TITLE
sculpt: focus-follows-mouse is sometimes not reliable

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#4059]
@cnuke reported a corner case where the focus would not always follow the mouse when quickly moving the pointer back and forth between windows.

**Comment by nfeske** [comment]
Commit https://github.com/nfeske/genode/commit/4767c714b2b73a2368a38a34e5deb8bbfb873608 should fix this issue but will need a bit of testing.

@cnuke I have published a package of the fixed wm. You can find it in my sculpt index. I'd be grateful for your feedback.

**Comment by cnuke** [comment]
@nfeske thanks, with the commit I cannot reproduce the particular problem any longer. I'll keep using it and will keep you posted if any other issue related to the changes arise.
