### ISSUE TITLE
ldso: review the usage of Mutex in `dl_iterate_phdr`

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4071]
The mutex in `dl_iterate_phdr` prevents further function resolution in `callback` functions, if a function has not been relocated at this point this leads to a deadlock.

**Comment by ssumpf** [comment]
695368f should be merged with 6a016dfc25f99bd68e31c92d3c25ffa2d15f26b7

**Comment by nfeske** [comment]
Thanks. I squashed both commits to https://github.com/nfeske/genode/commit/c45d964bc23f4f0f370c74d8a1290c88fe974876 on staging. @ssumpf can you double-check the commit?

**Comment by ssumpf** [comment]
> Thanks. I squashed both commits to [nfeske@c45d964](https://github.com/nfeske/genode/commit/c45d964bc23f4f0f370c74d8a1290c88fe974876) on staging. @ssumpf can you double-check the commit?

Looks good to me.

**Comment by ssumpf** [comment]
@nfeske: 5dcee7e is a follow up to c45d964 because the latter caused a deadlock when dynamically loaded libraries (e.g., `dlopen`, `Shared_object`) threw exceptions during ELF setup. Please consider for staging.

**Comment by nfeske** [comment]
Thank you, merged to staging. The reworked version of the code looks so much better.
