### ISSUE TITLE
platform_drv: enrich device XML info with physical resource names

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4077]
For driver ports like DDE Linux device drivers, it is more easy to relate physical resources given by the platform driver, e.g. with information provided by a device-tree-blob. Therefore, it would be nice to export these additional information via the devices XML info. For simple-and-clean, written-from-scratch drivers to not "infect" them with these physical, global names we can make the whole device info to be optional. Therefore, the client policy in the platfor_drv configuration has to include a `info=yes` attribute.

**Comment by nfeske** [comment]
@skalk can you please point me to the most recent commit / branch to merge?

**Comment by skalk** [comment]
@nfeske sorry, I mistakenly deleted the corresponding branch. I re-newed my merge_to_staging branch now. It is commit id 37b3035

**Comment by skalk** [comment]
A problem arised: the recent addition of utilities for platform devices on ARM* (see issue 4075) uses inherently the device XML information, when using the `device_by_index()` utility in `Platform::Connection`. When making the device information optional this utility breaks. To workaround the problem I would extend this issue in removing `device_by_index()`, which is primarily only used with index 0, and add a `acquire_single_device` RPC to the platform API instead that delivers the first device for clients that use a single device anyway.

**Comment by skalk** [comment]
@nfeske I've pushed a fixup commit 5a9a44d8d3e0786c8f4d5cc7d8414f1b8d3feb7a to my merge_to_staging branch, which fixes the Virtio NIC driver on x86, and implements above described API change.

**Comment by nfeske** [comment]
Thanks a lot. Merged to staging.
