### ISSUE TITLE
Apparently reversed capslock state in VM

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#4087]
I just accidentically pressed [ctrl]+[capslock] in my Linux VM in Sculpt and it apparently reversed my capslock state (i.e. LED off -> upper case, LED on -> lower case). This can be reverted by again pressing [ctrl]+[capslock]. Under native Linux [ctrl]+[capslock] also switches the case but together with the capslock LED. So, I assume that [ctrl]+[capslock] simply doesn't trigger LED handling in Sculpt while only [capslock] does.

**Comment by alex-ab** [comment]
The capslock state is consumed by vbox reading a capslock ROM. In Sculpt the global_keys_handler (sculpt.run) generates the source report. It seems that there is no configuration for [ctrl]+[capslock] to toggle the capslock state.

**Comment by chelmuth** [comment]
The background is that global keys are specified as the first key pressed, i.e., lose their *globalness* if pressed as secondary key in a combination. The best way to fix the issue would be the extension the special handling of capslock (as global state) in vbox. [capslock] could be filtered completely from the key event stream and only sent to the VM if the global state changes. But, this has high probability to bring more surprises for current configuration I'm afraid.

**Comment by m-stein** [comment]
To me, the issue is not that annoying. I just wanted to make it public, so it doesn't run under cover. Shall I prioritize it over other work anyway right now?

**Comment by chelmuth** [comment]
> To me, the issue is not that annoying. I just wanted to make it public, so it doesn't run under cover. Shall I prioritize it over other work anyway right now?

I don't think it deserves high priority currently. I just wanted to add my knowledge to the database ;-)

**Comment by jschlatow** [comment]
For me, the capslock state doesn't seem to be consumed by vbox at all. Hitting capslock when the VM is not in focus will lead to an inconsistent state between host and guest.

**Comment by jschlatow** [comment]
> For me, the capslock state doesn't seem to be consumed by vbox at all. Hitting capslock when the VM is not in focus will lead to an inconsistent state between host and guest.

Unfortunately, I cannot reproduce this anymore. Today, the capslock state is passed through as expected.

**Comment by chelmuth** [comment]
With bdb91e77e758b0540d889a2c21845aa0ce754938 vbox5 filters `KEY_CAPSLOCK` from the input-event stream in ROM mode. Any feedback appreciated.

Commit f6e7c306e66fc369fb8faccc2dd4caf2396855c0 adds the `capslock="rom"` feature to vbox6. Please note, it's actually `rom` not `ROM`.

**Comment by m-stein** [comment]
@chelmuth Thanks, I just updated my sculpt-installation and bdb91e7 works like a charm!
