### ISSUE TITLE
Pathname pointer check in the libc

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4088]
Due to a configuration mistake on my side and a missing check in some contrib code I encountered a page-fault because `open(NULL, …)` was called. I traced the page-fault down to https://github.com/genodelabs/genode/blob/efbed6f7bfd2879b28ba209e8bbd2a7ae40ba0b4/repos/os/include/os/path.h#L36-L39
where this method is called by `Path_base::import()` with an invalid path pointer and path is unconditionally dereferenced.

Now, passing such a pointer to a libc function in this manner points probably to a programmer's mistake (or the fact that one relies on that being handled gracefully, i.e. returning _EFAULT_) and might only exist on the theoretical side of things.

**Comment by cnuke** [comment]
Commit 2b9e289 (more of a band-aid) and 4afa399 lessen the problem - again I am indifferent to the practical relevenace in our situation but want to document the behaviour nonetheless.

**Comment by nfeske** [comment]
Those changes are definitely for the better. Thanks for the commits, which went to staging just now.
