### ISSUE TITLE
lx_fs: vfs_import always overwrites files

### ISSUE THREAD

**Issue by Jadovenn** [genodelabs/genode#4104]
`lx_fs` does not propagate that the file to be written already exists. Therefore, the VFS import-plugin always overwrites even when the `overwrite`-attribute is `no`.

The problem seems that `lx_fs` does not propagate an EEXIST error while calling `mknodat`.   

I provide a run script that demonstrate this behavior, and a fix for this problem, to be discussed.

**Comment by nfeske** [comment]
Thank you for the fix and the run script. I have merged both commits to staging now.

In fixup 2b34f0ebea1444dfb625ed373dd2ddc579402f79, I also added the run script to our nightly tests.

**Comment by nfeske** [comment]
Fixed in master.
