### ISSUE TITLE
cbe_tester: build error with gcc 10

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4113]
When building `app/cbe_tester` with gcc 10, the following error occurs:

```
  Program app/cbe_tester/cbe_tester
    COMPILE  main.o
/.../repos/gems/src/app/cbe_tester/main.cc: In member function ‘void Main::_cmd_pool_handle_pending_list_snapshots_cmds(bool&)’:
/.../repos/gems/src/app/cbe_tester/main.cc:2237:70: error: cannot bind packed field ‘ids.Cbe::Active_snapshot_ids::values[idx]’ to ‘long long unsigned int&’
 2237 |       log("   Snapshot #", snap_nr, " is generation ", ids.values[idx]);
      |                                                        ~~~~~~~~~~~~~~^
```

**Comment by m-stein** [comment]
I will look into this today.

**Comment by m-stein** [comment]
It seems that I need an older glibc:
```
  Library spark
    COMPILE  a-except.o
/usr/local/genode/tool/21.05/bin/../libexec/gcc/x86_64-pc-elf/10.3.0/gnat1: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/genode/tool/21.05/bin/../libexec/gcc/x86_64-pc-elf/10.3.0/gnat1)
```
Is this correct?

**Comment by m-stein** [comment]
Oh sorry, meant a newer one:
```
> ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27
```

**Comment by cproc** [comment]
Was the tool chain perhaps built on a newer system? Then building it (the tool chain) from source should work.

**Comment by m-stein** [comment]
Ah, that's a good hint. Yeah, I built it on another machine because it takes unbelievably long :)

**Comment by m-stein** [comment]
I'll do this on Monday and invest the rest of the day in the nic_router build problem instead.

**Comment by nfeske** [comment]
@m-stein Please keep an eye on this issue because it is critical for switching to GCC 10.

**Comment by m-stein** [comment]
Ok, I will prioritize it.

**Comment by m-stein** [comment]
With 127b5e37d5, the test finishes successfully and without any compiler warnings/errors with GCC 10.

**Comment by nfeske** [comment]
Cool! Merged to staging.
