### ISSUE TITLE
Unconditional URB sglist access in usb_host_drv

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4116]
Under certain conditions, namely when using a bounce-buffer, the `usb_host_drv`'s xHCI driver accesses the _URB_'s scatter-gather list unconditionally. The driver calls `sg_pcopy_to_buffer` and `sg_pcopy_from_buffer` which both are not implemented and lead to the component stopping its execution.

**Comment by cnuke** [comment]
* 93e1b28 backports a fix from upstream where the sglist access depends on `urb->num_sgs` being set. AFAICT this field only gets set in `usb_sg_init` that apparently is not called in our port.
* ea83b91 changes the dummy implementations to mere `TRACE` dummies that return a size of _0_. This return value will trigger the check introduced in the previous commit so we will see a warning in the unlikely event that should happen.

Thanks to Peter for reporting the issue and will add the fixed label as soon as he confirms the fix.

**Comment by nfeske** [comment]
I merged both commits to staging.
