### ISSUE TITLE
ports/expat: fix deprecated URL

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#4117]
The TAR file wasn't available anymore at the given URL.

**Comment by m-stein** [comment]
Fixed.

**Comment by chelmuth** [comment]
@cproc updated expat in f89414c6378ea8dbcc2f6ac95369758cc59f1489 issue #4060. Would it suffice to include this commit into sculpt_21_03b?

**Comment by m-stein** [comment]
Of course - set that his URL works :)
