### ISSUE TITLE
recursive 'memset()' calls with gcc 10

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4125]
gcc 10 generates 'memset()' calls in implementations of 'memset()' (base, libc and rump are affected). As suggested in [1], the "-fno-tree-loop-distribute-patterns" compiler option solves this problem.

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56888

**Comment by cproc** [comment]
Fixed in 3f47a9c

**Comment by chelmuth** [comment]
Merged to staging.
