### ISSUE TITLE
depot: fix locale influence on hash generation

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#4144]
I experienced the creation of many new hashes directly on tag sculpt-21.03b when creating package sculpt. Thanks to the guidance of @chelmuth, we found that this was related to my locale setting ``LC_ALL=en_US.UTF-8`` in ``.bashrc`` (I'm on a spanish system but want my bash to work entirely in English).

**Comment by m-stein** [comment]
Fixed by 4527f6f80b.

**Comment by m-stein** [comment]
Although in online discussions I read the contrary, I could verify that in Make ``$(sort ...)`` always sorts ``LC_ALL=C``-style independent of the environment settings. However, ``$(shell echo ... | sort)`` always sorts according to the environment settings.

**Comment by m-stein** [comment]
@chelmuth I added a commit 028def622e to be squashed that should cover all tools.

**Comment by chelmuth** [comment]
For completeness: GNU Make uses `strcmp()` (which is locale-independent) not `strcoll()` (which takes into account `LC_ALL`, `LC_COLLATE`, and `LANG` in this order).

https://github.com/mirror/make/blob/1ae90c030d5ffc79f74e3938880445a6b8b2412e/src/misc.c#L37-L50

BTW, this is also true for the ViM-internal sort function.
