### ISSUE TITLE
ports/libsparkcrypto: update for GCC 10

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#4145]
The old port version contained ``*.ali`` files that were build with an older GCC which led to problems when compiling packages that use the port with the new GCC 10. The ``*.ali`` files of the new port version are generated with GCC 10.

**Comment by chelmuth** [comment]
I tested the commit and merged it to my local staging branch. As soon as the builder started I'll update genodelabs/staging for the next round.
