### ISSUE TITLE
usb_hid_drv: extra key events with cherry mechanical keyboard

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#4146]
I'm using a Cherry MX Board 3.0S and noticed that a bunch of extra key presses are reported by nitpicker once I press numlock (see also #4069). I instrumented the hid code to see what's going on and found out that an extra input report is sent by the device when I press numlock. The report does not look like the typical input report for key presses but is interpreted as such.

For the record, I implemented the dummy `hid_dump_report` to log the report data (2bytes per line):

```
[drivers -> usb_hid_drv] dev_dbg: 0x901
[drivers -> usb_hid_drv] dev_dbg: 0x200
[drivers -> usb_hid_drv] dev_dbg: 0x1
[drivers -> usb_hid_drv] dev_dbg: 0x1
[drivers -> usb_hid_drv] dev_dbg: 0x1a1
[drivers -> usb_hid_drv] dev_dbg: 0x185
[drivers -> usb_hid_drv] dev_dbg: 0x15
[drivers -> usb_hid_drv] dev_dbg: 0x125
[drivers -> usb_hid_drv] dev_dbg: 0x2095
[drivers -> usb_hid_drv] dev_dbg: 0x175
[drivers -> usb_hid_drv] dev_dbg: 0xb509
[drivers -> usb_hid_drv] dev_dbg: 0xb609
[drivers -> usb_hid_drv] dev_dbg: 0xb709
[drivers -> usb_hid_drv] dev_dbg: 0xcd09
[drivers -> usb_hid_drv] dev_dbg: 0xe009
[drivers -> usb_hid_drv] dev_dbg: 0xe209
[drivers -> usb_hid_drv] dev_dbg: 0xe309
[drivers -> usb_hid_drv] dev_dbg: 0xe409
[drivers -> usb_hid_drv] dev_dbg: 0xe509
[drivers -> usb_hid_drv] dev_dbg: 0xe909
[drivers -> usb_hid_drv] dev_dbg: 0xea09
[drivers -> usb_hid_drv] dev_dbg: 0x520a
[drivers -> usb_hid_drv] dev_dbg: 0xa01
[drivers -> usb_hid_drv] dev_dbg: 0x153
[drivers -> usb_hid_drv] dev_dbg: 0x540a
[drivers -> usb_hid_drv] dev_dbg: 0xa01
[drivers -> usb_hid_drv] dev_dbg: 0x155
[drivers -> usb_hid_drv] dev_dbg: 0x8a0a
[drivers -> usb_hid_drv] dev_dbg: 0xa01
[drivers -> usb_hid_drv] dev_dbg: 0x221
[drivers -> usb_hid_drv] dev_dbg: 0x230a
[drivers -> usb_hid_drv] dev_dbg: 0xa02
```

This report is somehow triggered by the led update which is performed by `usb_hid_drv`. I'm not entirely sure why this does not occur on a native Linux system. I guess it might be related to the fact that `usb_hid_drv` does not set the led state via a hid output report but uses a usb message and, thereby, potentially circumvent some state keeping.

A workaround for this issue could be to ignore hid input reports that exceed a certain size limit since the typical input report for key presses is much smaller (8 bytes). I don't know, however, whether this holds for more fancy hid devices as well.

**Comment by chelmuth** [comment]
Can we close this issue or do you have plans to replace the quickfix by other means?

**Comment by nfeske** [comment]
@jschlatow are you planning to follow up on the issue? If not, we should consider closing it.

**Comment by nfeske** [comment]
@jschlatow in the meanwhile, a lot has changed in DDE Linux. I'm wondering if the issue still persists, and if yes, how to go about it?

**Comment by jschlatow** [comment]
The issue still persists with 23.05. However, since I'm not using the device anymore and don't plan to follow up on the quickfix, I'm going to close the issue.
