### ISSUE TITLE
ldso: Show dependencies of loaded 'Shared_object's in case 'ld_verbose' is set

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4147]
When loading shared objects via the `Shared_object` interface or `dlopen` the loading address of the freshly loaded shared object is displayed when `ld_verbose` of ldso is enabled. In case the object depends on other objects that had not been loaded by ldso prior, the loading information is lost. Note: Already loaded dependencies of a shared object should *not* be displayed.

**Comment by ssumpf** [comment]
@chelmuth: 10dfe0d fixes the issue, it can be tested with 416cfb9.

**Comment by chelmuth** [comment]
It works like a charm. Thanks for addressing this so quickly. Merged to staging.
