### ISSUE TITLE
Platform driver API: initial spurious interrupt

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4154]
Recently, when enabling the framebuffer driver for MNT Reform2 by using Linux Kernel code, it happened that the artificially initial interrupt signaled during handler registration lead to a crashed driver, which tried to access device resources not yet initialized. In case of ported Linux kernel drivers it should be possible to omit the initial IRQ trigggering when unsing the new Platform::Device introduced in issue #4075.

**Comment by nfeske** [comment]
Merged to staging.
