### ISSUE TITLE
tool: DDE linux helper to solve missing references

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4156]

**Comment by skalk** [comment]
To give a readable overview about missing references when porting drivers from Linux, tool support is needed. Moreover, the cumbersome work of writing dummy definitions for those identified references should be automated, see the following Genodians article for the proposal: http://genodians.org/skalk/2021-04-08-dde-linux-experiments-1

**Comment by nfeske** [comment]
What a delight! Can't wait to use the new tool. Merged to staging.
