### ISSUE TITLE
page fault in falkon when loading certain websites

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#4168]
I just discovered a reproducible page fault in falkon on current Sculpt (21.03b). The page fault always occurs a few seconds after loading booking.com. I'm using the prebuilt pkg `cproc/falkon/2021-03-23-a`.

```
[core] page fault, pd='init -> runtime -> falkon -> falkon' thread='pthread.14' cpu=5 ip=0x194f8e74 address=0x412beff8 stack pointer=0x412beff8
```

**Comment by cproc** [comment]
Commit 63b16c4 increases the stack size of the render thread. I've also uploaded an updated Falkon package.

**Comment by jschlatow** [comment]
That's great. I can confirm that the new package solves the issue.

**Comment by nfeske** [comment]
Merged to staging.
