### ISSUE TITLE
i2c: transactions with multiple messages and bytes needed

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4169]
The recently introduced I2c API and driver for the i.MX 8MQ SoC has a limited scope to ether read or write up to 2 bytes within a single transaction. When trying to use it to access the I/O registers of a eDP to MIPI bridge within the MNT Reform2, the limitation became obvious.
For instance to read a register of this device, one has to first write the address to the bus (one byte), and then read the content (one byte) within one transaction - that means without restarting the bus protocol. When trying to change a register's content a write message with two bytes needs to be transfered, one byte for the address, and one for the value. Within one such a message the I2C slave address should not be re-transmitted.
To meet the requirements of this use-case, and keep the existent ones, I propose to extend the existent API in the form that:
* There is only one API call `transmit(Transaction&)`
* A `Transaction` consists of an array of messages
* A `Message` has a direction (read/write) and contains a number of bytes
* The former `read_8bits`, `write_8bits`, etc. are getting moved into the `I2c::Connection` as util functions, which map to the new `transmit` call

**Comment by nfeske** [comment]
@skalk, after our offline discussion preceding this change, I haven't expected that the increase of complexity would be so little. That's great! Merged to staging.
