### ISSUE TITLE
Introduce array utility

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4170]
By now, I've use an `Array` class within base-hw internally only. It provides means to construct arrays with a maximum size and element type in a C++ fashion. For instance the constructor accepts multiple arguments to initialize the array. Array fillings at construction time are statically checked to not exceed the array size. Moreover, one can dynamically insert elements, or iterate via `for_each` over the array.

When working on issue #4169 I needed to use arrays in the RPC interface too. To shorten the code path there, and to profit from code re-use, I would like to generalize the `Array` class from base-hw to be publicly available at `base/include/util`.

**Comment by nfeske** [comment]
This utility looks very handy. Merged to staging.
