### ISSUE TITLE
imx8mq_platform_drv: introduce reset domains

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4171]
Few devices in the i.MX 8MQ SoC need to be reset resp. taken out of the reset state by the so called System Reset Controler (SRC) before they are ready to be used. One example is the MIPI DSI Phy used by the graphical subsytem when a panel is attached to it, like the touchscreen for the i.MX 8MQ EVK, or the eDP panel in the MNT Reform2. By now, we simply used the SRC directly in the Linux framebuffer driver for this SoC. But for robustness and security reasons, it is of course no good solution to provide general reset options to the framebuffer driver.

The natural place to handle reset pins is the platform driver. To not pollute the Platform API to much, I propose to add a `reset-domain` tag to the device configuration analogue to the `power-domain` the imx8mq_platform_drv already supports. A reset-domain gets set in runnable state whenever the device gets acquired, and is set into reset state again when the device gets released.

**Comment by nfeske** [comment]
Merged to staging.
