### ISSUE TITLE
tool: DDE helper to extract initcall order

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4172]
The initcall mechanism in the Linux kernel is used to register functions that need to be called during boot, e.g., to register a device driver. Thereby, the calling order of initcalls is essential as they have inner dependencies. Unfortunatly those dependencies are not explicitly stated, or at least not al, but dependent on the link order resp. the order within all Makefiles of the kernel.
When porting Linux kernel subsystems to Genode, e.g. drivers, we need to preserve the initcall order, and at best want to extract it automatically without the need to track this manually. Therefore, tool support is needed.

**Comment by nfeske** [comment]
Merged to staging.
