### ISSUE TITLE
usb_drv: abandon support for monolithic usb driver

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#4173]

**Comment by alex-ab** [comment]
The three commits contains the main consumer (2x interactive package, VM run scripts*) of the old driver I encountered.

**Comment by nfeske** [comment]
Thank you very much. Merge to staging.

So is it time to bury the old usb_drv? ;-)

**Comment by alex-ab** [comment]
Yes, after the release the final removal commit is scheduled from my side.

**Comment by alex-ab** [comment]
673d741e615983cee86f11db56b419291931ab17 removes the old usb driver.
