### ISSUE TITLE
fec nic driver: compiler warnings

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#4178]
Compiling the FEC NIC driver on staging gives me the following warnings: 
```
lx_emul.cc:711:13: warning: taking address of packed member of ‘page’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  711 |  atomic_inc(&page->_count);
      |             ^~~~~~~~~~~~~
lx_emul.cc:730:13: warning: taking address of packed member of ‘page’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  730 |  atomic_set(&page->_count, 1);
      |             ^~~~~~~~~~~~~
lx_emul.cc:755:27: warning: taking address of packed member of ‘page’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  755 |  if (!atomic_dec_and_test(&page->_count))
      |                           ^~~~~~~~~~~~~
```

**Comment by m-stein** [comment]
I don't have a good idea how to fix this, but at the same time, I think, that we shouldn't accept compiler warnings in non-contrib code.

**Comment by m-stein** [comment]
I have created two approaches to this issue. We should merge only one of them:
3e4234bfbd Approach #2 "fec nic driver: fix compiler warnings"
0cc2e454f1 Approach #1 "fec nic driver: fix compiler warnings"

**Comment by chelmuth** [comment]
I vote for Approach 2 as this data is never accessed by the device driven and, thus, removing `packed` should be ok.

**Comment by m-stein** [comment]
Fine with me :)
