### ISSUE TITLE
tool/dde_linux refinements

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#4188]
As I started using the new dde_linux tools for porting the EMAC Ethernet driver for the Pine64, I made a few adjustments to make the tools more versatile for my workflow. In this issue, I'd like to put up these suggestions.

**Comment by nfeske** [comment]
@skalk the commits linked above contain my suggestions.

**Comment by skalk** [comment]
@nfeske: Thank you very much for your careful improvements. Except for commit "show objs for variables", see my comment inline, I'm perfectly fine with the changes.

**Comment by skalk** [comment]
Unfortunately, commit "out-of-tree build dir" breaks the tool's functionality for me. None of the function definitions can be generated anymore with a non-out-of-tree built Linux kernel.

**Comment by nfeske** [comment]
I'm sorry for this regression and will look into it.

**Comment by skalk** [comment]
No matter. I've created a fixup commit feb53a133ed1771562c8d0559433882e73e8b2b8 on my merge to staging branch, and re-applied the following commits of yours too.

**Comment by nfeske** [comment]
Thank you @skalk for the careful review and the curation of the commit series. I merged the commits of your merge_to_staging branch to staging now.

**Comment by chelmuth** [comment]
Merged to master.
