### ISSUE TITLE
falkon: search engines not stored persistently

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#4194]
Falkon browser allows the customisation of search engines. Even though all other settings are stored persistently in my recall_fs, the search engines are reset once I restart falkon.

@cproc, can you reproduce this? Are you aware of any other (unsupported) storage location used by falkon?

**Comment by cproc** [comment]
Fixed by 0e4dd1d. I've also uploaded an updated Sculpt 21.03 Falkon package. In addition to the fix it appears to be necessary to quit the browser in a 'clean' way (not killing or restarting from the Leitzentrale) to get changed settings stored in the sqlite3 database ("browsedata.db").

**Comment by jschlatow** [comment]
@cproc that's great. Thanks for the quick investigation.
