### ISSUE TITLE
sculpt: Integrate webcam scenario

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4196]
* build packages and run scripts
* fix issues and add features on along the way

**Comment by ssumpf** [comment]
@chelmuth: Please consider the above for staging.

**Comment by chelmuth** [comment]
I merged your commits to staging and replaced the Framebuffer session in the webcam test by *test-capture* in e7264facbfb9a856392813092bd6b63208a29d70 and b1d29815a2dcb050495e85d40bf14879346d13e1.

**Comment by nfeske** [comment]
Fixed in master.
