### ISSUE TITLE
Function calling order requirement of 'Cpu_session' not documented (was mantis id 169)

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#42]
Currently, Cpu_session::set_pager() needs to be called before Cpu_session::exception_handler() for the exception handler to be set on Genode/Fiasco.OC. This calling order requirement should be documented somewhere.

**Comment by cnuke** [comment]
That issue should be closed since `Cpu_session::set_pager` is gone, right?

**Comment by nfeske** [comment]
Yes, indeed!
