### ISSUE TITLE
vbox: Already configured USB devices are not passed through on Sculpt

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4206]
When adding a USB pass-through device to `config/launcher/usb_devices_rom` before starting a virtual machine, the device is not passed to the VM. It needs to be (re-)added after the VM has been started.

**Comment by ssumpf** [comment]
1f3a4b6 initially parses the devices ROM during controller construction and fixes the issue.

**Comment by chelmuth** [comment]
This issue is related to #1788.
