### ISSUE TITLE
base: extend cache maintainance functionality

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4207]
Currently, the base-library provides one cache maintainance function namely `cache_coherent` only. It is primarily needed for self-modifying code, e.g. for JIT compilers, to write-back data-cache lines and invalidate the corresponding instruction-cache lines.
To support cached DMA buffers in Linux device driver ports, we typically need two additional functions, one when driver-code initially wrote data to the DMA buffer to write-back and invalidate the data-cache lines, and one which is executed right-before reading data provided by the device. I would call them:
```
cache_clean_invalidate_data(addr_t, size_t)
cache_invalidate_data(addr_t, size_t)
```

**Comment by nfeske** [comment]
Thanks for the excellent patch. Merged to staging.
