### ISSUE TITLE
dde_linux: mark current lx_emul/lx_kit as legacy

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4223]
To make room for a new more-automated, semantically more-equivalent lx_emul environment, which re-uses mostly the original Linux kernel headers, we need to move the existent lx_emul/lx_kit to a legacy sub-directory. To avoid aliasing effects, and to explicitely mark the current approach to be legacy code.

**Comment by nfeske** [comment]
Thanks a lot for the patch! I merged it to staging now.
