### ISSUE TITLE
tool/boot: update bender for balanced intel hwp

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#4224]

**Comment by m-stein** [comment]
Fixed by 2036f57585.

**Comment by alex-ab** [comment]
Please adjust tool/boot/README so that we track the sources matching the binary

**Comment by m-stein** [comment]
Added a fixup:
d319e9f5ff fixup "tool/boot: update bender for balanced intel hwp"

**Comment by chelmuth** [comment]
> I'm thinking about moving back to "performance" but I'd like to investigate a bit more and, if I switch, I want to make it easily switchable for the user. Therefore this will receive an extra issue.

If you plan to drop the use of this feature, shouldn't we refrain from merging it?

**Comment by m-stein** [comment]
I wouldn't drop any feature. For now, the "balanced" setting is fine for me and important for @jschlatow. As soon as I find the time to look deeper into whether the slight performance decrease in my current system really comes from lower CPU frequency levels in moments of high demand, I may want to make the HWP setting configurable to the user, so @jschlatow can set it to "balanced" and I can set it to "performance" with the same bender binary.

**Comment by chelmuth** [comment]
At this time I refrain from merging this change as it silently changes the HWP configuration for all users with unpredictable effects in the field. Please consider to make the change configurable with *performance* as default.

I removed the [fixed] tag.

**Comment by m-stein** [comment]
Ok, I'll schedule it.

**Comment by m-stein** [comment]
@alex-ab Could you give these two commits a review and maybe also test them on a hardware target (if not I'll do the latter tomorrow)?

https://github.com/m-stein/morbo/commit/5086245c62650d4574e19fe961d31fd93b115a98 Make Intel HWP mode configurable via command line 

d3ffb7fce1 Bender: Intel HWP mode configurable via RUN_OPT

**Comment by alex-ab** [comment]
Adding the parameter to intel_hwp_16 function will not work. The function is invoked in 16bit mode directly from assembly code (start.asm) and up to now there is no support/arrangement to provide any arguments.

**Comment by m-stein** [comment]
Mm, I thought so...

I could test only with qemu up to now and it worked fine. That said, is it right that ``intel_hwp_16`` is not used on every pc platform?

**Comment by m-stein** [comment]
Btw., I tried to implement argument support in ``start.asm`` but was not able to find the place where ``intel_hwp_16`` gets called.

**Comment by m-stein** [comment]
@alex-ab What do you think of the new version?

**Comment by alex-ab** [comment]
@m-stein: I am fine with the bender changes.
