### ISSUE TITLE
dde_linux: introduce re-newed approach for lx_emul/lx_kit

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4225]
Instead of re-implementing the needed datastructures and function declarations, we try to re-use the original Linux kernel headers as far as possible. Moreover, the semantic of the original implementation shall be preserved, e.g. by re-using device driver configuration data from device-tree-blobs. This new approack got tested for various drivers (framebuffer, sd_card, NIC) for the i.MX8 and Allwinner SoC in dedicated repositories. It is time to publish the results at a central place in `repos/dde_linux`.

**Comment by skalk** [comment]
@nfeske would you please consider to take fixup commit fd4d7b57fd96537d24dc39e65df598e5c67e5394 as well? There was still a problem in reverting explicitely allocated dataspaces (block request stream buffer) when a session got closed.

**Comment by skalk** [comment]
Sorry, I accidentally committed some recipe hash values as well, I've cleaned up the commit. Its id is now 3be10899425933ff0156f95cf6232543f1842e78

**Comment by nfeske** [comment]
Sure. I merged https://github.com/genodelabs/genode/commit/3be10899425933ff0156f95cf6232543f1842e78 to staging. Thank you.
