### ISSUE TITLE
os: introduce C-API to Genode sessions/services

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4226]
To have a consistent scheme for C-driver ports from, e.g., Linux or BSD kernel, a C-API shall be provided common for all drivers from one device driver class.

**Comment by skalk** [comment]
@nfeske would you please consider to take fixup commit 26fe23f60f7d3a28ffd4cd176b7f317a0f767fe3 to staging as well? Unfortunately the request stream shared buffer was not freed when a session got closed.

**Comment by skalk** [comment]
@nfeske sorry, the commit id changed due to changes to the previous commit. It is now 95f6bfa5e274f8500fe51a81b266359a282b9204

**Comment by nfeske** [comment]
Merged to staging.
