### ISSUE TITLE
nic_router: fix NS flag and data offset in Tcp_packet

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#4227]
When trying to log the MSS of TCP packets via `verbose_packets="yes"`, I wondered why the data offset of my TCP packets were always zero and noticed that the NS flag was always set although wireshark claimed the opposite.

Both header fields are found in a single byte of the TCP packet header. Currently, the implementation uses C++ bit field notation (https://github.com/genodelabs/genode/blob/master/repos/os/include/net/tcp.h#L49) to access the fields. Apparently, however, this indicates the compiler to perform a word-wide memory access and, due to the missing endianess conversion, misinterpret the window size as data offset and NS flag.

**Comment by jschlatow** [comment]
@m-stein could you please review commit da72d9b?

**Comment by jschlatow** [comment]
I also added a commit to correct the name of the CWR flag.

**Comment by m-stein** [comment]
Thanks @jschlatow. This looks good to me!
