### ISSUE TITLE
libports: Update Mesa to 21.0.0

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4254]
* enable gallium
* enable iris (Intel GPU) + support for Gen8+
* etnaviv (Vivante)
* remove i965 DRI driver

**Comment by ssumpf** [comment]
@chelmuth: The above contains the libdrm and Mesa update to version 21.0.0, the currently on Gen8 working state of the GPU multiplexer, a RAM framebuffer driver for Qemu, and qt5/OpenGL adaptions for the new Mesa version.

**Comment by ssumpf** [comment]
@chelmuth: 4a98482 builds `ram_fb_drv` for ARMv8 only, because the platform session is differs on x86.

**Comment by ssumpf** [comment]
@chelmuth: 0181afd removes the leftover drm port files.

**Comment by chelmuth** [comment]
Merged your fixups to staging.

**Comment by nfeske** [comment]
Fixed in master.
