### ISSUE TITLE
depot_autopilot: test-trace sporadically fails on some platforms

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#4261]

**Comment by jschlatow** [comment]
As it turns out, commit 9898341d4a2b34e1b485e071b7ae8fb34b46f757 did not correct the test case for every platform. Commit 4135ed4 further increases the number of subjects being queried and adds a sanity check to provide a hint in case we ran into the same problem again.

**Comment by jschlatow** [comment]
@chelmuth, I added a few fixup commits that fix the test timeout and the sporadic exceptions in the test-thread on destruction. Yet, I'm still trying to find what triggers the sporadic Ipc_error in the main thread.

**Comment by chelmuth** [comment]
I merged both commits just now.
