### ISSUE TITLE
lx_emul: dma-memory alignment, kworker scheduling, and softirqs

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4268]
During my work on porting the USB host controller driver of i.MX 8MQ to Genode, I've identified some implementation gaps in our new Linux emulation library, which are:

* all memory allocations have to be cacheline-aligned on ARM
* in 'schedule()' we have to check for 'kworker' threads whether they have to do further work before blocking them
* the softirq implementation was missing a bunch of semantics, it was still a dummy implementation
* when DMA requests return  (in USB layer) a lookup from DMA bus address to virtual address is needed
* when DMA requests return the corresponding memory should get invalidated only, when the memory direction was from device to cpu

**Comment by skalk** [comment]
@nfeske commit e8c33e2 leads to incompatibility for existing drivers. They have to use the original Linux implementation in `kernel/softirq.c` instead.

**Comment by skalk** [comment]
I made a mistake while merging. I have to re-examine the commit series, sorry.

**Comment by nfeske** [comment]
I merged your commit series to staging.
