### ISSUE TITLE
rpi: migrate framebuffer driver to new platform driver

### ISSUE THREAD

**Issue by tomga** [genodelabs/genode#4303]
After migrating `usb_host_drv` to new platform driver there is a strange situation that there is a working support for keyboard, mouse (usb) and display (framebuffer) for Raspberry Pi but it is not possible to have them all working at one time. This is because there can't be two platform drivers running in parallel - at least on rpi where both would have to acsess _mbox_ device.

I'm preparing to migrate framebuffer driver to new platform driver and have some idea how to implement this change but have some doubts if it doesn't conflict with some plans about platform driver future. On one hand I'd like to avoid too much refactoring and on the other hand I don't want to work on a solution that would work but would have to be reworked in near future due to some coming changes in platform driver.

Currently framebuffer driver uses old platform driver and uses rpi specific `setup_framebuffer` rpc call in platform driver to initiate graphics (it has quite specific input parameters: geometry info and address of memory to use as a buffer). Internally it makes a _call_ to _mbox_ to do the work.

New platform driver used by usb driver provides new API that has been designed as an attempt to unify platform session interface across different boards. 

My plan for implementation would be to create new Rpi_platform rpc interface that would implement `setup_framebuffer` function and add implementation of it to rpi specific implementation of new platform driver.

Probably it would be cleaner to have `Platform::Device_interface` extended with some ability to configure the devices in generic way but given that I don't have knowledge about other devices with such special requirements I wouldn't have courage to design such api myself.

If anyone has some comments or ideas that would influence my work then please write as I plan to start working on this in a few days.

**Comment by skalk** [comment]
@tomga here are my thoughts about the issue you've opened: honestly I'm not a big fan of a frayed RPC landscape. This is the situation we had with the old platform drivers with different APIs for Arndale, i.MX53, RPI, and x86 PCs. I would prefer to have one common RPC API across all platforms, and to hide everything platform-specific inside the implementation and XML configuration of the specific components.

Given the Rpi framebuffer example, I would prefer to incorporate a framebuffer configuration option within the "newer" platform driver. If it is mandatory to have a dynamic possibility to change the setting outgoing from the framebuffer driver without changing the platform driver's configuration, I would prefer to introduce a dedicated additional service/RPC-interface that is independent of the platform API. That new API could implement the access to the mbox functionality.

**Comment by tomga** [comment]
@skalk, thank you for commenting this.

> I'm not a big fan of a frayed RPC landscape.

I understand and I knew that is it is the opinion of whole Genode team. That is why I opened this issue before starting implementation to ask if you see a better solution to this problem.

>  If it is mandatory to have a dynamic possibility to change the setting outgoing from the framebuffer driver without changing the platform driver's configuration, ...

I think it is important to have this feature but it is not the real problem here. The problem is that this rpc call attaches a DMA buffer (allocated by framebuffer driver earlier) with the display, so that it data from this buffer starts to be displayed on the screen. Even if the display configuration was constant and provided in platform configuration xml currently there is no possibility to get a properly allocated DMA buffer already bound to screen (I hope I was clear enough with this description). So some extension to existing platform API would be needed anyway. And I can't see how it could look like to be generic.

> ... additional service/RPC-interface that is independent of the platform API. That new API could implement the access to the mbox functionality.

That is my plan. In my original description I named it `Rpi platform`, but after your comment it may be better to call it `Rpi_mbox`. Currently I think only `setup_framebuffer` function is required in this interface.

**Comment by nfeske** [comment]
> That is my plan. In my original description I named it Rpi platform, but after your comment it may be better to call it Rpi_mbox. Currently I think only setup_framebuffer function is required in this interface.

Covering this special case by a dedicated session interface is a sensible approach. I foresee that we will move the rpi support to a dedicated genode-rpi repository (similar to genode-imx, genode-zynq, genode-allwinner) sooner or later. Once that happens, this place would be the natural home for this rpi-specific session interface. Maybe it could simply be called `Rpi`?.

**Comment by tomga** [comment]
@skalk and @nfeske, I'm just letting you know that I have implemented this change in 338a186ba2a0d6bf08368965248aca2d632e66e7 and have `run/demo` working on `rpi`, `rpi2` and `rpi3_32` (on `rpi3` MMU fault is reported for framebuffer driver) with new platform driver using `drivers_interactive` package. It is definitely not ready to be merged but it works. Currently I stayed with `Rpi_mbox` name for rpc interface name as `Rpi` seemed for me too generic.

Regarding moving support to dedicated `genode-rpi` repository it is something I expected to happen but as an external contributor I have some uncertainties about it. I don't know and I believe there was no information what _promises_ you make about those board specific repositories. For main repository I've seen information about code in it being regularly tested and maintained by Genode team. `genode-world` was different in a way that there was a promise that Genode team will keep code there so it can be built but not it is not tested and therefore there are no promises about working properly. Now portions of code are moved from those repositories to board specific repositories maintained outside of genodelabs account and promises disappear - at least from an external contributor's view.

May I ask for clarification for this situation? I've been keeping up with my rpi work for quite a long time now thinking that someday when it is in a good enough shape it will be merged. Somehow I'm afraid that moving it to a dedicated repository may end up making it behave like a branch in my own repository where changes required after architectural improvements are not implemented along with those improvements and I implement them later when I can. While I understand that you may stop being interested in rpi or treat it as a secondary target as a contributor I'd like to know the situation. I hope I've been able to clearly describe my doubts.

**Comment by nfeske** [comment]
Thanks for the good news about the Rpi platform driver!

> May I ask for clarification for this situation?

Right now, we are in the middle of the process the modularization of the code base. To stress the approach of cleanly separating SoC-specific code from generic code, each of three developers picked a dedicated SoC family and went with it. @skalk took the i.MX-related code to his genode-imx repository, @jschlatow took the Xilinx Zynq code to his genode-zynq repository, and I maintain the Allwinner code in my genode-allwinner repository. By looking at this modularization from three different perspectives at the same time, we can reach satisfying interfaces between the generic and SoC-specific code. I'd say we are already quite happy. E.g., @skalk recently integrated the external genode-imx and genode-zynq repositories into our regular CI. Once this explorative phase is done (I estimate by Genode 22.02), we will of course move the SoC-specific repositories under the banner of the https://github.com/genodelabs. The `genode-<soc>` repositories are no second-class citizens at all.

At this point, it will be sensible to move the Rpi-specific code to a genodelabs/genode-rpi repository as well. As for the question of quality assurance, the effort we can justify spending on each SoC ultimately depends on the respective business value vs. maintenance costs. For each SoC hosted under the genodelabs account, we are committed to maintain a baseline of QA (e.g., nightly build tests). But automated device tests are only viable for a few selected boards. Currently we have integrated one Rpi1 board and don't plan to remove it.

**Comment by tomga** [comment]
@nfeske, thank you for sharing those plans.

**Comment by skalk** [comment]
@tomga I've moved your work on the rpi-specific platform driver to the genode-rpi repository, and adapted it slightly to avoid changes in the generic platform driver implementation. Moreover, I've also moved all rpi-specific drivers apart from the gpio_drv and usb_host driver. If you like, you can give it a try by using the staging branches of the https://github.com/skalk/genode-rpi repository and the genode main repository.

**Comment by tomga** [comment]
@skalk I'm not sure when I'm able to test this code but I looked briefly to the way you changed initialization of platform driver to avoid changes in generic implementation. I didn't know about `Constructible` before but really like the way it can be used in such cases. Deferring construction of object placed directly in memory of class instance until arguments can be computed is really elegant.

I have one minor question about your change. What was your motivation behind replacing `brcm,bcm2835-mbox` I used as type of `mbox` to `broadcom-mbox`. I have taken value from device tree used in Linux and thought it is appropriate.

**Comment by skalk** [comment]
@tomga I'm sorry, I've overseen your response until now. Actually, I've used a more generic name, because it can be used across different versions of broadcom 283x. Moreover, the naming schemes in the Linux device trees are meaningful in the scope of the Linux implementation itself only. Do you see an advantage in re-using the Linux compatible string here?
Now, that the re-newed framebuffer and platform driver are mastered, can we close this issue?

**Comment by skalk** [comment]
@chelmuth indirectly the `dma_addr` work on the PD session was responsible, but it only made visible that the `managing_system` property wasn't set for the platform driver within this scenario. I've fixed that now.

**Comment by tomga** [comment]
Hi @skalk.

> Do you see an advantage in re-using the Linux compatible string here?

I just did not see a reason to not do it. I imagine that in the future you'll probably have some tool to import (semi-automatically) configurations from linux tree into platform driver configurations and in that case the less differences the better. Additionally currently this name for mbox device type is used for all Raspberry Pi flavors in Linux:
```
./arm/boot/dts/bcm283x.dtsi:			compatible = "brcm,bcm2835-mbox";
```
Anyway it is not that important. I just wanted to know why you decided to circumvent new name. Thanks for describing your motivation.

> ... can we close this issue?

Recently I'm a little short of free time so I wasn't able to test those changes till now. Possibly I'll manage to do that over the weekend. However if you want to close the issue before my testing just do it. In case I find something I can ask you to reopen it.

**Comment by skalk** [comment]
@tomga thank you for your feedback. If you encounter any problems, please feel free to open an issue within the genode-rpi repository, and we'll try to solve it together.
