### ISSUE TITLE
CBE deadlock when using test/block/client and vfs_block

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#4304]
@throwException reported this issue on the mailing list https://lists.genode.org/pipermail/users/2021-October/007806.html

> Unfortunatly, I've discovered a deadlock with CBE when using the
> test/block/client on it's encrypted volume via the vfs_block.
>
> The runscript 'vfs_cbe_ram' on the following branch will reproduce the
> deadlock:
> https://github.com/throwException/genode/tree/cbe_ram_2

**Comment by m-stein** [comment]
Thanks for having reported this @throwException and @nfeske. I'll look into it as soon as possible. However, this might very well not be before the beginning of next year.

**Comment by nfeske** [comment]
With the old block/test components removed (#4405) and looking at the issue activity, I don't see anyone attending this issue.

@m-stein to rule out the problem being in the CBE (as opposed to the test program), you may consider giving the referenced branch a try. But if you don't plan to follow up on it, I'd appreciate you closing this issue.

**Comment by m-stein** [comment]
I currently don't have the time to investigate this problem if it ain't critical for our tests / day-to-dy work anyway. However, I'll keep the possible issue in mind for when I continue working at the CBE.
