### ISSUE TITLE
Window decorations not always visible when maximizing a window

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#4306]
Normally, when maximizing a window on Sculpt, the window decorations are shown, allowing the user to un-maximize a window be clicking again at the maximizer icon. However, sometimes in Sculpt 21.10, the content appears as full screen when maximized. The only way to un-maximize it in this situation is using the keyboard shortcut `[super+enter]`.

**Comment by chelmuth** [comment]
> @chelmuth, we may consider updating the genodelabs index for Sculpt 21.10 with the fixed window_layouter

I created the https://github.com/chelmuth/genode/commits/sculpt_21_10b branch and updated the depot incl. index for 21.10.
