### ISSUE TITLE
Toolchain cannot be built on x86_64 machine

### ISSUE THREAD

**Issue by udosteinberg** [genodelabs/genode#431]
I'm running a pure 64bit Linux (no multilib or compat libs installed). Since there's no precompiled Genode toolchain for x86_64 available on SF, I've tried building my own. That fails as follows:

> unpacking gmp...
> unpacking mpfr...
> unpacking mpc...
> builing gcc...
> gtype-desc.c:8868:18: error: subscripted value is neither array nor pointer nor vector
>      sizeof (x_rtl[0]),
>                   ^
> gtype-desc.c:8987:36: error: subscripted value is neither array nor pointer nor vector
>      sizeof (default_target_libfuncs[0]),
>                                     ^
> gtype-desc.c:9071:31: error: subscripted value is neither array nor pointer nor vector
>      sizeof (default_target_rtl[0]),
>                                ^
> gtype-desc.c:9092:31: error: subscripted value is neither array nor pointer nor vector
>      sizeof (default_target_rtl[0]),
>                                ^
> gtype-desc.c:9099:31: error: subscripted value is neither array nor pointer nor vector
>      sizeof (default_target_rtl[0]),
>                                ^
> gtype-desc.c:9106:31: error: subscripted value is neither array nor pointer nor vector
>      sizeof (default_target_rtl[0]),
>                                ^
> make[3]: **\* [gtype-desc.o] Error 1
> make[3]: **\* Waiting for unfinished jobs....
> make[2]: **\* [all-gcc] Error 2
> make[1]: **\* [all] Error 2
> make: **\* [build/x86/gcc/gcc/g++] Error 2

Is this a known problem? Do workarounds exist?

**Comment by rammanoj** [comment]
I am presently facing the same issue. I am trying to build a toolchain with gcc4.6.1. But executing 
"make install all-gcc" inside build directory of gcc 4.6.1 returning me the above error. So, does it get solved by upgrading the gcc version to 4.6.3?
