### ISSUE TITLE
Potential virtual-memory leak in base-hw's core-region-map

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#4323]
In https://github.com/genodelabs/genode/blob/master/repos/base-hw/src/core/core_region_map.cc#L53, a virtual-memory range is allocated. But should the subsequent `map_local` call fail, this allocation is not reverted.

**Comment by skalk** [comment]
Seems to be fixed implicitely by the solution for issue #4324.

**Comment by nfeske** [comment]
Yes, indeed. This was actually not quite intentional. I reworked so many places in #4324 and this was apparently one of them. ;-)
