### ISSUE TITLE
dde_linux: adaptions for upcoming etnaviv driver port

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4325]

**Comment by cnuke** [comment]
On one hand the commits c9f5f0d, cfc787e and 709a96a necessary for the etnaviv driver port where `Lx_kit::Memory` is used for managing the underlying memory for *buffer-objects* manually.

On the other hand commits b78e47b and c1eeb16 deal with unneeded diagnostic messages. @nfeske please have a look if those are in line with our discussion.

**Comment by nfeske** [comment]
Thanks for the commit series and the excellent explanation. Yes, the changes are perfectly in line with our discussion.

I merged your commits to staging. I'd still welcome @skalk to have a close look, too.

**Comment by skalk** [comment]
I'm fine with @cnuke's commit series.
