### ISSUE TITLE
net: fix tail size calculation in Ethernet_frame

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#4340]
The const-variant of the `Ethernet_frame::data()` method contains an erroneous calculation of the tail size. This leads to the size guard throwing an exception when trying to parse TCP packets that only contain the TCP header.

The correct implementation of the method is found in the non-const variant.

**Comment by nfeske** [comment]
Thank you @jschlatow for reporting and the fix. I merged your commit to staging.

I'm little curious about the symptoms that led you to this issue. Is there an anecdote to share?

**Comment by m-stein** [comment]
@jschlatow Thanks for having investigated and fixed this one! As far as I can tell from looking at the code, you are absolutely right.
