### ISSUE TITLE
sculpt_manager: integrate GPU device access

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4342]

**Comment by cnuke** [comment]
Commit dede820 adds a GPU device to the list of available resources. This allows for deploying a pkg that co-locates the application an the driver by setting the appropriate `Gui` and `Platform` session.

**Comment by nfeske** [comment]
I merged the change as f236f56648a3ac546b9c6c60a8d9ee29b673db92 to staging, only changing the name from "graphics hardware" to "GPU hardware" to make distinction from display hardware more clear.
