### ISSUE TITLE
Move Raspberry Pi support into designated repository

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4363]
Analogue to other boards/SoC like imx and allwinner, the board support for Raspberry Pi variants shall be collected in one designated repositories.

**Comment by skalk** [comment]
@nfeske @chelmuth as far as it matches your agenda, the removal from rpi1/3 from the genode main repository in commit dd61cb8 is ready to be merged. I've prepared a corresponding genode-rpi repository, which I would integrate into our testing infrastructure, as soon as you've merged this commit.

**Comment by nfeske** [comment]
I merged the commit to staging as https://github.com/genodelabs/genode/commit/fe95e140944a68b4d1daa7130415cb25c36d79ef while mentioning the new location in the commit message.

**Comment by chelmuth** [comment]
The issue is marked fixed and the commit entered master. Can we close this issue?

**Comment by skalk** [comment]
Sure!
