### ISSUE TITLE
tool_chain: ali2dep is not built even if ada is enabled

### ISSUE THREAD

**Issue by tomga** [genodelabs/genode#4365]
I've stumbled upon this problem when trying to run `run/depot_autopilot` recently. My locally built tool chain did not contain `ali2dep` binaries for some architectures. It seems that initially this script was built by `tool_chain` tool but when introducing ENABLE_FEATURES in issue #4094 regression was introduced that was hard to spot if someone had tool chain already built (as it finishes properly).

The problem is in [this line](/genodelabs/genode/blob/a6fe6c90d4adf6c44828a3ae7ac30dec93109d7d/tool/tool_chain#L217).
```
ifeq ($(filter ada,$(LANGUAGES)),)
```
That condition evaluates to true even if `ada` compiler is built. The root cause of the problem is that `LANGUAGES` contains list of features separated with commas (due to [line](/genodelabs/genode/blob/a6fe6c90d4adf6c44828a3ae7ac30dec93109d7d/tool/tool_chain#L215).

I believe the easiest fix would be to use `ENABLE_FEATURES` instead of `LANGUAGES`. That variable contains list of features separated with spaces and condition would be properly evaluate to `true` only if `ada` is not being built.

**Comment by nfeske** [comment]
Sorry for attending this issue so late. Thank you @tomga for pointing out this problem and providing a solution. I added commit dc7d42d00f2f1c27959c6e5c28a10c9d84503d15 that follows your suggestion.
