### ISSUE TITLE
run tool: mechanism to obtain list of build artifacts

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#4368]
It would be nice if the run tool provided a way to track the build artifacts for invocations of the build system to be able to automate the creation of the list of boot modules for a given build. This way, the manually curated list of boot modules in run scripts could be replaced with a line like:

```
build_boot_image [build_artifacts]
```

This would simplify run scripts and make the combination of `import_from_depot` with custom built targets more convenient and robust.

**Comment by nfeske** [comment]
This topic is related to a prior discussion in #4073.

**Comment by tomga** [comment]
@nfeske, I did not realize that during our earlier discussion but I think it is not compatible with `--skip-build` option of `run` tool. So it won't be possible to use this option for those run scripts that use `build_artifacts` procedure? Am I right?

**Comment by nfeske** [comment]
> Am I right?

That sounds logical. With no build, there are no build artifacts after all.
