### ISSUE TITLE
audio_in: fix compile errors when strict warnings are enabled

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4373]
Fix compile errors related to implicit conversion and effective C++ when strict warnings are enabled.

**Comment by cproc** [comment]
Fixed by 9ff4a64.

**Comment by chelmuth** [comment]
Merged to  staging.

`Audio_out::Stream` does not include its members too. Maybe this could also be fixed? Do you see any chance to remove the extensive code duplication between the audio-session headers? I also wondered if the subtle difference between the implementations of `alloc()` and `reset()` in both sessions is intended.

**Comment by cproc** [comment]
Commit 527855a initializes the ```Audio_out::Stream``` members. I'll have a look at the code duplication issue.
