### ISSUE TITLE
vfs_oss improvements

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4375]
- add support for audio input
- implement additional sndctl commands for VirtualBox 6
- add a simple OSS microphone monitor test
- if buffer size to be written is not aligned to stream packet size, fill the last stream packet partially and continue filling on the next ```write()``` instead of filling up with silence to avoid free buffer space calculation mismatch issues 

Depends on #4374.

**Comment by cproc** [comment]
Fixed by f6c3a66.

**Comment by chelmuth** [comment]
Great, merged to staging.
