### ISSUE TITLE
dde_bsd: audio driver configuration on Sculpt

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4378]
On a Lenovo x260 I need to add the following driver configuration line to enable recording:

```
<mixer field="record.enable" value="on"/>
```

Depending on the actual audio hardware it might be necessary for a Sculpt user to tweak other mixer fields as well, but I'm not sure what exactly needs to be done to make the driver configurable on Sculpt. Moving the configuration into a raw package seems to be one necessary step. Anything more? And should the "record.enable" line be part of the default configuration?

**Comment by nfeske** [comment]
Fixed by 4a9e6a001fe0205e5cf0f3d953e12aacf83accc7 in master.
