### ISSUE TITLE
Allow derived classes of `Genode::Array`

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#4382]
I wrote a [utility class](https://github.com/jschlatow/genode-zynq/blob/ad9361/include/util/lazy_array.h) for kind of a fixed-capacity vector, i.e. an array of Constructible<T> that is able to store noncopyable and non-default-constructible objects. I based this on `Genode::Array` but this requires access to its private members. I'd therefore like to change their visibility to _protected_.

The implementation currently resides in genode-zynq. If it could be of interest for other scenarios, I'd be happy to add it to the main repo though.

**Comment by nfeske** [comment]
The commit reached the master branch.
