### ISSUE TITLE
platform API: make io-ports part of the generic platform device

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4436]
When we want to re-new the platform driver for x86 to use the new, generic platform API, we have to add io ports as device resources to it. Although this is useful for x86 only, we shall add it to serve only one common API. As long as no io ports are provided to a client it won't be used on non-x86 architectures.

**Comment by nfeske** [comment]
I suggest the consistently apply the naming "io-port range".

**Comment by skalk** [comment]
@nfeske: I've renamed all occurences of Io_port to Io_port_range accordingly.

**Comment by nfeske** [comment]
Thank you for the renaming.
