### ISSUE TITLE
pc_usb_host_drv: add missing UHCI support

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4438]

**Comment by chelmuth** [comment]
Commit 8a8e3f53ea66f1a7cc7556d8674497c297b542bf *temporarily* fixes usb_hid_raw on ultra PC by adding empirically determined config space offsets/addresses for EHCI BIOS handoff. As the address is not static or fixed but read from MMIO of the device, it may be challenging (resp. impossible) to define. I'm wondering why the protocol reads an address from MMIO but uses configuration space operations for the handoff procedure. XHCI works MMIO-only.
