### ISSUE TITLE
genode_c_api: unify shared dataspaces allocation callbacks

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4439]
Currently, there are identical callbacks defines in the Genode C API for USB and Block device drivers. Both are used to allocate, attach, and free dataspaces, which can serve as packet stream buffer in between driver and client. They are not managed by the Genode C device library, but provided by the concrete driver instance to enable the usage of dma-capable memory, and potentially use it for DMA transfers directly.
However, we can provide one central declaration of USB and Block. Moreover, the only available drivers until now are Linux kernel driver ports, which all share the same implementation. That implementation can be unified within the lx_emul code base.

**Comment by nfeske** [comment]
Merged to staging.
