### ISSUE TITLE
lx_kit: alternate memory backend

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4443]
Currently, the new lx_kit always uses the platform API to allocate memory dynamically, because drivers that are using DMA have to do so. But if we port protocol stacks like, file-systems, TCP/IP, or wireguard, we do not use devices and especially DMA-capable engines, therefore the dependency on the platform API is not wanted here. To get rid of the dependency provide an alternative memory backend, and also do not use the device abstraction in that case.

**Comment by nfeske** [comment]
Merged to staging.
