### ISSUE TITLE
usb_host_drv: share linux specific genode_c api implementation in between drivers

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4444]
The implementation needed to back the Genode C API for USB in the context of Linux kernel code is identical in between, e.g., genode-imx and pc. It is expected to be the same for other USB host controllers as well, as it depends on the generic USB interface of the Linux kernel only. On the other hand, it is the most sophisticated hand-drafted code of this driver sub-class and shouldn't be duplicated. So we should move this part to `repos/dde_linux/src/lx_emul`.

**Comment by nfeske** [comment]
Merged to staging.
