### ISSUE TITLE
Utilities for the formatted output of text

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#4449]
Genode's existing text-output facilities provided by base/output.h are deliberately simple to avoid code complexity at the lowest levels of the framework. For higher-level components, however, nice formatting is often a desirable feature. In particular, while revisiting the trace-logger component (#4448), I found that tabular output of the data would greatly enhance the value of the component. It would be nice to have a (small) set of reusable utilities for such purposes.

**Comment by m-stein** [comment]
:+1:
