### ISSUE TITLE
Improve cpu_bench, memcpy and cache benchmarks

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#4454]
When comparing CPU performance and memory throughput between base-hw on Zynq and Linux, I noticed a several issues that voided comparability.

1. On Linux, gcc default to -mthumb, which makes a difference in the bogomips reported by cpu_bench.
2. The memcpy test was significantly affected by linux' copy-on-write optimisation.

**Comment by nfeske** [comment]
Fixed in master.
