### ISSUE TITLE
pc: update wlan driver

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4455]
The following commits series introduces a new WLAN driver for the PC platform based on the Linux 5.14.2 sources that features support for  Intel wireless AX (WIFI-6) devices. It is still WIP as it lacks *rfkill* support and the management front end integration is not yet properly done. The included *wlan-test.run* may be executed to test the new driver (so far it was only tested it with a 7265D and AX201 device).

**Comment by cnuke** [comment]
Sculpt integration will follow next week (the _pc_wlan_drv_ recipe is already available). Since I have not yet tested if rejoining or roaming works, I'll expect one or the other rough edge.

**Comment by cnuke** [comment]
The branch [pc_wlan-2022-03-29](https://github.com/cnuke/genode/commits/pc_wlan-2022-03-29) contains the Sculpt integration and was so far tested on `Fuji5b` and `test-x250`.

**Comment by jschlatow** [comment]
@cnuke, on my t490s the driver cannot find the firmware. I believe the sculpt manager does not generate the corresponding rom route.

```
[runtime] Warning: wifi_drv: no route to service "ROM" (label="wifi_drv -> iwlwifi-9000-pu-b0-jf-b0-46.ucode")
[runtime -> wifi_drv] Error: ROM-session creation failed (ram_quota=6144, cap_quota=3, label="iwlwifi-9000-pu-b0-jf-b0-46.ucode")
[runtime -> wifi_drv] Error: Could not open ROM session for "iwlwifi-9000-pu-b0-jf-b0-46.ucode"
[runtime -> wifi_drv] Error: Uncaught exception of type 'Genode::Rom_connection::Rom_connection_failed'
[runtime -> wifi_drv] Warning: abort called - thread: ep
```

**Comment by jschlatow** [comment]
I added the route to the sculpt manager for further testing. Unfortunately, the driver fails at `dma_sync_single_for_device`:

```
[runtime -> wifi_drv] override physical BDF 0:14.3 -> 0:1.0
[runtime -> nic_router] [uplink] dynamic IP config: none
[runtime -> nic_router] [uplink] NIC sessions: 0
[runtime -> nic_router] [default] static IP config: interface 10.0.1.1/24, gateway 0.0.0.0, P2P 0
[runtime -> nic_router] [default] NIC sessions: 0
[runtime] child "nic_router" announces service "Nic"
[runtime] child "nic_router" announces service "Uplink"
[runtime -> wifi_drv] NR_IRQS: 4352, nr_irqs: 4352, preallocated irqs: 16
[runtime -> wifi_drv] clocksource: dde_counter: mask: 0xffffffffffffff max_cycles: 0x1d854df40, max_idle_ns: 3526361616960 ns
[runtime -> wifi_drv] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[runtime -> wifi_drv] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[runtime -> wifi_drv] PCI: Probing PCI hardware
[runtime -> wifi_drv] PCI host bridge to bus 0000:00
[runtime -> wifi_drv] pci_bus 0000:00: root bus resource 1670380R
[runtime -> wifi_drv] pci_bus 0000:00: root bus resource 1670340R
[runtime -> wifi_drv] pci_bus 0000:00: No busn resource found for root bus, will use [bus 00-ff]
[runtime -> wifi_drv] pci 0000:00:01.0: [8086:9df0] type 00 class 0x00028000
[runtime -> wifi_drv] pci 0000:00:01.0: reg 0x10: 1a58d0R
[drivers -> platform_drv] Warning: 00000000:00000014.3 write access to address=0x30 value=0xfffff800 size=0x2 got dropped
[drivers -> platform_drv] Warning: 00000000:00000014.3 write access to address=0x30 value=0x0 size=0x2 got dropped
[runtime -> wifi_drv] pci_bus 0000:00: busn_res: 407fedb0R end is updated to 00
[runtime -> wifi_drv] clocksource: Switched to clocksource dde_counter
[runtime -> wifi_drv] NET: Registered PF_PACKET protocol family
[runtime -> wifi_drv] Intel(R) Wireless WiFi driver for Linux
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: enabling device (0000 -> 0002)
[drivers -> platform_drv] runtime -> wifi: assignment of PCI device 00:14.3 succeeded
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: pci_enable_msi failed - -38
[drivers -> platform_drv] 00000000:00000014.3 adjust IRQ as reported by ACPI: 255 -> 16
[drivers -> platform_drv] 00000000:00000014.3 uses MSI (supports MSI-X) vector 0x7b, address 0xfee00018
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 0
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 1
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 2
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 3
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 4
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 6
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 8
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 9
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 10
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 11
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 15
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 16
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 18
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 19
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 20
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 21
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: WRT: Overriding region id 28
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: loaded firmware version 46.6b541b68.0 9000-pu-b0-jf-b0-46.ucode op_mode iwlmvm
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: Detected Intel(R) Wireless-AC 9560 160MHz, REV=0x318
[runtime -> wifi_drv] task_work_add: task: 1aea60 work: 416fee40 notify: 0
[drivers -> usb_drv] usb 1-7: USB disconnect, device number 14
[runtime -> wifi_drv] iwlwifi 0000:00:01.0: base HW address: 04:33:c2:1d:af:1f
[runtime -> wifi_drv] ieee80211 phy0: Selected rate control algorithm 'iwl-mvm-rs'
[runtime -> wifi_drv] sched_clock: Marking stable (512818000, 39053000)->(543431000, 8440000)
[runtime -> wifi_drv] greg: Loading compiled-in X.509 certificates for regulatory database
[runtime -> wifi_drv] reg: loaded regulatory.db is malformed or signature is missing/invalid
[runtime -> wifi_drv] Warning: /dev/rtc not readable, returning 0
[drivers -> usb_drv] usb 1-7: new high-speed USB device number 15 using xhci_hcd
[runtime -> wifi_drv] Error: Function dma_sync_single_for_device not implemented yet!
[runtime -> wifi_drv] Backtrace follows:
[core] no RM attachment (READ pf_addr=0xffffffffffdd0da0 pf_ip=0x1522703 from pager_object: pd='init -> runtime -> wifi_drv' thread='ep') 
[core] page fault, pd='init -> runtime -> wifi_drv' thread='ep' cpu=0 ip=0x1522703 address=0xffffffffffdd0da0 stack pointer=0x41bfe990 qualifiers=0x4 irUwp reason=1

```

**Comment by cnuke** [comment]
@jschlatow thanks for testing - I'll look into it.

**Comment by cnuke** [comment]
@jschlatow please give commit [c2cbc59](https://github.com/cnuke/genode/commit/c2cbc591da4d63727e40968d901df6d9f3b8a17f) a try.

**Comment by cnuke** [comment]
Commits [8392c36](https://github.com/cnuke/genode/commit/8392c36d269477df3a7e1c003ac2f95db74002d5) and [be97d5b](https://github.com/cnuke/genode/commit/be97d5b29c6481c1a03d3a60de469c3e4b0dfc3e) deal with `netperf`.

**Comment by jschlatow** [comment]
@cnuke, with c2cbc59 the driver starts and associates with the AP. The nic_router assigns it to the default domain and not the uplink domain, though. This is because the generated nic_router config has a `<policy label="wifi_drv -> " ...` whereas the wifi drivers creates a session with label `wifi_drv -> wlan0`.
Nonetheless, if I manually fix the policy, I am able fetch packages and run a speedtest in falkon.

**Comment by cnuke** [comment]
@chelmuth please give [2eba830](https://github.com/cnuke/genode/commit/2eba83097b72c7644ec2283834fffd27f31f7a04) a try.

**Comment by chelmuth** [comment]
Does *quick-fix* mean you like to propose a cleaner solution for later implementation?

**Comment by cnuke** [comment]
@chelmuth not necessarily - it just means I took the first opportunity to fix the problem but did not spend time to explore other ways.

**Comment by jschlatow** [comment]
@cnuke, on my t490s the wifi_drv loses AP authentication after some time (occured twice within ~1h) and does not reauthenticate. Interestingly, the Leitzentrale still shows the wifi as "associated".

```
[runtime -> wifi_drv] wlan0: authenticate with 4c:1b:86:5b:de:18
[runtime -> wifi_drv] wlan0: send auth to 4c:1b:86:5b:de:18 (try 1/3)
[runtime -> wifi_drv] wlan0: authenticated
[runtime -> wifi_drv] wlan0: associate with 4c:1b:86:5b:de:18 (try 1/3)
[runtime -> wifi_drv] wlan0: RX AssocResp from 4c:1b:86:5b:de:18 (capab=0x1431 status=0 aid=5)
[runtime -> wifi_drv] wlan0: associated
[runtime -> wifi_drv] create uplink for net device wlan0
[runtime -> nic_router] [uplink] NIC sessions: 1
[runtime -> nic_router] [uplink] dynamic IP config: interface 192.168.2.189/24, gateway 192.168.2.1, P2P 0, DNS server 192.168.2.1
[runtime -> wifi_drv] wlan0: deauthenticated from 4c:1b:86:5b:de:18 (Reason: 2=PREV_AUTH_NOT_VALID)
[runtime -> nic_router] [uplink] dynamic IP config: none
[runtime -> nic_router] [uplink] NIC sessions: 0
```

**Comment by cnuke** [comment]
@chelmuth please merge [6f5c31f](https://github.com/cnuke/genode/commit/6f5c31f4804e945e3f267b91253af34047942827).

**Comment by cnuke** [comment]
@jschlatow long story short, it is currently not possible in the wifi management layer to differentiate between auth-failures due to a forced de-authentication (basically a re-authentication request) by the AP and a failed authentication due to a wrong PSK. With the debug commit one is able to react upon the re-authentication request. In case of a manual managed wifi config a rewrite of the file will trigger trying to join the network once more. When a managed config is used the user will be prompted to enter the PSK again.

I guess it could be reasonable to hide this particular situation from the user and track the state of each AP in the management layer.

**Comment by chelmuth** [comment]
@cnuke Do we have any chance to trigger such reauth requests regularly in our testing environment? How does Linux WPA Supplicant play with these?

**Comment by cnuke** [comment]
@chelmuth please see answers below:

> Do we have any chance to trigger such reauth requests regularly in our testing environment?

Yes, we could use the `ubus` interface via ssh on an OpenWrt AP to force de-/reauthentication.

> How does Linux WPA Supplicant play with these?

I did not check how it fares but I guess it will cope with the situation. AFAICT the problems mainly arise from how we interact with the supplicant. My commit [accab77](https://github.com/cnuke/genode/commit/accab77ccca68ea811add6623fee84148edb9ec5) addresses this by ignoring it on our side, which leads to the supplicant doing its thing and rejoining the network.

I vaguely remember @nfeske having some issue in the past where he could not rejoin a network after he got disconnected. This is probably due to disabling the network (I changed that to removing the network in my debug commit [9069335](https://github.com/cnuke/genode/commit/9069335e62c68429237018f42ae9c22cb73b6d35)) in case we get disconnected. Since it never gets re-enabled from our side the supplicant will not join the network again.

All in all we should spend some time to rework the wifi management state-machine.
