### ISSUE TITLE
genode_c_api/usb: report iface class and protocol

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4463]

**Comment by cnuke** [comment]
Commit [277914e](https://github.com/cnuke/genode/commit/277914e0b76c9bfbfd335acda58d3ac548123a41) implements the currently absent feature from the Genode C API for USB where the device report contains interface class and protocol information also.
Since I did not want to change the API itself I call the various callback functions to gather the information from the report method directly.

**Comment by skalk** [comment]
@chelmuth: I think this is a valid approach in the current state. I have no objections against @cnuke's solution.
