### ISSUE TITLE
libdrm: Get rid of dangling allocations when destructed

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4466]
During exit of glmark2 dangling allocations can observed

`Warning: 3 dangling allocations at allocator destruction time`

**Comment by ssumpf** [comment]
* c61bfbd makes sure to remove all meta data blocks but the initial one. When `free_empty_blocks` is called for meta data, new unused regions may be produced. Therefore, we call `_revert_unused_ranges` and `free_empty_blocks` unitl no more unused regions are found
* 637baea makes sure the driver name strings can be freed with `free`
* f5ec7d4 removes all allocated objects when `Drm_call` is destructed

With the commits above `glmark2` does warn about any dangling allocations during exit

**Comment by chelmuth** [comment]
@nfeske what is your stance on 1440f572d26ae0638cd48eb8a88430049e421d54 + ac455649aaef357ee63343069522225e2c376f62 ?

**Comment by nfeske** [comment]
That looks good to me, even better with the added comment. Thanks @ssumpf and @chelmuth.
