### ISSUE TITLE
Remove block devices from filesystem only tests

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4490]
Currently, certain run-scripts that actually shall test filesystems and/or their integration into the VFS use a variety of block devices (ahci, sd-card, vfs_block) although they run on Linux and Qemu only. Those run-scripts repeatedly stay in the way when changing device driver and platform driver interaction. Moreover, it constrains on which platforms the run-scripts can be tested (typically pbxa9, linux, qemu-pc only), because to test it on all platforms would mean to extend the zoo of different block devices.
Instead I vote for using the vfs_block component always, which uses a raw image from the boot-modules, and remove the different block devices and drivers from the picture.
The related run-scripts are:
* libc_block
* fatfs_blkio
* libc_vfs_*
Moreover,  I've identified `repos/libports/run/libc_filesystem_test.inc` to be an orphaned run-script snippet that is not included by any run-script.

**Comment by nfeske** [comment]
> Those run-scripts repeatedly stay in the way ...

As this matches my experience, I'd welcome this change very much.
