### ISSUE TITLE
qemu-usb: support policy labels without specifying vendor/product information

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#4492]
The qemu-usb lib expects product/vendor and bus/dev in the usb_devices configuration as criteria to differentiate various USB devices. If not specified, all USB devices get the same default bus/dev and product/vendor ids. On unplug of one USB device, all others will be removed also.

On Sculpt the use-case arose to use virtual labels, e.g. not "usbstick" instead of "USB1-2", without specifying the vendor/product etc. This happened to work, by accident, for exactly one virtual labeled USB device, but not reliable for more (unintended removal of other USB devices, see above).

**Comment by alex-ab** [comment]
With commit 80be2fc just using virtual labels in usb_device configuration now works, tested on vbox6 and vbox5 on Sculpt 22.04.

**Comment by nfeske** [comment]
As a quick feedback, thanks to this change, VBox behaves very well now in my usage scenario (usb serial + usb fastboot). Thanks for making my life easier! :-)
