### ISSUE TITLE
lx_emul: basic support for Cortex-A9

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#4499]
When porting the sd_card_drv for the Zynq SoC, I made a few architecture-specific modifcations and additions to lx_emul.

**Comment by skalk** [comment]
@jschlatow yes it is, thank you.
On Fri, May 06, 2022 at 05:46:14AM -0700, Johannes Schlatow wrote:
> @skalk, I referenced your ARM 32-bit commit as a prerequisite. Is this ready to be merged from your point of view?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/genodelabs/genode/issues/4499#issuecomment-1119579063
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

-- 
Stefan Kalkowski
Genode labs

https://github.com/skalk | https://genode.org

**Comment by nfeske** [comment]
I merged the commit series to staging now.

**Comment by m-stein** [comment]
@nfeske: @skalk and I have added a fix-up https://github.com/m-stein/genode/commit/48002fb43f6e98f87dd1c1ea5d7728deb9ef992e.

**Comment by nfeske** [comment]
The commits entered the master branch.
