### ISSUE TITLE
trace_buffer: race between initialisation and iteration

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#4513]
The monitor should wait until the buffer has been initialised by the subject before iterating buffer entries. Otherwise, this occasionally has the effect that the first entry is processed twice.

**Comment by jschlatow** [comment]
Fixe by commit d075d71

**Comment by nfeske** [comment]
Besides the fix, I like the introduction of `Entry::invalid`, which makes the code more self-explanatory. Thank you. I merged the commit to staging.

**Comment by jschlatow** [comment]
@chelmuth, thanks for letting me know. I added a fixup: 64d771a.
