### ISSUE TITLE
libports: update e2fsprogs to 1.46.5

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4524]

**Comment by chelmuth** [comment]
Should *e2fsprogs.port* also be updated like the library? Which port is relevant for Sculpt?

**Comment by cnuke** [comment]
@chelmuth The library port is relevant for Sculpt, which is why I updated this one.

*e2fsprogs* initially relied on `noux` while the *e2fsprogs-lib* did not. By now the differentiation is mood and the most prominent reason for the existens of *e2fsprogs* would be easier integration into the *system_shell* pkg. At the moment I have not use for that and the port itself would probably be better covered by using `goa`.
