### ISSUE TITLE
pci_decode: does not report any devices on Qemu

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4539]
After a report on the mailing list by @trimpim, I tried to run pci_decode on Qemu (BOARD=pc) with Nova and base-hw. Unfortunately, it does not report any PCI device.

**Comment by skalk** [comment]
I could see that the problem arises from trying to be type-safe. When storing the maximum count of buses in the `bus_t` type (bus number), it happens that the actual limit of the type gets exceeded by one. The ACPI report returns a maximum of 256 buses within the PCI config space window. This leads to `bus_t bus_count = 0` in the calculation, and to no PCI bus getting parsed at all.

**Comment by m-stein** [comment]
I've added the fixed label in the name of @skalk.
