### ISSUE TITLE
pc: use lx_emul_gen_random_bytes() for randomness

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#4544]
Consolidate all existing mocks into one (complete) implementation.

**Comment by chelmuth** [comment]
@cnuke may I merge this to staging?

**Comment by cnuke** [comment]
@chelmuth LGTM.

**Comment by m-stein** [comment]
@chelmuth Would you be fine with 9c427d93669280ff3de9455cf25e194c6bd6720a ? I tried to adapt all places that used to call ``lx_emul_gen_random_uint`` and tested it with wireguard and wifi.
