### ISSUE TITLE
legacy_platform_drv: ACPI devices in configuration

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#4545]
Currently, resource information for non-PCI devices is not available at runeimte. This patch enables the specification of statically known ACPI device resources on startup like follows.

```xml
<config>
  <policy label_prefix="driver">
    <device name="ACPI0000"/>
  </policy>
  <acpi-device hid="ACPI0000">
    <irq    number="99"/>
    <iomem  base="0xfc000000" size="0x100000"/>
    <ioport base="0x4000"     size="4"/>
  </acpi-device>
</config>
```

This is a preparatory commit for the pending i2c_hid driver.

**Comment by chelmuth** [comment]
@alex-ab could you please review a252906718cc10033adf9fe97f4a3804837032a1 as it touches several places in the legacy platform driver

**Comment by alex-ab** [comment]
I am fine with the commit, beside a naming remark regarding an member object.
