### ISSUE TITLE
sandbox: prevent non-empty list model on destruction

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#4547]
The parent-provides model is destroyed if no `<parent-provides>` node is found in the configuration, which results in

```
  Warning: list model not empty at destruction time
```

and leaking memory for previously allocated nodes.

**Comment by chelmuth** [comment]
@nfeske any objections to merging this fix?

**Comment by nfeske** [comment]
No objection. I very much appreciate the fix and the updated test in particular.
