### ISSUE TITLE
libc: socket_fs_plugin ignores SOCK_NONBLOCK when creating a socket

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#4550]
When creating a socket with `socket(AF_INET, SOCK_DGRAM | SOCK_NONBLOCK, 0)`, the socket remains blocking because the socket_fs_plugin ignores `SOCK_NONBLOCK`.

**Comment by jschlatow** [comment]
Fixed by 707e4b1

**Comment by nfeske** [comment]
The fix entered the master branch.
