### ISSUE TITLE
usb_net: Enable ECM support & disconnect

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4557]
The Quectel modem of the PinePhone requires ECM + the modem can be shutdown and restarted. Handle this gracefully.

**Comment by ssumpf** [comment]
For disappearing and reappearing NICs (e.g., LTE modem when restarted) the NIC (uplink) and the gateway (LTE) can receive new MAC addresses. Therefore, https://github.com/genodelabs/genode/issues/4558 should also be added.

**Comment by nfeske** [comment]
Merged to master.
