### ISSUE TITLE
libc: output warning if real time clock is requested but not present

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#4561]
Currently, `clock_gettime(CLOCK_REALTIME)` returns `EINVAL` when no RTC has been configured in the VFS. Unfortunately, it appears to be uncommon to check the return value of `clock_gettime()`. An example for this is stdcxx, which uses the wall-clock time in `std::this_thread::sleep_for()`. When no RTC is configured, `sleep_for()` will sleep indefinitely. This is quite a stumbling block when running 3rd-party applications on Genode since there is currently no warning about the fact that the RTC is used but unconfigured.

**Comment by chelmuth** [comment]
I do not get why *sleep_for* would need `CLOCK_REALTIME` if `CLOCK_MONOTONIC` is sufficient. Do we have a configuration issue here or does the usage example use something like `chrono::system_clock::now()` ?

**Comment by nfeske** [comment]
Merged in master.
