### ISSUE TITLE
Noticable lag on USB unplug in sessions to unrelated USB devices

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#4566]
According to user report, this can be tested by moving a USB mouse while unplugging another USB device (e.g., thumbdrive). The mouse pointer hangs noticeably for a subsecond period. It was also reported that Isochronous audio streams experience stutter in this situation. The effect can be mitigated (but not eliminated) by removing `usb_reset_device()` on release. This is a regression with the new USB host driver.

**Comment by chelmuth** [comment]
Based on my experiences in #4565 I suggest to remove `usb_reset_device()` and rely on the *unbind* magic in `usb_driver_release_interface()`. Further investigations of potential remaining lags after this change are pending.

**Comment by skalk** [comment]
@alex-ab please merge commit c51bb8f to staging to partly fix this issue.

**Comment by alex-ab** [comment]
> @alex-ab please merge commit [c51bb8f](https://github.com/genodelabs/genode/commit/c51bb8fba668ef45732daade9d7d36f82c44b555) to staging to partly fix this issue.

Added to staging.

**Comment by chelmuth** [comment]
Users still report small but noticeable lag with d9407c74609864397464f7c8ed318bce3d9e3a99 applied.

**Comment by skalk** [comment]
IMO we can only address this issue when changing the USB session in a way that almost everything is done asynchronously, especially opening/closing resp. claiming/releasing interfaces. Thereby, we also have to use an asynchronous way in closing USB sessions.

**Comment by chelmuth** [comment]
@skalk may we close this issue with the USB renewal merged?

**Comment by skalk** [comment]
Yes
