### ISSUE TITLE
Pagefaults in USB host driver on plug/unplug of full hub

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#4567]
According to user report, a USB descriptor `memcpy` operation faults if a hub is quickly unplugged while attached devices are enumerated.

**Comment by skalk** [comment]
alex-ab: please apply commit 43b8a80 to staging to fix this issue.

**Comment by alex-ab** [comment]
> alex-ab: please apply commit [43b8a80](https://github.com/genodelabs/genode/commit/43b8a80fd09c5ad2de5753a3bae14ebc4602e80b) to staging to fix this issue.

Added to staging.
