### ISSUE TITLE
qemu-usb library: handle Interface_not_found exception

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4572]
At some places the Interface_not_found exceptions from the USB session API are not handled that can occur if a device vanishs while handled by a guest OS in virtualbox.

**Comment by skalk** [comment]
@alex-ab: please merge commit 785da9b to staging to fix this issue.

**Comment by alex-ab** [comment]
> @alex-ab: please merge commit [785da9b](https://github.com/genodelabs/genode/commit/785da9b9ea7b62c57b35a243c26c8714b7fc0ab9) to staging to fix this issue.

done
