### ISSUE TITLE
qt5: update to version 5.15.2

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4589]
Qt 5.15.2 is the latest Qt version with QtWebEngine support on FreeBSD.

**Comment by cproc** [comment]
Fixed by e4c8d69.

To use the updated version, the Qt host tools need to be updated as well with the `tool/tool_chain_qt5` script.

**Comment by chelmuth** [comment]
Thanks, I merged the commits and built the tools.

**Comment by chelmuth** [comment]
@cproc Why does the port come with *genode/api/include/QtGui/5.15.2/QtGui/qpa_genode/qgenodeplatformwindow.h* and *qtbase/src/plugins/platforms/genode/qgenodeplatformwindow.h* and why do those files diverge?

**Comment by cproc** [comment]
> @cproc Why does the port come with _genode/api/include/QtGui/5.15.2/QtGui/qpa_genode/qgenodeplatformwindow.h_ and _qtbase/src/plugins/platforms/genode/qgenodeplatformwindow.h_ and why do those files diverge?

The `api` one is used by `QGenodeViewWidget` and `qt_avplay`. If they diverge it just means that I forgot to update the copy.
