### ISSUE TITLE
platform API: simplify _wait_for_device

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4615]
The current implementation of `_wait_for_device` in the `Platform::Connection` class is a bit too complicated, and although correct it can lead to nasty kernel warnings when a signal to an invalid signal handler is raised. We can supress this warning, and thereby simplify the waiting for a valid devices ROM.

**Comment by nfeske** [comment]
When looking at the patch, I'm wondering if there is any chance that a signal may get lost?

When the platform driver tries to submit a signal just after the client called `sigh(Signal_context_capability())`, would the platform driver send the signal on the next call of `sigh(_handler)`?

**Comment by skalk** [comment]
After rethinking it, I think you're right, but actually the problem existed already before. In general, we have to register the signal handler at construction time, and need to overwrite it, when the client requests it. Thereby, we cannot loose a signal, nor accidentally overwrite an explicitly set signal handler of the client. I'll sketch a solution in a follow-up commit.

**Comment by skalk** [comment]
@nfeske I've replaced the original commit by commit a2e15db

**Comment by nfeske** [comment]
The new version looks good to me. I merged the commit to staging.
