### ISSUE TITLE
tool chain: improve 'autoconf' version selection

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4622]
On Ubuntu 22.04 `autoconf2.69` is needed, but on Ubuntu 20.04 it's `autoconf` (which is version 2.69 as well).

**Comment by cproc** [comment]
Fixed by 492a3aa.

**Comment by chelmuth** [comment]
Great, it seems to work as intended - x86 was built successfully, other platforms are in the queue. Merged the commit to staging.
