### ISSUE TITLE
pci_decode: virtual MSI interrupt numbers can be wasted

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4628]
The pci_decode component has to provide MSI interrupt values. These so to say virtual slot numbers can get wasted, when the process of PCI device discovery gets re-started (due to too small initial Report buffers), while the MSI number counter already got increased.

**Comment by skalk** [comment]
@nfeske @chelmuth commit b41961abd7a6e03070b464de6b1f9954c3588739 is destined for the Sculpt release as well

**Comment by nfeske** [comment]
Fixed in master.
