### ISSUE TITLE
Sculpt 22.10: Minor issues

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4631]
A place to put minor issues while testing the upcoming Sculpt release.

**Comment by cnuke** [comment]
FWIW, while fetching a large pkg I noticed what seems to be reoccuring diagnostic messages, e.g.

```
[init -> runtime -> depot_query] Warning: directory 'alex-ab/raw/vm-tc-firefox/105.0.1-tc-13' does not exist
[init -> runtime -> depot_query] Warning: directory 'alex-ab/bin/x86_64/vfs_block/2022-10-05' does not exist
[init -> runtime -> depot_query] Warning: directory 'alex-ab/bin/x86_64/vfs_import/2022-10-05' does not exist
[init -> runtime -> depot_query] Warning: directory 'alex-ab/bin/x86_64/seoul/2022-10-05' does not exist
[init -> runtime -> depot_query] Warning: directory 'alex-ab/raw/seoul-config/2022-06-06' does not exist
[init -> runtime -> depot_query] Warning: directory 'alex-ab/raw/vm-tc-firefox/105.0.1-tc-13' does not exist
[init -> runtime -> depot_query] Warning: directory 'alex-ab/bin/x86_64/vfs_block/2022-10-05' does not exist
[init -> runtime -> depot_query] Warning: directory 'alex-ab/bin/x86_64/vfs_import/2022-10-05' does not exist
[init -> runtime -> depot_query] Warning: directory 'alex-ab/bin/x86_64/seoul/2022-10-05' does not exist
[init -> runtime -> depot_query] Warning: directory 'alex-ab/raw/seoul-config/2022-06-06' does not exist
[…]
```

Commit [f0044cf](https://github.com/cnuke/genode/commit/f0044cfa89230c3965c2bc0e21a390f8fe4b9e50) removes the message but it is probably put in place for a reason. (Since I use a somewhat modified Sculpt branch it is likely I introduced the problem.)

**Comment by cnuke** [comment]
Restarting the updated `dde_bsd` driver leads a page-fault, e.g.
```
[init -> runtime -> bsd_audio_drv] --- probe drivers ---
[init -> runtime -> bsd_audio_drv] azalia0 [8086:160c]
[init -> runtime -> bsd_audio_drv] : 
no RM attachment (WRITE pf_addr=0x4 pf_ip=0x101d490 from pager_object: pd='init -> runtime -> bsd_audio_drv' thread='ep') 
page fault, pd='init -> runtime -> bsd_audio_drv' thread='ep' cpu=0 ip=0x101d490 address=0x4 stack pointer=0x404fe2d0 qualifiers=0x6 irUWp reason=1
```

I'll look into that.

**Comment by nfeske** [comment]
I'd like to remove vbox5 from the default Sculpt index and the sculpt_distribution. By now, we should all have migrated to vbox6. What do you think?

**Comment by nfeske** [comment]
> I think that I´ll drop these intermediate attempts and merely issue a new query once the installation is settled.

@cnuke, commit c6900821d7a6835f21d8c7e08b52ff3c1cda18eb + fixup 79471f04fe4a9083d5ffdff2178a00aedd4a3503 should remove the annoying warnings.

**Comment by cnuke** [comment]
@nfeske thanks, those commit indeed address the warnings.

However (even without the fixup commits), as I noticed now on the X250, the download does not succeed for larger pkgs when using the ethernet nic. At some point it stops and I cannot even ping the machine after that. The problem does not occur on Fuji3.

**Comment by nfeske** [comment]
> as I noticed now on the X250, the download does not succeed for larger pkgs when using the ethernet nic

This symptom sounds unrelated unrelated to the Sculpt manager's change though, doesn't it? At least, I cannot draw any connection. I wonder, may the former pressure on the file system have masked a networking issue?

**Comment by cnuke** [comment]
Yes it is unrelated. I just noticed it now as it was the first time I used the X250 for testing.

**Comment by cnuke** [comment]
@chelmuth booting from an USB stick makes all the difference. So it points to an PXE related problem.

**Comment by ssumpf** [comment]
@chelmuth, @nfeske: When issuing a `poweroff` I experienced a RAM resource request from `acpica`. c04a0e8 should fix that.

**Comment by nfeske** [comment]
All fixes went to master. Thanks everyone for testing and refining.

**Comment by alex-ab** [comment]
With ae84eb1d9bcca247f758d05af1fe3832741f95ce the battery app works now with the current acpica port again.

**Comment by nfeske** [comment]
> With https://github.com/genodelabs/genode/commit/ae84eb1d9bcca247f758d05af1fe3832741f95ce the battery app works now with the current acpica port again.

That is super cool! Thank you for solving this long-standing riddle. :-)
