### ISSUE TITLE
vmm_x86: guest code page in separate asm file

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#4638]
Implement the guest code in dedicated assembler source file, assemble and link the binary to vmm_x86. The resulting guest-code binary populates one page that is mapped to host the reset vector of the guest.

This approach simplifies future guest code adaption resp. extension, e.g., to test rdmsr/wrmsr exiting.

**Comment by chelmuth** [comment]
@alex-ab What's your opinion on de97a8252b28bd2d33e5a347d76ffe3c1f5368ea?

**Comment by alex-ab** [comment]
I like it :+1:
