### ISSUE TITLE
nova: report of platform_info crashes on systems with more than 30 CPU cores. 

### ISSUE THREAD

**Issue by mmueller41** [genodelabs/genode#4640]
For my research, I tried to run Genode with NOVA as kernel (as is recommended in the documentation) on our servers with >64 cores, and noticed that Genode crashes during boot without giving an error message. I tried deactivating cores in UEFI settings and found out that if the number of CPU cores is below 30, Genode boots fine, but not as soon the number is increased again.

The problem seems to be the creation of the report for platform_info in `repos/base-nova/src/core/platform.cc`. At line 680 there is a fixed amount of one memory page requested for the ROM module, but the actual size of the ROM module depends on the number of CPU cores the system has. One memory page is enough to accommodate the report for around 30 CPUs. If there are more CPUs in the system, the report is written over the bounds of the memory page into memory that has not been allocated. Of course, this leads to a page fault. But, since the page fault handler for core has not been registered yet, there is no error message printed but instead the machine just reboots.

A quick fix would be to just allocate more fixed memory for the ROM module, but this only postpones the problem into the future.
A nicer fix would be to allocate just enough memory to fit in the XML reports for the CPUs and the rest of platform_info, depending on the actual number of CPU cores. For this the size of the XML node for the CPU information and the number of CPUs is needed.

Here the corresponding lines from platform.cc:
```cpp
export_pages_as_rom_module("platform_info", 1,
		[&] (char * const ptr, size_t const size) {
			Xml_generator xml(ptr, size, "platform_info", [&] ()
```

**Comment by mmueller41** [comment]
I can confirm, that the fix to `platform.cc` at [https://github.com/genodelabs/genode/commit/dd124f27b7cc5e7f4704507ac1bfb6aae6116e50](dd12f4f2) works for me with 64 cores in Qemu. I will give it a try on one of our servers with 64 CPU cores later.

**Comment by alex-ab** [comment]
@chelmuth: please review a0ac9f3867044efe06cc3120024d662fb3889fc0 and consider for staging

**Comment by nfeske** [comment]
Fixed in master.
