### ISSUE TITLE
Enable more compiler warnings

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#465]
A good start would be a warning-less Genode build with `-Wextra`. This may exclude several contrib sources. Further, we should evaluate other warning flags not in `-Wextra`, e.g. `-Wnon-virtual-dtor`.

**Comment by chelmuth** [comment]
Is seems desirable to enable `-Weffc++` for Genode base sources.

**Comment by m-stein** [comment]
@chelmuth, @nfeske These commits fix the problem with the net lib and effective C++ in a cleaner way and remove some unnecessary code from the lib interface:

783ec54 net: remove unused enums
000cc58 net: remove placement new operators
f278b35 net: check packet data size in accessor
813787d fixup "Follow practices suggested by "Effective C++" (net lib)

I removed the packet class constructors completely for now. Of course, when composing a new packet they would be nice to ensure that all members are written and therefore no local data is leaked, but it is not so easy to adapt the NIC router to this schema and I don't want to further delay merging. Instead, with the commits composing stays as is (cast an allocated pointer and write members manually) and I would address this problem in an extra issue.

**Comment by m-stein** [comment]
I just noticed that, at least in the NIC router, leaking data due to missing packet member initialization is not an issue. In the newest version, the router composes packets directly in the RAM freshly allocated by the packet stream. This RAM, AFAIK, is nulled.

**Comment by ssumpf** [comment]
@chelmuth:  eaf8c1a makes RISC-V compile again.

**Comment by nfeske** [comment]
@m-stein Thanks for reviewing the NIC router in this respect. Note, however, that - even thought the packet-stream buffer is cleared initially as it is a RAM dataspace - allocations within the packet-stream buffer during the lifetime of the session are not cleared individually. So content from old packets may leak into uninitialized header fields of later packets. Granted, this is not a leak between domains but may cause erratic network behavior.

For the general direction: I think it is not ideal to review all current (and future) users of the net headers whether they are prone of information leaks through the header fields or not. Ultimately, the headers should initialize all members. User code can still cast a pre-populate packet buffer to a pointer of such a type and thereby explicitly bypass the initialization. This is needed in particular when parsing received packets. But this (non-default, risky) case is easy to spot in the code. In contrast, code that creates a packet from scratch should use the safe default constructor, preferably via `construct_at`.

**Comment by nfeske** [comment]
The strict warnings are enabled by default in master now.
