### ISSUE TITLE
sculpt: integrating new FEC NIC driver fails due to missing ROM route

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4652]
When trying to integrate the newly ported i.MX FEC NIC driver into Sculpt OS on i.MX 8Q EVK and MNT Reform2, I've encoutered the following problem:
The new driver is generic and fits to i.MX 5/6/7/8, as well as different boards. For each board a different DTB blob file exists, e.g., fec_nic_drv-imx8q_evk.dtb and fec_nic_drv-mnt_reform2.dtb. The generic driver asks for a generic DTB ROM name, but a route to the concrete board DTB file has to be provided.
In current sculpt OS the sculpt_manager starts the NIC driver component, and creates its routing information. Replacing the sculpt_manager is no easy option, because its package can't be shadowed. Therefore,  to me the only good option right now is to add a route to the generic DTB ROM name inside the sculpt_manager's NIC driver configuration generation.
To re-label the generic DTB ROM to the concrete board's DTB ROM some kind of aliasing or binary copying in the modular Sculpt approach would be fine. Unfortunately, I do not see a hook like this currently. Therefore, I would add another ROM routing, like the one to the concrete NIC driver binary name inside the generic sculpt.run script.

**Comment by nfeske** [comment]
Fixed in master.
