### ISSUE TITLE
platform_drv: add leave_operational attribute to device node

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4654]
To enable the flexibility to leave a device operational after it got released, add an additional attribute to the "device" node parsed by the platform driver. The use-case is when device drivers only need to initialize a device, and release it afterwards. The need for this came when implementing the PCI host bridge driver for i.MX 8Q. The PCI host driver gets the device resources from the imx8mq_platform_drv, which implicitely powers the bridge, sets clocks etc.. The PCI driver initializes the bridge and scans the PCI bus. In the end, it generates a PCI devices report consumed by the platform driver itself, which then can export these PCI devices. But the PCI config space of these devices for instance is a sub-set of the I/O memory window formerly given to the PCI host driver. A double opening of the resp. I/O memory leads to an error. On the other hand the PCI host bridge driver is done, and can release its resources, but then the PCI bridge get implicitely powered off again.
I think this pattern, although rare right now, can apply more often in the future: that a driver is meaningful for the initialization of a device only. Therefore, keeping a device alive is a good opportunity.

**Comment by nfeske** [comment]
Fixed in master.
