### ISSUE TITLE
sculpt: relax NIC drivers policy label rule of nic_router configuration

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4660]
The uplink part of the Genode C API uses a device name as label part when asking for an Uplink session. THis somehow collides with the strict way of the sculpt_manager to generate a policy label for network drivers inside the nic_router configuration. To support a wider range of NIC drivers, it would be beneficial to relax the policy to a label prefix.

**Comment by nfeske** [comment]
Merged to staging.

**Comment by nfeske** [comment]
Fixed in master.
