### ISSUE TITLE
base_hw & core: Software TLB with static size

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#467]
Currently one must donate extra memory on demand to page tables. The goal is a page table that receives a static amount of buffer memory on construction and displaces older mappings on demand. This is a Software TLB, while the according class shall be called ``Tlb`` because it abstracts also from the hardware TLB.

But displaceable mappings are not suitable for core. Kernel can not be a pager for core because it also uses the virtual core space. Thus the class ``Core_tlb : public Tlb`` from issue [466](https://github.com/genodelabs/genode/issues/466) shall ensure that no displacement occurs in the core software TLB.

**Comment by skalk** [comment]
From my point of view commit d1add405bb60d6d343af7ce7a33973d4cbc83b93 targets the intention of this issue. @m-stein do you agree, can we close this issue?

**Comment by m-stein** [comment]
Yes, of course. But we should keep in mind to try other replacement strategies in my opinion.

**Comment by skalk** [comment]
yes definitely, the current approach has no future performance-wise, but is functional correct and builds the ground for a more sophisticated replacement strategy.
