### ISSUE TITLE
virtualbox6: tsc calibration

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4672]
When testing VirtualBox6 on Tigerlake I experienced a warning storm of

`Warning: preemption during measurement, uTsc=15395455261 uTsc_again=15395769153 uVirtNanoTS=7331468113`

that would not stop and occasionally lead to stalling the bootup of a guest VM completely. Some investigation showed that vbox6 was stuck in ` Sup::update_gim_system_time`'s TSC calibration loop because the code assumed the measurement was preempted by another Genode component and the value of MAX_MEASUREMENT_DURATION  (200) was always exceeded. Depending on the TSC frequency 200 ticks might be very little on machines with a high TSC rate (> 3GHz). Therefore, I propose that we convert the MAX_MEASUREMENT_DURATION  to a time (in nanoseconds) not a tick based variable and  calculate `max_ticks` (which we'll use for the check) using MAX_MEASUREMENT_DURATION and the actual TSC frequency. This way, we would become TSC frequency independent.

**Comment by ssumpf** [comment]
dd51a53 implements the idea above, please consider for staging.

**Comment by nfeske** [comment]
That's a very welcome improvement. Thank you!
