### ISSUE TITLE
sculpt_manager: fix router label lookup

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#4695]
The commit "sculpt_manager: relax nic_drv policy label" introduced the use of
    the "label_prefix" attribute instead of "label" for the uplink policy in the
    NIC router. However, it missed an appropriate adaption of the lookup of that
    attribute when the Sculpt manager has to decide which uplink is used in a
    manually managed router config. This causes the uplink to disappear whenever a
    user creates a manually managed router config.

**Comment by m-stein** [comment]
@nfeske This should fix the issue:
b89d764ab8 sculpt_manager: fix router label lookup

**Comment by nfeske** [comment]
Related to #4660.

Thanks @m-stein for uncovering and fixing this regression. I merged your commit to staging.
