### ISSUE TITLE
legacy/lx_emul/usb: handle saturated submit queue

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4701]

**Comment by cnuke** [comment]
Commit [53a040f](https://github.com/cnuke/genode/commit/53a040f73482f1e58a17ad3ee832a8d5ea1af8ef) addresses the issue.

**Comment by cnuke** [comment]
@chelmuth please see commit [abf72e3](https://github.com/cnuke/genode/commit/abf72e38f00960f8a9df502f392fb5d7653a7646) - due to our discussion it now uses `schedule_timeout` for the control-message case.

**Comment by chelmuth** [comment]
Removed *fixed* because of comment about memory leak.

**Comment by cnuke** [comment]
Commit [8aa64c1](https://github.com/cnuke/genode/commit/8aa64c19fc7b91c90f1a15cc68145b4978707a36) addresses the apparent memory leak in the timeout case.

**Comment by chelmuth** [comment]
@cnuke You added and later removed the fixed label. What is the current state of the fix?

**Comment by cnuke** [comment]
@chelmuth my bad, the removal was accidental.
