### ISSUE TITLE
gpt_write: use GPE LBA from header

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4720]

**Comment by cnuke** [comment]
Commit [4c20e0e](https://github.com/cnuke/genode/commit/4c20e0ea03dbefd89922a8ba25b20d47c3d2609e) fixes the issue. The problem was apparently first encountered by running Sculpt on the PinePhone as there the GPT entries are located at LBA 2048.

@nfeske that should fix the observed behaviour.

**Comment by nfeske** [comment]
Thanks a lot @cnuke! Merged to staging.
