### ISSUE TITLE
nic_router: fix updating UDP/TCP links

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#4728]
There is a bug in the updating of UDP/TCP links on reconfiguration that was introduced by this earlier commit:

0f6714c6d7 nic_router: find forward rules w/o exceptions

The NIC router falsely dissolves TCP/UDP connection states while re-configuring although the connection states are still legal according to the new config. The reason is that the above mention commit introduced nested lambdas but missed to return from the top-most nesting level when having found a configuration that legitimates the connection state.

**Comment by m-stein** [comment]
Fixed:
a7b1f7b639 nic_router: simplify updating of TCP/UDP links
223e8a810f nic_router: fix updating UDP/TCP links

**Comment by chelmuth** [comment]
Merged fixes to staging.

**Comment by m-stein** [comment]
@chelmuth After careful re-thinking of the matter I had to add a fixup commit:
9cf4c20370 Squash "nic_router: simplify updating of TCP/UDP links"

**Comment by m-stein** [comment]
Again without hashes:
df7b4e4109 Squash "nic_router: simplify updating of TCP/UDP links"
