### ISSUE TITLE
sculpt: mechanism for integrating multiple deploy presets into the boot image

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#4731]
The mobile version of Sculpt OS will offer an easy way to switch between different deploy configurations that come as presets with the boot image. To implement this mechanism, the sculpt.run script must be extended with the notion of presets.

* The .sculpt files at `<repo>/sculpt/` must support a new "presets:" tag accepting a list of deploy configs.
* The presets must be included in the XML syntax checking.
* The pkg information of presets must be processed in the same way as the deploy and launcher configs today, supplementing pkg version information, and aggregating the referenced pkgs for assembling the depot.tar archive.
* On target, the presets must be integrated in the config file system at /config/presets/.
* At runtime, the sculpt manager needs to query the presets similar to how launchers are queried today.

With this infrastructure in place, the only missing piece is a convenient user interface. I'm going to implement this first for the mobile version.

**Comment by chelmuth** [comment]
Merged to master.
