### ISSUE TITLE
qt5: make physical screen size info configurable

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4733]
Currently, `QScreen::physicalSize()` calculates the screen size based on the resolution and a fixed value of 100 dpi. To get the Morph browser to detect a small screen on the PinePhone and add "like Android 9" to the User-Agent string as mobile device indicator for web servers, it should be possible to get the real size, for example by basing the calculation on Qt's "logical dpi" value which can be overridden with the `QT_FONT_DPI` environment variable in the Morph browser init configuration.

**Comment by cproc** [comment]
Fixed by 8010225 (depends on #4732).

**Comment by nfeske** [comment]
Merged to staging.
