### ISSUE TITLE
hw: prepare ARMv8 EL2 mode appropriatedly to run Rockchip 3588

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4759]
@mickenx has enabled a first version of Genode's hw kernel running on RK3588. Therefore, it was necessary to zero out HCR and CPTR of EL2. He has done this within the initial assembler code that is run more or less unconditionally. In the generic codebase we cannot do so, because we do not necessarily start in EL2 mode. I wonder whether it is enough to zero these two registers within bootstrap's high-level code in Platform::enable_mmu() at the right place.

**Comment by skalk** [comment]
@mickenx I've prepared commit 9c6b97e that shall also solve your initial bootstrap problems without replacing our crt0.so. I would be happy, if you could try it on your hardware target. In case it works, I would push it upstream. I did not zeroed the general-purpose and FPU registers. AFAIK there is no need in calling conventions to hand over zeroed registers, did you really need that to proceed?

**Comment by skalk** [comment]
@mickenx I had to re-merge the commit to Genode's master branch, the staging one had problems, the new commit id is 0e6f390.

**Comment by mickenx** [comment]
I will not be able to test this right away because of health issues. But will do in a week or so.

**Comment by skalk** [comment]
@mickenx please take the time you need. There is no need to hurry up. Get well soon!

**Comment by mickenx** [comment]
It works! Thanks.

**Comment by skalk** [comment]
@mickenx thanks for testing.

**Comment by chelmuth** [comment]
Merged to master.
