### ISSUE TITLE
dde_linux: work structs that depend on each other may deadlock

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4762]
In test cases we could trigger sporadic deadlocks when one work blocks, schedules another work to the same work queue, and waits for completion of the later work.

**Comment by ssumpf** [comment]
Commit 723790f addresses the issue.

**Comment by chelmuth** [comment]
@ssumpf in an offline discussion @cnuke expressed his opinion that the change in this commit may be a temporary fix for a symptom and the original cause is related to something called "recycle task/work". Could you please shed some light on this and (if appropriate) open a distinct issue to address the original issue?

**Comment by ssumpf** [comment]
@chelmuth: The rescue (not recycle) task is programmed via a timeout when a work is scheduled. In case a work does not finish within the timeout, the rescue task will execute the next work from the queue. The rescue task might, therefore, fix this issue as well. But because timing is not reliable right now, I cannot decide this. It might still be a UP vs. MP problem. We will have to review this when timing works better. In the meantime the fix works well, because there will always be three tasks per work queue present, so in case two works depend on each other, the third can possibly resolve their suffering.

**Comment by ssumpf** [comment]
@chelmuth: Btw, the commit message says more or less the same as the above.
