### ISSUE TITLE
ABI symbols: mirror changes required for Goa

### ISSUE THREAD

**Issue by trimpim** [genodelabs/genode#4764]
Changes the tooling to handle ABI symbols so that an integration in to Goa can use the
same core files.

**Comment by nfeske** [comment]
This issue is related to https://github.com/nfeske/goa/pull/27.

Before considering the change for Genode, we should first try to use the existing version of the `abi_symbols` and `check_abi` tools in Goa.

**Comment by jschlatow** [comment]
@trimpim, @nfeske I just pushed genodelabs/goa@e0d9f94, which adapts the abi tools used in Goa to the versions from the Genode repo. I'm therefore closing this issue.
