### ISSUE TITLE
lx_emul: adjust and unify time handling

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4778]
Time handling still isn't always done appropriatedly in the Linux device driver environment. The jiffies value sometimes is outdated too long. Every driver implements its own fashion of udelay, which isn't semantically correct  either.

**Comment by ssumpf** [comment]
@skalk: This looks really promising. Good job!

**Comment by chelmuth** [comment]
Current build/link errors in *app/wireguard* stem from commit 65e1948b98f816ddb16ea434e7e758695264cf8c and the following code in contrib linux.

```c
static __must_check inline bool may_use_simd(void)
{
	return !in_interrupt();
}
```

**Comment by skalk** [comment]
Okay, that means the former semantic of `in_interrupt` returned true, although this was wrong. Now, it tries to use optimized SIMD instructions. We should simply add them.

**Comment by chelmuth** [comment]
Merged to master.
