### ISSUE TITLE
Remove util/avl_string.h

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#4780]
With the `Dictionary` introduced in #4610 in place, the old `Avl_string` utility should be retired.

**Comment by nfeske** [comment]
The commits above eliminates the use of `Avl_string` from the code base except for one remaining little VFS plugin, namely `vfs_trace`.

I tried and failed two times attempting to wrap my head around the code at https://github.com/genodelabs/genode/blob/master/repos/gems/src/lib/vfs/trace/directory_tree.h on my mission to decouple it from `Avl_string`. Both times I got lost in a forest of trees.

@ssumpf, could you please do the update of the code to the use of the Dictionary utility?

**Comment by ssumpf** [comment]
@nfeske: 84bb68f is my take on a library full of dictionaries.

**Comment by nfeske** [comment]
Thanks @ssumpf for updating the code so quickly.
