### ISSUE TITLE
part_block: split reporting from parsing

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4786]

**Comment by cnuke** [comment]
Commit [73c53c0](https://github.com/cnuke/genode/commit/73c53c0249773aa6ca5168d3cce879afa52b985a) seperates parsing from reporting.

**Comment by nfeske** [comment]
Thanks a lot @cnuke for much appreciated rework.

As a minor further improvement, may you consider replacing the `generate_report` interface from

```
virtual void generate_report(Expanding_reporter &reporter)
```

to

```
virtual void generate_report(Xml_generator &xml) const
```
?

The `const` reinforces that the report-generation has indeed no side effects, and the use of the `Xml_generator` exposes only as much as actually needed.

**Comment by cnuke** [comment]
No problem, the fixup commit [9603424](https://github.com/cnuke/genode/commit/960342498d53b555126683550ca2281bd13f861f) makes the *const* change.

**Comment by nfeske** [comment]
Thanks.

Do you have reservations about the suggested change of the argument type?

**Comment by cnuke** [comment]
@nfeske sorry, my bad - I overlooked changing the argument. I prepared commit  [7805c57](https://github.com/cnuke/genode/commit/7805c57b296b01f7d69ff486565fc6784f3a3f2c) that includes both suggestions.

**Comment by cnuke** [comment]
Commit [8fcee8f](https://github.com/cnuke/genode/commit/8fcee8ffb40bf81e241f136d6f2b422be42d2eb4) contains fixups for the various remarkes.
