### ISSUE TITLE
Split Qt5 api recipe into smaller parts

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4793]
When linking against the Qt5 API, Goa uses all ABIs found within the API, leading to the case that a simple hello world Qt5 program requires the Webengine and more at runtime. Therefore I propose two split the API into `qt5` - base libraries, `qt5_qml` - anything QML/Quick related, and `qt5_webengine` which would make it possible to link more fine grained against an API.

**Comment by cproc** [comment]
Another variant could be to split and name everything according to the corresponding Qt modules. This would (more or less) involve:

- qt5_base
- qt5_declarative
- qt5_graphicaleffects
- qt5_quickcontrols
- qt5_quickcontrols2
- qt5_svg
- qt5_virtualkeyboard
- qt5_webchannel
- qt5_webengine

I guess both variants have some advantages and disadvantages with regard to ease of use and consistency with the official Qt module structure.
