### ISSUE TITLE
base: linking of dynamic list

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4794]
Genode links dynamic binaries using the:

`--dynamic-list=<genode>/repos/base/src/ld/genode_dyn.dl`

option. This is done so that possible unreferenced symbols like `main`, `Component::construct`, or `_ctors_start` are not garbage collected during linking. This option was removed from Goa lately, leading to the garbage collection of `main`. If we could make sure that for any dynamic binary all symbols in `genode_dyn.dl` are referenced (either through a library or a symbol file) we could remove this option.

**Comment by ssumpf** [comment]
@chelmuth: I have added a comment to [018bd4f](https://github.com/ssumpf/genode/commit/018bd4f82f66f1e0e02fec3e63347a528e068ce0) on my pinephone branch. Otherwise and from my point of view, we can close this issue because the dynamic list does not cause symbols to be kept, but is used to make symbols global (.dynsym) so that they can be found by our dynamic linker.

**Comment by chelmuth** [comment]
@ssumpf please have a look into last night's package builds. These failed with the following error.

```
/usr/local/genode/tool/21.05/bin/../lib/gcc/x86_64-pc-elf/10.3.0/../../../../x86_64-pc-elf/bin/ld: /data/depot/checker/bin/x86_64/test-qpluginwidget/2023-04-11.build/test/qt5/qpluginwidget/qmake_root/lib/qt5_component.lib.so: undefined reference to `main'
collect2: error: ld returned 1 exit status
```

**Comment by ssumpf** [comment]
@chelmuth: This is related to issue https://github.com/genodelabs/genode/issues/4793. I will add a commit there.

**Comment by ssumpf** [comment]
@chelmuth: And 2nd the `qtpluginwidget` test does not have a `main` function, but implements `Libc::Component::construct` directly (See: https://github.com/genodelabs/genode/blob/master/repos/libports/src/test/qt5/qpluginwidget/main.cpp). The `qt5_component` library is there to implement `Libc::Component::construct` and call `main`. So it's a wrong dependency.
