### ISSUE TITLE
how to use sculpt OS image with qemu on Windows 10?

### ISSUE THREAD

**Issue by yf13** [genodelabs/genode#4797]
Dear experts,

I followed [this page](https://genode.org/download/sculpt) and tried to run the downloaded sculpt-22-10.img with qemu-system-x86_64 on Windows. There was a QEMU window showed out, but the content is black after the Genode logo disappeared.

Is there any possibility to use QEMU on windows with the downloaded image?

Regards,
yf13

**Comment by nfeske** [comment]
This issue remained unattended for more than a month. I'm afraid that none of Genode's developers who monitor the issue tracker is in the position to help out.

Maybe the mailing list (https://genode.org/community/mailing-lists) - which is monitored by a broader community - could be considered for consultation?
