### ISSUE TITLE
dde_rump: Add RISC-V support

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4800]
As recently asked on the mailing list, RISC-V support for rump should not be too hard to enable.

**Comment by ssumpf** [comment]
471227c adds RISC-V support to our rump port through the same backport as provided by ARMv8.

**Comment by chelmuth** [comment]
@ssumpf  `./tool/depot/create genodelabs/bin/riscv/rump FORCE=1 UPDATE_VERSIONS=1 REBUILD=` fails like follows.

```
fatal error: machine/cdefs.h: No such file or directory
```

**Comment by ssumpf** [comment]
@chelmuth: 2dbf332 fixes the src archive for RISC-V

**Comment by chelmuth** [comment]
That was quick. Thanks!
