### ISSUE TITLE
Principle support for wifi on ARM platforms

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#4813]
Currently, wireless networking is supported only on PC platforms using PCI wireless cards, i.e. Intel iwl. In order to enable Wifi on ARM platforms like the PinePhone, the DDE-Linux-based driver code must be decoupled/generalized from PC hardware.

**Comment by nfeske** [comment]
@cnuke I've merged your commit series to staging, and tagged the commits with this issue to clarify the context of the changes.

**Comment by nfeske** [comment]
Related to genodelabs/genode-allwinner#17.

**Comment by skalk** [comment]
Commit c0c741e7d2a2fb3d7fc23982f563c4e1af26e3b2 is also needed when building the wifi driver for the MNT Reform 2.
