### ISSUE TITLE
Add a function that allows iterating over an XML node's attributes

### ISSUE THREAD

**Issue by Time0o** [genodelabs/genode#4817]
At Gapfruit we have noticed that there seems to be no way to iterate over the attributes of an `Xml_node` object that does not rely on exception handling. In the current state, we are either forced to know all the possible attribute types beforehand or we have one exception for each xml node when using `Xml_attribute::next()`. We'd rather not require exceptions for control flow. Since we need this functionality in several places and think it would be useful for others as well, we'd like to propose an additional `for_each_attribute` function implemented as in 278cf2c2c12e5b2313c42eb30c5c6310e01b6810. Is this approach reasonable?

**Comment by nfeske** [comment]
Fixed in master.
