### ISSUE TITLE
vfs_block: syncing blocks failed

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#4825]
The above message is logged by the VFS `<block/>` plugin the `Block::Session::sync_all_packet_descriptor()` does not succeed. In Sculpt, this can easily experienced when checking or expanding the GENODE partition on a USB stick. The behavior is not new - tested a Sculpt 21.10 stick.

From my analysis, the reason behind this is the *usb_block_drv* that responds to all non-payload requests with `Response::REJECTED` in https://github.com/genodelabs/genode/blob/d8ff3f655a1466f8545dcdc1087cf298d7ae442d/repos/os/src/drivers/usb_block/main.cc#L1010-L1016

In my opinion, `SYNC` requests should be implemented as done in all file-system layers above: Only answer SYNC after all earlier operations finished and before later operations are started.

@cnuke can this easily be done because of the sequential nature of the driver?

**Comment by cnuke** [comment]
@chelmuth commit [c6ce405](https://github.com/cnuke/genode/commit/c6ce4056611142050c1fb733b38cdcb991d7b692) implements the requested behaviour.
