### ISSUE TITLE
nvme_drv: read proper FLBAS value

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4832]

**Comment by cnuke** [comment]
Commit [4109b04](https://github.com/cnuke/genode/commit/4109b0490161a949eaf3ed4c984b165f807b8e82) address the issue.

@atopia could you please provide feedback whether the commit fixes the problem as you appear to be the only with the proper hardware at hand.

**Comment by atopia** [comment]
Yes, that fixes the issue for me.
