### ISSUE TITLE
libusb: remove dependency from obsolete libc-plugin interface

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#4854]
As of now, https://github.com/genodelabs/genode/blob/master/repos/libports/src/lib/libusb/genode_usb_raw.cc#L757 relies on the obsoleted plugin interface of the libc to get hold of the `Genode::Env`.

This hook should be replaced by a pseudo VFS plugin.

**Comment by cproc** [comment]
Fixed by a908be4 (tested with Sculpt usb_webcam/test_capture scenario)
