### ISSUE TITLE
dde_bsd: OpenBSD 7.1 no longer available for download

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#4857]
The official server (https://cdn.openbsd.org/pub/OpenBSD/7.1/sys.tar.gz) no longer provides OpenBSD 7.1 for download. As long as some mirrors still provide the archive (e.g., https://ftp.fau.de/pub/OpenBSD/7.1/sys.tar.gz), we could just change the URL. The other option is an update to 7.2 or 7.3.

@cnuke what's your stance?

**Comment by cnuke** [comment]
@chelmuth I would squeeze in updating the driver as the diff is small and the update brings in support (mostly adding PCI IDs) for newer platforms.

**Comment by cnuke** [comment]
Commit [a61fdf7](https://github.com/cnuke/genode/commit/a61fdf72c169f61e275ccb8f503efd002d0ac370) updates the driver to version 7.3 (and thereby fixes this issue).

I have briefly tested (`audio_out.run` and `audio_in.run`) the new version on the X201, Fuji4 and Fuji6 where it worked as advertised.

**Comment by chelmuth** [comment]
> I have briefly tested (`audio_out.run` and `audio_in.run`) the new version on the X201, Fuji4 and Fuji6 where it worked as advertised.

Thanks. Audio-In on U7412 worked?

**Comment by cnuke** [comment]
@chelmuth no, the recording is still unsupported. Sorry for not being explicit about that.

**Comment by chelmuth** [comment]
Nevermind, that's what I expected anyway ;-)
