### ISSUE TITLE
Remove stale Xen support

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#4859]
Today I stumbled upon a long forgotten historic artifact: https://github.com/genodelabs/genode/blob/master/tool/run/power_on/xen

Since the Xen support is not stressed by any tests or known users, we should consider to remove it.

@cproc what do you think? When removing it, the source tree should be grep'ed for "xen" to remove all traces. The `xen_args` in run/log.run script comes in mind.

**Comment by cproc** [comment]
Fixed by 0694b89.
