### ISSUE TITLE
depot/downloader: let curl fail on 404 response

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4865]

**Comment by cnuke** [comment]
Commit [1597add](https://github.com/cnuke/genode/commit/1597addade35a0214ce09e4404392eab7b2448e9) addresses the encountered issue but I am not 100% sure if it break legitimate use-cases.

**Comment by chelmuth** [comment]
This looks like another occurrence of unexpected `pipefail`.

**Comment by nfeske** [comment]
Fixed in master.
