### ISSUE TITLE
qt5: reduce external dependencies of host tools

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4868]
Disable the use of some host libraries or use an internal version to improve the compatibility with different host systems for a binary release.

**Comment by chelmuth** [comment]
@cproc what do you think about merging */usr/local/genode/qt5/$(TOOL_VERSION)* into */usr/local/genode/tool/$(TOOL_CHAIN_VERSION)* for the binary release?

**Comment by cproc** [comment]
> @cproc what do you think about merging _/usr/local/genode/qt5/$(TOOL_VERSION)_ into _/usr/local/genode/tool/$(TOOL_CHAIN_VERSION)_ for the binary release?

Commit fdf8ae0 changes the install location.
