### ISSUE TITLE
ADA runtime update for GCC 12

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#4880]
The build of *lib.spark* and the *test-spark*" components fails with GCC 12. Issue #4827 states an update of the ADA runtime in *repos/libports/ports/ada-runtime.port* is required.

**Comment by cnuke** [comment]
Commit [a78339d](https://github.com/cnuke/genode/commit/a78339d59ffe5d5db0c38703db5c6d16e71c7e4f) address the compiler warning turned into an error and commit [bf0d1ef](https://github.com/cnuke/genode/commit/bf0d1efd501242b6b65af7a9f25deea33d3bdaac) update the _.ali_ files. With that changes `test-spark`, `test-spark_exception` and `test-spark_secondary_stack` (via _depot_autopilot.run_) work again.

I did not update the runtime itself, it is still the original version imported from GCC 8.3 and I am hesitant to do that if it is not really required. I noticed the discussion in [Componolit/ada-runtime/issues/86 ](https://github.com/Componolit/ada-runtime/issues/86) and judging by a brief looking at the current GNAT sources updating would indeed involve some integration work.

**Comment by chelmuth** [comment]
That's fantastic - I like your pragmatic approach! It works like a charm in the *test-spark** scenarios.
