### ISSUE TITLE
Ensure usage of the genode tool chain in all places

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#490]
We discovered one place, where the third-party build system does not adhere to the configured tool chain, but there may be more. The current problem is in:
 `base-fiasco/contrib/fiasco/snapshot/l4/pkg/bootstrap/server/src/Makefile:215` resp.
 `base-foc/contrib/l4/pkg/bootstrap/server/src/Make.rules:376`.

**Comment by nfeske** [comment]
How should we go about this issue?

**Comment by chelmuth** [comment]
The issue itself (in its described scope) has the problem of generality as we'd need a mechanism that *ensures* only our custom tool chain is used. Maybe it should just be closed?

**Comment by nfeske** [comment]
There does not seem to exist a tangible plan to address this issue. Once we adopt the Nix-based package management, it will be implicitly resolved. Even though this will not happen over night, I don't think that we will work on a solution for cross compiling on Linux in the meanwhile. Hence, I'm closing this issue.
