### ISSUE TITLE
mesa: remove run scripts that use GPU hardware

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4900]
Run scripts that use iris or etnaviv Gallium drivers are broken (because they need GPU device access) and cannot be repaired. Therefore, I would suggest to remove them and use modular Sculpt instead (https://github.com/genodelabs/genode/commit/b723b11b30bee0ef80ddc24523b2696489971839).

**Comment by ssumpf** [comment]
@cnuke: I hope you approve.

**Comment by cnuke** [comment]
> @cnuke: I hope you approve.

Most definitely :smile:.

**Comment by nfeske** [comment]
Fixed in master.
