### ISSUE TITLE
genode_c_api: build errors with -std=gnu++20

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4901]
enum problems in uplink.cc

**Comment by ssumpf** [comment]
Fixed by [1a934af](https://github.com/ssumpf/genode/commit/1a934af27e33092bc5306e5d0002068296ba6064)

**Comment by chelmuth** [comment]
Already addressed in b6351224ce5ce728af7c9e93472b4a2a54218419, or not?

**Comment by ssumpf** [comment]
> Already addressed in [b635122](https://github.com/genodelabs/genode/commit/b6351224ce5ce728af7c9e93472b4a2a54218419), or not?

Yes, overlooked it. Just tested Sculpt with staging and fixed everything in the way. So, I will close the issue.
