### ISSUE TITLE
sel4: convert io memory on demand

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#4913]
During boot-up core converts all untyped I/O memory eagerly. On x86 and qemu this takes quite a long time for memory never used. On demand conversion should avoid the overhead.

**Comment by chelmuth** [comment]
I merged the commits to staging. Could the issue be marked fixed?

**Comment by alex-ab** [comment]
> I merged the commits to staging. Could the issue be marked fixed?

Yes, marked it.

**Comment by nfeske** [comment]
The change in https://github.com/genodelabs/genode/commit/24cd9cfa5e1ec73a288796bb8fafd6d5795b168c looks good to me. I was slightly puzzled that the interface change of `Io_mem_session_component::_map_local` does not affect other base platforms. But then, I saw the fixup https://github.com/genodelabs/genode/commit/7986f9fafe44c199df2a24d258932ccace320043. All fine by me.
