### ISSUE TITLE
pc_nic_drv: ethernet NIC driver based on Linux 6.1

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#4921]
New NIC driver for PCs using Linux 6.1 sources with support for Intel e1000/e1000e and Qemu's pcnet32 model. The driver also addresses issue #4538 and the interplay with Intel ME/AMT-SOL.

**Comment by cnuke** [comment]
I'd like to piggy-back on this issue by adding support for the Realtek 8169 driver. Commit [391fc0c](https://github.com/cnuke/genode/commit/391fc0c55c714f211aef4e3ed63f5d41cdfe5806) and [b87b412](https://github.com/cnuke/genode/commit/b87b4123319bc7415fd43d6d784c8bfd099e7c0b) extend the _pc_linux_ config whereas [bd553c8](https://github.com/cnuke/genode/commit/bd553c81ad55b6373d284c0f5706f219273c0c1d) enables the driver.

So far I only tested a handful of 8169 and 8125B devices running at 1000Base-T which, apart from the noted remaks in the commit, performed well.
