### ISSUE TITLE
lib/net: enable strict warnings

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#4924]

**Comment by chelmuth** [comment]
@m-stein I merged commits in this issue plus

b0c673b6a10 tresor: do not use on-disc-layouted structs
65975342cd2 fixup "tresor: do not use on-disc-layouted structs" (fall asleep instead of spinning in assertion)

Please check your merge_to_staging branch as IMO the other commits are obsolete.

**Comment by chelmuth** [comment]
> Thanks for the hint! I've re-based my merge_to_staging.
> 
> Is commit [ff89007](https://github.com/genodelabs/genode/commit/ff89007771e7c631bc9436e874344622f705586f) considered valuable? Otherwise, I can remove it.

This change was already merged as e0dc544aa52ff8cc531a506398e7d6959d1c865d in a slightly modified version.

**Comment by m-stein** [comment]
@chelmuth Thanks! Good to know.

**Comment by m-stein** [comment]
@chelmuth I'm sorry for the inconvenience with the failing tests! Here is the fix-up 568c1df3c0.
