### ISSUE TITLE
sd_card.run: fix broken config

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#4925]

**Comment by m-stein** [comment]
I'd opt for either adding 5fb676de46 _and_ adding the test to autopilot or removing the test. Any opinion?

**Comment by nfeske** [comment]
Thank you for the repair.

> I'd opt for either adding https://github.com/genodelabs/genode/commit/5fb676de46b72812b62c969951144e00f0b67de1 and adding the test to autopilot or removing the test. Any opinion?

I foresee retiring our original SD-card driver(s) in favor of DDE-Linux-based drivers as already used on i.MX8, allwinner A64, and Zynq. Once we remove the old driver(s), we will retire the run script as well. It is probably not worth adding the run script for automated testing in the intermediate phase.
