### ISSUE TITLE
lx_kit: decouple scheduler execution

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4927]

**Comment by cnuke** [comment]
Commit [743b6cb](https://github.com/cnuke/genode/commit/743b6cbabb5c76342510354c103e03261482ac93) implements the change discussed during coffee-break. I tested Sculpt on the Fuji6 and PinePhone and with it in place at least the _pc_usb_host_drv_ (judging by the backtrace it appears to get stuck in `lx_emul_execute_kernel_until`) and the _goodix_touch_drv_ (at some point i2c timeout errors occur and the driver does not recover from that) do not work any longer as they presumably depend on the previous behavior.

**Comment by skalk** [comment]
@cnuke the `lx_emul_execute_kernel_until` is dependent on the previous behaviour. It won't work the way you sketched. The problem here is that work has to be done on behalf of an RPC-call resp. session close, because of the USB-session's structure. The mentioned call waits for a condition, and as long executes `wait_and_dispatch_one_io_signal`. Using the "normal" signal, the EP can never execute it, because it still handles the RPC. I don't have a solution down pat, but have to think of it.

**Comment by cnuke** [comment]
Commit [4f86caa](https://github.com/cnuke/genode/commit/4f86caa4071de772d9458d7c1926d73ffbcf1186) contains the change to `lx_emul_execute_kernel_until` that fixes the observed problem. I introduced the Scheduler::execute` member function that can be used to trigger the execution of the scheduler from well defined places, i.e. the EP context.

I have not yet adapted all places where this is the intent behind calling `Scheduler::schedule` as I am unsure if everybody is fine with my naming.

(In contrast to my faulty recollection `gpu/etnaviv` and `gpu/lima` suffer from the same problem.)

**Comment by cnuke** [comment]
Commit [d40f1a8](https://github.com/cnuke/genode/commit/d40f1a85005acd5fe64b55d8f998e4c805db37e8) fixes the problems with the touchscreen driver on the PinePhone where interrupts might get lost otherwise. As denoted by the _PoC_ tag I am working on a more reasonable version.

**Comment by chelmuth** [comment]
I must admit I'm struggling to understand entriely when a signal handler should call `schedule()` and in which cases it is safe (and required) to call `execute()`. For example, *wlan.cc* uses `schedule()` while most other places incl. *usb_host/pc/main.cc* where changed to `execute()`. Could you please enlighten me?

**Comment by cnuke** [comment]
`schedule()` must be called if triggered from a I/O signal handler, where as `execute()` must only be called if you are not in in an I/O signal handler but run in context of the EP, e.g. from an RPC-call, and the scheduler should be executed immediately. I already touched upon the naming since I am not sure it transports the intent well enough.

**Comment by chelmuth** [comment]
Okay, I think what confused me was the difference between *pc/src/drivers/nic/pc/main.cc*, which uses an `Io_signal_handler` and *usb_host/pc/main.cc*, which does not.

**Comment by cnuke** [comment]
Commit [4820a43](https://github.com/cnuke/genode/commit/4820a43292b49c66c5517575e26b7bc4ee4fe4bb) is a cleaned up version of the previous _PoC_ commit that stores the _pending interrupt_ information in the IRQ handling object itself.

**Comment by m-stein** [comment]
Commit f550108d880a45b32b51f149f26b28c4eb7ca0c5 breaks x86_64.pc.hw.nic_router_flood. I'm at it.

**Comment by m-stein** [comment]
Commit https://github.com/genodelabs/genode/commit/f550108d880a45b32b51f149f26b28c4eb7ca0c5 seems to have a significant effect on network performance on x86_64 as depicted in #4954

**Comment by cnuke** [comment]
Commit [d2f4f84](https://github.com/cnuke/genode/commit/d2f4f847fa5c4e6710caeff6f2b29f1ff7ef10b1) address the problem encountered in #4954 and touches on  #4952 slightly.

Commit [fd0ebbe](https://github.com/cnuke/genode/commit/fd0ebbe6ecb294a3b466d8529823898fc2f4e33e) and [ec215a8](https://github.com/cnuke/genode/commit/ec215a83be10baad74f4b6ced921604d432db518) are preliminary steps.

(So far I only adapt the drivers in the repositories that are part of Genode repository, the other board specific repos will follow.)

**Comment by cnuke** [comment]
Commit [239f920](https://github.com/cnuke/genode-allwinner/commit/239f9200bd549f0ead47ddd152a9084fce383c3b), [cf4d94c](https://github.com/cnuke/genode-zynq/commit/cf4d94cf5458f1d6643603937284de5a5086ddcc) and [4e8e673](https://github.com/cnuke/genode-imx/commit/4e8e673716253cf7d30fa3785709f7d9002203e2) adapt the board-specfic repositories.

**Comment by cnuke** [comment]
* allwinner: commit [08b0c3](https://github.com/cnuke/genode-allwinner/commit/08b0c3dbe5396a49beed266b7498b9c5b2f18aaa) and [ea4762e](https://github.com/cnuke/genode-allwinner/commit/ea4762e82e4b8eaba0dd4ef33eececd6b5869e48)

* imx: commit [7d1a8f4](https://github.com/cnuke/genode-imx/commit/7d1a8f476c3f968306bbf3739a0038a5e6a2bd4d) and [7a08968](https://github.com/cnuke/genode-imx/commit/7a0896872fda00e4dff1751793998cf9e28489a8)

adapt to the wifi driver changes.

**Comment by chelmuth** [comment]
I merged the whole bunch. Does Sculpt also need adaptions to the wifi changes?

**Comment by cnuke** [comment]
Thanks and sorry for the somewhat convoluted bunch of commits.

> I merged the whole bunch. Does Sculpt also need adaptions to the wifi changes?

Those changes are part of 5f1d1e6ed1a9776b018709d186b5cf38fbc9c27b, which you already merged.

**Comment by cnuke** [comment]
@chelmuth commit [8b42233](https://github.com/cnuke/genode-imx/commit/8b42233219c53b969c0766860941a536a51c3d43) addresses the `usb_host_drv` on _imx_ build errors.

**Comment by cnuke** [comment]
@chelmuth please also merge [b3be9b7](https://github.com/cnuke/genode/commit/b3be9b705309927a6ffff094675768c8d91776ab) which adapts the various run-scripts using the wifi driver.

**Comment by nfeske** [comment]
The commits entered the master branch.
