### ISSUE TITLE
pci_decode: calculate 64bit BAR size

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4949]

**Comment by cnuke** [comment]
While fooling around with an Intel A380 GPU I noticed that the aperature size is wrongly detected with as size of `0`. I tracked it down to the handling of the size of 64bit BARs. Commit [ae17316](https://github.com/cnuke/genode/commit/ae1731674e433385cc2d9c65af1eedcbc3f0603f) incorporates the upper 32 bits to calculate the full size of an 64bit BAR.

**Comment by nfeske** [comment]
Fixed in master.
