### ISSUE TITLE
tool/dts/extract: parsing issue with label declared at supplemental node

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4962]
When having a label declaration like the following inside a device tree:
```
dummy_name: &some_device {
...
};
```
even if that label isn't selected or of any interest, the extract tool produces a result like this:
```
dummy_name:
```
which is no valid device tree source, and the device tree compiler won't accept it.

**Comment by nfeske** [comment]
Can you give https://github.com/genodelabs/genode/commit/f017339445fa2d571d23beafe8424691efc99324 a try?

**Comment by skalk** [comment]
@nfeske: works like a charm, thank you very much!
