### ISSUE TITLE
tresor: support and test snapshot management

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#4971]

**Comment by m-stein** [comment]
Fixed:
7e44665d4b tresor: support and test snapshot management
c0a3823b10 tresor: fix bad hash update during rekeying in vbd
7029730738 tresor: fix <initialize> config constraints
63b6a1e864 tresor: snap garbage collection on each request
5412ad9177 tresor: no local impl. of snap garbage collection
c1169f85b6 tresor: no local copy of snapshots in vbd module
1f8e282ec5 tresor: improve verbosity modes

**Comment by m-stein** [comment]
This b8755c0e8a makes the implementation much simpler to understand.

**Comment by m-stein** [comment]
Another one ff4a0d38c8.

**Comment by chelmuth** [comment]
How does this issue (and the current *fixed* state) correlate to ongoing tresor refactoring? Should we remove the label for now?
