### ISSUE TITLE
acpica: port download fails

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4982]
http://acpica.org/sites/acpica/files/acpica-unix2-20180810.tar.gz currently redirects to an overview page.

**Comment by chelmuth** [comment]
Is https://github.com/acpica/acpica/archive/refs/tags/R08_10_18.tar.gz equivalent?

**Comment by cproc** [comment]
The archive content differs a bit (different number of files and different copyright headers in the source files), but `acpica.run` still works. Fixed by 6ead523.
