### ISSUE TITLE
Hack'n'Hike 2024

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#4989]
__The Hack'n'Hike is dead - long live the Hack'n'Hike!__

In 2020 we celebrated the 9th Hack'n'Hike - and because we don't like the fuzz around decadal birthdays, the event then went into hibernation for 3 years (or maybe it was because of a global pandemic - but wouldn't that sound quite made-up...) . However, the GOA community (https://github.com/genodelabs/goa/issues/52#issuecomment-1704770525) now have had enough with the laziness and demanded that the anniversary may be conducted once and for all.

Jokes aside, I'd like to invite everyone interested in a new Hack'n'Hike to participate in the organizational discussions in the context of this issue! We are eager for some good ideas regarding location and activities when rebooting the event.

**Comment by m-stein** [comment]
Let me throw in a first option for the target region: The Zschopau river valley near Mittweida has some nice hiking trails like the circular route "Kriebstein Talsperre" with the "Wappenfelsen Lauenhain" and back trip via boat and we could visit Castle "Kriebstein".

**Comment by m-stein** [comment]
Here's another idea: [Villa Wilsch](https://www.villa-wilisch.de/hotel.html) near the [Castle "Scharfenstein"](https://www.burg-scharfenstein.de/) also at the Zschopau river but far more to the south.

**Comment by nfeske** [comment]
@m-stein thank you for creating this issue! I have never been there but from looking at pictures about "Kriebstein" on the web, this area looks indeed very tempting. :-)

**Comment by m-stein** [comment]
The date and location for the Hack'n'Hike 2024 are now set!

## When?
__Start:__ 3 pm Friday 3rd May 2024
__End:__ 11 am Monday 6th May 2024

## Where?
__Villa Wilisch__, An der Schlösselmühle 1, 09439 Amtsberg
- [Homepage](https://www.villa-wilisch.de/index.html)
- [Google Maps](https://maps.app.goo.gl/AG2NmEx6EHdQhK2Y7)

## What is provided?
* Lodging with Bath, Bedding and Towels
* Exclusive seminar room with LAN, WLAN, Internet
* Catering for breakfast and dinner (__please tell us in advance if you have special requirements!__)
* Parking place

## How to register?
* The event is at no cost, lunch not included.
* We want to give participants from diverse backgrounds a chance to attend. Due to the limited capacity of the venue, please limit the number of attendees of your organization to a maximum of two.
* Please register via mail to [hacknhike@genode-labs.com](mailto:hacknhike@genode-labs.com) __till end of February 2024__.

If you have further questions regarding the event, please don't hesitate to ask in this issue or via mail to [hacknhike@genode-labs.com](mailto:hacknhike@genode-labs.com) !

**Comment by m-stein** [comment]
For those of us that don't own a private helicopter, I have made a list of some of the public transport connections that go from Dresden Main Station to the Villa Wilisch (be aware that each comes with a more or less short walk):

...

Departure at 13:08  Pl. 9  with RB 74060, arrival at 15:25 **with 249 m Walk**
View journey: https://int.bahn.de/en/buchung/start?vbid=889a900f-fdb4-4f20-b6eb-86af16f7dec3

Departure at 13:52  Pl. 10  with RE 74020, arrival at 15:34 **with 1,5 km Walk**
View journey: https://int.bahn.de/en/buchung/start?vbid=6eea44f2-d570-46be-8d75-3b156f7dfdcc

Departure at 13:52  Pl. 10  with RE 74020, arrival at 16:32 **with 249 m Walk**
View journey: https://int.bahn.de/en/buchung/start?vbid=263fadc6-389e-4097-aced-5c919cb70ba1

Departure at 14:08  Pl. 7  with RB 74062, arrival at 16:32 **with 249 m Walk**
View journey: https://int.bahn.de/en/buchung/start?vbid=0b7e74f7-90aa-435d-bc31-e7199fcd2e97

Departure at 14:52  Pl. 10  with RE 74022, arrival at 16:33 **with 1,5 km Walk**
View journey: https://int.bahn.de/en/buchung/start?vbid=f5e263d2-4ace-4b9a-a740-82a7336a6cd0

Departure at 14:52  Pl. 10  with RE 74022, arrival at 17:29 **with 249 m Walk**
View journey: https://int.bahn.de/en/buchung/start?vbid=21dc756e-7783-4af6-9dd0-25f95cf21d6e

...

**Comment by chelmuth** [comment]
I truly enjoyed hacking and hiking with all of you. See you next time :smile:

**Comment by mewmew** [comment]
It was an absolutely incredible event! So happy to meet all of you again <3

*happy hugs*
Robin & Daniel

P.S. here are some photos from the Hack n' Hike. (If anyone prefers to not have their photo online, just let me know and I'll take it down)

![2024-05-03 - 18 18 42, Hack n Hike  daniel](https://github.com/genodelabs/genode/assets/1414531/28987001-224c-442f-8337-83d99bb21c9d)
![2024-05-03 - 18 18 54, Hack n Hike  robin](https://github.com/genodelabs/genode/assets/1414531/36eb34a9-7b0c-44f6-be7f-6fc3568c73b2)
![2024-05-04 - 12 28 47, Hack n Hike](https://github.com/genodelabs/genode/assets/1414531/3f002e54-e29e-44ba-b09d-d2cffb4ae3d9)
![2024-05-04 - 18 00 15, Hack n Hike](https://github.com/genodelabs/genode/assets/1414531/d3598fcb-5ca8-4f23-91ae-2dd2725f86e9)
![2024-05-04 - 21 14 03, Hack n Hike](https://github.com/genodelabs/genode/assets/1414531/f46d617f-6a83-426b-8e7d-acd6520be6a8)
![2024-05-05 - 23 37 07, Hack n Hike](https://github.com/genodelabs/genode/assets/1414531/08e6ea2f-8f0c-4ea9-9416-007fdec46b1d)
![2024-05-06 - 00 38 17, Hack n Hike](https://github.com/genodelabs/genode/assets/1414531/975fddd1-d43f-49b9-8a68-d06948e68ad1)
![2024-05-05 - 12 39 45, lion king, Germany  robin](https://github.com/genodelabs/genode/assets/1414531/d5008438-a5e3-41e5-8d18-e5cf35b24992)
