### ISSUE TITLE
Problems with USB audio passthru in VBox6

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4990]
Using a USB audio device from within VBox6 exhibits unexpected behaviour:

* The load on one EMT thread (normally the last one) increases substantially
* The audio quality is bad as interruptions in playback occurs regularly

This does not happen with VBox5.

**Comment by nfeske** [comment]
@cnuke I wonder, is this issue obsolete by now?

**Comment by cnuke** [comment]
@nfeske indeed it is as the problem should be addressed by now - I'll close the issue.
