### ISSUE TITLE
add missing libc support for ripgrep

### ISSUE THREAD

**Issue by atopia** [genodelabs/genode#4997]
The `ripgrep` command line program calls or links to a couple of functions via the `libc` crate that so far have not been provided by our C library.

To enable basic support for ripgrep:

- Implement FreeBSD11 ABI versions of `lstat` and `readdir_r` and provide them as versioned symbols in our `compat_libc`
- Provide dummy implementations of the following functions:
  - `pthread_set_name_np()`
  - `posix_spawn_file_actions_addchdir_np()`
  - `cpuset_getaffinity()`
- Implement support for FreeBSD's `KERN_ARND` sysctl interface

**Comment by atopia** [comment]
Cleaned up and rebased on current staging. @chelmuth please have a look and give it a spin.

**Comment by chelmuth** [comment]
Merged to staging.

**Comment by atopia** [comment]
@chelmuth please pick the attribution fixups.

**Comment by chelmuth** [comment]
Merged the fixups to staging.

**Comment by chelmuth** [comment]
Fixed in master.
