### ISSUE TITLE
tool: add -no-kvm automagically when tool/run is executed

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#500]
At the moment `-no-kvm` is added to _etc/build.conf_ when the build directory is created. This option however is only available in Qemu binaries having KVM support. Qemu binaries w/o KVM will exit with `-no-kvm: invalid option`.
Therefore it should only be added if there the KVM support is actually enabled in the Qemu binary.

**Comment by nfeske** [comment]
I propose to close this issue since it does not seem to trouble too many people. At least, we don't get many questions about the topic on the mailing list. In my opinion, the QEMU_OPT variable is easy enough to configure, so that any kind of magic won't improve the situation much. What do you think?

**Comment by cnuke** [comment]
:+1:

**Comment by mewmew** [comment]
> I propose to close this issue since it does not seem to trouble too many people. At least, we don't get many questions about the topic on the mailing list.

I know this is an old issue, so consider this a data point from an Arch Linux user.

Following the Foundations "Getting started" instructions using the official [Qemu package](https://github.com/archlinux/svntogit-packages/blob/packages/qemu/trunk/PKGBUILD) of Arch Linux runs into the issue of the `-no-kvm` command line flag being absent from the `qemu-system-x86_64` command.

> the QEMU_OPT variable is easy enough to configure, so that any kind of magic won't improve the situation much.

I agree that it's best to avoid magic solutions. Perhaps a non-magic solution would be to include a comment above the `QEMU_OPT` line explaining that this can be an expected issue, where the solution is to comment out/remove the line.

```diff
 # prevent Qemu from using KVM
 #
+# Note: On some systems the `-no-kvm` command line argument is not included in `qemu-system-x86_64`,
+# resulting in the error `-no-kvm: invalid option`. To resolve this issue, simply comment out or remove the
+# line below.
 QEMU_OPT += -no-kvm
```

Something along those lines?

Cheers,
Robin
