### ISSUE TITLE
core: extend system management functionality to be available per CPU

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#5009]
On x86 machine specific registers (MSR) and their privileged instructions (rdmsr, wrmsr) are used to steer various system functionality which is just available to the kernel.

Some MSRs provide functionality to monitor system state (e.g. temperature, frequency) and adjust the power consumption (e.g Intel HWP or AMD pstate), which one may want to adjust/read out dynamically, e.g. on Sculpt OS. Depending on the MSR, see Intel/AMD specification, the instruction must be called per SMT thread (hyper_thread), or just per CPU core, or per CPU packet to be effective.

On Genode, by now, we have the Pd_session::managing_system() as a guarded privileged call on imx8 by the platform driver and on x86 for ACPI suspend functionality. This functionality is solely available on the boot CPU by now.

By extending the PD managing interface per Genode Affinity::Location, we will be able to leverage the MSR functionality per CPU core resp. per SMT thread when supported by the kernel.

**Comment by alex-ab** [comment]
@nfeske: my issue_5009 contains the commits. I added the discussed change of this morning as fixup.

**Comment by nfeske** [comment]
While testing, I came up with fixup https://github.com/genodelabs/genode/commit/1f2776ba9a882730040634f4386c89fa9dbf287c.

**Comment by alex-ab** [comment]
@chelmuth: on issue_5009 the both top most commits add the msr access for core on nova
