### ISSUE TITLE
Effects of pthread_cancel() in Thread_base destructor on lx_hybrid 

### ISSUE THREAD

**Issue by afett** [genodelabs/genode#501]
The pthread_cancel() call in the Thread_base destructor in
base-linux/src/platform/lx_hybrid.cc will cause stack unwinding by throwing an exception
under C++. See http://udrepper.livejournal.com/21541.html for example.

With a canceltype of PTHREAD_CANCEL_ASYNCHRONOUS this might happen
anywhere, for example during deconstruction of another object within the
canceled thread which is probably not what one wants.

It will also not work in catch all statements which do not rethrow, but I
tend to regard this a coding error.

One could somewhat mitigate those effects by using deferred cancellation
and document that cancellation points should be avoided in any destructors running
on a threads stack. (Yes I know, the whole point of the Thread abstraction goes down
the drain with that)

Above problems are one reason why when using posix threads most (sane) people
tend do avoid thread cancellation and either just return from the function passed
to pthread_create or call an explicit pthread_exit().

**Comment by nfeske** [comment]
I suspect that this issue is outdated and won't receive any further attention. Hence, I'm closing it.
