### ISSUE TITLE
gdb_interactive.run: pass Ctrl-C to GDB

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#5019]
Currently, Ctrl-C quits socat on the Linux host.

**Comment by cproc** [comment]
Commit fb21ddd fixes the problem when GDB is running on hardware. On Qemu, Ctrl-C still does not reach GDB for some reason. I've read about the difference between `-serial stdio` and `-serial mon:stdio` with regard to the handling of Ctrl-C, but in this case Ctrl-C is transferred over a separate socket chardev.

**Comment by nfeske** [comment]
Fixed in master.
