### ISSUE TITLE
ldso: load posix.lib.so first

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#5027]
Load `posix.lib.so` first, if it is a dependency, to satisfy the invariant of the libc fork/execve mechanism that this library and its dependencies are always loaded in the same order.

**Comment by chelmuth** [comment]
The final solution supersedes #5026 and #5025. Also, *lib/compat-libc* may become a shared library again. @atopia, do you agree?

**Comment by cproc** [comment]
Fixed by a0d42b6.

**Comment by chelmuth** [comment]
The commit fixes vim-internal command execution via `:!` in my current RC7 published on depot.genode.org.
