### ISSUE TITLE
libc/lxip: support connect(...AF_UNSPEC..) on UDP sockets

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#5031]
POSIX specififies the following behavior for `connect()`

> If the initiating socket is not connection-mode, then connect() shall set the socket's peer address, and no connection is made. For SOCK_DGRAM sockets, the peer address identifies where all datagrams are sent on subsequent [send()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/send.html) functions, and limits the remote sender for subsequent [recv()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/recv.html) functions. If the sa_family member of address is AF_UNSPEC, the socket's peer address shall be reset. Note that despite no connection being made, the term ``connected'' is used to describe a connectionless-mode socket for which a peer address has been set. [^1]

Commits 63a65fbc20009eb7622330e5bc0ec6986f2eb5c3 and 0c153e9c4666462d31e7e86343940dd91e727094 by @ssumpf must be considered.

[^1]: https://pubs.opengroup.org/onlinepubs/9699919799/

**Comment by ssumpf** [comment]
@chelmuth: 00bbf37 and [20bfde3](https://github.com/ssumpf/genode/commit/20bfde302c7b4bf3173f6d08a8137c2d528c9f37) address your comments.

**Comment by chelmuth** [comment]
@ssumpf may we close this issue as fixed?

**Comment by ssumpf** [comment]
@chelmuth: Yes
