### ISSUE TITLE
base-hw: Unmap regards thread that is not bind to PD

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#504]
For any reason it seems that a thread can be added as client to an RM session before it gets bind to a PD. The questionable point is located in 'Thread_base::start' within 'base-hw/src/base/thread_support.cc'. As it has no further effects, the resulting strange unmap requests are simply ignored by now. It seems to come from a race condition, because it occured first when entrypoint threads of two child objects started simultanously.

**Comment by skalk** [comment]
The order seems to be reversed today: `repos/base-hw/src/base/thread/start.cc`. The thread is first bound to a PD, and then added to a RM session. Can we close the issue?

**Comment by m-stein** [comment]
So, we should not check for this anymore: [Commit](https://github.com/m-stein/genode/commit/a1dd75690ff65f64bacde8816a7bab62679bd6ea) is based on staging.

@skalk: Do you agree?

**Comment by skalk** [comment]
No, I would not depend on the correct behaviour of core clients. If some component decides to reverse the order again, core will end up in a pagefault. Just leave it defensive like it is.

**Comment by m-stein** [comment]
@skalk: Updated.
