### ISSUE TITLE
vbox: network model may get stuck during transfer of large files

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#5045]

**Comment by alex-ab** [comment]
With commit c4c1a545119b9f438ec0c62897d0a7ee6175305f (thanks Peter!) a scp of a large file (8GB) initiated from within a guest VM with Ubuntu 22.04 to a remote ssh server _ever_ aborts with broken pipe after 1-2% of the file.

**Comment by chelmuth** [comment]
Merged the top commit to staging, drivers-23.05, and drivers-23.10.

**Comment by chelmuth** [comment]
Also merged 4758caf to staging.
