### ISSUE TITLE
 tresor: improved module framework and clean-up

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#5062]
Until now the Tresor library kept on suffering from design decisions made years ago with its predecessor, the CBE library. I have identified these main problems:

1. The code has much unnecessary state and indirections in execution flow  because a Tresor module can generate a request to another module only after having waited for the Module framework to ask the remote module whether it is ready for receiving.
2. All Module request classes must be copyable, which implies several negative effects.
3. Some modules, like the Free Tree module have such complex state machines and execution flow patterns, that debugging them almost always becomes a forensic, tiresome task. A dedicated internal restructuring of these modules is overdue.
4. There is a lot of redundancy because much bureaucracy around the communication between modules is not yet part of the Module framework but implemented module-specific.
5. Further redundancy comes from the fact that some implementations, like securing a superblock are required in many places but are not well extracted because of their asynchronous nature. Such implementations would benefit from a concept for sub-state-machines that is easy to understand when looking at the surrounding state machine.
6. The back end modules (block_io, crypto, trust_anchor) all work on files but each has its own implementation of this access with only subtle but dangerous differences. These modules would benefit from a generic file abstraction in form of a sub-state machine.
7. All users of the library (Tresor Tester, VFS Tresor, Tresor Init, Tresor Check) implement kind-of modules and individually glue them to the Tresor modules. Tresor users should use only generic Module utilities for Module-related tasks.

**Comment by chelmuth** [comment]
I see you're still busy with this cleanup. Please leave a note here when the branch is ready for review.

**Comment by m-stein** [comment]
@chelmuth Yesterday, after having pushed the latest commits for this issue, I switched to the 23.04/23.11 compatibility issue. As my merge_to_staging is now compatible with File Vault 23.11 containers, I'd say that we can start reviews for this issue.

**Comment by chelmuth** [comment]
Tresor rework entered the master branch.
