### ISSUE TITLE
sculpt_manager: select correct launcher in + menu

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#5064]
I think I found a problem with the sculpt manager here. When I clicked one launcher in the + menu, the program started, and then I clicked a launcher that came after the first launcher in the menu, the second program wouldn't start. In fact nothing visible happened at all on the second click.

**Comment by m-stein** [comment]
@nfeske Do you think 92989de2ca is a good fix for this?

**Comment by m-stein** [comment]
@nfeske Maybe we should centralize the aspect of the "viewed" launcher: 14d876c262

**Comment by nfeske** [comment]
Thanks for reporting this issue and the fix, which I merged to staging just now.

**Comment by nfeske** [comment]
Fixed in master.
