### ISSUE TITLE
lx_emul: provide 'flush_dcache_page' as dummy on arm64

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#5065]
This function is currently provided as generated dummy in various DDE-Linux _arm64_ drivers (`wireguard` is the notable exception where it already is a dummy). As this generated dummy is regularly triggered on the current Sculpt release in the wifi driver on the MNT Reform 2 (with the Atheros wlan card) and changing it to a NOP dummy there as well has no noticable side-effects, it stands to reason to consolidate it.

**Comment by nfeske** [comment]
Fixed in master.
