### ISSUE TITLE
os: build 'lib/ld' in 'monitor_gdb.inc'

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#5068]
Related to #5061.

**Comment by cproc** [comment]
Fixed by 23c9f2d.

**Comment by nfeske** [comment]
Thanks. Merged to staging.

**Comment by nfeske** [comment]
Fixup https://github.com/genodelabs/genode/commit/b0aa20c41ae318023ed0d50076e0181aebaa3a73 covers ports/run/gdb.inc as well.
