### ISSUE TITLE
core: mark implicitly detached regions as reserved

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#5069]
This is a follow-up issue to #5046 for the suggested solution in core.

**Comment by cproc** [comment]
Commit 29fec69 marks the regions which get detached by `Dataspace_component::detach_from_rm_sessions()` as reserved until `detach()` is called from somewhere else.

**Comment by nfeske** [comment]
Why have you made the marking optional (via `_keep_reserved_on_detach`)? Wouldn't it be desirable to have one consistent behavior?

Do you think that there is valid use case for clearing the `_reserved` state? If not, I suggest to tighten the interface by only having a `mark_as_reserved` method that sets the bit.

**Comment by cproc** [comment]
Commit 88e6e77 implements the feature with a dedicated `reserve_and_flush()` function.

**Comment by cproc** [comment]
Fixup commit 83e7769 checks the reserved state in `_core_local_addr()` as well and should fix the errors which occurred on kernels like Fiasco(.OC) and Pistachio during the nightly test.

**Comment by chelmuth** [comment]
run/seoul-auto fails on nova with the following message. May this be related to changes in this issue?

```
[2023-12-07 05:50:35] [init -> seoul] Error: Uncaught exception of type 'Genode::Region_map::Region_conflict'
```

**Comment by alex-ab** [comment]
An artificial base-nova test to trigger resource pressure in a PD seem now to require more capabilities (fcbab4df69a183f5dd387e273921739d6a976eac) to succeed. The test is very simple, it just creates a dataspace and attaches in a loop the same ds again and again. Presumably, with this change the amount for the metadata handling in core increased. In this test The specific test calls ~320.000 attach in a loop.

**Comment by cproc** [comment]
> We may consider turning the dataspace reference into a pointer, which would become a nullptr when `mark_as_reserved` is called. In this case, the `_dsc` reference would no longer be valid anyway. For wrapping up this change, the `dataspace` accessor should better be replaced with a `with_dataspace` method that checks the dataspace pointer before calling a functor with the de-referenced pointer as argument.
> 
> @cproc would you like to supplement this change as a separate commit?

Commit f1b28d1 is my current state of this change and it causes a compile error which I don't understand. Any ideas how to fix it?

```
In file included from /.../repos/base/src/core/include/pd_session_component.h:37,
                 from /.../repos/base-nova/src/core/pd_session_support.cc:15:
/.../repos/base/src/core/include/region_map_component.h: In instantiation of 'auto Core::Rm_region::with_dataspace(const auto:6&) const [with auto:6 = Core::Region_map_component::with_mapping_for_fault<Core::Pd_session_component::map(Genode::addr_t, Genode::addr_t)::<lambda(const Core::Mapping&)>, Core::Pd_session_component::map(Genode::addr_t, Genode::addr_t)::<lambda(Core::Region_map_component&, const Core::Fault&)> >(const Core::Fault&, const Core::Pd_session_component::map(Genode::addr_t, Genode::addr_t)::<lambda(const Core::Mapping&)>&, const Core::Pd_session_component::map(Genode::addr_t, Genode::addr_t)::<lambda(Core::Region_map_component&, const Core::Fault&)>&)::<lambda(const Core::Rm_region&, const Core::Fault&)>::<lambda(Core::Dataspace_component&)>]':
/.../repos/base/src/core/include/region_map_component.h:608:34:   required from 'Core::Region_map_component::With_mapping_result Core::Region_map_component::with_mapping_for_fault(const Core::Fault&, const auto:11&, const auto:12&) [with auto:11 = Core::Pd_session_component::map(Genode::addr_t, Genode::addr_t)::<lambda(const Core::Mapping&)>; auto:12 = Core::Pd_session_component::map(Genode::addr_t, Genode::addr_t)::<lambda(Core::Region_map_component&, const Core::Fault&)>]'
/.../repos/base-nova/src/core/pd_session_support.cc:87:41:   required from here
/.../repos/base/src/core/include/region_map_component.h:130:34: error: inconsistent deduction for auto return type: 'void' and then 'Core::Region_map_component::With_mapping_result'
  130 |                         return fn(*_dsc);
      |                                ~~^~~~~~~
/.../repos/base/src/core/include/region_map_component.h:130:34: error: return-statement with a value, in function returning 'void' [-fpermissive]
```

**Comment by nfeske** [comment]
The method `with_dataspace` should not return anything but merely call `fn`.

**Comment by cproc** [comment]
Commit 31223f0 implements the dataspace pointer change, which decreased the capability demand of the platform test again.

**Comment by chelmuth** [comment]
@cproc I tested Sculpt with a Ubuntu MATE 22.04 VM. On `poweroff` I get an endless log of the following message - I added the address output to the message in *repos/base/src/core/vm_session_common.cc*.

```
Error: reserve_and_flush unimplemented 0x125000
Error: reserve_and_flush unimplemented 0x125000
Error: reserve_and_flush unimplemented 0x125000
Error: reserve_and_flush unimplemented 0x125000
...
```

Any ideas?

**Comment by cproc** [comment]
Commit 7384708 implements `Vm_session_component::reserve_and_flush()`.

**Comment by cproc** [comment]
The `Vm_session_component::detach(addr_t, size_t)` variant probably also needs to check now if some of the regions in the address range are reserved. I'm looking into that.

**Comment by cproc** [comment]
Commit 4e2721f adapts the `Vm_session_component::detach(addr_t, size_t)` variant as well.

**Comment by chelmuth** [comment]
Thanks, I already tested the first variant successfully and are no longer stuck on poweroff. Will merge the recent commit to staging.
