### ISSUE TITLE
base: let `Region_map::attach()` return the size of the attached region

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#5070]
This is a follow-up issue to #5046.

Currently, `Region_map::attach()` returns only the address of the attached region and the debug monitor tries to calculate the size of the region for its memory map by itself, which involves the risky invocation of the dataspace capabilty to obtain the size of the dataspace.

One way to enhance `Region_map::attach()` and related functions could be to return a `Local_region` with address and size instead of a `Local_addr`, but this would involve the need to adapt all existing users.

**Comment by nfeske** [comment]
I would appreciate you implementing the `Local_region` approach, but let us better call the return type `Byte_range`.

BTW, I was planning to change the `Region_map::attach` interface in two further respects:

* I'd like the replace the exceptions by the `Attempt` pattern, following the lines of https://github.com/genodelabs/genode/blob/master/repos/base/include/base/ram_allocator.h#L37
* The various `attach` parameters should go into one `Attach_attr` struct similar to what I did inside core already: https://github.com/genodelabs/genode/blob/master/repos/base/src/core/include/region_map_component.h#L474. The distinction between the various usage patterns (attach_at, attach_executable, attach_rwx) would then be realized as `Attach_attr` class functions. E.g., `Attach_attr::executable(at, size, offset)` would return an `Attach_attr` object with the corresponding members set.

I'm not suggesting to implement those three changes all at once, but wanted to share where we should be heading.

**Comment by skalk** [comment]
@nfeske please consider fixup commit ae80c7d for staging

**Comment by nfeske** [comment]
Thank you very much!
