### ISSUE TITLE
libc: `TZ` environment variable ineffective when calling `localtime()`

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#5074]
I tried converting the RTC-provided time into a local time using `localtime()`. According to the man page, the following should do the trick:

```
struct timespec ts;
setenv("TZ", "UTC-1", 1);
clock_gettime(CLOCK_REALTIME, &ts);
struct tm *tm = localtime((time_t*)&ts.tv_sec); 
```

Unfortunately, this does not work on Genode. I dug into the contrib code and noticed that the timezone is already set with `clock_gettime()`. As it turned out, our libc rtc implementation uses `mktime()` to convert a date/time string into an epoch, however, `mktime()` assumes local time instead of UTC. Instead of `mktime()`, we should therefore use `timegm()`.

**Comment by jschlatow** [comment]
Fixed by e00c291

**Comment by nfeske** [comment]
Interesting that you came across the same code as I recently visited during my investigation of https://github.com/genodelabs/genode/issues/3707#issuecomment-1836114200

I observed the mktime function getting stuck deep in the tzcode library. Now, I'm wondering if you change might possibly side-step this issue? ;-)

**Comment by nfeske** [comment]
> Now, I'm wondering if your change might possibly side-step this issue?

Unfortunately, my hope was unfounded. The `timegm` shows the same symptoms as `mktime`.

**Comment by nfeske** [comment]
Fixed in master.
