### ISSUE TITLE
acpica: some improvements

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#5083]
- printf based on format lib
- remove static constructor
- detach MMIO region before re-attaching

**Comment by chelmuth** [comment]
@alex-ab please review the changes

**Comment by alex-ab** [comment]
@chelmuth: looks good to me. I added 2 commits, one fixup to detach the region before iomem ds destruction and the other one is a proposal to add acpica to the default index of genodelabs. I will not provide battery and acpica packages anymore with the next Sculpt release.
