### ISSUE TITLE
New audio record and play infrastructure

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#5097]
Genode's current audio_in/audio_out sessions and the accompanied mixer have the following limitations:
* All components need to operate on a fixed sample rate of 44100 Hz, which recently has become a problem because some audio drivers tend to support only 48000 Hz.
* The interfaces are prone to effects caused by the drifting of time between the producer and consumer of audio data. One effect are buffer under-runs, which produce audible noise. The other is the slow accumulation of buffered sample data, which increases latency over time (affecting the effectiveness of aec) and yields an audible buffer overrun after a while.
* The mixer is single client of the audio driver, which has two drawbacks. First, the audio driver cannot be restarted without also restarting the mixer and - transitively - each client of the mixer. Second, it is not possible to route audio between different audio drivers.

The new session interfaces named "Record" and "Play" are designed to overcome these limitations. The accompanied mixer acts as resource multiplexer serving both interfaces. Drivers and applications have the role mere clients.

To bridge the gap between audio clients operating at different sample rates, the mixer automatically detects and converts sample rates as needed. It observes the jitter of clients to automatically to adjust buffering parameters to attain continuous playback while trying to optimize for low latency. Those runtime-measurements can be augmented by explicit configuration values.

Multi-channel playing and recording is realized by one session per channel whereas one channel is used to drive the time allocation (active time synchronization with the mixer via synchronous RPC) while all further channels merely enqueue/obtain data into/from their respective sessions without any synchronous interplay with the mixer.

**Comment by nfeske** [comment]
Commit https://github.com/nfeske/genode/commit/54621c4f8d6abac486d98522e6b297d34eeb3b2f contains the implementation of the ideas along with an artificial experimentation scenario at gems/run/waveform_player.run, which combines a simple waveform generator, the mixer, and a simple oscilloscope. No sound yet.

**Comment by chelmuth** [comment]
Simply *Wow*. Though I have a small advantage over those not involved in the discussions of the last weeks I think the code is greatly self-describing and backed by the excellent mixer README.

**Comment by cnuke** [comment]
@nfeske the commits look good to me, thanks. I am looking forward to playing (no pun intended ;-)) with the record session.

**Comment by nfeske** [comment]
The new commit https://github.com/genodelabs/genode/commit/92a5af105efe9102572f7c4db7ee15100af2c07e covers both the input and output of the BSD audio driver. Because of the green light by @cuke for the intermediate version, I have pushed it (long with the coding-style one) to staging. It probably wouldn't hurt if @cnuke takes another scrutinizing look on this one.

@ssumpf I hope that the commit may be useful as reference for the future adaptation of your DDE-Linux-based audio driver.

@cnuke :-) I'd be thrilled about exposing the mixer to real-world audio applications via the vfs-oss plugin. So yeah, you are more than welcome to pick up the new toy.

**Comment by cnuke** [comment]
Please merge [012625c](https://github.com/cnuke/genode/commit/012625c0c124a8b524454b82cc4effbf83af5912) to staging.

**Comment by nfeske** [comment]
> Please merge [012625c](https://github.com/cnuke/genode/commit/012625c0c124a8b524454b82cc4effbf83af5912) to staging.

At your service. Thank you!
