### ISSUE TITLE
Enhance input-event handling for variety of devices generating "motion"

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#5105]
Handling of the following device types should be improved in this issue.

| &nbsp;          |                                                      |
| :-------------- | :--------------------------------------------------- |
| **Mouse**       | relative motion                                      |
| **Pointer**     | absolute motion (Qemu usb-tablet and IP-KVM devices) |
| **Touchpad**    | relative motion via absolute touchpad coordinates    |
| **Touchtool**   | absolute motion (e.g., stylus)                       |
| **Touchscreen** | absolute motion and finger (multi-) touch            |

Also, transformation of input events (like scaling and rotation) and gestures (like tap-to-click [^1]) shall be considered.

[^1]: https://wayland.freedesktop.org/libinput/doc/latest/tapping.html

**Comment by nfeske** [comment]
> I pushed the series to my repo for review.

All I can say is that this is a truly beautiful commit series. I especially like the simplicity and flexibility of the <transform> filter.

**Comment by ssumpf** [comment]
Awesome!

**Comment by cproc** [comment]
I got an input problem with Sculpt on the current staging branch and can reproduce it by opening an Inspect shell and repeatedly entering the `true` command. The output then often looks similar to this:

```
inspect:/> true
inspect:/> true
inspect:/> tre
```

and the log shows the following warning:

```
[init -> nitpicker] Warning: suspicious double press of KEY_U
```

and when this happens, hovering the mouse pointer over one of the top buttons (for example "Components") does not highlight the button and pressing the button has no effect. The mouse pointer is still visible and moving, though.

**Comment by cproc** [comment]
forgot, git bisect found commit 66889cb

**Comment by cproc** [comment]
Yes, USB keyboard.

**Comment by chelmuth** [comment]
What a bummer, my assumption that event packets only host single key events is absolutely misguided. Obviously n-key-rollover may report multiple key events that *occur at the same moment in time* (see Documentaion/input/event-codes.rst SYN_REPORT). A fixup is already in the works. Thanks for reporting!

**Comment by chelmuth** [comment]
@cproc commit 0adb361e541800393b50fcbe2d12265f059bf420 address your issue

**Comment by cproc** [comment]
> @cproc commit [0adb361](https://github.com/genodelabs/genode/commit/0adb361e541800393b50fcbe2d12265f059bf420) address your issue

Confirmed, thanks.
