### ISSUE TITLE
vfs_import: overwrite does not truncate existing file

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#5107]
When working on goa_testbed, I noticed that using the import vfs plugin to initialise the log file failed in case the file already existed and contained the log messages from a previous run since the length of the file was not reset.

**Comment by jschlatow** [comment]
Commit e2becec fixes this issue and modifies the run script to cover the aforementioned situation.

**Comment by chelmuth** [comment]
Merged to master.
