### ISSUE TITLE
test-terminal_expect_send: line parsing broken for too long input

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#5108]
As it turned out during the work on issue #4081 the `test-terminal_expect_send` utility breaks when trying to parse a line, whereby input might be send without line-break.

**Comment by nfeske** [comment]
My take to address this issue: https://github.com/genodelabs/genode/commit/eb78b5591f0db542b5bbc07260bc201379190be1

**Comment by skalk** [comment]
@nfeske thank you for fixing this issue!
