### ISSUE TITLE
hw: make virtualization implementation more generic

### ISSUE THREAD

**Issue by atopia** [genodelabs/genode#5113]
The implementation of x86 virtualization did not lend itself to a runtime selection of the x86 virtualization technology.

Make the general virtualization support less specific to AMD's SVM and encapsulate functionality in the VMCB class to facilitate adding support for Intel's VMX.

**Comment by atopia** [comment]
The renewed series of commits accesses the VMCB State Save Area via the Mmio framework.

**Comment by chelmuth** [comment]
@atopia I'd like to defer the review and merge until you come up with the final addition of the VMX implementation. Only then, we may discuss some design decisions you made because of the virtualization-technology duality. Do you agree?

**Comment by atopia** [comment]
Sorry for the late reply, your comment slipped through. Yes, I'm fine with doing the review and merge together with the VMX implementation.

**Comment by chelmuth** [comment]
I merged the series. Please address my comments in fixup commits.

**Comment by atopia** [comment]
Fixed in master.
