### ISSUE TITLE
hw: refine scheduler class for better comprehensibility 

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#5115]
Try to make API more slim, reduce state variables, find more common namings. These changes should not change any semantics at this point.

**Comment by skalk** [comment]
There are still some things that could be nicer, like getting rid of the `_current` pointer to the currently scheduled context, but for the time-being I would mark this issue as being fixed.

**Comment by nfeske** [comment]
I very much welcome these changes. @jschlatow do you concur?

**Comment by jschlatow** [comment]
I haven't reviewed the commit series in detail (only the commit messages), yet I very much appreciate the improved readability as it will simplify future modifications.

**Comment by nfeske** [comment]
I just tested these changes for Sculpt on PinePhone, where everything works fine. Hence, I have merged the commit series to staging now.
