### ISSUE TITLE
trace_recorder: get session arguments from config

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#5123]
The following commit adds support for setting the `TRACE` session arguments via the configuration. This is useful for scenarios where the default settings are not sufficient. The component now also displays a warning in case the number of received subjects equals the limit imposed by the argument buffer size to hint at potentially truncated results.

**Comment by cnuke** [comment]
Commit [98b4a44](https://github.com/cnuke/genode/commit/98b4a447378aa7f6cbf934e7c4e8e38aef5a106f) addresses this issue.

**Comment by chelmuth** [comment]
I'd like to merge these commits but think the renaming went into the wrong direction. Without your patch trace_recorder and trace_logger used consistent naming of `buffer` resp. `default_buffer` attributes for buffer sizes. I suggest we stick to this naming for `default_buffer` (was `buffer_size`) and `session_arg_buffer` which unifies these aspects of the config of both components. You may squash the final commit, thanks.

**Comment by cnuke** [comment]
My bad, commit [449a72d](https://github.com/cnuke/genode/commit/449a72d8a227bcbee516b3c60a49a754baec601c) contains the proper adaption.

**Comment by chelmuth** [comment]
Thanks, merged to staging.
