### ISSUE TITLE
hw: add support for VMX

### ISSUE THREAD

**Issue by atopia** [genodelabs/genode#5128]
Add support for Intel's Virtual Machine Extensions with nested paging.

**Comment by atopia** [comment]
Works on nested virtualization under Linux/KVM with qemu:
- vmm_x86
- seoul-auto (1 vCPU)
- seoul-net
- seoul-genode
- seoul-disc
- seoul-disc-64

Does not work:
- SMP (AP initialization hangs)
- virtualbox6 (error)

**Comment by atopia** [comment]
@chelmuth please have a look. The VMX virtualization feature contained in this issue is in good shape. There is an unresolved issue with (timer) interrupt injection, possibly connected to "recall" exit injection in the VMM on hw that likely transcends the VMX hypervisor implementation contained in this issue. On top of these commits, practical use of VMX under hw requires a reworked nested page table implementation that is orthogonal to VMX and will be provided in an upcoming issue.

**Comment by chelmuth** [comment]
I merged cba426c139f1dcf2eb5752e540a15d3ad8fc663d but got merge conflicts with 12e87b11a3ae03953e6ec86bf6099fab1c8e190d. Please address my remarks and rebase on staging.

**Comment by atopia** [comment]
The new commit should address the previously discussed points and is meant to be added on top of staging with the fixup commits from #5113 applied.

**Comment by chelmuth** [comment]
Merged to staging.
