### ISSUE TITLE
usb_net: "schedule: unexpected preempt_count"

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#5129]
When testing with `iperf3` using RTL8156 we observe a "schedule: unexpected preempt_count" message leading to `abort` being called. This behavior is triggered when trying to `schedule` while holding a lock or mutex.

Reported by @alex-ab

**Comment by ssumpf** [comment]
@alex-ab: d1e4352 does resolve the problem for me. How this goes together with https://github.com/genodelabs/genode/issues/5021 I don't know. It might not be an issue there.

**Comment by alex-ab** [comment]
@ssumpf: test scenario works now as expected, nice, thx

**Comment by skalk** [comment]
The issue stems from the fact that the `submit_urb` emulation code for USB client drivers was blocking when the USB packet stream was saturated. However, flow control is apparently done at another (upper) layer, and we cannot block here, but have to accept the URB. With the USB rework of issue #5021 the `submit_urb` emulation code got removed completely, and we use more original contrib code here, and do not block anymore at this layer. In my eyes, we can therefore close this issue. @ssumpf @alex-ab what do you think?

**Comment by alex-ab** [comment]
I re-tested my scenario and the specific issue does not trigger anymore. However, when using the usb_net, in the test (iperf) starts with high cpu utilization (which is expected), but after while the utilization drops to 0 and the final throughput of the iperf scenario is not good. But this is another issue. So, from my side this issue can be closed.

**Comment by chelmuth** [comment]
So shall it be.
