### ISSUE TITLE
libc: select() based on poll()

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#5131]
Measurements with `oprofile` for the QtWebEngine-based web browsers showed a relatively high percentage of time spent in `select()`-related functions, in particular the lookup of file descriptor objects. When I re-implemented `poll()` and `select()` in a way that `select()` uses `poll()` internally instead of the other way around and `poll()` looks up the file descriptor objects only once early-on, the corresponding `oprofile` percentages were reduced notably. The re-implementation also removed the global `Select_cb_list` and the dedicated mutex used to protect it and keeps more information local on the stacks of the individual threads instead, which might lower the risk of synchronization problems within the libc.

**Comment by cproc** [comment]
Commit 34f8689 contains the re-implementation. It has been in use by the Falkon and Morph browser depot packages in the `cproc` depot for months now and appears to work well so far, at least in these scenarios.

**Comment by SunriseJungle** [comment]
Hello, I hope you’re able and willing to answer my question and I’m sorry if I’m not supposed to respond to this email….. But I am wondering if Genode Will now function, most computers, generally, or if it will only work on certain computers still. I would like to try it out On my pine phone Pro Explorer or just a laptop.

**Comment by cproc** [comment]
@SunriseJungle: the mailing list [1] would be a better place for generic questions about Genode. Regarding supported hardware, there is an unofficial hardware compatibility list at [2] and some additional hardware not mentioned there like the original PinePhone or the ARM-based MNT Reform laptop. There is also a ready-to-use Sculpt OS image available which you could try on your laptop [3].

[1] https://genode.org/community/mailing-lists
[2] https://usr.sysret.de/jws/genode/hcl.html
[3] https://genode.org/download/sculpt
