### ISSUE TITLE
usb_block: fix 'Request_sense_response' MMIO size

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#5133]
USB storage devices that require a 'Request_sense' command are currently unusable as the response size does not match the MMIO size.

For reference, a *Kingston DataTraveler 3.0* `0x0951:0x1666` triggered the problem.

**Comment by cnuke** [comment]
Commit [ddbc9c5](https://github.com/cnuke/genode/commit/ddbc9c5cd496f1585d24ad0317338dd30f2f8e63) addresses issue.

With the MMIO boundary changes in place we could drop the various `LENGTH` enum's but I would post-pone such an alteration until the Usb session changes are on staging.

**Comment by alex-ab** [comment]
@cnuke: thanks, added a fixup to make it working with post 24.02

**Comment by chelmuth** [comment]
Thanks @alex-ab and @cnuke! Merged the fix to staging.
