### ISSUE TITLE
gems: add dbg_download

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#5143]
Add a Sculpt subsystem which watches `/config/managed/runtime` and downloads any missing `bin` and `dbg` depot archives of monitored components using `depot_download`.

**Comment by cproc** [comment]
Commit c0340a0 adds the subsystem. It currently starts "public_rw" and "depot_rw" chroot components internally to limit the file system access, but these could in principle also be started separately by the user if made available or maybe the "individual directory assignment" feature which is planned for the August release could be used in the future.

**Comment by cproc** [comment]
Commit edc23f8 adds the sculpt distribution archives and index entries as well.

**Comment by nfeske** [comment]
This is a really elegant solution. Love it!

**Comment by nfeske** [comment]
Maybe we can consider adding a launcher called `downlod_debug_info` that already contains the delicate routing rules. So the mechanism could be activated/deactivated with a single click. This launcher may even alleviate the need to offer the pkg in the index. @cproc what do you think?

**Comment by cproc** [comment]
Fixup commit a368a2c adds the launcher and removes the pkg from the index.

**Comment by nfeske** [comment]
Thanks! Merged to staging.

**Comment by chelmuth** [comment]
@cproc we get build errors on 32-bit.

```
.../repos/gems/src/app/dbg_download/main.cc: In member function ‘void Main::_handle_runtime_config_update()’:
.../repos/gems/src/app/dbg_download/main.cc:145:54: error: conversion from ‘Vfs::file_size’ {aka ‘long long unsigned int’} to ‘Genode::size_t’ {aka ‘long unsigned int’} may change value [-Werror=conversion]
  145 |                 size_t buf_size = _root_dir.file_size(_runtime_config_path);
      |                                   ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by cproc** [comment]
Commit dc6fd16 fixes the 32-bit build error.

**Comment by nfeske** [comment]
Could the use of `File_content` be a possible alternative to the manual alloc/free? This would nicely alleviate the need for any cast.

**Comment by cproc** [comment]
Commit d931291 uses `File_content`, but it needs the cast as well when the file size is used as limit. Or we could set a fixed limit, but what would be a good value?

**Comment by nfeske** [comment]
The managed/runtime file on my current Sculpt system is around 80 KiB. May 512 KiB a reasonable limit?

**Comment by cproc** [comment]
Commit 2e3525c uses `File_content` with a limit of 512KiB.

**Comment by nfeske** [comment]
Thanks, merged to staging.
