### ISSUE TITLE
dde_linux: don't use `nm -U` during generation of initcall_table.c

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#5155]
I noticed a missing initcall (usbnet_init) for the Allwinner USB host driver. The problem could be traced to the unexpected behavior of `nm`.

**Comment by nfeske** [comment]
Fixed by https://github.com/genodelabs/genode/commit/437efded90b9822bea12923418b0ca62a7c5fa79.

**Comment by chelmuth** [comment]
Binutils fixed the bug in 2.42 https://sourceware.org/bugzilla/show_bug.cgi?id=31105
