### ISSUE TITLE
dde_linux: initcall_table.c is sometimes built too early

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#5159]
The code must be generated not before all other object files are compiled (and fresh).
By chance (parallel build), the rule for generating the .c files can be invoked earlier because the rule's dependencies are not completely known at the position where the rule is defined.

**Comment by nfeske** [comment]
Fixed by https://github.com/genodelabs/genode/commit/9b101c9a6c9b691e7b64ccdeaea74dd791b169cf

**Comment by ssumpf** [comment]
[6098432](https://github.com/ssumpf/genode-imx/commit/60984324fb689f2628b81ad2e7045505454356d3) makes the necessary for the MNT Reform Linux.

**Comment by nfeske** [comment]
Thanks @ssumpf, merged to staging.
