### ISSUE TITLE
curl: update to version 8.7.1

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#5184]

**Comment by cnuke** [comment]
Commit [5957f64](https://github.com/cnuke/genode/commit/5957f642dea48915a1c4dabe76f038608df12613) addresses this issue while commit [d00b6f6](https://github.com/cnuke/genode-world/commit/d00b6f6af6efd370b87aa8a7c93359b09dc811b9) and [c785ef0](https://github.com/cnuke/genodians.org/commit/c785ef04655275a550660fa8b3ffa89e01df29c8) adapt the external repositories.

Commit [c076e04](https://github.com/cnuke/genode/commit/c076e04331629ca0d4add554e1093d24b4f228bd) allows for setting the verbose option via the configuration.

**Comment by chelmuth** [comment]
Commit 5957f642dea48915a1c4dabe76f038608df12613 misses the *curl_setup.patch* file.

**Comment by cnuke** [comment]
> Commit [5957f64](https://github.com/genodelabs/genode/commit/5957f642dea48915a1c4dabe76f038608df12613) misses the _curl_setup.patch_ file.

You are right - sorry, commit [acabff6](https://github.com/cnuke/genode/commit/acabff611c471e27ac679b1aaaba8d47c0017611) adds the missing patch file.

**Comment by cproc** [comment]
Fixup commit fa7118f adapts the `dbg_download` recipe as well.
