### ISSUE TITLE
record_play_mixer: reduce volume of diagnostic messages by default

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#5186]
In Sculpt, the latency warnings by the record-play mixer are too many (rate of 1 second). Those warnings were intended for diagnosis. But Sculpt users will hardly participate in the debugging of latency issues but have to ensure all his warning noise.

To address this issue, a `warning_rate_ms` attribute could be added to the record_play_mixer config. By using 10000 ms default, regular users won't be bothered when seeing a message every now and then. But for latency diagnosis, we can set the attribute even to a low value like 200 ms.

Related to #5174

**Comment by chelmuth** [comment]
I would even be more user-oriented and implement `warning_rate_ms` as mere debugging feature with a default of `0` (no warnings).

**Comment by nfeske** [comment]
@cnuke what do you think?

**Comment by nfeske** [comment]
@chelmuth this would be fine for me as well.

**Comment by cnuke** [comment]
@nfeske I think that is a good idea (introducing the feature and setting it to `0` be default).
