### ISSUE TITLE
sculpt: Adding French Bépo keyboard

### ISSUE THREAD

**Issue by goutnet** [genodelabs/genode#5202]
Hi there,

I am starting to use scuplt OS, but alas my keyboard layout (bépo: https://en.wikipedia.org/wiki/B%C3%89PO ) is not yet supported.

As discussed with @nfeske  the best course of action would be to create an issue and a pull request to fill this need.

Will tag this issue in my next commits :)

**Comment by goutnet** [comment]
The above commits fixes this issue for me (and add the Bépo support)

With that said: while doing the test, I realized the terminal does not show accentuated characters properly (while the font does include those).

The issue can be seen when trying to type characters in a command set for example.

I will look into this too, and if the fix is simple, I'll tag this issue there. (else that will be for a new issue).

**Comment by goutnet** [comment]
@chelmuth  I just pushed a lighter version of the bepo layout, let me know what you think

**Comment by chelmuth** [comment]
Look good to me. Merged to staging.

**Comment by nfeske** [comment]
Fixed in Genode 24.05
