### ISSUE TITLE
Add check_tool to build system utilities

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#5213]
There are some Makefiles in different repositories (allwinner, rpi, imx) which already define a `check_tool` Makefile variable to test whether a tool is installed, and otherwise print a helpful message. Before duplicating the next occurrences of this utility, we should move it to `base/mk/util.inc`.

**Comment by chelmuth** [comment]
Merged both commits to their repositories. Would you mind to update allwinner and rpi too?
