### ISSUE TITLE
Busybox port for reproduceable Linux image creation

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#5214]
In the process of Linux device driver porting, as well as to build simple Linux VM images it is helpful to provide a common way to build a simple initramfs for the Linux kernel via the Busybox project.

**Comment by chelmuth** [comment]
Nice, I just tested this feature and have some remarks for discussion.

1. It would be nice to have a little documentation what I could do if I get `*** Need to have 'arm-linux-gnueabihf-gcc' installed`. Maybe a note in the port file that suggest `sudo apt install gcc-arm-linux-gnueabihf`?
2. For clarity, I suggest to use `BB_MK_ARGS := ARCH=x86_64 CROSS_COMPILE=x86_64-linux-gnu-gcc` in *busybox/x86_64/target.mk*.
3. Does the port create the rootfs as directory tree only or is there some image file?

**Comment by skalk** [comment]
@chelmuth I've added the documentation including the requirements in a README file, and have add the x86_64 suggestion.

**Comment by chelmuth** [comment]
Great, merged to staging.
