### ISSUE TITLE
sculpt: power down on t490s triggers reboot

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#5216]
On my t490s, issuing an ACPI power down immediately turns the laptop off, yet, after a few seconds the laptop restarts. This is reproducible with Sculpt 24.04.1 on my t490s but not on the x260. I disconnected all peripherals (except the USB thumb drive) to rule out that any peripheral causes the wake up.

Has anyone observed this behaviour already?

**Comment by alex-ab** [comment]
Not seen it, but try to revert 14b3a0c7942f897519d18ab871357e782f210a0e, does it change things ?

**Comment by jschlatow** [comment]
> Not seen it, but try to revert [14b3a0c](https://github.com/genodelabs/genode/commit/14b3a0c7942f897519d18ab871357e782f210a0e), does it change things ?

Yes, it appears to solve the issue, i.e. I was not able to reproduce the effect after reverting the commit.

**Comment by nfeske** [comment]
> So either we remove the feature from platform driver completely [...]

That's probably the easiest solution. So I think let's go for it.

**Comment by alex-ab** [comment]
I added a commit which removes the feature.

**Comment by nfeske** [comment]
Thank you. Merged to staging.
