### ISSUE TITLE
hw: the bsd_audio_driver does not work

### ISSUE THREAD

**Issue by atopia** [genodelabs/genode#5220]
The audio driver hangs at "probe drivers".

**Comment by cnuke** [comment]
@atopia could you please give the `audio_out.run` run-script a try as the driver does work here with `base-hw` on the Fuji4 on the current *sculpt-24.04.1* branch.

**Comment by nfeske** [comment]
For the record, audio works fine with @jschlatow's Sculpt/hw [image](https://genode.org/documentation/release-notes/24.05#First_version_of_Sculpt_OS_based_on_Genode_s_custom_kernel) on my x260.

**Comment by atopia** [comment]
I probably ran into #5231 and can confirm that it works with @jschlatow's image.
