### ISSUE TITLE
sculpt: support launchers with pkg attributes of the form '<user>/pkg/<name>'

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#5223]
I was experimenting with creating a modded Sculpt image based on the genodelabs depot but with added launchers that reference packages from my depot. I noticed that pkg attributes of the form '<user>/pkg/<name>' are already partially supported, i.e. the depot archives are versioned and collected correctly and added to the image (if DEPOT=tar). However, the launcher files were not adapted accordingly.

**Comment by nfeske** [comment]
Merged to staging.
