### ISSUE TITLE
lx_emul: set refcnt in __alloc_pages_bulk

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#5225]

**Comment by cnuke** [comment]
Commit [75abf73](https://github.com/cnuke/genode/commit/75abf73abf244b02ddc56373416983a85214f2a0) addresses the issue by initializing the page count and is required for the FEC driver in 6.1.20 to work properly.

(As it might influence other DDE Linux drivers the *fixed* label is omitted as I would like to give it more exposure first.)

**Comment by chelmuth** [comment]
Do I understand correctly that `__alloc_pages_bulk()` is like a loop, which calls `lx_alloc_pages(1)` for each array element but requires only one call to `lx_emul_mem_alloc_aligned()`? And, thus, each page will be free'd individually later?

**Comment by chelmuth** [comment]
If the deallocation is used later on I'd expect `lx_free_pages()` may call `lx_emul_mem_free()` for multiple virtual addresses inside the single `lx_emul_mem_alloc_aligned()` allocation. Please correct me if I'm wrong.

**Comment by cnuke** [comment]
> Do I understand correctly that `__alloc_pages_bulk()` is like a loop, which calls `lx_alloc_pages(1)` for each array element but requires only one call to `lx_emul_mem_alloc_aligned()`? And, thus, each page will be free'd individually later?

Yes, that is the intended use case and might warrant a change in its implementation (especially considering your second comment).

> If the deallocation is used later on I'd expect `lx_free_pages()` may call `lx_emul_mem_free()` for multiple virtual addresses inside the single `lx_emul_mem_alloc_aligned()` allocation. Please correct me if I'm wrong.

Yes, that may happen as each page could be used individually.

**Comment by chelmuth** [comment]
Is commit 67e6c63 ready for merge?

**Comment by nfeske** [comment]
Fixed in master.
