### ISSUE TITLE
Support to sign grub2 bootloader for shim usage

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#5230]
During Hack'n'Hike #4989 we had a x86 notebook, where I (and others) did not manage to disable the UEFI secure boot feature in the boot menu, which excludes Sculpt to be testable easily. 

Even so a user may enroll its own UEFI keys (https://wiki.linuxquestions.org/wiki/How_to_use_Secure_Boot_with_your_own_keys), the step may not be suitable for all scenarios, e.g. if you still want to use other OSes and it can be problematic (see preparations chapter).

Another option is to use the shim bootloader, which is nowadays common in the Linux community. Shim is signed by the "trusted" CA. Shim itself has a feature called MOK (machine owner key), that permits the owner of a machine to add personal certificates which it trust in order to boot self build+signed bootloader or linux kernels, without wiping the "built in" CA certificates. 

This option would give us the chance, to ship Genode framework based scenarios, e.g. Sculpt OS, with a self created certificate and signed grub2 bootloader.

If the user is willing to trust the self-signed certificate (or the Genode Labs provided certificate) and install it as MOK, he would be able to boot a Sculpt scenario on secure-boot only systems.

**Comment by alex-ab** [comment]
With the wip commit on a Ubuntu 22.04 installation, I get a bootable USB stick for T490 with secure boot enabled. Debian 12 does not work for me currently. Please try also other distros so we can get an idea how for this takes us.

The commit expects that you have installed the shim packages of your Linux host distribution. For Debian 12 it was for me
shim-signed and pesign.

The commit in the current form adds the option, to specify a x509 certificate, for either image/uefi or image/disk, e.g:

--include image/disk --image-disk_shim genode.cer
--include image/uefi --image-uefi_shim genode.cer

When invoked without existing certificate file, it will give you some basic hints to create a key and certificate (mainly using the efigenkey tool as proposed by the basic tutorials). If all is fine, the grub2 efi files will be signed and embedded to the generated Genode image.

When booted on a secure boot enabled machine, it will be denied, because the signing key is unknown. I attached a raw slide show, what you will have to do. Mainly looking for the certificate, which is on the USB stick, checking that all is fine, from your perspective and enroll/accept the certificate. Afterwards you reboot, and if all is fine, your USB stick should boot  ...

<img src="https://github.com/genodelabs/genode/assets/1506104/b1275f06-3a87-48b7-a2f7-921fef22a708" width=20% height=20% />
<img src="https://github.com/genodelabs/genode/assets/1506104/af2898e0-0f1e-4507-8c50-1508b23c7aa3" width=20% height=20% />
<img src="https://github.com/genodelabs/genode/assets/1506104/0f605884-4b3a-4bfc-8b0d-c3382b54c25d" width=20% height=20% />
<img src="https://github.com/genodelabs/genode/assets/1506104/2fb29e1f-a77f-4f43-b182-765a9e6f5d7b" width=20% height=20% />
<img src="https://github.com/genodelabs/genode/assets/1506104/34c2817c-1afa-455c-b1b3-e34514f613a9" width=20% height=20% />
<img src="https://github.com/genodelabs/genode/assets/1506104/31a7d018-048f-4fc1-a3a3-76f943c526e2" width=20% height=20% />
<img src="https://github.com/genodelabs/genode/assets/1506104/08505019-bbf0-44ff-aff0-84ffd1bc9346" width=20% height=20% />
<img src="https://github.com/genodelabs/genode/assets/1506104/d9ca270a-6bb4-40b9-af29-37f3ccabf7ec" width=20% height=20% />
<img src="https://github.com/genodelabs/genode/assets/1506104/5fcf3289-18c1-4cc5-822a-f6cda2f0356a" width=20% height=20% />
<img src="https://github.com/genodelabs/genode/assets/1506104/82e364a8-7d55-41da-9340-20c04301dd73" width=20% height=20% />
<img src="https://github.com/genodelabs/genode/assets/1506104/387d3412-cedd-4a1f-8a9c-49924ae4d805" width=20% height=20% />
<img src="https://github.com/genodelabs/genode/assets/1506104/804beee2-c880-40bf-b440-1898c3b96861" width=20% height=20% />

If you want to remove the self-sign certificate from the machine again, you will need a native Linux installation or live medium. First list your enrolled certificate (you will have to use sudo or have to be root):

mokutil --list-enrolled

Export the certificates into files

mokutil --export

You will  get several MOK-number.der files in the current directory.
Schedule the entries you want to remove, e.g.

mokutil --delete MOK-number.der

You will be requested to enter a new password, which you will require later to confirm the removal during reboot.
Check finally the certificates which are scheduled to be deleted with:

mokutil --list-delete

Finally, reboot.
You will be presented with the same blue screen of the key manager, where you have to acknowledge the removal.

**Comment by nfeske** [comment]
Just noticed that the GRUB output has become quite noisy since this commit was merged to staging.

**Comment by alex-ab** [comment]
I will craft a fixup.

**Comment by alex-ab** [comment]
@nfeske: please add 4c9fa3c4ffcf1ef9cb5da546da97b71d6159b893 to staging
