### ISSUE TITLE
black_hole: add missing "report" in config.xsd

### ISSUE THREAD

**Issue by Time0o** [genodelabs/genode#5233]
The XML schema for `black_hole` is missing an allowed `<report/>` element even though `black_hole` supports report sessions. This was omitted by 14d0b72f52e25afc89aba664e324388dfa6b133e. Here is a quick fix: https://github.com/Time0o-gf/genode/commit/69f29e9d912b130d67546105ffab113ec9cbbda7

**Comment by nfeske** [comment]
Fixed in master.
