### ISSUE TITLE
libc: handle invalid file descriptor in poll()

### ISSUE THREAD

**Issue by atopia** [genodelabs/genode#5249]
poll(2) needs to handle invalid file descriptors in the pollfd struct, specifically `-1` as it may be used to disable entries in the `fds[]` array.

**Comment by chelmuth** [comment]
Slightly modified the commit to avoid style issues and merged to staging as 610e801dc43cfaf113aa3fa967da15c069000252.

**Comment by atopia** [comment]
Thanks for the additional clarification in the comment!
