### ISSUE TITLE
Linux: is CLONE_VFORK required in lx_create_process?

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#525]
Genode processes are created via `lx_create_process`, which is implemented in `base-linux/src/core/include/core_linux_syscalls.h`

``` c++
inline int lx_create_process(int (*entry)(void *), void *stack, void *arg)
{
	int flags = CLONE_VFORK | SIGCHLD;
	return lx_clone((int (*)(void *))entry, stack, flags, arg);
}
```

I'm not sure that we still need `CLONE_VFORK` here as it just synchronizes the pre-execve phase of the forked process with the forker. The man page states

> If  CLONE_VFORK is set, the execution of the calling process is suspended until the child releases its virtual memory resources via a call to execve(2) or _exit(2) (as with vfork(2)).
>
> If CLONE_VFORK is not set then both the calling process and the child are schedulable after the  call, and an application should not rely on execution occurring in any particular order.

I tend to remove it but only after thorough testing.

**Comment by nfeske** [comment]
The issue does not seem to address any real problem. Since it has not received any attention for 3 years, I 'm closing it.
