### ISSUE TITLE
reproducible builds: add limited support

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#5255]
To make parts of the build more reproducible two steps can be taken:

* add support for the `SOURCE_DATE_EPOCH` environment variable (as suggested by https://reproducible-builds.org/docs/source-date-epoch) for components that rely on DATE/TIME during build
* set `user`, `group`, and `mtime` consistently for in _tar_-archives

This issue addresses a subset of the Genode tree that can be extended as needed. For _tar_ a global `TAR_OPT` that sets the parameters above would be sufficient.

**Comment by nfeske** [comment]
Merged to staging.
