### ISSUE TITLE
usb: set control transfer timeout in libusb

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#5259]
Re-enable the setting of a timeout in the libusb backend implementation, otherwise certain devices (e.g. smartcard-reader) won't do any progress.

**Comment by nfeske** [comment]
Merged to staging.

**Comment by chelmuth** [comment]
I'm wondering if this is an intermediate step as you planned to apply a default timeout in the host driver and remove the timeout from the API.

**Comment by skalk** [comment]
@chelmuth that is true, but after looking at the different timeout values more closely again, I decided against the default timeout, as they can be quite different. Therefore, having the option within the API seemed necessary. Alternatively, we would need the ability to cancel a single request to track timeouts client-wise.

**Comment by chelmuth** [comment]
Thanks for the clarification - hence, timeouts in the API make much sense :-)
