### ISSUE TITLE
vbox: guest triggered screen-blanking does not clear the screen

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#5263]
It can happen with guests running in vbox6 on Sculpt that screen-blanking, for example triggered as part of energy-saving means, does not clear the screen but still shows the last displayed content indefinitely (until a new input event is received).

The behavior could be provoked with a Win10 guest (screen-saver set to 1 min) and with a void-linux guest by executing `xset dpms force off`. A Ubuntu 22.04 guest (screen-server set to 1 min as well) on the other hand shows a blank (black) screen, which would be the expected result.

**Comment by alex-ab** [comment]
I have a commit, which solves the issue for me on Win10 guest. Same is also done already by vbox5.
