### ISSUE TITLE
Add relevant topics to Github repository for SEO

### ISSUE THREAD

**Issue by axiomsss** [genodelabs/genode#5280]
To gain more exposure, increase Search Engine Optimisation(SEO) and be promoted in Github topics. We should add topic tags relevant to this project.

https://docs.Github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

I regularly browse Github topics to see if I find any interesting projects related to the topic tag. I often do come across projects I otherwise would not have.

For Genode we can add tags such as: microkernel, os, operating-system, sel4, framework, Genode, sculpt, sculpt-os, c++, nova, linux, goa, x86, risc-v, arm
For GOA we can add tags such as: goa, Genode, c++, gcc, sculpt, sculpt-os, linux
For genodians: Genode, sculpt-os, genodians

When I was looking through the microkernel topics in Github to see if I found any interesting projects I hadn't encountered, I noticed that Genode was not listed anywhere. 

You can see in this list that genode is not listed: https://github.com/topics/microkernel

That is because we have not added the microkernel topic. So to increase the user base and contributors it is important that we use all avenues available to increase SEO which helps open source projects thrive. You can’t contribute to a project you’ve never heard of.

I actually only found out about the Genode project when I was googling for open source operating systems that used micro kernels when I seen a comment on a Reddit thread that mentioned Genode. The Genode Github nor website appeared in google search when I searched open source microkernel operating systems. I would have thought google would suggest this project as one of the first results as it is exactly what I’ve been searching for, but it didn’t. So I think we need to work on increasing SEO.

![github-topics1](https://github.com/genodelabs/genode/assets/168964823/fb5af29d-af2b-4851-ad54-f262a0e0c707)
![github-topics2](https://github.com/genodelabs/genode/assets/168964823/d52c9779-4669-4047-9644-d35b44ae0f89)
![github-topics3](https://github.com/genodelabs/genode/assets/168964823/1b0c20a6-96de-486d-ab31-c7ed49a3d0a8)
![github-topics4](https://github.com/genodelabs/genode/assets/168964823/d34f250f-d15e-4969-ab29-bf16ee646736)

**Comment by chelmuth** [comment]
![Screenshot_2024-07-09_13-30-00](https://github.com/genodelabs/genode/assets/968883/323983bd-b5fa-4a43-a4f6-0ee9aa396ee9)

**Comment by chelmuth** [comment]
@axiomsss I added *cpp* as well

**Comment by atopia** [comment]
Our Ada/SPARK based encryption has since been replaced by a C++ implementatio. For details, see the [Genode 23.05 release notes](https://genode.org/documentation/release-notes/23.05#Revision_of_Genode_s_custom_block-encryption_infrastructure). With our main Ada based component phased out, I does not make sense to add a topic that nobody is actively pursuing anymore.
