### ISSUE TITLE
sculpt: make display mode interactively configurable

### ISSUE THREAD

**Issue by axiomzzzz** [genodelabs/genode#5286]

**Comment by nfeske** [comment]
Implemented by https://github.com/genodelabs/genode/commit/3e6f465344f4f9243ab7503ff0a80c8ae6d52398.

**Comment by chelmuth** [comment]
I :heart: the new icons :wink:

**Comment by atopia** [comment]
I'm confused by the interplay between this feature and `/config/fb` / `/config/managed/fb`:
- when I move my external 4k display to the top, I end up with a `/config/managed/fb` with:
```
	<merge width="3840" height="2160" name="DP-3">
		<connector name="DP-3" width="3840" height="2160" hz="60" mode="1"/>
		<connector name="eDP-1" width="2160" height="1350" hz="60" brightness="69" mode="1"/>
	</merge>
```
So far, so good.
- If I now simply unplug the big resolution connector (`DP-3`) the capture session is not adjusted, which means in my case that I can't access the `intel_fb` menu anymore
- If I copy `/config/managed/fb` (with the big resolution still first) to `/config/fb`, the capture session is adjusted to the smaller size.

**Comment by atopia** [comment]
Wow that was an extremely quick fix! Works like a charm and addresses the problem.
