### ISSUE TITLE
sculpt: Mini Tactile Pro USB keyboard function keys incorrectly mapped

### ISSUE THREAD

**Issue by axiomzzzz** [genodelabs/genode#5288]

**Comment by chelmuth** [comment]
To investigate this please edit */config/nitpicker* and change
```
<report ... keystate="no"/>
```
to
```
<report ... keystate="yes"/>
```
and monitor */report/log* (Log in Leitzentrale). Now, you can press any key on the keyboard and record which ones are incorrectly mapped to unexpected events. Please add this information to this issue.

Further, are you aware of any quirks Linux may apply to support this keyboard we may miss in our ported driver?

**Comment by chelmuth** [comment]
I already found the reason why `F4` switches to Leitzentrale in [*drivers/hid/hid-apple.c*](https://elixir.bootlin.com/linux/v6.1.20/source/drivers/hid/hid-apple.c#L243).

```
  { KEY_F4, KEY_DASHBOARD, APPLE_FLAG_FKEY },
```

We use `KEY_DASHBOARD` as Leitzentrale switch event. So you may try to use `Fn+F12` to switch.

**Comment by chelmuth** [comment]
Great investigation, thanks! But I came to a different conclusion than yours. For me, Sculpt is quite correct in not detecting `KEY_FN+KEY_DASHBOARD` as Leitzentrale toggle event. `KEY_DASHBOARD` is a nitpicker *global key* and global keys are only effective *at the beginning of key-press sequences*. You may try SHIFT-F12 on your laptop keyboard to check this.

What puzzles me is the reporting of `KEY_FN` from *hid-apple.c*, which up to now never happened with any keyboard I tested.  Therefore, I never included the Fn key as real key event into the event handling - it was just a *hardware switch* that changes the reported scancodes of other keys to me. In my eyes, the behavior of hid-apple.c looks wrong as it on one hand reports different key events depending on the Fn state but sends the Fn press and release events too.

Would you mind to help me with another test? Please edit */config/event_filter* and append the following line in the `<remap>` node right after `</merge>`.

```
  <ignore-key name="KEY_FN"/>
```

Does Sculpt now reacts as expected?

**Comment by chelmuth** [comment]
I'm glad we could identify the issue that quickly :-) I will adapt the usb_hid driver to not report `KEY_FN` as this makes no sense with simultaneous scancode translation (F key -> Function key) and prevents to use F keys as global keys. This effectively restores the inherent assumption that Fn keys are a hardware feature.

> The `event_filter` XML file was not located in `/config/event_filter`, it was actually in `/config/managed/event_filter`

Indeed, */config/managed/event_filter* is used by the Sculpt system, but if you want to adjust any config you should not directly edit in */config/managed/*. First, copy the current state from */config/managed/* to */config/* and afterwards edit there. The Sculpt system monitors */config/* and merges changes applied with internal policies into */config/managed/*. (see https://genode.org/documentation/articles/sculpt-24-04#Manual_configuration).
