### ISSUE TITLE
Make Github milestones for features?

### ISSUE THREAD

**Issue by axiomzzzz** [genodelabs/genode#5296]

**Comment by nfeske** [comment]
The project has an official road map (https://genode.org/about/road-map) that reflects our high-level planning.

The road map is annually updated at the turn of the year, following a public brainstorming. You can find the discussion for 2024 at https://lists.genode.org/mailman3/hyperkitty/list/users@lists.genode.org/thread/IJR5J5PZJ42GBAMZ36BWUOD4JFJHWJXG/#D7AHQS2HI4XTRG24MPI6Q6O4LDOMYO4C.

The mile stones as presented on the road map can be taken as a form of commitments but they are not definite. See the statement at the top of the road-map page.

To subsume a set of related issues under one umbrella topic, we use simply cross-reference issues. Multiple detail issues can refer to one higher-level issue. See #5174 as an example for such a meta issue.

Presenting the list of topics you suggested as project milestones would be misleading. The topics collected at the challenges page (https://genode.org/about/challenges) are not actively pursued by the Genode developer team. They are merely a collection of ideas presented as inspiration for others. Presenting those topics as Genode milestones would wrongly suggest a form of commitment on our side.
