### ISSUE TITLE
sculpt: power off not working for HP ZBook Fury 16 G10 Mobile Workstation

### ISSUE THREAD

**Issue by axiomzzzz** [genodelabs/genode#5297]

**Comment by alex-ab** [comment]
HP is currently not part of our regular test machines in the GenodeLabs office. Nevertheless, I tried on 2 different notebooks with 13th generation CPUs of Intel (Framework and Fujitsu) and there it is working fine. So, the feature is not in *general* not working, just specifically for your model. So, I change the title of the issue to avoid this wrong impression of the over generalization. Please try to avoid this next time.

Does acpi_support show some anomalies during component start-up ? If so, can you please paste the snippets of the report/log ? Maybe they can give us some hints.
