### ISSUE TITLE
fs_query: use dictionary to make directory entries unique

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#5334]
If there are multiple overlaying file systems in the fs_query's VFS such that the same (shadowed) file name exists several times, the component reports the shadowed file multiple times. Currently, the component uses an AVL tree for sorting the directory entries. We can replace this with our Dictionary implementation instead in order to check for duplicates.

**Comment by jschlatow** [comment]
Fixed by c26975e

**Comment by nfeske** [comment]
Thank you for the very welcome update!
