### ISSUE TITLE
libc: basic support for SIGALRM

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#5337]
Some POSIX applications like netperf use the POSIX `alarm` mechanism, which schedules a SIGALRM signal after a specified amount of seconds. To allow using netperf w/o patches, Genode's libc should emulate that.

**Comment by nfeske** [comment]
Commit https://github.com/nfeske/genode/commit/05269d5fa0d5b783d80e26c4695595303b6c4224 implements the mechanism accompanied with a simple test.

@alex-ab would you like to try applying it to netperf? This could have a nice effect on the nightly tests.

**Comment by alex-ab** [comment]
@nfeske: I removed all the patches and the setitimer emulation from netperf and gave it a short test on the nightly x86_64 test machine. Looks good so far.

**Comment by nfeske** [comment]
Fixed in master.
