### ISSUE TITLE
intel/display: support panel self refresh

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#5339]
Panel Self Refresh (PSR) is a feature for lowering device power by letting the display panel refresh independently, when the screen contents stay static.
[Linux kernel description](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/gpu/drm/i915/display/intel_psr.c?h=v6.6.47#n42)
[Phoronix feature stories](https://www.phoronix.com/search/Panel+Self+Refresh)

**Comment by alex-ab** [comment]
The first commit enables the support, but is not so effective since it ever marks the whole framebuffer dirty. With the second commit, solely if according to the capture session something changed, the framebuffer is marked as dirty, which then may trigger the wakeup of the panel. In principal the commits can also be squashed, I personally would prefer them to stay separated.

**Comment by nfeske** [comment]
Very nice to see the direction the code is taking, as you just mentioned to me in person. Merged to staging.
