### ISSUE TITLE
intel/display: support multiple capture sessions

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#5345]
Currently, our port of the Intel display driver supports solely to mirror one Capture session to all physical attached displays.

For advanced usage patterns, e.g. multi-head/multi-screen/multi-display, support is required, to establish for each connected display a separate Genode Capture session. Our ported driver thereby requires support to manage per discrete (not-mirrored) connector a specific framebuffer, instead of one framebuffer used across al mirrored connectors. The consequence of this will be, that the memory usage will increase significantly, depending on the attached displays and the chosen mode, because of the discrete usage.

**Comment by alex-ab** [comment]
I adjusted the labeling according to the connector names and updated the README. The commit is ready for usage.

**Comment by nfeske** [comment]
Super cool! Thank you @alex-ab for realizing our ideas piece by piece in such nice way.

As a minor detail, the word "discret" should be "discrete".

**Comment by chelmuth** [comment]
Fantastic indeed ;-)

@alex-ab how does `force_width/height` affect the driver now? I could imagine to move the documentation into section *Non-discrete usage of connectors* and, thus, limit the scope of forced virtual resolution to the *mirrored* connectors. In the future, it could be moved into the `<merge>` node.

**Comment by alex-ab** [comment]
Thanks for your input. I added two fixups, which should address all your comments. Please check.

**Comment by alex-ab** [comment]
I added the support for labeling the merge node and squashed all together.

**Comment by chelmuth** [comment]
With the `<merge>` node available, I vote for moving `force_width/height` from global config scope into `<merge width="..." height="...">`.

**Comment by alex-ab** [comment]
@chelmuth: I added several fixups to the discussed topics.
