### ISSUE TITLE
framebuffer session: safe access to pixel/alpha/input portions of the GUI buffer

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#5351]
The memory layout of the virtual framebuffer as created a GUI server is defined as the pixel buffer, followed by the alpha channel, followed by the input mask. The latter two parts exist only when using an alpha channel. Currently, the access to those portions involves finicky pointer calculations scattered through the code base. To ease the life of GUI clients and simplify the implementation of the GUI server, we should better provide a central place with safe accessor methods.

Since the GUI-buffer layout depends on the mode and the use of an alpha channel, it would be natural to host those accessors in the `Framebuffer::Mode` type. Before we can do that, however, we have to make the `use_alpha` attribute part of the `Mode`. Currently, this attribute is propagated as distinct argument.

Accessing the pixels, alpha values, and input mask should best become possible via `Byte_range_ptr` and via the `Surface` API.

**Comment by nfeske** [comment]
The commit series above implements this change.

Note that it introduces an API incompatibility because the `Framebuffer::Mode` got the new `alpha` attribute.

**Comment by nfeske** [comment]
Merged to staging.

@cproc would you take care of adapting qt5 and qt6 to these changes?

**Comment by cproc** [comment]
Commit 29ea16d adapts qt5 and qt6.

**Comment by nfeske** [comment]
Thank you @cproc.

**Comment by nfeske** [comment]
Fixed in master.
