### ISSUE TITLE
nitpicker: support panorama spanning mulitple monitors

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#5352]
So far, the nitpicker GUI server handed out the same picture to each capture client. So each client obtained a mirror the same picture. By subjecting each client to a policy defining a window within a larger panorama, a driver creating one capture session per monitor becomes able to display the larger panorama spanning the connected displays.

**Comment by nfeske** [comment]
Implemented by https://github.com/genodelabs/genode/commit/21815ef62725e022047d50fb16723619211973b3

**Comment by chelmuth** [comment]
The following commits address cases of dynamic capture screen sizes in intel_fb.

664ebd0760b intel/display: clear fb on screen size change
e9502af5969 WIP nitpicker: clip affected rects on capture to screen size
87d563f38b4 WIP intel/display: clip affected rects on capture to screen size

The WIP commits are alternatives to address clipping to the actual screen size to prevent stale pixel data on screen.
