### ISSUE TITLE
nitpicker: uncaught Buffer_result exception

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#5366]
During testing Sculpt 24.10 alpha #5356  I'm able to kill nitpicker reliable:
```
[init -> runtime -> top_view_config -> graph] config: freq_khz=2000000
[init -> runtime -> runtime_view] Warning: more than one dialog unexpectedly hovered at the same time
[init -> runtime -> top_view_config -> graph] Warning: attempt to handle the same signal context twice (nested)
[init -> nitpicker] Error: Uncaught exception of type 'Gui::Session::Buffer_result'
[init -> nitpicker] Warning: abort called - thread: ep
```
When using the top_view package (version 2024-10-11), selecting a thread to be monitored, another "graph" window is shown and then trying to resize this graph window, nitpicker reliable causes the abort. Afterwards Sculpt is not usable anymore.

**Comment by alex-ab** [comment]
For me it looks a bit, that by accident the exception is thrown in 59008f777b56c362c714dbb68fe4ea4873f4a3a8 instead of returning the OUT_OF_CAPS value, as done 3 lines before with OUT_OF_RAM. With the commit nitpicker is not killed anymore.

**Comment by nfeske** [comment]
> For me it looks a bit, that by accident the exception is thrown

That is a slip-up on my side indeed. Thank you for uncovering and fixing it!
