### ISSUE TITLE
intel/display: unimplemented i915_gem_evict_for_node function triggers with Sculpt 24.10

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#5377]
When attaching a lot of monitors or some few 4k monitors, then the assertion about the unimplemented function may trigger.

**Comment by cnuke** [comment]
@chelmuth commit [5237c07](https://github.com/cnuke/genode/commit/5237c07f59293cb42736ff0472a52d360ccdf0e2) implements the discussed behavior with the minor adjustment that the display driver takes precedence, i.e. in case the aperture is too small sacrifice usable GPU service.
