### ISSUE TITLE
libc: synchronize implicit pthread mutex initialization

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#5386]
Related to #3262 and #3741. Also add a check to cond and rwlock initialization to detect if a different thread has already initialized the internal object in the meantime.

**Comment by cproc** [comment]
Fixed by 85be218.

**Comment by nfeske** [comment]
I may miss to see the complete picture but I think that the `try { } catch` can be omitted because the `Libc::Allocator` should never raise an exception. As far as I know, our implementation of `malloc` never returns NULL. Whenever the available memory is exhausted, a resource request is issued.

**Comment by cproc** [comment]
> I may miss to see the complete picture but I think that the `try { } catch` can be omitted because the `Libc::Allocator` should never raise an exception. As far as I know, our implementation of `malloc` never returns NULL. Whenever the available memory is exhausted, a resource request is issued.

Commit 3784275 has the `try { } catch` removed from `mutex_init()` and commit 35a679d contains the corresponding cond/rwlock changes.

**Comment by nfeske** [comment]
Thank you @cproc. I merged your commits to staging now.
