### ISSUE TITLE
Sculpt/hw: sluggish UI on Full-HD displays

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#5388]
After giving Sculpt 24.10(.2) a try with base-hw on my x230, x260 and t490s, I noticed that the Leitzentrale UI feels very sluggish on the x260 but very responsive on the x230. The sluggishness is also noticeable on the t490s, yet less obvious. The effect is reproducible with Sculpt 24.04.

Comparing the resolutions of the internal displays revealed that the t490s and x260 come with a Full-HD display whereas the x230 has a resolution of 1366x768. Reducing the resolution from Full-HD to, e.g., 1280x720 removes the sluggishness.

I've also noticed that _mesa_gears_ achieves significantly less fps on base-hw than on base-nova. On my x260, it barely gets up to 500fps on base-hw whereas it achieves 1k fps on base-nova.

Note that I published a ready-to-use Sculpt/hw image on my depot: [sculpt-pc-2024-11-26-hw.img](https://depot.genode.org/jschlatow/image/sculpt-pc-2024-11-26-hw.img.xz).

**Comment by alex-ab** [comment]
Just a hint, I think no one ever added intel_hwp bender configuration options to base-hw/x86_64 ...

**Comment by jschlatow** [comment]
> Just a hint, I think no one ever added intel_hwp bender configuration options to base-hw/x86_64 ...

Adding _intel_hwp_performance_ to bender actually solves both issues (UI and mesa_gears).

**Comment by nfeske** [comment]
Merged to staging.
