### ISSUE TITLE
ram_fs issues

### ISSUE THREAD

**Issue by iloskutov** [genodelabs/genode#556]
I again try to use ram_fs and have some issues.
First issue similar #348, I sometimes receive  Packet_alloc_failed when read file straight after write. I use the same test from issue #348.
Next issue is incorrect file size calculation. I have increased buffer size to 1024K in libc_fs test from libport and after write stat returned file size 1039232 bytes. I think this occurred because stat worked before full write was complete.

**Comment by nfeske** [comment]
I am closing this issue because it is stale for two 5 years.
