### ISSUE TITLE
base-foc: capability mapping problem on 64-bit Fiasco.OC

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#559]
When running the Noux bash test on 64-bit Fiasco.OC and running

```
for ((i=0;;i++)) do /bin/echo $i; done
```

after ~365 iterations the execution stops and the log output shows several 'mapping cap failed" error messages.

**Comment by nfeske** [comment]
As far as I can see, we won't take any further steps. So may we close this issue?
