### ISSUE TITLE
core: Avoid redundant unmap operations

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#595]
On the Genode-Mailingliste, the following observation was brought up: http://sourceforge.net/mailarchive/forum.php?thread_name=CANud0THTTLbBT25bQcH3nf2q-w5wEzoYShgK0SsseLeZvOtqnA%40mail.gmail.com&forum_name=genode-main

```
While I was browsing, I found that, in function
Rm_session_client::detach(), there is a part that looping over Rm_client
and unmap it:

        for (Rm_client *rc = _clients.first(); rc; rc = rc->List<Rm_client>::Element::next()) {
                /*
                 * XXX Unmapping managed dataspaces on kernels, which take a core-
                 *     local virtual address as unmap argument is not supported yet.
                 *     This is the case for Fiasco, Pistachio, and NOVA. On those
                 *     kernels, the unmap operation must be issued for each leaf
                 *     dataspace the managed dataspace is composed of. For kernels with
                 *     support for directed unmap (OKL4 or Codezero), unmap can be
                 *     simply applied for the contiguous virtual address region in the
                 *     client.
                 */
                if (!platform()->supports_direct_unmap()
                 && dsc->is_managed() && dsc->core_local_addr() == 0) {
                        PWRN("unmapping of managed dataspaces not yet supported");
                        break;
                }
                rc->unmap(dsc->core_local_addr() + region->offset(),   // <=== this part
                          region->base(), region->size());
        }


The implementation of Rm_client::unmap is the following:

        void Rm_client::unmap(addr_t core_local_base, addr_t virt_base, size_t size)
        {
                // TODO unmap it only from target space
                unmap_local(core_local_base, size >> get_page_size_log2());
        }

In the above function, since it is not using any member variables of
Rm_client, when Rm_session_client::detach() calls multiple of
Rm_client::unmap it is just calling the same function of "unmap_local" with
the same parameters.
It results in calling l4_task_unmap multiple times with the same parameters.
I'm just concern that this may not cause anything harmful.
```

In the presence of multiple threads, detaching a dataspace will indeed result in multiple subsequent unmap operations referring to the same virtual addresses, one operation for each thread (aka `Rm_client`). Even though this causes no harm, it poses redundant work. Hence, avoiding those redundant unmap operations might improve the performance, in particular during the destruction of processes.

Currently, the RM session is associated to threads (RM clients). This is needed because on L4, page tables of address spaces are populated by sending mappings as a reply to a page fault message to a thread residing in the address space. However, the mapping ultimately affects all threads in the same address space. The reverse case (unmap) is always asynchronous and ultimately refers to the address space rather than an individual thread. If we kept track of the PDs (Genode's representation of an address space) that use an RM session, we could target the unmap operation directly to the corresponding address space rather than taking a hop through the RM clients. This change would not only eliminate the redundant unmap calls but also would allow for the use of Fiasco.OC's directed unmap functionality (further improving the performance by pruning only the needed branches of mapping trees instead of unmapping the whole tree).

**Comment by alex-ab** [comment]
Solved by 430bde3636af33f81e976a280e1f350aea7a1715
