### ISSUE TITLE
Warning about insufficient RAM quota does not always throw Quota_exceeded

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#596]
In `os/src/drivers/timer` all implementations warn about insufficient RAM quota donation, but nevertheless continue to create the session component. In case of `os/src/server/nitpicker` I also get a warning on insufficient donations, the session component is not created, and `Quota_exceeded` is thrown. Is there a reason the timer behaves differently? Nitpicker does what I expected.

There's also a small typo in nitpicker's warning message: dontated -> donated.

**Comment by nfeske** [comment]
This issue is long obsolete.
