### ISSUE TITLE
Tiling and tabbing window manager

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#60]
Over the course of the year 2012, I expect that calls for a tiling window manager on Genode will be articulated. So we should start making up our minds with respect to the desired feature set.

Personally, I would like to take a subset of the functionality of Ion3 as starting point. (right now, I am using notion on Linux) Ion3 is a static tiled window manager that provides tabbing, tiling, and virtual desktops.

The most important Genode interfaces to support are the framebuffer and input session interfaces. Other interfaces such as terminal and nitpicker can be integrated via intermediate components (i.e., the graphical terminal in the gems repo, or the nitpicker GUI server). By using Nitpicker, we can easily emulate a floating-window desktop.

At a later stage, we could implement some of the other interfaces (in particular the terminal session interface) natively to reduce memory foot print (by avoiding the storage of single pixels for each terminal) and improve the level of integration of the GUI with interactive terminals. This way, we could provide feaures such as searching text patterns across terminal instances.

**Comment by m-stein** [comment]
@nfeske I'm not sure, but hasn't this been fixed by #3031 ?

**Comment by nfeske** [comment]
We are not quite there yet. The mechanism is in place, but a convenient interactive user interface for the window layouter is still missing. That said, we can take the missing pieces to dedicated issues once we start to tackle them. Feel free to close this one.

**Comment by m-stein** [comment]
Thanks for the explanation ;)
