### ISSUE TITLE
Base: memcpy_cpu for x86

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#605]

**Comment by skalk** [comment]
Recent observations with different ARM platforms and different memcpy implementations (base lib, libc, ...) showed that we do not "win" in optimization against the compiler. The fastest memcpy approach was a simple for-loop that copied byte-wise compiled with gcc with FPU hard-float support and -O3 flag.
My suggestion is to close this issue and save the energy of platform-specific function implementation, but put it into our toolchain-update and higher compiler optimization level support instead. Do you agree?

**Comment by skalk** [comment]
Ok, I see two approvals and no opposite view, therefore I close the issue.
