### ISSUE TITLE
mkisofs vs. genisoimage

### ISSUE THREAD

**Issue by parthy** [genodelabs/genode#627]
This is just a minor point, but would it be possible to support both mkisofs and genisoimage? While Ubuntu seems to prefer genisoimage, some distros ship with mkisofs as part of cdrtools. From what I found both are very similar and should therefore be easily supportable by the creation script.

**Comment by jameysharp** [comment]
I tripped over this while trying for the first time today to build Genode. I'd appreciate it if `create_iso` would just invoke either mkisofs or genisoimage, based on whichever one is installed. It seems gratuitously inconvenient to require the user to create a symlink.

**Comment by nfeske** [comment]
This issue is obsolete with version 17.11. We use xorriso now.
