### ISSUE TITLE
base-hw & arm: rework SCTLR assignment

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#636]
At the one hand the SCTLR assignment should be checked against the new ARMv7A revision C. At the other hand assignment should happen as follows:
```
void Arm::Cpu::Sctlr::init(access_t & v) { M::set(v, 0); }

void Arm_v7::Cpu::Sctlr::init(access_t & v) {
   Arm::Cpu::Sctlr::init(v);
   Sw::set(v, 0);
}

void Cpu::init() {
   Sctlr::access_t v = 0;
   Sctlr::init(v);
   Sctlr::write(v);
}
```

instead of simply OR the values all together. This is because the bitfields of the specs may overlap and more specific specs should override the more generic ones.

**Comment by skalk** [comment]
Seems to be outdated to me. As far as I can see, that issue is solved in current code base. @m-stein: do you agree?

**Comment by m-stein** [comment]
Of course.
