### ISSUE TITLE
base-hw & arm_v7: unable to disable caches

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#643]
When disabling caches through 'memory_region_attr()' or even set them to "write trough / not allocate" core runs just fine, but the first process on top of it fails to prefetch its first instruction. Cores pagefault-handling maps the according region and reactivates the faulter, but the faulter directly produces a new pagefault at the same address as if the mapping was not done. This continues in an infinite loop.

This behavior occurs only since the following commit:
"aa1612f... base-hw & cortex_a9: use caches in pagetable walks"

**Comment by skalk** [comment]
It would be fine if we could close issue not valid anymore, or at least if we can reproduce it otherwise.

**Comment by m-stein** [comment]
Yes, thanks for the hint.
