### ISSUE TITLE
PS2: make verbose flags run-time configurable (was mantis id 36)

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#7]
The verbose flags in the ps2 mouse and keyboard implementation must be defined at compile time. However, the ps2 driver is often used for diagnostic purposes. In such a case, the driver must be recompiled. It would be convenient to have 'verbose_mouse' 'verbose_keyboard' arguments to the config node of the PS/2 driver.

**Comment by chelmuth** [comment]
@alex-ab That's a great catch for easy bug-squashing points ;-) Merged into staging just now.
