### ISSUE TITLE
low unmap performance on Fiasco.OC with enabled MP support on single-core CPU

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#712]
The test case in a2f00e7554dde59e40bd8cc2ff659fd8eaf82705 allocates and frees a RAM dataspace of 4096 bytes for 10000 times.

When running this test on Fiasco.OC without multiprocessor support in single-core Qemu, the measured execution time of the alloc/free loop was about 3.5s, whereas with enabled multiprocessor support it was about 30.1s.

According to the kernel debugger, with enabled MP support, the idle thread was running for about 30s (4ms without MP support) overall. The same idle thread execution times were reported when running the test natively on a single-core IBM T60 computer.

Debug messages added to the kernel (https://github.com/cproc/foc/commit/0b9052aca213063d969dd0f8d87d66cd64c07311) showed that the ```Kernel_thread::idle_op()``` function got called 3 times while the thread executing the ```l4_task_unmap()``` syscall was in the ```lock_wait``` state.

**Comment by nfeske** [comment]
Even though we documented the problem via this issue, we probably won't ever address it because it is outside the scope of Genode. So I am closing the issue for now.
