### ISSUE TITLE
libc: thread-safety

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#725]
Some libc functions, like `getaddrinfo()`, are supposed to be thread-safe according to the POSIX specification, but are currently not thread-safe in Genode because of unimplemented (silently failing stub) phtread functions in the libc.

**Comment by chelmuth** [comment]
With the integration of the pthread library into the libc this issue should be solved. What remains is the unification of pthread locks/condvars with the libc execution model.

**Comment by nfeske** [comment]
AFAIK, `errno` is not thread-safe yet, see https://github.com/genodelabs/genode/blob/master/repos/libports/src/lib/libc/errno.cc

**Comment by nfeske** [comment]
Featured in Genode 20.02.

**Comment by chelmuth** [comment]
Sorry for not commenting earlier but during my pthread work I discovered that at least `fprintf(stdout,...)` is also not thread-safe. It seems we need a thorough investigation of libc's thread-safety implementation to make it effective.

**Comment by cproc** [comment]
While working on qtwebengine it turned out that the integration of the pthread library into the libc did not make `getaddrinfo()` thread-safe yet, because the libc calls pthread functions prefixed with an underscore internally and therefore still the stub functions were used. Commit 5bf3d15 adds alias functions with underscore for those functions which are listed in `_pthread_stubs.c` [1].

[1] https://github.com/freebsd/freebsd/blob/master/lib/libc/gen/_pthread_stubs.c

**Comment by cproc** [comment]
Another factor for thread-safety in the libc in general seems to be the `__isthreaded` variable, which, according to a comment in `exit.c` [1], is supposed to be set to non-zero when a thread is created.

[1] https://github.com/freebsd/freebsd/blob/fc5c7c80ccfc8a687a4f2d85faf99a081dae1eed/lib/libc/stdlib/exit.c#L48

**Comment by cproc** [comment]
Commit 5f81441 enables threaded mode in the FreeBSD libc code when a non-main pthread is created and commit 85ff518 adds aliases for the `___pthread_cleanup_push_imp()` and `___pthread_cleanup_pop_imp()` functions which are used by the `FLOCKFILE_CANCELSAFE()` and `FUNLOCKFILE_CANCELSAFE()` macros.

In threaded mode, some of the stdio file functions like `fopen()` or `fclose()` use a spinlock with the `__sys_spinlock()` and `__sys_spinunlock()` functions, which are not implemented yet and currently print warnings. The FreeBSD spinlock implementation [1][2] uses a static array of 72 spinlocks and I'm not sure yet how similar to that a Genode version would need to be.

[1] https://github.com/freebsd/freebsd-src/blob/main/lib/libc/include/spinlock.h
[2] https://github.com/freebsd/freebsd-src/blob/main/lib/libthr/thread/thr_spinlock.c

**Comment by cproc** [comment]
The pthread cleanup commit seems to prevent the Sculpt "prepare" sub system from exiting on the PinePhone. I'll investigate.

**Comment by cproc** [comment]
> The pthread cleanup commit seems to prevent the Sculpt "prepare" sub system from exiting on the PinePhone. I'll investigate.

The actual problem was in the experimental "CPU-local libc timer" commit which I used on the PinePhone and only got triggered by the pthread cleanup changes.

**Comment by cproc** [comment]
It turned out that the FreeBSD libc code uses only a single spinlock instance and I did not see an obvious reason why it would need to be implemented as an actual spinlock, so I implemented the `_spinlock()` and `_spinunlock()` functions with a static pthread mutex in commit 56a8e72.

**Comment by chelmuth** [comment]
I merged the commits. Could you tell me why `__isthreaded` must be initialized at two places in the code?

https://github.com/genodelabs/genode/blob/7bce4ec10cade4f672f5539ae0a6bb26d13b3ab6/repos/libports/src/lib/libc/pthread.cc#L78-L79
https://github.com/genodelabs/genode/blob/7bce4ec10cade4f672f5539ae0a6bb26d13b3ab6/repos/libports/src/lib/libc/pthread_create.cc#L177-L178

**Comment by cproc** [comment]
> Could you tell me why `__isthreaded` must be initialized at two places in the code?

One place is for newly created threads and the other for adopted Genode threads (currently only used by VirtualBox).

**Comment by nfeske** [comment]
Fixes in master.
