### ISSUE TITLE
base-hw: extend IRQ session for TrustZone

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#739]
Introduce non-secure IRQs in IRQ session extension.

**Comment by nfeske** [comment]
@skalk What is the rationale and the plan behind this issue?

**Comment by skalk** [comment]
The rationale is to get rid of the hard-coding of interrupt assignment (secure/non-secure) within the kernel, but give the instance with the interrupt session the ability to set it.

**Comment by skalk** [comment]
After thinking a bit more about it, I think it is better to implement this, if we really have a use-case e.g.: different TrustZone scenarios for the same board, instead of eagerly adding a lot of code to base-hw for this feature. I'll therefore close the issue for now.
