### ISSUE TITLE
libc: malloc() alignment

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#754]
Currently, addresses returned by 'malloc()' are 4-byte aligned, which is too small for some code in Qt5 ('QArrayData::allocate()') on 64-bit platforms. This code uses the 'alignof' operator on a particular class type and assumes that the address returned by 'malloc()' is aligned according to the result of this operator, which was 8 in a case where the mismatch caused problems (running Qt launchpad on 64-bit Genode/Linux).

The POSIX 'malloc()' documentation[1] says:

```
The pointer returned if the allocation succeeds shall be suitably aligned so
that it may be assigned to a pointer to any type of object and then used to
access such an object in the space allocated (until the space is explicitly
freed or reallocated).
```

I'm not sure which minimum alignment that would mean exactly for x86_64, but this is what glibc 'malloc()' does[2]:

```
The address of a block returned by malloc or realloc in GNU systems is always
a multiple of eight (or sixteen on 64-bit systems).
```

So I would suggest to just use these values, too.

[1] http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html
[2] http://www.gnu.org/software/libc/manual/html_node/Aligned-Memory-Blocks.html

**Comment by alex-ab** [comment]
cde8248b05aa309f2f9c039d42b676479a745735 extends the libc test to check for alignments. With the b05f03c557a0f53e9da6e1c658e2d26256930cb1, cf917321b6abf28793e63d286dff2fa1efaa2402 and 55373a1f87d603bac3c0127eafe05e10b8c523a9 the test succeeds.
