### ISSUE TITLE
pci: support ram quota trading between device drivers and pci driver

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#755]
In some of the run scripts, pci_drv gets a RAM quota of 1M, which is not sufficient anymore.

**Comment by alex-ab** [comment]
I hijack this issue to actually solve the underlying issue of the pci driver, which should not pay for the client, instead the client should pay, as @cproc already pinpointed. So, I rename the issue slightly.

**Comment by alex-ab** [comment]
In principle this works. I have not tested/adapted all run scripts for now. :+1: for #1372
