### ISSUE TITLE
Extend run tool with a "plugin" concept

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#765]
In the recent past, there were a bunch of issues related to missing adaptions of run scripts. For example, when configuration of components have changed e.g.: #744, or when new components were added, but not added to all necessary run scripts e.g.: the sd_card drivers for OMAP4 and Exynos5.
To sum it up: it gets more and more complicated to maintain the growing number of run scripts, including a growing complexity of their configuration themselfs, e.g.: having either acpi, pci, or SoC platform driver, or choosing between usb driver, or nic etc.

I suggest to extend the run tool by a mechanism to be able to define snippets, which can be used by generic, and potentially more complex run scripts. When discussing this idea with Norman, we came to the proposal, to have functions that return ready to use strings, e.g. in the following manner:
```
...
append build_components [build_net]
build $build_components
...
append config [config_net]
...
```
These snippets might be defined at a central place next to the run tool itself.

**Comment by nfeske** [comment]
This problem has been addressed by the recent introduction of ```repos/base/run/platform_drv.inc```. May we close it?

**Comment by skalk** [comment]
sure
