### ISSUE TITLE
[seoul] Discussion: Get rid of double mapping in VMM

### ISSUE THREAD

**Issue by parthy** [genodelabs/genode#808]
This is meant to be a proposal to remove the need for the double mapping of guest memory and I/O memory. I know that this approach has historic roots (NUL), but especially on x86_32 host systems this can be a real pain. The two major issues here are:
* A limited amount of guest RAM (~1280 MiB)
* Collisions in the I/O memory
While the first point is somehow acceptable in most conditions, the second one is a real pain. Currently (in NUL at least) the VMM receives I/O memory from sigma0 and attaches it to the upper region of its own address space. When the guest tries to access the assigned region, the corresponding memory gets mapped to the "real" address in the guest's address space. This means that every I/O memory region that is assigned to the guest is effectively present twice. With large regions (such as graphics aperture), this pollutes the address space quite a bit and can even lead to fatal errors when the host and guest regions start to collide (basically an endless loop of pagefaults and non-successful mappings). And it should not be necessary at all, because the VMM can just request the memory region directly with the G-Bit enabled. This part should be easy and can be considered when you plan to implement PCI assignment in the VMM port.

The first point seems a bit more involved to remove. But in consideration of issue #803, it seems to be a desirable improvement. As far as I know, the reason for the double mapping is to create the memory holes needed for the device emulation (i.e., BIOS, VGA ROM). So the memory needs to be accessible by the VMM, but not by the guest. It should be possible to create the memory layout at VM boot time, mapping the guest RAM with the G-Bit while the holes are mapped VMM-only.

Now I would like to start a discussion here about the necessity, feasibility and expected effort to implement these changes. Maybe @vmmon, @blitz, @alex-ab or @udosteinberg have an opinion here, too.

**Comment by alex-ab** [comment]
There will be no such development in the close future and if it happens - we may reopen the issue.
