### ISSUE TITLE
lwip: 64-bit problems

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#817]
Since commit d822b82 ```MEM_ALIGNMENT``` is defined as 8 for x86_64, which triggered some problems:

* memory corruption

in function ```pbuf_alloc()```:
```
pbuf.c:308:
    p = (struct pbuf*)mem_malloc(LWIP_MEM_ALIGN_SIZE(SIZEOF_STRUCT_PBUF + offset) + LWIP_MEM_ALIGN_SIZE(length));
...
    p->payload = LWIP_MEM_ALIGN((void *)((u8_t *)p + SIZEOF_STRUCT_PBUF + offset));
```

These calculations only work correctly if the pointer ```p``` returned by ```mem_malloc()``` has at least ```MEM_ALIGNMENT```, too, which is currently not always the case (#754).

In the error case, the allocated buffer gets exceeded by up to 4 bytes when the payload gets written.

c3ce4bed916252bc7b01b3543b85de1c9e11aa2d prints an error message in those cases.

Fixing #754 should fix this problem.

* failed assertions 'seg->tcphdr not aligned'

in function ```tcp_enqueue_flags()```:

```
tcp_out.c:803:
LWIP_ASSERT("seg->tcphdr not aligned", ((mem_ptr_t)seg->tcphdr % MEM_ALIGNMENT) == 0);
```

When the assertion fails, ```seg->tcphdr``` got calculated as ```p->payload - TCP_HLEN```, where ```p->payload``` is aligned with ```MEM_ALIGNMENT``` and ```TCP_HLEN``` is a constant 20.

This looks more like an lwip-internal problem, so I created a bug report at https://savannah.nongnu.org/bugs/index.php?39683.

**Comment by alex-ab** [comment]
I close the issue, since the bug is fixed. Just don't use unsupported MEM_ALIGNMENT values (like 8).
