### ISSUE TITLE
mmio: register stencils

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#845]
By now to instantiate register patterns at multiple arbitrary offsets, one have to use an ugly solution like this:
```
template<unsigned OFF>
struct Pin_cfg : Register<OFF, 8>
{
   /* ugly template prefixes */
   struct A : Register<OFF, 8>::template Bitfield<0, 1> { };
   struct B : Register<OFF, 8>::template Bitfield<1, 7> { };
};
struct Pin0_cfg : Register_print<0x32, Pin_cfg> { };
struct Pin1_cfg : Register_print<0x64, Pin_cfg> { };

/* can't use 'Pin_cfg' here although 'cfg' shall be generic */
Pin0_cfg::access_t cfg = 0;
Pin0_cfg::A::set(cfg, 1);
Pin0_cfg::B::set(cfg, 8);
write<Pin0_cfg>(cfg);
write<Pin1_cfg>(cfg);
```

My first Idea was to provide a ``struct Mmio::Register_print`` that receives a ``Genode::Register`` as pattern and is used as follows:
```
struct Pin_cfg : Genode::Register<8>
{
   struct A : Bitfield<0, 1> { };
   struct B : Bitfield<1, 7> { };
};
struct Pin0_cfg : Register_print<0x32, Pin_cfg> { };
struct Pin1_cfg : Register_print<0x64, Pin_cfg> { };
```
This solution does fine until one wants to read or write one of the bitfields, wich fails because ``A`` and ``B`` don't know their specialized compound regs ``Pin0_cfg`` respective ``Pin1_cfg``.

So far i have no idea how to fix this but maybe someone else can help me. Otherwise i close this issue in a while.

**Comment by nfeske** [comment]
@m-stein How should we go about this issue?

**Comment by m-stein** [comment]
I think we have to leave it as it is. Even with macros I couldn't find a solution that is as simple as using Bitfield in a normal Register.
