### ISSUE TITLE
hw: account quota for PD kernel-object

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#864]
According to ``base-hw/src/core/include/platform_pd.h``, when creating a new PD via a PD session, the new kernel object gets allocated at ``platform()->ram_alloc()``, which bypasses the appropriate quota accounting. Embedding PD kernel-object into platform PD is not feasible because of alignment requirements.

**Comment by skalk** [comment]
In the meantime the PD kernel object is part of Platform_pd and thereby accounted when constructed via a Pd_session_component.

**Comment by m-stein** [comment]
Cool. Thank you for the update.
