### ISSUE TITLE
hw: avoid using RM session in platform thread

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#888]
By now, at least in ``~Platform_thread`` (remove RM client, detach UTCB of core/main threads) and ``Platform_thread::start`` (attach UTCB of core/main threads) the member RM-session of the according RM client is used. This shall be avoided as platform thread is a lower level of abstraction and, in contrast to a call via a session entrypoint, locking is insufficient this way.

**Comment by skalk** [comment]
I do not see the issue here. AFAIK starting and destroying of threads is done via core's entrypoint anyway. Thereby synchronization is no issue, and a call to the entrypoint is not possible. Do I overlook something, or can we simply close the issue?

**Comment by m-stein** [comment]
Admittedly I'm not that sure anymore whether this is an issue. Can one expect the entry-point of the CPU-root to be the same as of the RM-root? I know there is only one entry point, but the the corresponding classes allow for the use of multiple threads as well.

**Comment by skalk** [comment]
To me it seems to be an artificial discussion, because currently both sessions share the same entrypoint. If this would not be the case we would have hit the synchronization problems already regularly in the past. On the other hand what is the alternative? How do you want to not use the RM session directly, although the thread executing the CPU session code is the same that executes RM session requests? What do you want to use from core's perspective instead of the RM session the client is using to attach the UTCB?

**Comment by nfeske** [comment]
I agree with @m-stein's sentiment that the ```Platform_thread``` is a lower level of abstraction than ```Rm_session```. Hence, it is unnatural (and hints at a design deficiency) to use the ```Rm_session``` type there.

**Comment by skalk** [comment]
Ok, from a offline discussion with Norman I've learnt that he solved the same issue for SEL4 by excluding an additional page from the general RM layout, and use it to page the initial UTCB of a component's main thread. I think we should follow the same approach here for HW. Thank to m-stein and nfeske for questioning my closing attempt ;-)

**Comment by skalk** [comment]
ready for review process.

**Comment by m-stein** [comment]
Thanks for solving this issue :-) Reviewed.

**Comment by skalk** [comment]
Ok, fixed the alignment issues.

**Comment by m-stein** [comment]
Thank you!

**Comment by chelmuth** [comment]
I merged the whole [issue#888 branch](https://github.com/skalk/genode/compare/issue%23888), fixed the typo identified by @nfeske, and am waiting for your opinion/fixup of the constexpr constant remark.
