### ISSUE TITLE
pci: support systems with multiple PCI root complexes

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#943]
The feature was requested on the mailing list.

http://sourceforge.net/mailarchive/forum.php?thread_name=6C6CC53089B3A54A9378BEBA898EA2A33669B975%40sisaex02sj&forum_name=genode-main

The thread contains a hint for a quick fix by Jilong Kuang and hints by @udosteinberg to support this feature.

**Comment by nfeske** [comment]
Because, we don't have such a system available, we won't fix this issue in the foreseeable future.
