### ISSUE TITLE
base-linux: Breakpoints are not working for dynamic binaries

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#952]

**Comment by ssumpf** [comment]
Since this is a debugging issue only and I always can cherry pick the commit when debugging with GDB on Linux, it can be closed after 5+ years.

**Comment by chelmuth** [comment]
Agreed, but I must inquire: Why do hardware breakpoints not fit your use case?

**Comment by ssumpf** [comment]
@chelmuth: Because single stepping and stepping over functions ('n') also set breakpoints, and therefore do not work.
