### ISSUE TITLE
hw: core's signal session runs out of memory

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#956]
Due to recent changes in hw, where page fault handling was mapped to signals, now core uses a signal session intensely. Thereby, the meta-data to manage signal contexts in a signal receiver exceed the session's quota. As a consequence, the core thread calls env()->parent()->upgrade(...), whereby core's simple environment doesn't support resource upgrades. As a consequence the system crashes with just a few threads running in the system.

**Comment by Kensan** [comment]
We encountered this issue while porting base-hw to x86_64 and worked around it in a similar fashion: raising the ram quota of the signal session, see commit 29c4ae0 in staging.

**Comment by skalk** [comment]
ready for review ;-)

**Comment by m-stein** [comment]
Cool commits! Just a small nitpicking comment ^^
