### ISSUE TITLE
hw: activity table via key

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#962]
When compiled in non-release mode, the kernel should provide an activity table as soon as a specific key code is received at the UART. This is a first step in the direction of providing an interactive kernel debugger. To achieve this goal, the redundant UART initialization in core should be removed first: core can use UART as the kernel initialized it. Additionally UART drivers must be equipped with receipt functionality. The kernel already provides all information for the activity table: user labels of PDs and their threads, message-transfer and signalling information of blocking threads, and the CPU context of active threads.

**Comment by chelmuth** [comment]
:+1: just for bumping the issue ;-)

**Comment by chelmuth** [comment]
Is this issue a candidate for WONTFIX close?

**Comment by skalk** [comment]
I agree
