### ISSUE TITLE
Parsing ACPI tables causes unhandled page fault

### ISSUE THREAD

**Issue by olesalscheider-intel** [genodelabs/genode#998]
On my machine, the acpi_drv parses the DSDT and then unmaps it. Then it finds the SSDT and starts to parse it, too. During the parsing, ```_indirect_prt``` is called, which finds an element in the DSDT. This element is used to call ```_direct_prt``` which in turn calls ```_packet```. ```_packet``` passes the data pointer to the constructor of Element which causes an unhandled page fault in ```if (data[0] != PACKAGE_OP)``` since the dataspace of the DSDT is not attached anymore.

**Comment by alex-ab** [comment]
@chelmuth: fixes acpi issue on test machine
